bolt/bolt

changelog.md, src/TwigExtension.php
=> Set default width/height of showImage() to '0'

theme/base-2013/_sub_menu.twig, theme/base-2014/_sub_menu.twig
=> Import macro instead of direct usage of _self in theme base-2013/14

app/view/js/bolt.js, app/view/js/src/obj-datetime.js
As criticised by @bobdenotter  in [#2378](https://github.com/bolt/bolt/pull/2378#discussion_r22375739)
I think that is the way to go, ok?
=> Fix omitting parentheses issue

src/Application.php, src/BoltUrlMatcher.php
The UrlMatcher was doing duplicate logic as Silex's RedirectableUrlMatcher. 
I just extended it which removed the need for a lot of the code.
=> Url matcher updates

src/Config.php
c.f. [Symfony\Component\HttpFoundation\Request](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Request.php#L1668)
=> Also use XMLHttpRequest to detect AJAX requests in getWhichEnd()

src/Application.php, src/Configuration/ResourceManager.php, src/Provider/SafeTwigServiceProvider.php, src/TwigExtension.php
=> Revert "Refactor Twig setup"

app/resources/translations/cs_CZ/messages.cs_CZ.yml, app/resources/translations/de_DE/messages.de_DE.yml, app/resources/translations/en_GB/messages.en_GB.yml, app/resources/translations/es/messages.es.yml, app/resources/translations/fr/messages.fr.yml, app/resources/translations/hu/messages.hu.yml, app/resources/translations/id/messages.id.yml, app/resources/translations/it/messages.it.yml, app/resources/translations/ja/messages.ja.yml, app/resources/translations/nb/messages.nb.yml, app/resources/translations/nl_NL/messages.nl_NL.yml, app/resources/translations/pt/messages.pt.yml, app/resources/translations/ru/messages.ru.yml, app/resources/translations/zh_CN/messages.zh_CN.yml, app/view/twig/nav/_secondary-configuration.twig, src/Omnisearch.php
I wanted to see how I should translate these things and how the process would work. Rarila did help me bigtime.
=> Translated Routing Setup to new keysystem

src/Controllers/Frontend.php
=> Pager correction at listing categories.

src/Storage.php
Fixes #2471 
I saw vast MySQL performance increases after implementing this change.
=> Separate table queries for MySQL and Postgres

src/Extensions.php
=> extension to twig_extension

src/Config.php
Most of this is breaking getConfig() into separate methods. 
I made resources a class variable since it is used all over the class.
I'm not sure if anything in here is considered a BC break. BC only counts for using the class right, not extending it? 
I ask because I changed some of the methods to now return their results instead of setting them to class variables.
This wouldn't affect users of the class only people who are extending it.
=> Refactor config

.gitignore, composer.json, src/Configuration/LowlevelChecks.php, src/Configuration/LowlevelException.php, tests/BoltSystemMock.php, tests/Configuration/ComposerConfigurationTest.php, tests/Configuration/LowlevelChecksTest.php, tests/Configuration/Mock/Config.php, tests/Configuration/ResourceManagerTest.php, tests/Controller/ExtendControllerTest.php, tests/bootstrap.php, tests/bootstraps/lowlevel-bootstrap.php
This takes tests/Configuration up to 100% code coverage
Plus:
Fixes a bug in LowlevelException where the file search path was wrong.
=> Configuration Module Test improvements (and bug fixes)

src/Cache.php
=> Have Cache::clearCache() use $app['resources']->getPath('root') for the 'thumbs' directory

composer.json, phpunit.xml.dist, src/Library.php, tests/Configuration/LowlevelChecksTest.php, tests/Extensions/Mock/Extension.php, tests/Library/BoltLibraryTest.php, tests/Nut/ExtensionsDisableTest.php, tests/Nut/ExtensionsEnableTest.php, tests/Nut/ExtensionsTest.php
Hopefully this should go green now.
=> Next round of test improvements

composer.json, phpunit.xml.dist, src/Configuration/LowlevelChecks.php, src/Configuration/LowlevelException.php, src/Configuration/ResourceManager.php, tests/Configuration/ComposerConfigurationTest.php, tests/Configuration/LowlevelChecksTest.php, tests/Configuration/ResourceManagerTest.php, tests/Twig/BoltTwigHelpersTest.php, tests/bootstrap.php
Also includes a fix for incorrect copying of existing config.yml file
=> Next Batch of Test improvements

src/Application.php, src/Configuration/LowlevelException.php
Don't leak secure DB password information on connection error during set up.
Fixes #2532
=> Hotfix DB info leak

app/src/Bolt/Database/IntegrityChecker.php
=> Fix indexing on changelog table

composer.json
=> Replace upload composer packages

src/Logger/Manager.php
... Which would otherwise happen when upgrading: The 'changelog' in the sidebar is shown _before_ the user gets a chance to update the db.
=> Don't throw a fatal error, when column 'context' does not yet exist in log table.

app/view/Gruntfile.js
Allthough removed in #2556 it's still there
=> Catchpaste removal leftover

src/Config.php
So they can be extended by others.
=> Config protected variables and methods

src/Application.php
This allows Config to be overridden before initialization
=> Initialize config and session separately

tests/Controller/BackendTest.php
=> Add test for system log

src/Config.php
=> Config simpify parseConfigYaml method

src/Database/IntegrityChecker.php
Waited forever for @rarila to beat me to this...  Guess it's up to me! :checkered_flag:
=> Bring unrequired double quotes closer to extinction

src/Config.php
Here's the big one....I would look at each commit separately.
=> Config split parsing methods

src/Application.php, src/Config.php, src/Provider/TwigServiceProvider.php
Commit messages should be self-explanatory.
=> Twig configuration updates

app/nut, src/Application.php, src/BaseExtension.php, src/Provider/NutServiceProvider.php
=> Nut service provider

src/Application.php, src/Config.php, src/Database/IntegrityChecker.php, src/Storage.php
=> Use doctrines reserved words

src/Application.php, src/Database/InitListener.php
This will execute the queries for every connection established, not just the first one. Also, it moves it out of Application.
=> Move post connect queries to an InitListener class

src/Config.php
=> b147fb9 Wasn't merged correctly

composer.json, tests/Filesystem/BrowsePluginTest.php, tests/Filesystem/FilesystemContainerTest.php, tests/Filesystem/ManagerTest.php, tests/Filesystem/SearchPluginTest.php, tests/Filesystem/ThumbnailUrlPluginTest.php
* Updated Flysystem from version 0.5 to 1.1
=> Update Flysystem to track latest version, with php5.3 patch.

src/Configuration/ResourceManager.php
=> Replace relative path regex with pathogen solution

app/theme_defaults/error.twig
ping @rossriley for follow up.
=> Remove some debugging that was killing Travis/PHPUnit

app/bootstrap.php, src/Application.php, src/Config.php, src/Configuration/ComposerChecks.php, src/Configuration/LowlevelChecks.php, src/Exception/LowLevelDatabaseException.php, src/Exception/LowlevelException.php, src/Exception/PermissionLexerException.php, src/Exception/PermissionParserException.php, src/Library.php, src/PermissionParser.php, tests/Configuration/ComposerConfigurationTest.php, tests/Configuration/LowlevelChecksTest.php, tests/Library/BoltLibraryTest.php
=> Move exception classes to Bolt\Exception

src/YamlUpdater.php
The idiot who wrote that in the first place apologises.
=> Scan file iteratively, instead of recursively. Fixes #2611.

theme/base-2014/_recordfooter.twig, theme/default/_recordfooter.twig
the default theme did not work out of the box because of files not found
fixes #https://github.com/bolt/bolt/issues/2649
Changelog
---------
* Fixed: Default theme out of the box (see https://github.com/bolt/bolt/issues/2649)
=> Issue 2649 fix default theme

app/resources/translations/en_GB/messages.en_GB.yml, app/view/twig/_macro/_macro.twig, app/view/twig/changelog/_macros.twig, app/view/twig/components/panel-lastmodified.twig, src/Controllers/Frontend.php, src/Logger/ChangeLogItem.php, tests/Extensions/ExtensionsProviderTest.php
This is more work on the change log viewing...  Working, but `textarea` and `markdown` field types still need love...  UI needs advice/PRs.
=> More logging updates

src/Extensions.php
=> Have require failures report an error for extension loading

.scrutinizer.yml, src/BaseExtension.php, tests/BoltUnitTest.php, tests/Extensions/BaseExtensionTest.php, tests/Extensions/Mock/ExtendedExtension.php
This takes the base extension class up to 98% coverage.
=> BaseExtension test improvements

app/view/twig/_base/_page.twig, app/view/twig/editcontent/_fields.twig, app/view/twig/editcontent/fields/_geolocation.twig, app/view/twig/editcontent/fields/_markdown.twig
- Load include files only once (includes would have been multiple times for geolocation)
- Load ckeditor only on pages with a html field
Not the big art of software design, but pragmatically and working in the sense of our beloved k.i.s.s.
=> Edit field includes (geolocation/html)

app/view/twig/dbcheck/dbcheck.twig
=> small ui improvement

src/Composer/Action/CheckPackage.php, src/Composer/Action/DumpAutoload.php, src/Composer/Action/InstallPackage.php, src/Composer/Action/RemovePackage.php, src/Composer/Action/RequirePackage.php, src/Composer/Action/SearchPackage.php, src/Composer/Action/ShowPackage.php, src/Composer/Action/UpdatePackage.php, src/Composer/Factory.php, src/Composer/PackageManager.php, src/Controllers/Extend.php, src/Exception/BoltComposerException.php, src/Exception/PackageManagerException.php
* Simplify constructors for Bolt\Composer\Action classes
* Fix "Run all Updates"
* Fix package initial install
* Catch and log to the system log errors in the Action 
* Clean up Bolt\Controllers\Extend
=> Updates to Extend/Composer

src/Composer/Action/ShowPackage.php
=> Make ShowPackage::execute() optionally query the Bolt installs root composer.json

app/view/sass/modules/_dashboard.scss, app/view/twig/dashboard/_recently_edited.twig, app/view/twig/users/_panel-actions_users.twig, app/view/twig/users/_sessions.twig, app/view/twig/users/_userlist.twig
-fixed wrong class declaration
-deleted unneeded class
-centered "add User-Button"
-make the "User Tables" responsive so the screen width does not scroll
anymore on mobile
=> various fixes

src/TwigExtension.php
Depends on https://github.com/bolt/bolt-thumbs/pull/16
=> Generating thumbs route

src/Controllers/Routing.php, src/Storage.php, tests/Storage/StorageTest.php
- No more statics
- I think config parsing is easier to follow
- Moved two methods from Storage to Routing (10d2296)
=> Cleanup Routing Controller

app/view/twig/files/_folders.twig
attempts to redirect user to http when using some links over https
=> fixes issue using file manager over https

composer.json, src/Application.php, src/Config.php, src/Content.php, src/Controllers/Frontend.php, src/Database/IntegrityChecker.php, src/Helpers/String.php, src/Storage.php, src/TwigExtension.php, src/Users.php, tests/Helper/StringTest.php, tests/Provider/SlugifyProviderTest.php
=> Implement slugify and kill one more old lib.php function

src/Library.php, tests/Library/BoltLibraryTest.php
=> Use ISO/IEC 80000 format

src/Config.php
=> Flip array replace arguments

src/Cache.php, src/Controllers/Async.php, src/Controllers/Extend.php, src/Exception/FilesystemException.php, src/Extensions.php, src/Filesystem/FilePermissions.php, src/Filesystem/Manager.php, src/Nut/ConfigGet.php, src/Nut/ConfigSet.php, src/Provider/CacheServiceProvider.php, src/Provider/FilePermissionsServiceProvider.php, src/YamlUpdater.php, tests/Cache/CacheTest.php, tests/Controller/BackendTest.php, tests/Events/CronEventTest.php, tests/FilePermissions/FilePermissionsTest.php, tests/Nut/CacheClearTest.php, tests/Nut/ConfigGetTest.php, tests/Nut/ConfigSetTest.php, tests/Provider/FilePermissionsServiceProviderTest.php
The rival to #2720. Personally I like this one. However there are still some things that need to be done and the tests need to be adjusted.
=> [RFC] Flysystem vs Filesystem - Take 2

src/Cache.php, src/Composer/Factory.php, src/Extensions.php, src/Nut/ConfigGet.php, src/Nut/ConfigSet.php, src/Provider/CacheServiceProvider.php, src/YamlUpdater.php
=> Insight cleanup

composer.json, src/Helpers/String.php, tests/Helper/StringTest.php
Fixes #2729
* Tested with tags, taxonomies, select values, etc.  All work.
* PHPUnit tests changed to expect the correct transliteration.
=> Refactor out last instance of "URLify" 

src/Exception/LowlevelException.php
Dedicated to @tobias2k :beers:
=> Output plain text on the CLI for fatal errors in LowlevelException

src/Controllers/Backend.php
Fixes #2763 for stable branch
- Fixed: Logged in user can no longer disable themselves
=> New users and the current users don't need to disable themselves

src/Config.php
=> Only added flash errors on backend requests. Fixes #2774

src/Controllers/Async.php
Fixes #2776. Thanks to @GawainLynch for pointing me in the right direction!
=> Async::makeuri - Converting query parameter to boolean

app/view/twig/_sub/_messages.twig
=> Block flooding/duplicate FlashBag messages

src/Controllers/Backend.php
=> Check that there is a current user before checking isEnabled()

src/Content.php
=> Return only a single related ID when required in Content::related()

src/Composer/Action/RequirePackage.php, src/Composer/Factory.php, src/Composer/PackageManager.php
- Added: Installed extensions now defaults to adding version constraints to allow for easier updating
=> Use contraints for installed extension packages

tests/Translation/TranslationFileTest.php, tests/Translation/TranslatorTest.php
First batch of work on test suite for the Translation classes
=> Tests for Bolt Translation module

src/Application.php, src/Controllers/Frontend.php, src/TemplateChooser.php
=> Fix 'twig.logger' is not defined errors

src/Filesystem/Local.php
=> [For Testing] Windows - replace backslashes where present

app/view/twig/dashboard/_quicklinks-buttons.twig, app/view/twig/dashboard/_quicklinks-dropdown.twig, app/view/twig/nav/_secondary-content.twig, app/view/twig/overview/_panel-actions_overview.twig, src/Application.php, src/Controllers/Backend.php, src/Extensions.php, src/Omnisearch.php, tests/Extensions/ExtensionsProviderTest.php
Also a couple other things.
Is everyone ok with `app->path()`? (3658157)
=> Fix Omnisearch to generate paths

app/view/twig/nav/_secondary-configuration.twig
Fix configuration menu config file edit links
=> Fix configuration menu config file edit links

src/Database/IntegrityChecker.php
This should take care of #2491.
Cheers!
=> fix fatal when field type is unknown

app/view/sass/modules/_aside.scss
=> Fix overflow in dropdown in the sidebar for Firefox.

app/view/twig/editcontent/editcontent.twig
=> Display incoming relations in relationships tab

app/view/twig/activity/systemlog.twig, src/BaseExtension.php, src/Cache.php, src/Composer/Action/DumpAutoload.php, src/Composer/Action/InstallPackage.php, src/Composer/Action/RemovePackage.php, src/Composer/Action/RequirePackage.php, src/Composer/Action/SearchPackage.php, src/Composer/Action/UpdatePackage.php, src/Composer/Factory.php, src/Config.php, src/Content.php, src/Controllers/Async.php, src/Controllers/Backend.php, src/Controllers/Cron.php, src/Controllers/Frontend.php, src/Controllers/Login.php, src/Extensions/StatService.php, src/Logger/DeprecatedLog.php, src/Logger/Handler/SystemHandler.php, src/Storage.php, src/TwigExtension.php, src/Users.php, tests/Extensions/BaseExtensionTest.php, tests/Twig/BoltTwigHelpersTest.php
If it hasn't broken now, we're good.  Shifting calls to PSR-3 to keep @CarsonF from complaining 
**Added bonus:** That damn array dump in the tests is gone!
=> Logging prep for beta

app/view/twig/email/firstuser.twig, app/view/twig/email/pingtest.twig, src/Controllers/Async.php, src/Controllers/Backend.php, src/Users.php
I am submitting this for 2.1 — @rossriley style ![@rossriley style](http://i0.kym-cdn.com/photos/images/newsfeed/000/313/188/13b.jpg)
What it adds in existing codepaths is close to zero and is foundational for what we want to attempt in 2.2. It also allows "in the know" people to test their email set up ahead of #2863's additional fixes to address the full range of problems.
=> Hotfixing mailer handling

app/view/twig/dashboard/_aside.twig, src/Controllers/Async.php
=> Don't show 'latest activity', when there is none.

src/Controllers/Routing.php
=> Fix Routing controller creation

src/Controllers/Routing.php
Fixes #2905
Routing middlewares - creating class so method doesn't get called statically. 
This will also fix middlewares from extensions
=> Routing middlewares fix calling statically 

src/Storage.php
=> Remove log line

src/Controllers/Async.php, src/Logger/ChangeLog.php
=> Only set query values that exist

src/Composer/Action/RequirePackage.php, src/Composer/Action/SearchPackage.php
Fixes #2911
Fixes #2913
Resolves #2912 (not an issue)
=> Extend composer updates

src/BaseExtension.php
Made config variable public. Still at least it's defined now.
=> Extension config variable public

src/Application.php, src/Config.php, src/Provider/TemplateChooserServiceProvider.php, src/Render.php
=> Allow theme template loading on async paths

src/Config.php
=> Check that select field's value key is set

src/Library.php, tests/Controller/LoginTest.php
Fixes #2653
If the user doesn't have access to the backend, redirect them to the frontend.
=> Fix redirect loop.

app/view/twig/editcontent/_fields.twig
=> Fix #2961 (No fields are shown in editor)

src/Controllers/Backend.php, src/Library.php
=> Use $app->redirect() on valid first user creation to skip checks

src/Application.php, src/Provider/RoutingServiceProvider.php, src/Routing/ControllerResolver.php, src/Routing/UrlMatcher.php
=> Allow extensions to be used as controllers (non static)

app/view/lib/bolt/init.js, app/view/lib/jquery-watchchanges/jquery-watchchanges.js
Fixes #2994
Will need a JS rebuild, but @rarila has a PR with modified JS, so merge that and one of us can rebuild.
=> Update CKEditor field objects if they exist on AJAX content saves

src/Application.php, src/Composer/Action/RequirePackage.php, src/Composer/Action/ShowPackage.php, src/Composer/PackageManager.php, src/Configuration/ResourceManager.php, src/Controllers/Async.php, src/Controllers/Backend.php, src/Controllers/Cron.php, src/Controllers/Extend.php, src/Controllers/Frontend.php, src/Controllers/Routing.php, src/Controllers/Upload.php, src/Events/StorageEvent.php, src/Filesystem/Local.php, src/Filesystem/Manager.php, src/Filesystem/Plugin/AdapterPlugin.php, src/Filesystem/Plugin/Authorized.php, src/Filesystem/Plugin/ThumbnailUrl.php, src/Logger/ChangeLogItem.php, src/Logger/Handler/SystemHandler.php, src/Logger/Manager.php, src/Nut/ConfigGet.php, src/Nut/ConfigSet.php, src/Permissions.php, src/Provider/GuzzleServiceProvider.php, src/Provider/PrefillServiceProvider.php, src/Storage/Prefill.php, src/TwigExtension.php
Dedicated to the friends of OCD
=> Coding style

tests/Composer/Action/CheckPackageTest.php, tests/Composer/Action/InstallPackageTest.php, tests/Composer/Action/SearchPackageTest.php, tests/Composer/Action/ShowPackageTest.php, tests/Composer/Action/UpdatePackageTest.php, tests/Composer/FactoryTest.php, tests/Filesystem/ManagerTest.php, tests/Logger/ChangeLogItemTest.php, tests/Logger/LogManagerTest.php, tests/Logger/RecordChangeHandlerTest.php, tests/Logger/SystemHandlerTest.php, tests/Mocks/DoctrineMockBuilder.php, tests/Mocks/LoripsumMock.php, tests/Storage/StorageTest.php, tests/Translation/TranslationFileTest.php, tests/Translation/TranslatorTest.php, tests/Twig/BoltTwigHelpersTest.php
=> Coding style - tests

src/Controllers/Async.php
Fixes #2996
Ping @CarsonF — can you check with the slaves configuration please.
=> Use QueryBuilder for Async::tags() and Async::populartags()

app/config/contenttypes.yml.dist, app/view/twig/editcontent/fields/_select.twig
.. and snuck in some assorted goodies.
=> Fix sorting in 'select'-fields. Fixes #2991

src/Configuration/ResourceManager.php
=> Added base path to current url

src/DataCollector/BoltDataCollector.php
=> Don't duplicate 'beta 3' in the profiler nub.

src/Composer/CommandRunner.php
Give a helpful error message for extension errors when allow_url_fopen is disabled
=> Allow_url_fopen error message 2.0.x

src/Extensions/ExtensionsInfoService.php
Throw exception if allow_url_fopen is disabled.
=> Throw exception if allow_url_fopen is disabled.

src/Provider/TranslationServiceProvider.php
=> Only add yml and xlf files

app/view/Gruntfile.js
Ok, we now care for quoted urls in lib css.
Fixes #3029
=> Fix for #3029

app/config/config.yml.dist
Oh, "files" in plural is even better, but I don't know how to change the pull request.
=> Difference between files and images

tests/scripts/config.yml.dist, tests/scripts/coverage.php
* Cleaner (a little, it's for devs)
* Better error handling
* Prettier
* Ability to define a personal GitHub token… think rate limits and eventually posting directly to the PR.
=> Coverage tool enhancements

app/view/twig/activity/systemlog.twig, src/Controllers/Frontend.php
=> Return the error from Twig rather than swallow it

src/Controllers/Backend.php
Fixes #3056
I am hanging my head in shame at this one… I blame the :koala:
=> Don't redirect to 'Users' page on form validation failure

src/Application.php, src/Storage.php
Nobody tell @CarsonF that I missed these… I'll never live it down :grinning:
=> Missing s/addCritical/critical/ on some logger.system calls

src/Composer/ExtensionInstaller.php
This should prevent Insight, Gawain, Ross, Carson, and myself from twitching.
Cheers!
=> handle proper event types from composer

src/Application.php, src/Controllers/Async.php, src/Controllers/Backend.php, src/Controllers/Frontend.php, src/Controllers/Login.php, src/Controllers/Upload.php, src/Database/IntegrityChecker.php, src/Translation/TranslationFile.php
Dibs on early merge when we branch, before everyone starts pulling controllers apart.
=> Use Response constants for HTTP return codes

src/Content.php
=> bugfix/generating-taxonomy-links 2.2

src/TwigExtension.php
=> Account for base path in menu links.

src/TwigExtension.php
=> Account for base path in menu links 2.2

src/Configuration/ResourceManager.php
Don't reset urls when adding base path.
Relevant to #3016
=> Don't reset urls when adding base path.

.gitignore
Updated to take into account #3080
=> Add app/src/tmp/ to gitignore and tidy up a touch

src/Provider/TranslationServiceProvider.php
=> Remove SplFileInfo::getExtension 2.1

src/Provider/TranslationServiceProvider.php
=> Remove SplFileInfo::getExtension 2.2

src/Application.php
Fixes #3102
With help and debugging of @GawainLynch!
=> Fix database connection exception leaking information 2.1

src/Application.php
=> Fix database connection exception leaking information 2.2

src/Composer/ScriptHandler.php
Un-breaks current master `composer create-project bolt/composer-install` installs
=> Hotfix composer install scripts

contributing.md
Noticed these and thought this would be an easy first contribution to Bolt from my side ;)
Totally related: Is there even a single person who likes brown M&M's? I don't know any.
=> Fix grammar and typos in contributing.md

.travis.yml, composer.json, tests/scripts/travis-db-config
=> Have Travis run acceptance test on MySQL in addition to Sqlite

.travis.yml, composer.json, tests/scripts/travis-db-config
Requires #3162 
This gives us, on a git install (currently), coverage of our 3 supported database installs
=> Have Travis run acceptance test on PostgreSQL in addition to Sqlite & MySQL

src/Composer/Action/BoltExtendJson.php
=> Workaround Bolt 2.0 installs with "require": []

src/Nut/DatabasePrefill.php, src/Provider/NutServiceProvider.php
=> Add a database pre-fill command to Nut

src/Cache.php, src/Controllers/Backend.php
=> Flush the cache if the Bolt version has changed

src/Storage.php
=> Allow ||| queries to be more complex (2.1)

src/Controllers/Frontend.php, src/Storage.php
Only log content not found errors if slug isn't numeric, since next it next checks by id.
=> Only log content not found errors if slug isn't numeric, since next it next checks by id. 2.2

src/Storage.php, tests/phpunit/Storage/StorageTest.php
=> Fix Storage not using sort from contenttype for 2.1 #2

src/Content.php
=> Fixed ParsedownExtra usage (2.1)

src/Logger/ChangeLog.php, src/Storage.php
Fix changelog content tablenames
=> Fix changelog content tablenames 2.1

src/Logger/ChangeLog.php, src/Storage.php
Fix changelog content tablenames
=> Fix changelog content tablenames 2.2

src/Render.php, src/Response/BoltResponse.php, tests/phpunit/unit/Controller/ExtendControllerTest.php, tests/phpunit/unit/Response/BoltResponseTest.php
=> BoltResponse updates

src/TwigExtension.php, tests/phpunit/unit/Controller/FrontendTest.php
test to cover functionality in #3214
=> add test for new canonical url behaviour

src/Configuration/ResourceManager.php, tests/phpunit/unit/Configuration/ResourceManagerTest.php
=> Handle canonical config settings that don't include a scheme

app/view/twig/activity/systemlog.twig, src/Logger/Handler/SystemHandler.php, src/Nut/BaseCommand.php, src/Nut/CacheClear.php, src/Nut/ConfigGet.php, src/Nut/ConfigSet.php, src/Nut/CronRunner.php, src/Nut/DatabaseCheck.php, src/Nut/DatabasePrefill.php, src/Nut/DatabaseRepair.php, src/Nut/Extensions.php, src/Nut/ExtensionsDisable.php, src/Nut/ExtensionsEnable.php, src/Nut/Info.php, src/Nut/LogClear.php, src/Nut/LogTrim.php, src/Nut/TestRunner.php, src/Nut/UserAdd.php, src/Nut/UserRoleAdd.php, src/Nut/UserRoleRemove.php, tests/phpunit/unit/Nut/LogClearTest.php, tests/phpunit/unit/Nut/LogTrimTest.php
* Fixes #3172
* Set $app['request'] in BaseCommand to enable logging and getContent() functionality in Nut commands
* Add an audit log wrapper function to BaseCommand
* Logs (by default) system modifying events in the system log
* Adds a 'nut' context to the system log UI
* PHPDoc love
=> Washers for Bolt's Nuts

app/view/twig/nav/_secondary-content.twig
=> Revert "Allow 'name' in contenttype to override translation, for 2.1.x"

src/Composer/PackageManager.php
=> Don't break when keywords aren't set.

app/view/twig/editcontent/fields/_integer.twig
=> Fix strange step behaviour when no min is set for integer fields

app/src/sass/modules/_ckeditorcustom.scss, app/src/sass/modules/_editcontent.scss
As a followup to #3274. See screenshot:
=> Minor tweaks, to make wysi and markdown a bit more similar.

src/TwigExtension.php, tests/phpunit/unit/Twig/BoltTwigHelpersTest.php
"Fixes" #3306 and makes it easier to predict bolt-thumbs image generation.
=> Add exif aspect ratio and exif orientation data to imageinfo()

.travis.yml, src/Controllers/Backend.php, tests/phpunit/unit/Controller/BackendTest.php
This takes test coverage up to 85%
Most of the remaining coverage is for edge cases in editContent and files methods which will be a little more indepth to do so getting this lot in first.
=> Part 2: Backend controller tests

src/Content.php, theme/base-2014/record.twig
As suggested by @miguelavaqrod in #3303
=> Fix path for non-ajaxy file-upload.

theme/base-2014/record.twig
Thanks to Degin and Intendit, on IRC..
=> Fix checks for empty arrays in record.twig

app/view/twig/activity/systemlog.twig
=> Add storage to the system log context

src/Application.php
=> Only setting default timezone if config provides it

src/TwigExtension.php, tests/phpunit/unit/Twig/BoltTwigHelpersTest.php
And add lat, long and datetime.
=> Move exif info to it's own array

src/Application.php, src/Config.php, src/Database/IntegrityChecker.php, tests/phpunit/unit/Nut/DatabaseCheckTest.php, tests/phpunit/unit/Nut/DatabaseRepairTest.php
…I may have also accidentally done some type hints and PHPDoc.
=> Allow explicit setting of a Contenttype's table name suffix

src/Composer/PackageManager.php, src/Controllers/Async.php
=> Catch Guzzle 3 & 5 errors

app/src/js/modules/editcontent.js, app/view/twig/extend/install-package.twig
=> Small UX improvement: Show spinner while doing ajaxy save.

src/Filesystem/Plugin/ThumbnailUrl.php, src/Provider/SafeTwigServiceProvider.php, src/Provider/TwigServiceProvider.php, src/Twig/Handler/AdminHandler.php, src/Twig/Handler/ArrayHandler.php, src/Twig/Handler/HtmlHandler.php, src/Twig/Handler/ImageHandler.php, src/Twig/Handler/RecordHandler.php, src/Twig/Handler/TextHandler.php, src/Twig/Handler/UserHandler.php, src/Twig/Handler/UtilsHandler.php, src/Twig/TwigExtension.php, tests/phpunit/unit/BoltUnitTest.php, tests/phpunit/unit/DataCollector/TwigDataCollectorTest.php, tests/phpunit/unit/Twig/BoltTwigHelpersTest.php
Quoth @bobdenotter in #3327
> [Sure. But why? :-)](https://github.com/bolt/bolt/pull/3327#issuecomment-90966593)
:koala: :hear_no_evil:
=> Start of refactor of TwigExtensions

src/Application.php, src/Controllers/Backend.php
This could be a bit of a mission… and help from Club OCD would be good.
=> Scrutinizer review clean ups

src/Provider/LoggerServiceProvider.php
Probably should be cherry-picked into release/2.1 too
=> Set the SystemHandler default log level to Logger::INFO

src/Composer/Action/ShowPackage.php
=> Sort package names

composer.json
At best a tiny performance optimisation, at the most obvious… CDO.
=> Move the autoloader for testing classes into autoload-dev

app/view/twig/editcontent/fields/_image.twig
This PR adds the ability to use on image field Alt text and title on same time
=> Fix to use title and alt text on image field

src/Cache.php, src/Controllers/Backend.php, src/Controllers/Extend.php, src/Controllers/Frontend.php, src/Controllers/Login.php, src/Controllers/Upload.php, src/Library.php
=> More code cleanups

src/Config.php, src/Configuration/ResourceManager.php, src/Content.php, src/Controllers/Backend.php, src/Controllers/Cron.php, src/Database/IntegrityChecker.php, src/Database/Migration/AbstractMigration.php, src/Database/Migration/Export.php, src/Permissions.php, src/Twig/TwigExtension.php, src/Users.php
=> Clean ups, PHPDoc, etc.

src/Translation/Translator.php
Hope the :koala: is now able to sleep :zzz: again ;-))
=> Make Translator class scruti-nicer

src/Controllers/Async.php, src/Controllers/Backend.php, src/Provider/TwigServiceProvider.php, src/Storage.php, src/Users.php
**Notable code change**:
In Users I have just replaced the super globals. This needs attention when we branch for v3. But we're calling Request::createFromGlobals() to get the data out of scope, so let's leverage that in the meantime.
=> Further clean up

src/Composer/Action/ShowPackage.php
A few bags of rice fall down in China… ;-)
Nothing to see here, go on!
=> "Refactoring" of ShowPackage.php

app/config/config.yml.dist, src/Controllers/Async.php, src/Controllers/Backend.php, src/Users.php
Makes the ability to set the sender Mail and sender name in the config.yml
@issue: https://github.com/bolt/bolt/issues/3376
=> Ability to set a Email Sender Mail in config.yml

src/Controllers/Extend.php, src/Database/Migration/Output/YamlFile.php, src/Extensions/ExtensionsInfoService.php, tests/phpunit/unit/Extensions/InfoServiceTest.php
=> Move the ExtensionsInfoService to use the Guzzle provider

src/Composer/Action/BoltExtendJson.php, src/Composer/PackageManager.php, src/Controllers/Async.php
May the scrutinizer score go up!
=> Various cleanups

src/Composer/ScriptHandler.php
=> Composer install backport fixes for 2.1

src/Config.php, src/Logger/ChangeLog.php, src/Storage.php
This is a follow up to #3342… because… :koala:
=> More Contenttype table name fun

app/config/contenttypes.yml.dist, src/Config.php
Technically this isn't limited to Contenttypes, but that is where it makes the most sense and add the greatest amount of value… Calling #1555  on the PHP code change!
Full credit for the idea goes to @rossriley, resulting from [this Gist](https://gist.github.com/rossriley/0a2dc17108ac9f2f13b3)
@bobdenotter if you agree that this is worthy of Bolt, I will follow up with a PR on bolt/docs.
:koala: goes and eats :leaves:
=> YAML repeated nodes

app/view/twig/editcontent/_aside.twig
=> do not show the delete button if this is a new record

src/Events/StorageEvent.php
=> remove the strict typehint and change doc param to match

src/Controllers/Backend.php, src/Users.php
Hey,
i have refactored the getUser function to make it effective when a single user will be getted
=> Refactoring getUser

src/Twig/Handler/RecordHandler.php, theme/base-2014/config.yml
Enhancement to define templates for the template chooser in backend
@issue: #3338
=> Enhancement to define templates for the template chooser in backend

src/Storage.php
Thank you for bringing this to our attention, Tameroski.
=> Make sure we set the status correctly for 'async' requests.

tests/phpunit/unit/Composer/FactoryTest.php
This is due to changes in upstream Composer (npm compatibility)
Fixes #3468
=> [Tests] Update expected result from findBestVersionForPackage() 

tests/phpunit/Composer/FactoryTest.php
This is due to changes in upstream Composer (npm compatibility)
Fixes #3468
=> [Tests] Update expected result from findBestVersionForPackage()

app/resources/translations/en_GB/messages.en_GB.yml, src/Controllers/Backend.php, tests/phpunit/unit/Controller/BackendTest.php
A better PR this time for #3491
=> Adding check for issue 3491 (password must be different from username)

src/Extensions.php
=> Handle empty composer config, e.g. themes

tests/phpunit/BoltListener.php
=> [Tests] Write out test timer after cache flush

src/Users.php
=> Bolt\Users exception handling

src/Storage.php
copy of #3523 for 2.1 release branch
=> Cast booleans to integer to force correct PDO handling

src/Content.php
See http://stackoverflow.com/questions/30242572/bolt-getting-blank-screen-after-upgrading-to-2-2beta
=> Make sure `$unserdata` is an array, and not merely `false`

app/config/config.yml.dist
Totally calling #1555 on this too.
=> Make comment line lengths consistent, and break up text to be more readable.

src/BaseExtension.php, src/Extensions.php
There are several reasons that this got overlooked:
* Gnomes
* :koala:'s not having the right :leaves: 
* Coding sober
Depends on #3528
=> Make addCss() and addJavascript() function declaration and handling consistent

src/Nut/DatabaseExport.php, src/Nut/DatabaseImport.php, src/Nut/LogClear.php
I don't think these classes exist (so does PhpStorm). Replaced them with the correct class (confirmed by get_class).
=> Fix classnames

theme/base-2014/config.yml
As HTML is one of the most problematic fields when it comes to template fields, it makes sense that we have it here for testing.
Helps #3516 
Ping @rarila
=> Change section in templatefields example to html

app/src/js/modules/liveeditor.js
=> HTML template fields updated after live edit. Fixes #3516

.travis.yml, src/Controllers/Backend.php
=> On "Save and return to overview", save and return to overview.

app/src/js/modules/files.js, app/view/twig/files/files.twig, src/Controllers/Async.php
"Create File" Button in Filebrowser
Fixes #3180
=> "Create File" Button in Filebrowser

composer.json, src/Application.php, src/Debug/WebProfilerServiceProvider.php
…would you like some derp with that derp, sir?
=> Require Silex WebProfiler ^1.0.6

composer.json
These guys are turning into my idea of a bad joke… another patch release, another breaking refactor.
This is what's broken the last few Travis runs for people. :frowning:
=> Lock the Codeception version to 2.0.12

src/Controllers/Backend.php
Note: This is a fix #3604 for 2.2. Should also be fixed for `master`.
=> Fixes server-side error when ajaxy-deleting records that were created programmatically

src/Composer/PackageManager.php, src/Config.php, src/Content.php, src/Controller/Backend/Database.php, src/DataCollector/BoltDataCollector.php, src/Helpers/MenuBuilder.php, src/Twig/Handler/AdminHandler.php, tests/phpunit/unit/Controller/Backend/DatabaseTest.php
Fixes #3599
Removes last use of `Lib::path()` in core
=> URL generation

src/BaseExtension.php, src/Database/Migration/Output/JsonFile.php, src/Extensions/ExtensionsInfoService.php, src/Storage/Prefill.php
* Clean up of stuff that I missed on last pass
* Change BaseExtension::initialize() to be abstract (c.f. #3257)
=> PHP 5.3 cleanout

src/Composer/PackageManager.php, src/Extensions/ExtensionsInfoService.php
=> [2.2] Extend SSL/TLS Handling 

app/view/twig/_macro/_macro.twig
=> Explicitly get the title, instead of 'preferring' a field named title.

src/Composer/Action/BoltExtendJson.php, src/Composer/EventListener/BufferIOListener.php, src/Composer/EventListener/PackageEventListener.php, src/Composer/ExtensionInstaller.php, src/Composer/PackageManager.php, src/Configuration/ResourceManager.php, src/Controller/Backend/Extend.php, src/Provider/ExtensionServiceProvider.php
* Change the namespace(s)
* Events now run for CLI installs/uninstalls
* No more copying events class to `extensions/`
=> Extension Composer events

app/view/twig/email/firstuser.twig, src/Controller/Backend/Authentication.php, src/Controller/Backend/BackendBase.php, src/Controller/Backend/Users.php, tests/codeception/acceptance/000-FirstUser/FirstUserCest.php
This change does the login after successful first user creation and greets them warmly :smile:
=> Streamline first user creation UX

src/Helpers/Menu.php, src/Helpers/MenuBuilder.php
Fixes #3647 
PR for master: #3649
=> [2.2] Menu link regression

src/Helpers/Menu.php, src/Helpers/MenuBuilder.php
=> Menu link regression

src/Helpers/MenuBuilder.php
**Partly**(!) fixes #3655 
Thanks to @hartigdan!
And sry that I said you are wrong.
=> Fixes bug in populateItemFromRecord

src/Controllers/Frontend.php
=> Generate search pager link

src/Controller/Frontend.php
=> Generate search pager link 2.3

tests/phpunit/unit/Helper/MenuBuilderTest.php
It references to #3655 
Just one test for the moment. Will add some more test by time
=> Added unit test for the MenuBuilder helper populateItemFromRecord method

src/Nut/ConfigGet.php, src/Nut/ConfigSet.php, src/YamlUpdater.php
=> Fix/yaml config readwrite for 2.2 release branch

app/view/twig/email/firstuser.twig
=> Fix a spelling mistake

app/view/twig/email/firstuser.twig
=> Fix spelling mistake

app/resources/translations/de_DE/messages.de_DE.yml
Updated messages.de_DE.yml content
=> German translation

src/Composer/Action/UpdatePackage.php, src/Composer/PackageManager.php, src/Config.php, src/Configuration/Check/BaseCheck.php, src/Configuration/ResourceManager.php, src/Controller/Backend/FileManager.php, src/Controller/Backend/Upload.php, src/Cron.php, src/Events/CronEvent.php, src/Events/StorageEvent.php, src/Filesystem/FilePermissions.php, src/Filesystem/Plugin/AdapterPlugin.php, src/Filesystem/Plugin/Browse.php, src/Helpers/MenuBuilder.php, src/Library.php, src/Logger/ChangeLogItem.php, src/Logger/Manager.php, src/Nut/BaseCommand.php, src/Nut/CronRunner.php, src/Nut/DatabaseExport.php, src/Provider/MarkdownServiceProvider.php, src/Provider/RenderServiceProvider.php, src/Render.php, src/Storage/RecordModifier.php, src/TemplateChooser.php, src/Translation/ContenttypesKeygen.php, src/Translation/TranslationFile.php, src/Twig/Handler/TextHandler.php, src/Users.php
* PHPDoc
* Removed some loose comparisons
* Bug fix in MenuBuilder
* Bug fix in ChangeLogItem
* 60 Scrutinizer issues resolved
=> Scutinizer based fixes

src/Extensions.php, tests/phpunit/unit/Extensions/ExtensionsProviderTest.php, tests/phpunit/unit/Extensions/resources/local/testvendor/testext/GumLeaves.php, tests/phpunit/unit/Extensions/resources/local/testvendor/testext/composer.json
* Corner case bug fix in Extensions::setLocalExtensionPsr4()
* Move lock file to cache
* Unit tests for local extension autoloader
=> Local extensions autoloader updates & tests

src/Extensions.php, tests/phpunit/unit/Extensions/ExtensionsProviderTest.php, tests/phpunit/unit/Extensions/resources/local/testvendor/testext/GumLeaves.php, tests/phpunit/unit/Extensions/resources/local/testvendor/testext/composer.json
=> [2.2] Local extensions autoloader updates & tests

src/Controllers/Frontend.php
Bolt 2.2 version of this PR #3704
=> Add the possibility to use the search for spcific contenttype(s)

src/Storage/Repository/CronRepository.php
Repository class to handle queries on the cron table.
=> Add new cron repository class

app/view/twig/users/_sessions.twig, src/AccessControl/Authentication.php, src/Provider/AuthenticationServiceProvider.php, src/Provider/StorageServiceProvider.php, src/Storage/Repository/AuthtokenRepository.php, tests/phpunit/unit/BoltUnitTest.php, tests/phpunit/unit/Controller/Backend/AuthenticationTest.php, tests/phpunit/unit/Controller/Backend/RecordsTest.php, tests/phpunit/unit/Controller/Backend/UsersTest.php, tests/phpunit/unit/Controller/FrontendTest.php, tests/phpunit/unit/Storage/Repository/AuthtokenRepositoryTest.php, tests/phpunit/unit/Users/AuthenticationTest.php
This PR provides a new Authtoken repository and delegates appropriate queries from the authentication class to the new repository.
**This will depend on another upcoming PR so do not merge yet**
=> Refactor Authtoken to new Storage Layer

src/Users.php
=> Fix divide by zero

src/Config.php, src/Controller/Frontend.php, src/TemplateChooser.php
Fixes #3721. Only used if there is no homepage template selected.
=> Allow selection of homepage template based on content

src/Controller/ConfigurableBase.php
=> Fix regex route requirements

src/AccessControl/Login.php, src/AccessControl/Password.php, src/AccessControl/Token/Generator.php, src/Composer/EventListener/PackageEventListener.php, src/Controller/Backend/Users.php, src/Events/CronEvent.php, src/Events/StorageEvent.php, src/Storage/Database/Schema/CheckResponse.php, src/Storage/Repository/ContentRepository.php, src/Users.php
Some :leaves: for the :koala:.
Cheers!
=> cleanup imports

README.md
Added configuration examples of Debian Jessie and Ubuntu 14.04
=> Added configuration examples for Debian Jessie and Ubuntu 15.04

src/Helpers/Str.php, tests/phpunit/unit/Helper/StrTest.php
Don't forget to ``composer update``
Makes use of the new cocur/slugify 1.2 feature to preserve uppercase chars.
Also added Tests.
=> Helper/Str.php non-strict makeSafe() can has Uppercase

tests/phpunit/unit/Pager/PagerTest.php
Added Pager::makeParameterId unit test
Added Pager::makelink unit test
=> Added pager unit tests

src/Composer/PackageManager.php
this gets rid of the "undefined" versions and adds a button for the extension config on the extension page
=> config button in extension overview

src/Application.php, src/Library.php, tests/phpunit/unit/BoltUnitTest.php, tests/phpunit/unit/Controller/BackendTest.php
=> Add caching for the translation provider

README.md
=> Add 3rd party install options section to the readme

app/view/twig/components/panel-activity.twig
Prevents a HTTP 500 on new installs
=> Pass whole array to activity panels

tests/phpunit/unit/Controller/FrontendTest.php
Checks if the canonical in relation to config and url schema. Added this because the bahaviour could change.
=> Added canonical setting test for Frontend

src/Provider/TranslationServiceProvider.php, tests/phpunit/unit/Provider/TranslationServiceProviderTest.php
See #3553 for the initial discussion.
I've added a test case to validate this new functionality, and also 2 other test cases covering the existing behavior of `TranslationServiceProvider`.
Let me know what you think about this.
=> Make translations overridable

src/Storage/Migration/Export.php
1. Fix typo on this 
2. Fix difference between how contenttype array was constructed… for single vs multiple contenttypes
=> Minor fixes for database export command

src/Database/Migration/Export.php
2.2 Branch version of #3811 
1. Fix typo on this
2. Fix difference between how contenttype array was constructed… for single vs multiple contenttypes
=> Minor fixes for database export command (2.2 branch)

app/view/twig/editcontent/fields/_geolocation.twig
=> [2.2] Regression in Geolocation: Change value "_address" back to "formatted_address" 

src/Database/IntegrityChecker.php
=> [2.2] Trigger database update notifications for changed field names

src/Storage/Database/Schema/CheckResponse.php
=> Trigger database update notifications for changed field names

app/view/twig/_base/_listing.twig
=> Fix #3821 – Sort order handle for records is always displayed

.travis.yml, tests/phpunit/unit/Composer/Action/ShowPackageTest.php
=> Workaround for Travis/Composer failures

app/resources/translations/de_DE/messages.de_DE.yml, app/resources/translations/en_GB/messages.en_GB.yml, app/resources/translations/nl_NL/messages.nl_NL.yml, app/view/twig/editcontent/fields/_markdown.twig
Backport of #3820 for Bolt 2.2.x
=> Update JS Markdown Options to match Parsedown [2.2]

src/Provider/DatabaseSchemaProvider.php, src/Storage/Database/Schema/Manager.php
=> Have schema DI include ContentTypes

.travis.yml
c.f. https://github.com/composer/composer/commit/ff84b32097796106757a088327ff09fad4e18534 and #3829
=> [Travis] Use degraded mode for Composer

app/bootstrap.php
=> Alias field classes

src/Helpers/MenuBuilder.php, src/Storage/RecordModifier.php
=> Update usages of "fragment" key to "#"

app/view/twig/_base/_listing.twig
=> Fixing layout issue in Chrome 44. Pretty sure it's a weird bug in Chrome.

app/view/twig/_base/_listing.twig
=> [2.2] Fixing layout issue in Chrome 44. Pretty sure it's a weird bug in Chrome.

src/Controller/Backend/Upload.php
=> Fixes typo in 'UploadNamspace'.

src/Logger/Handler/RecordChangeHandler.php, tests/phpunit/unit/Logger/RecordChangeHandlerTest.php
=> Handle custom Content classes and clean up the class slightly

src/Logger/Handler/RecordChangeHandler.php, tests/phpunit/unit/Logger/RecordChangeHandlerTest.php
=> [2.2] Handle custom Content classes and clean up the class slightly

src/Events/StorageEvents.php, src/Storage.php
=> [2.2] Storage publish/depublish events

app/view/twig/nav/_macros.twig, app/view/twig/nav/_secondary-content.twig
Fixes #3783 as @rossriley suggested.
=> Add custom sidebar groups

src/Storage.php
=> Koalas can't use tense

src/Storage.php
=> Ensure grouped taxonomies aren't wiped from listing pages

src/Storage/Query/ContentQueryParser.php, tests/phpunit/unit/Storage/Query/ContentQueryParserTest.php
Couple of extra tests to up the coverage percentage.
=> Few tweaks to the Query area tests

app/view/twig/_base/_listing.twig, app/view/twig/_sub/_editable_record_list.twig, app/view/twig/dashboard/_recently_edited.twig, app/view/twig/omnisearch/omnisearch.twig, app/view/twig/overview/overview.twig, app/view/twig/relatedto/relatedto.twig, src/Controllers/Backend.php, src/Omnisearch.php, src/Permissions.php
This is the 2.2 backport for #3902
Fixes #3802 for 2.2
@rarila can you give this one the once over to make sure there is nothing obvious… Stable branch targeted and all.
@bnelson-cainc can you please test [the patch](https://patch-diff.githubusercontent.com/raw/bolt/bolt/pull/3906.diff) in your environment to see if it properly solves #3802 for your requirements
=> [2.2] Permissions streamline

app/src/js/modules/liveeditor.js
=> Tiny js docu fix

src/EventListener/StorageEventListener.php, src/Provider/StorageServiceProvider.php, src/Storage.php
Just a slight performance boost in the front end on a default install…
**Before**
**After**
…and for a more complex site…
**Before**
**After**
=> [2.2] Publishing queries speed up

src/AccessControl/Permissions.php
=> Allow edit permission to be assigned to the owner role

src/Permissions.php
=> [2.2] Allow edit permission to be assigned to the owner role

.travis.yml
PSR-7 changes… stable branches… who are we to complain…
=> [Travis] Require Guzzle for Composer based builds

src/Provider/DatabaseSchemaProvider.php
=> Log deprecated use of $app['integritychecker']

src/Application.php
Look what I found! DBAL has a config option to filter tables!
Should fix #2769 and #3936.
=> Filter db tables

app/src/js/modules/video.js
=> Use embedly without protocol. Fixes #3955

app/src/js/modules/video.js
=> [2.2] Fix/protocol less embedly 22. Fixes #3955

src/Application.php
Fixes #3948 #3950
Already done in master as part of the controller refactor.
=> Move initMailCheck() call to a before() handler

app/src/grunt/cssmin.js, app/src/grunt/libcssimg.js
=> Fix/grunt updates for 2.2

app/src/js/extend.js, src/Controller/Backend/Extend.php, src/Exception/ExtensionsInfoServiceException.php, src/Extensions/ExtensionsInfoService.php
=> Provide UI feedback on extension site timeouts

src/Storage/Database/Schema/CheckResponse.php, src/Storage/Database/Schema/Manager.php
This is a forward port of the changes in #3872.
@ntomka could you be so kind as to review/test when you have a second? :beers:
=> Add foreign key checks to schema management checks

app/src/js/extend.js, src/Controllers/Extend.php, src/Exception/ExtensionsInfoServiceException.php, src/Extensions/ExtensionsInfoService.php
**Rebuild Alert:** bolt.js will need attention.
=> [2.2] Provide UI feedback on extension site timeouts

src/Controller/Backend/Records.php
CDO got the better of me while looking at something I wasn't sure if I was going to PR…
=> Update some variable names and comments

src/Controller/Backend/General.php, src/Controller/Base.php, src/Provider/StorageServiceProvider.php, src/Storage/ContentLegacyService.php, src/Storage/Entity/Content.php, src/Storage/Hydrator.php, src/Storage/Query/ContentQueryParser.php, src/Storage/Query/Handler/HydrateHandler.php, src/Storage/Query/Handler/PagingHandler.php, src/Storage/Repository/ContentRepository.php
1. Injects a legacy service into all new content entities via an event listener.
2. Adds some empty handlers for missing query directives.
=> Refactor Wars Episode V: The legacy strikes back

src/AccessControl/Permissions.php
Commit 1549a93 was partially buggy. This makes it work.
See my latest message on #3909 for full details.
=> Truly allow edit permission to be assigned to the owner role

src/Permissions.php
Commit 59003ad was partially buggy. This makes it work.
See my latest message on #3909 for full details.
=> [2.2] Truly allow edit permission to be assigned to the owner role

src/Application.php
As stated in #1405, silexphp/Silex@57d74eb fixed this problem
=> Remove locale hack

app/view/twig/users/_userlist-actions.twig
Fixes #4008.
(The fix for 2.2 is already in. Committed that directly, sorry!)
=> Show profile button on users page, if not allowed to edit other users than yourself.

app/view/twig/changelog/_macros.twig, app/view/twig/changelog/changelogrecordsingle.twig
=> [2.2] Fix changelog single item links

src/Storage.php
The content are not fetched correctly 
See issue #3862 for more Info
=> Fix Timed publish events sending

src/BaseExtension.php, src/Extensions.php
Already in 2.3/master as $app['asset.queue.file']->clear();
Will add to docs after merge.
=> Add clearAssets() for extensions.

src/EventListener/SnippetListener.php
=> Don't add base snippets on async routes

src/AccessControl/Password.php, src/Configuration/Check/EmailSetup.php, src/Controller/Backend/Users.php
:nut_and_bolt:s of this one is that Google tends to flag a lot of these as potential spam checking the spam folder is getting tedious :grin:
=> Spam workaround

src/Twig/TwigExtension.php
If the users table doesn't exist, attempting to fetch user data will throw exceptions. This was the reason white screens were being shown for new set ups on master when hitting the base URL.
**Note:** The storage layer error handling is still to be completed, which will partially mitigate this edge-case being hit, but not prevent it.
:+1: to @CarsonF for finding this after a while spent hunting by both of us.
=> Catch exceptions in user fetches

app/view/twig/_base/_listing.twig
=> Don't show (non working) drag'n'drop in list overviews.

src/EventListener/SnippetListener.php
=> Check the request for isXmlHttpRequest() in SnippetListener

src/Provider/SessionServiceProvider.php, src/Session/Handler/FileHandler.php
* Make sure we respect `session.save-path` settings for file permissions
* Log errors handling session files
=> Session file security and logging

src/BaseExtension.php
=> Add [ $this, .. ] to callback.

.gitignore
Stable branch version of #4079
=> [2.2] Ignore theme directory except for base-* and default

src/Config.php
(edge-case that could happen if you have a contenttype with more than one slug)
=> Make sure the slug is an array.

src/Config.php
(edge-case that could happen if you have a contenttype with more than one slug)
=> [2.2] Make sure the slug is an array.

src/EventListener/ExceptionListener.php
=> Did you see that? :koala:

src/Application.php, src/Composer/PackageManager.php, src/Config.php, src/DataCollector/BoltDataCollector.php, src/Omnisearch.php
[Application] Deprecated and removed usages of Application::generatePath
=> [Application] Deprecated and removed usages of Application::generatePath

src/Application.php, src/Provider/RandomGeneratorServiceProvider.php
Moved randomgenerator to its own service provider
=> Moved randomgenerator to its own service provider

src/Twig/Handler/UserHandler.php, src/Twig/TwigExtension.php, src/Users.php
@gawainlynch can this change be applied to `AccessControl` code as well?
=> Users::token to use csrf provider instead of our own code

src/Application.php, src/Config.php, src/Provider/TranslationServiceProvider.php, src/Translation/TranslationFile.php, src/Translation/Translator.php, src/Twig/Handler/HtmlHandler.php, tests/phpunit/unit/Provider/TranslationServiceProviderTest.php, tests/phpunit/unit/Twig/BoltTwigHelpersTest.php
Also, moved locale initialization into TranslationSP
=> Kill App::DEFAULT_LOCALE

app/config/taxonomy.yml.dist, app/view/twig/editcontent/_taxonomies.twig, src/Config.php
=> Optionally allow spaces in tag names. [2.2]

app/src/README.md
@bobdenotter 's gonna party today! :tada:
=> Grunt tasks documentation

app/src/js/modules/app.js, app/src/package.json
- Works again on windows
- Warning fixed
=> Fix grunt docjs

src/Storage.php
Fixes #4139
Tested on
- PostgreSQL
- MySQL
- Sqlite
=> Timed publishing fix

tests/phpunit/unit/Helper/StrTest.php
See: https://github.com/cocur/slugify/pull/77
=> Fix test after cocur/slugify update.

app/config/contenttypes.yml.dist
Incorrect URL to Documentation listed in app/config/contenttypes.yml.dist
=> Fixed this documentation error

app/view/twig/nav/_macros.twig
=> [2.2] Fix secondary nav element's class not being output in certain cases

src/Legacy/Content.php
=> Use hydration for `{{ record.previous() }}` and `{{ record.next() }}`

src/TemplateChooser.php
=> Don't override "templatechosen" if previously set.

.travis.yml, app/view/twig/_base/_listing.twig, composer.json, tests/codeception/_support/YamlHelper.php, tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php, tests/codeception/acceptance/104-BackendAuthor/BackendAuthorCest.php, tests/codeception/acceptance/_bootstrap.php
=> [2.2] Fix dashboard user permissions not resolving correctly

app/view/twig/_base/_listing.twig, tests/codeception/_support/YamlHelper.php, tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php, tests/codeception/acceptance/104-BackendAuthor/BackendAuthorCest.php, tests/codeception/acceptance/_bootstrap.php
=> Fix dashboard user permissions not resolving correctly

src/EventListener/StorageEventListener.php, src/Legacy/Storage.php, src/Provider/StorageServiceProvider.php, src/Storage/Entity/ContentValuesTrait.php, src/Storage/Query/ContentQueryParser.php, src/Storage/Query/SearchWeighter.php
Forward porting this to prevent regressions if the new layer's parts aren't cut over in this cycle.
=> Timed storage forward port

src/AccessControl/AccessChecker.php, src/Controller/Base.php, src/Controller/Frontend.php, tests/phpunit/unit/Controller/FrontendTest.php
=> Fixes for first user set up

src/Asset/Snippet/Queue.php
=> Handle snippets passed in a Twig_Markup

src/Controller/Frontend.php
=> Fix error in taxonomy listing

theme/base-2016/record.twig
=> Don't dump record unless asked to. Fixes #4211

theme/base-2016/_aside.twig, theme/base-2016/css/custom.css, theme/base-2016/extrafields.twig, theme/base-2016/index.twig, theme/base-2016/listing.twig, theme/base-2016/record.twig
Sorry, but I can't git. I couldn't get #4214 to rebase right, so this should work.
=> Fix columns in 800px-1100px in base-2016.

src/Storage/Database/Schema/Table/AuthToken.php, src/Storage/Database/Schema/Table/ContentType.php, src/Storage/Database/Schema/Table/Cron.php, src/Storage/Database/Schema/Table/FieldValue.php, src/Storage/Database/Schema/Table/LogChange.php, src/Storage/Database/Schema/Table/LogSystem.php, src/Storage/Database/Schema/Table/Users.php
=> Ignore 'type' properties for Date and DateTime columns

src/Controller/Backend/Records.php, src/Controller/Base.php
=> Return to previous page, with paging and filtering

src/Controller/Async/FilesystemManager.php, src/Controller/Async/General.php, src/Controller/Backend/General.php, src/Controller/Backend/Records.php, src/Controller/Base.php, src/Controller/Frontend.php, tests/phpunit/unit/Controller/Backend/RecordsTest.php
=> Fix for status transition in overviews

src/AccessControl/Login.php, src/AccessControl/Password.php, tests/phpunit/unit/AccessControl/PasswordTest.php
This brings that class to 100% coverage
=> Test coverage for AccessControl\Password

src/Config.php
Fixes: `Warning: Invalid argument supplied for foreach() in /[xxx]/src/Config.php on line 761`
=> Backporting fix for quirk in checks, from #4127

src/AccessControl/Permissions.php, src/Storage/RecordModifier.php
=> Handle save status transitions

src/Storage/RecordModifier.php
=> Fix user ownership changes

src/Twig/Handler/ImageHandler.php
Fixes #4022 and #2275.
All credit for for the title fix to @GDmac which I grabbed from #4022 since I got impatient after waiting for a month ;)
This also seems to fix #2866 if I am not wrong...
=> Fix alt and title tags for popup & showimage, height/width for showImage

src/Twig/Handler/ImageHandler.php
=> Port #4231 to 2.2

src/Controller/Backend/Extend.php
=> Check for an array before iterating

src/Controllers/Extend.php
=> [2.2] Check for an array before iterating

src/Legacy/Storage.php, src/Provider/ControllerServiceProvider.php, tests/phpunit/unit/Storage/StorageTest.php
Oh, look… :koala: 
Also fixes #4241
**Edit:** Ended up adding a fix for table checks as I thought that was flooding the logs… Turns out it was the news site being down :grin:
=> Use correct mount prefix for upload controller

src/AccessControl/AccessChecker.php, tests/phpunit/unit/AccessControl/AccessCheckerTest.php
The rest are waiting on some upcoming work from @rossriley but I want to get this off my plate for now :grin:
=> [Tests] Start of AccessControl\Accesschecker

src/Users.php
Fixes a corner-case bug found by @rarila where an extension that checks for users will fatal if the database has been removed.
=> Catch TableNotFoundException exceptions on Bolt\Users lookup and handle gracefully

src/Configuration/ResourceManager.php
=> Put right cannonical link into html head on paging content request 

LICENSE.md
See [Section 401](http://www.copyright.gov/title17/92chap4.html#401) of *Notice of copyright: Visually perceptible copies*
=> Copyright should match year of first publication

tests/phpunit/unit/Twig/Handler/TextHandlerTest.php
For reference the missing lines are "should never get there" and Windows.
=> [Tests] Twig handler text

tests/phpunit/unit/Twig/Handler/UserHandlerTest.php
=> [Tests] Twig handler users

app/config/config.yml.dist, src/EventListener/NotFoundListener.php
Port of @richardhinkamp ’s #4293 to master.
=> Not found using a template instead of a database record

tests/phpunit/BoltListener.php, tests/phpunit/unit/BoltUnitTest.php, tests/phpunit/unit/Configuration/ResourceManagerTest.php, tests/phpunit/unit/Extensions/ExtensionsProviderTest.php, tests/phpunit/unit/Translation/TranslationFileTest.php
:koala: :leaves: … enough said
=> [Tests] Fully decouple repo app directory

src/Twig/Handler/UtilsHandler.php, tests/phpunit/unit/Twig/Handler/UtilsHandlerTest.php
=> [Tests] Twig handler utils

src/Twig/Handler/RecordHandler.php, tests/phpunit/unit/Storage/StorageTest.php, tests/phpunit/unit/Twig/Handler/RecordHandlerTest.php
Well that was a lot of work for 13 commits :frowning: 
@doertedev your wish from #970 is wrapped up in here :grin:
=> [Tests] Twig handler records

src/Asset/Widget/Queue.php, tests/phpunit/unit/Twig/Handler/HtmlHandlerTest.php
=> [Tests] Twig handler html

app/resources/translations/de_DE/messages.de_DE.yml, app/resources/translations/en_GB/messages.en_GB.yml, app/view/twig/editcontent/_taxonomies.twig, app/view/twig/editcontent/_templatefields.twig, src/Storage/ContentRequest/Edit.php
=> Group "template" translation

app/config/contenttypes.yml.dist
- Templateselect: meta -> template group
- Extra group for repeaters
- Switch repeaters and template group position
=> contenttypes.yml.dist reorder

.travis.yml, tests/phpunit/unit/Twig/Handler/AdminHandlerTest.php
=> [Tests] Twig handler admin

src/Twig/Handler/ArrayHandler.php, tests/phpunit/unit/Twig/Handler/ArrayHandlerTest.php
=> [Tests] Twig handler array

tests/phpunit/unit/Twig/BoltTwigHelpersTest.php, tests/phpunit/unit/Twig/TwigExtensionTest.php
Too many tests to fit on the image… But this brings our Twig **extension** tests to complete coverage!
…and total unit tests to 933
=> [Tests] TwigExtension

src/Twig/Handler/TextHandler.php, src/Twig/SetcontentTokenParser.php, tests/phpunit/unit/Twig/Handler/TextHandlerTest.php, tests/phpunit/unit/Twig/SetcontentTest.php
=> [Tests] 100% Twig coverage!

src/Controllers/Backend.php, src/Permissions.php
Backport of #4233 to `release/2.2`
Fixes #4323
=> [2.2] Handle save status transition

src/Config.php, src/Storage/ContentRequest/Edit.php
=> Correctly detect the need for TemplateField tab

composer.json
=> Set composer/composer to dev stability

src/Extensions/AssetTrait.php
Prevent this notice: 
Notice: Undefined offset: 1 in /[..]/src/Extensions/AssetTrait.php on line 129
=> Prevent notice if working in strict mode.

src/Content.php, src/Controllers/Frontend.php
=> [2.2] Retrieve existing relations before setting them from POST. Fixes #4044

src/Controller/Backend/Upload.php
Just an educated guess that this would be the correct naming ;-)
=> Cutom vs. Custom

.gitignore, app/src/grunt-local/dist/bootlint.js, app/src/grunt-local/dist/htmllint.js, app/src/grunt-local/dist/pages.js, app/src/grunt-local/dist/sourcemap.js
See the :koala: celebrating :christmas_tree::gift::santa::tada:
=> grunt-local dist files

src/Storage/ContentRequest/Edit.php, src/Storage/Entity/Content.php, src/Storage/Mapping/ContentType.php, src/Storage/Mapping/ContentTypeTitleTrait.php, src/Storage/Repository/ContentRepository.php
Fixes #4339 
Fixes #4259 
**Edit:** Updated and confirmed fix for 4259
=> Getter for a record's 'title' field.

app/resources/translations/en_GB/messages.en_GB.yml, app/resources/translations/nl_NL/messages.nl_NL.yml, app/src/js/modules/extend.js, app/src/sass/modules/_extend.scss, app/view/twig/extend/_package.twig, app/view/twig/extend/extend.twig, app/view/twig/extend/install-package.twig
=> Some visual tweaks for the "Extend" screen.

src/Asset/Snippet/Snippet.php
=> To string… or not to string… that is the question we cast.

src/Composer/Action/BoltExtendJson.php, src/Config.php, src/Configuration/Environment.php, src/Configuration/LowlevelChecks.php, src/Configuration/ResourceManager.php, src/Provider/ConfigServiceProvider.php, tests/phpunit/bootstrap.php, tests/phpunit/unit/Configuration/ResourceManagerTest.php
If it's green… it's now merge worthy! :+1:
=> Remove realpath() use from Bolt\Configuration\Environment

src/Asset/Injector.php
It is related to #4367 in release 2.2 branch
=> Regex that insert snippets not working when </head> does not starts the line

src/Asset/Injector.php, tests/phpunit/unit/Extensions/ExtensionsProviderTest.php
Note: The unit-tests on this PR will fail, until the fix in #4368 is merged in.
=> Don't insert empty assets, and improve tests for assets.

composer.json
Already required by bolt/codingstyle
=> Remove symfony2 codingstyle requirement

src/Nut/UserAdd.php
Tell me if you think that we should use the second parameter when hashing the password.
Also tell me if I'm not using the right implementation you were thinking of...
Fixes #4373
=> Allow to encode password when editing/adding users.

app/src/sass/buic/_select.scss, app/src/sass/fieldsets/_slug.scss, app/src/sass/modules/_editcontent.scss, app/view/twig/components/panel-activity-change.twig, app/view/twig/components/panel-activity-system.twig, app/view/twig/users/_panel-actions_users.twig, app/view/twig/users/_userlist.twig
=> Fixing height for the dropdown in slugs.

src/AccessControl/Login.php, src/EventListener/StorageEventListener.php, src/Storage/Entity/Users.php, tests/phpunit/unit/AccessControl/LoginTest.php, tests/phpunit/unit/Controller/Backend/AuthenticationTest.php
The default value will be set at database level when creating a user so this fix is pretty straightforward but not sure it's the perfect way to go, what do you think?
Fixes #4237
=> [WIP] Allow to disable a user.

src/EventListener/StorageEventListener.php, src/Storage/Entity/Users.php, src/Storage/Repository/UsersRepository.php
Fixes:
* Some POST saves of users are generating associative arrays
* The "everyone" role is needlessly persisted
=> Hotfix role handling

src/EventListener/StorageEventListener.php, src/Storage/Entity/Authtoken.php
Fixes #4394
Closes #4395
Underps my last PR :stuck_out_tongue_winking_eye:
=> Limit user agent strings to 128 characters on persist

src/Nut/DatabaseExport.php, src/Nut/DatabaseImport.php, src/Nut/LogClear.php, tests/phpunit/unit/Nut/LogClearTest.php
More replacing the deprecated DialogHelper with QuestionHelper
=> Nut deprecations

app/view/twig/editfile/editfile.twig
[WIP] Don't merge until :+1: from @jadwigo 
Was it really that easy?
Fixes #4196
=> Fix #4196 - ckeditor on chrome in android is not working

src/Config.php
I have a plane to catch, but the branch is on upstream if anyone wants/needs to change it prior to submission!
=> Repeating field validation

app/view/twig/users/_userlist.twig
=> [2.2] No scrolling panes on userlist.

src/Config.php, src/Controller/Frontend.php, tests/codeception/_support/YamlHelper.php
* 5 parts CDO
* 2 parts DRY
* 1 part derpy test
=> Path handling tidy

src/Storage/Database/Schema/Manager.php
=> Set the 'expiry', if it doesn't exist, but the checks are OK. Fixes #4456

src/Storage/Collection/Relations.php
=> Minor fix to Relations to add a check for empty values

src/Controller/Frontend.php, src/Storage/Entity/ContentRelationTrait.php, src/Storage/Entity/ContentValuesTrait.php
=> Retrieve existing relations before setting them from POST. Fixes #4044

src/Storage/Database/Schema/TableModifier.php
Derpy is derpy… :koala: is :koala:
=> Return after exception

src/Twig/Handler/WidgetHandler.php, src/Twig/TwigExtension.php, tests/phpunit/unit/Twig/Handler/WidgetHandlerTest.php, tests/phpunit/unit/Twig/TwigExtensionTest.php
* Widget exception handling follows Twig strict mode
* Updated tests
=> Widget updates

app/view/twig/dbcheck/dbcheck.twig, src/Controller/Backend/Database.php, src/Storage/Database/Schema/Manager.php, src/Storage/Database/Schema/SchemaCheck.php, tests/phpunit/unit/Controller/Backend/DatabaseTest.php
This adds the ability to use `debug` as a query parameter in the URL when viewing the **Database check / update** page in order to display the SQL that will be applied when the update is attempted
=> Database check debug mode

tests/phpunit/unit/Twig/Handler/WidgetHandlerTest.php
=> fix typo to match newly edited message

src/Storage/Entity/Taxonomy.php, src/Storage/Field/Type/TaxonomyType.php
Replaces the taxonomyType part of #4484
=> Fix notice in TaxonomyType

src/Legacy/Storage.php
Fixed the perceived problem in #2409. 
We now search for the original words as-is, and only if that produces no results fall back to the current behaviour of getting all ‘or’ matches. 
While this doesn’t actually solve the underlying problem (which is that Bolt can’t read your mind), it _will_ work better for most people. 
For example, if you now search for “foo bar”, you’ll get results that contain the exact string “foo bar”. If there are no results for “foo bar”, you will get results for “foo” and/or “bar”, with the usual searchweight applied.
=> Search twice, results once. Fixes #2409

app/src/js/widgets/buic/buicSelect.js
=> buicSelect event handling

app/view/twig/editfile/editfile.twig
=> [2.2] Fix css syntax highlighting.

app/view/twig/editcontent/fields/_repeater-group.twig, app/view/twig/editcontent/fields/_repeater.twig, src/Storage/Entity/FieldValue.php, src/Storage/Field/Collection/FieldCollection.php, src/Storage/Field/Collection/RepeatingFieldCollection.php, src/Storage/Field/Type/CheckboxType.php, src/Storage/Field/Type/FieldTypeBase.php, src/Storage/Field/Type/FileType.php, src/Storage/Field/Type/ListTypeBase.php, src/Storage/Field/Type/RepeaterType.php, src/Storage/Field/Type/SelectType.php, src/Storage/Field/Type/TemplateSelectType.php, src/Storage/Field/Type/TextAreaType.php, src/Storage/Mapping/MetadataDriver.php
Ok, this now gets repeating fields very close to ready. Handles the additions to the templates to fix/improve rendering.
Implements a load of changes to the Collections to support saving/updating and deleting whilst keeping queries to a minimum.
Some additional fixes to the field types to make sure that the correct storage type is selected.
=> More fixes for repeating fields

src/Storage/Field/Type/SlugType.php, src/Storage/Mapping/MetadataDriver.php
=> Slugless ContentTypes

src/Config.php, src/Provider/DatabaseSchemaServiceProvider.php
=> ContentType table names

src/Storage/Entity/Builder.php, src/Storage/Field/Type/FieldTypeBase.php, src/Storage/Field/Type/ListTypeBase.php
Fixes #4532 
Fixes #4481 
Replaces #4530
=> Fix field defaults when creating new content / Removes notices from create content

app/view/twig/editcontent/fields/_imagelist.twig
Fixes #3983 
Uses the files url to link to the full version of an uploaded file
=> Fix adjustable files urls

src/Storage/Entity/ContentValuesTrait.php
Fixes log flooding:
```
PHP Notice:  Undefined index: file in src/Storage/Entity/ContentValuesTrait.php on line 503"
```
=> Check array parameter exists

src/AccessControl/AccessChecker.php, src/AccessControl/Login.php, src/Controller/Backend/Authentication.php, src/Controller/Backend/Users.php, src/EventListener/GeneralListener.php, src/Provider/AccessControlServiceProvider.php, src/Users.php, tests/phpunit/unit/AccessControl/AccessCheckerTest.php, tests/phpunit/unit/AccessControl/LoginTest.php, tests/phpunit/unit/BoltUnitTest.php, tests/phpunit/unit/Controller/Backend/AuthenticationTest.php, tests/phpunit/unit/Controller/Backend/UsersTest.php
I'd like to dedicate this one to @CarsonF… Without his nagging, this wouldn't have been possible :stuck_out_tongue_winking_eye:
=> AccessControl request stack usage

src/Render.php
Add in ```max-age`` cache control directive to allow pages to be served from the cache 
Fixes #4600
=> add in cache-control max age to go along with s-max-age directive

src/Application.php
Same as #4605, but for master.
=> Extremely minor comment tweaks (3.0)

.htaccess
Can be cherry-picked into master
=> Add JSON to list of denied file types for Apache

app/src/README.md
=> [2.2] Typo

src/Render.php
=> Process queue only once.

.gitignore
See https://github.com/bolt/bolt/wiki/Developing-Bolt-in-PHPStorm
=> Updating .gitignore. Add PHPstorm cruft.

src/Legacy/Storage.php, theme/base-2014/listing.twig, theme/base-2016/listing.twig
=> Listing by Taxonomy doesn't respect grouping taxonomies with option 'has_sortorder'

src/Storage.php, theme/base-2014/listing.twig
=> Listing by taxonomy doesn't calculates with option 'has_sortorder'

app/view/twig/_base/_fieldset.twig, app/view/twig/_macro/_buic.twig, app/view/twig/editcontent/fields/_checkbox.twig
As discussed in  #4616 .
@sbonardt , @bobdenotter : May I ask one of you to add that new behavior to the documentation?  :pray:
=> Add editcontent checkbox label left, right, left+right

app/view/twig/editcontent/fields/_repeater-group.twig, app/view/twig/editcontent/fields/_repeater.twig, src/Storage/Field/Collection/RepeatingFieldCollection.php
=> Fix for repeating fields errors in strict mode

tests/phpunit/unit/Controller/Backend/UploadTest.php
Introduced by https://github.com/bolt/filesystem/pull/34
=> [Tests] Change exception expectation to match upstream

src/Content.php
=> [2.2] Fix Templatefields in Viewless records (Fixes #4150)

src/Controller/Backend/FileManager.php
Remember kids, :koala:s are dangerous… Code with care!
=> Set depth limit on file/directory look up

src/Response/BoltResponse.php
Yes… You could be forgiven for thinking I am having to work with a stable version of Bolt for once :wink:
=> Don't whitescreen on a response with a Twig exception

app/resources/translations/fr_FR/messages.fr_FR.yml, app/view/twig/nav/_secondary-content.twig
Adding some missing translation in French :)
I don't know if I must ask to pull in master or release/2.2 ?
=> Translation - French (fr_FR) missing translation

theme/base-2014/index.twig
...just been there... resolves #4675
=> Missing xlation - Resolves #4675

app/view/twig/editcontent/fields/_slug.twig, src/Config.php, src/Legacy/Storage.php
=> Look for slugs and singular ones too

app/view/twig/editcontent/_relations.twig
Pass in missing permissions for delete, publish and depublish.
=> Fixes twig error when showing a list of relations

app/bootstrap.php, src/Application.php, src/Config.php, src/Exception/LowlevelException.php
=> LowlevelException udpate

src/Controllers/Frontend.php
Back port of #4678 into an existing class file… :koala:
=> Added capability to set a record amount for specific kind of taxonomy

src/Controller/Backend/FileManager.php, src/Controller/Backend/General.php, src/Controller/Backend/Users.php, src/Controller/Base.php, src/Provider/TwigServiceProvider.php
Lowers deprecation count from 340 to 182. c.f. #4508 
Requires #4698 first
=> First round of fixes for Symfony deprecations

app/config/config.yml.dist, tests/codeception/acceptance/102-BackendDeveloper/BackendDeveloperCest.php, tests/codeception/acceptance/105-BackendLemmings/BackendLemmingsCest.php, tests/codeception/acceptance/200-Frontend/FrontendCest.php, theme/base-2016/_menu.twig, theme/base-2016/theme.yml
I'm proposing making base-2016 the default (as discussed on IRC this morning/lunchtime) now so that we actually find any rough edges before we get into beta/RC. This PR also includes all the necessary test changes (I hope).
=> Make base 2016 default

app/view/twig/activity/systemlog.twig, src/AccessControl/Permissions.php
=> No actions on non-existing contenttypes

src/Twig/SwitchNode.php, src/Twig/SwitchTokenParser.php, src/Twig/TwigExtension.php
=> Add Twig `{% switch %}` statement.

src/Provider/TwigServiceProvider.php
@CarsonF I know we need to probably approach this better prior to release, just haven't been able to schedule time with you to finalise.
=> Add matching paths to 'twig.loader.bolt_filesystem' as are in 'twig.loader'

composer.json
Shiny and new! http://filp.github.io/whoops/
=> Update Composer.json for Whoops 2.0

src/Twig/Handler/ImageHandler.php
to catch unfilled fields and getImage
=> Make showimage/popup do an empty check

web.config
fix iis rewrite extend 404
admin/extend/install?package=sahassar%2Ffoxycart&version=0.1
404
=> fix iis rewrite extend 404

src/Storage/Mapping/Type/CarbonDateTimeType.php, src/Storage/Mapping/Type/CarbonDateType.php
=> Prevent empty date values being passed to DateTime classes

app/view/twig/editcontent/fields/_repeater-group.twig
=> Add support for prefix, postfix and divider in repeating fields

src/Storage/ContentRequest/Save.php
=> Update the datechanged field on save

app/src/js/init.js, app/src/js/modules/app.js, app/src/js/modules/editcontent.js, app/src/js/widgets/fields/fieldGeolocation.js
Add js events to allow extensions and custom fields to know about the savestate of content/files. Oh, and 	port #4682 to master.
=> Add js events to editfile/editcontent ajax saving

theme/base-2016/record.twig
this will prevent some warnings and other ugly output
=> add condition to image field in theme

app/src/js/init.js, app/src/js/modules/editcontent.js
Add js events to allow extensions and custom fields to know about the savestate of content/files.
=> [2.2] Add js events to editfile/editcontent ajax saving

.htaccess
I'm sure we had this in at some point, but it got lost again.
=> Block access to .git folders in .htaccess.

.htaccess
I'm sure we had this in at some point, but it got lost again.
=> [2.2] Block access to .git folders in .htaccess

src/Storage/Field/Type/FieldTypeBase.php
=> Prevent notices when hydrating from partial data, fixes #4624

app/src/js/modules/editcontent.js
=> move onbeforeunload init and remover, fixes #4640

app/src/js/modules/editcontent.js
=> [2.2] move onbeforeunload init and remover, fixes #4640

app/src/js/modules/editcontent.js, app/view/twig/editcontent/fields/_checkbox.twig
=> [2.2] Don't use value on checkbox, and set with prop (fixes #4356)

app/src/js/modules/editcontent.js
=> Set checkboxes with prop (fixes #4356)

app/src/js/extend.js, app/view/twig/extend/install-package.twig
=> [2.2] Make the More info buttons actually do something

src/Content.php
Fixes #4358
This works for me but it seems too "simple" for it to be a proper solution... :wink:
Can anyone think of any glaring issues with it?
=> Fix select fields in templatefields (fixes #4358)

app/view/twig/editcontent/fields/_slug.twig
Hack slug prefix to "look" right until real fix can be applied with #4014
=> Hack slug prefix to "look" right until real fix can be applied with #4014

app/view/twig/editcontent/_aside-preview.twig, app/view/twig/editcontent/_buttons.twig, src/Twig/Handler/RecordHandler.php, src/Twig/TwigExtension.php
There's no need to go through the process of generating a url for a route just to see if the route exists. Much less do we need yet another twig function.
=> Check app.routes for preview route

.travis.yml
This adds a significant speed boost to building our Travis environment for testing
=> [Travis] Composer parallel install 

src/Extension/Manager.php
=> Fix extension's relative urls

src/Composer/ScriptHandler.php
Forward port of #4750 with credit to @skript-cc
=> Enable non-interactive configuration of composer-install

src/Extension/ConfigTrait.php, src/Extension/SimpleExtension.php, tests/phpunit/unit/Extension/Mock/DeprecatedAssetExtension.php, tests/phpunit/unit/Extension/Mock/MenuExtension.php
@rossriley this one is dedicated to you!
=> Extension simplification

src/Storage/Entity/ContentValuesTrait.php
=> Quick fix by Ross, for #4820.

src/Controllers/Frontend.php
I'm guessing we need to set the amount before the query :wink: Fixes #4822
=> [2.2] fix listing_records in taxonomies

src/Composer/PackageManager.php
fix PackageManager ping 504 Gateway Time-out
=> fix PackageManager ping 504 Gateway Time-out

src/Controller/Backend/Upload.php, src/Storage/ContentRequest/Edit.php
Fixes #3831 
This tidies up a couple of bugs that were causing breakages on uploads to multiple locations.
=> Fixes for multiple filesystem namespaces

app/view/twig/editcontent/data/_uploads.twig, src/Filesystem/FilePermissions.php
This came out of testing for #4291 and covers the one edge case found.
=> Fixing reporting for upload errors
