bolt/bolt

src/Database/IntegrityChecker.php
On new installs, it currently causes a duplicate index error.
=> duplicate index error on new installs

src/Content.php, src/Controllers/Backend.php, src/Database/IntegrityChecker.php, src/Storage.php, src/Users.php
Fixes #2395 
* Fields that previously used `0000-00-00` and `1900-01-01` now default to using `NULL` instead
=> Use null defaults for dates

src/TemplateChooser.php
For everything except taxonomies, the template priority is something like:
global config < theme config < specific type config
Taxonomies go
global config < specific type config < theme config
This is unexpected behaviour, and it makes it impossible to specify a custom taxonomy template if you have a listing template specified in your theme (which is pretty common). On top of that, the function's code for choosing taxonomy was slightly inconsistent with all of the other template choosing functions.
Anyway, it was a simple fix. This PR changes the priorities to the expected behaviour.
=> Change priorities of taxonomy templates

src/Application.php, src/Configuration/ResourceManager.php, src/Provider/SafeTwigServiceProvider.php, src/TwigExtension.php
The problem I had is twig was getting initialized to add globals and extensions before my customizations were added.
Twig shouldn't be initialized until it is needed, so others can extend it further.
I also moved the globals into the TwigExtension class, which also dries them up. Same with the SetcontentTokenParser.
=> Refactor Twig setup

src/Application.php
An example of what is given in error generating AJAX requests now:
```
{
"error" : {
"type" : "UnexpectedBeerException",
"message" : "Expected more beer in request. Unable to continue!",
"file" : "src/Application.php",
"line" : 123
}
}
```
**NOTE** This attaches to the Whoops! service provider, so will only be sent in the cases where a HTML Whoops! otherwise would.
- Whoops now sends errors to AJAX callers in JSON format
=> Enable JsonResponseHandler for Whoops! to send JSON formatted errors for AJAX requests

src/Application.php
Primarily so the database service can be extended before creation with the connection check.
=> Refactor db initialization methods to separate methods. 

app/view/twig/editcontent/fields/_select.twig, src/TwigExtension.php
Fixes #2437.
As an added benefit, this change makes sure that you don't lose the current settings if you later decide to set or remove `multiple: true` on your field, because we always check for values in an array. 
Also, if anyone has a suggestion for a better name than `currentsel`, i'm all ears!
=> Fixes select field type, with values from another content type. 

src/Controllers/Backend.php
#2457 - Removes the changed own username message when creating first user.
=> Fix for #2457. Remove changed self message when creating first user.

src/TwigExtension.php
Debug flag shouldn't be checked from config, because config assigns it to app['debug'] which can be overridden by others.
=> Fix debug check in TwigExtension

src/TwigExtension.php
Hm, can't find anything about `filter` in the docs but it's there by default in `contenttypes.yml` as `*.twig`. This is quite a useful feature to have. E.g. use `filter: invoice*.twig` to only select invoice templates. Not sure about its security implications though.
=> Makes filters work for templateselect fields.

src/Storage.php
It ought to be 'paging', but it needed better checks. 
For an example, see:
```
<h4>1 latest, without paging:</h4>
{% setcontent records = "entries/latest/1" printquery %}
<h4>6 latest, with paging:</h4>
{% setcontent records = "entries/latest/6" allowpaging printquery %}
```
output:
=> Check for 'paging' in array. Fixes #2474

src/Controllers/Frontend.php
I'm using my own controller, but I still want to use the frontend permission check.
Currently you're forced to copy the whole function to your own controller, this PR solves that by changing the visibility to protected.
I think the impact will be minimal, but I'm not sure.
=> Changed visibility of the frontend permission check so derived classes can keep using this.

src/Controllers/Frontend.php
Instead of doing a manual search for a template prior to actually loading the template, use Twig’s built-in function.
Advantages include:
1. Doing the same check as the real loader a couple lines below.
2. Using Twig’s path loader.
This PR is needed to make https://github.com/wemakecustom/bolt-parent-theme work for base templates (not only includes).
=> Use Twig’s resolveTemplate instead of file_exists in Frontend Controller.

app/view/twig/nav/_secondary-extensions.twig, app/view/twig/nav/_secondary-filemanagement.twig
when you use the nav links it attempts to load extensions and file-managment pages using http
=> fixes nav links in admin dashboard when accessed over https

app/nut, src/Application.php, src/BaseExtension.php, src/Provider/NutServiceProvider.php
Those who want to modify their Bolt install mostly likely need to create their own `nut` file which has their own bootstrap. 
The problem is they then have to add all the nut commands manually. 
What happens when these are removed/changed or others are added?
Moving these commands to a service provider fixes that.
=> Moved Nut commands to a service provider

composer.json
See also: https://github.com/doctrine/doctrine2/pull/1255
=> Fix doctrine/dbal at version 2.5.1, since it's the last to support PHP 5.3.3

app/config/config.yml.dist, app/view/Gruntfile.js, app/view/lib/bolt/extend.js, app/view/twig/extend/_package.twig, app/view/twig/extend/extend.twig, src/Composer/Action/BoltExtendJson.php, src/Composer/Action/CheckPackage.php, src/Composer/Action/DumpAutoload.php, src/Composer/Action/InitJson.php, src/Composer/Action/InstallPackage.php, src/Composer/Action/RemovePackage.php, src/Composer/Action/RequirePackage.php, src/Composer/Action/SearchPackage.php, src/Composer/Action/ShowPackage.php, src/Composer/Action/UpdatePackage.php, src/Composer/ExtensionInstaller.php, src/Composer/Factory.php, src/Composer/PackageManager.php, src/Configuration/LowlevelException.php, src/Controllers/Extend.php, src/Nut/Extensions.php, src/Nut/ExtensionsDisable.php, src/Nut/ExtensionsEnable.php
"And...  In the blue corner, weighing in at 146 commits..."
So here is, a canary merge branch, branched fresh off my feature branch. A big thank you goes out to @rossriley for figuring so much of this out in the first place.
* LOTS!
* Using the Composer API more directly, rather than proxying through console commands
* Each implemented `Composer\Command` has a corresponding `Bolt\Composer\Action` class that closely mimics how the `Composer\Command` classes individually interface `Composer\Installer`
* Actions currently implemented:
- BoltExtendJson
- CheckPackage
- DumpAutoload
- InstallPackage
- RemovePackage
- RequirePackage
- SearchPackage
- ShowPackage
- UpdatePackage
* `Bolt\Composer\Action` classes are all declared `final`, for now. Our implementation of these classes is likely to …
=> Extend's Composer Implementation for v2.1

composer.json
- Put `bolt/pathogen` in alphabetical order
- Use tagged version for `ircmaxell/random-lib`
- Use `dev-master` for `composer/composer`. We don't see that there will be an actual 1.0.0 release anytime soon, so we might as well use the latest.
=> Cleanup of composer.json

src/Config.php
The `Config::getWhichEnd()` method relies some custom logic that uses the `$_SERVER` superglobal to determine which 'end' of the application is being used.  I propose instead using the Symfony `Request` object, since it does a better job of determining path information for various environments.
If the `$app['request']` hasn't been initialized yet, we can create a local copy of the Symfony `Request` object using `createFromGlobals()`.  This will ensure that the `getWhichEnd()` uses the same HTTP interpretation logic that the routing does.
This benefits of this pull request include:
- simplifies the code in the `getWhichEnd()` method, and
- fixes an issue where certain pages in the admin section throw "missing Twig template" errors; specifically pages where the URI ends with a file …
=> Refactor Config::getWhichEnd() to work with PHP CLI Server and use Symfony Req Object

src/Config.php
Generally it's better not to do logic in constructor.  This allows others to override initialize() to change caching/loading config behavior without having to recreate the constructor.
=> Refactor constructor into initialize method

src/Config.php
Depends on #2571.
Generally, (IMO) it's better to return variables than set them in the class. It makes code easier to follow.
In this case, it allows others to modify defaults without having knowledge of where the defaults are set in the config.
=> Config::setDefaults -> getDefaults

src/Config.php
Depends on #2572 and #2571.
Removes local version of ResourceManager::getPaths() since this can become out of sync and doesn't fit with the "Bolt" way of referencing services.
=> Config remove local resources paths

src/Application.php, src/Database/IntegrityChecker.php, src/Storage.php
Removed the calls to Config::getDBOptions. It is better to use the DBAL connection object.
- Using Platform name instead of driver name because that's really what we are checking for (this fixes pdo_mysql != mysqli).
- Getting database name from database connection
=> Using Doctrine Platform instead of our config values.

src/Controllers/Async.php, src/Storage.php
Replaced prepare() queries with executeQuery() since that supports read slaves. 
Replaced prepare() with query() on write queries because why do 3 method calls when you can do one?
Cleaned up tag queries in Async Controller as well.
Should some of those queries be on multiple lines? Like:
```sql
SELECT id 
FROM $tablename 
WHERE status = 'published' 
and datedepublish <= :now 
and datedepublish > '1900-01-01 00:00:01'
and datechanged < datedepublish
```
=> Update queries for slaves

app/view/Gruntfile.js
I forgot to commit the updated gruntfile when I updated magnific popup to 1.0.0.  
Also removed version number from the directory to make future manual updates easier (if not using a package manager like Bower or NPM )
=> update gruntfile for magnfic popup

src/Config.php
In a `type: select` field, the current situation is that the YML parser does not distinguish between hashes and map typ arays. 
The reason that we would want to do this, is because if you set values to ['blue', 'green'], that is what you'd expect to see in the database, normally. Not '0' and '1', which is what would happen, if we didn't "correct" it here. 
I'm fully aware that this solution is conceptualy wrong. However before it was actually _broken_, it just wasn't very apparent. So, now we choose: "Wrong and fixed" or "correct and broken". ^_^
=> "Fix" arrays in type:select fields.

src/Configuration/ResourceManager.php, tests/Configuration/ResourceManagerTest.php
=> Feature - allow ResourceManager getPath to return a relative path based on a known base

src/Configuration/ResourceManager.php, tests/Configuration/ResourceManagerTest.php
Paths are joined together with "/" hardcoded in several places. This is the first step to allow them to be joined properly.
=> Allow getPath to return PathInterfaces

phpunit.xml.dist
This should get rid of the tests directory from the code coverage report.
=> exclude the tests directory from the code coverage reports

app/view/Gruntfile.js, app/view/package.json
- ``default`` task now only watches changes in bolts own js/css so that files are not automatically regenerated when grunt is started
- ``default`` task now also jshints
- ``updateBolt`` task now regenerates bolts own js/css
- ``updateLib`` task now regenerates external library stuff
- In Bolts css for now CRLF is converted to LF (until libsass catches up)
- Tasknames are now more descriptive
- Comments added
- Bolts js files are now in list template
- Gruntfile.js is watched now and reloads config on change
These changes are in preparation of things to come.
Be sure to update npm!
=> Gruntfile reorganisation

src/Config.php, src/Configuration/ResourceManager.php, src/Controllers/Frontend.php, src/TemplateChooser.php, src/TwigExtension.php
Fixes #2445
If you specify `template_directory` in your theme's `config.yml`, all related template activities will be relative to that directory (which is relative to the theme directory).
It adds `templatespath` to the paths object, and I *think* I managed to change all of the correct instances of `themepath`. This should be checked by someone who knows their stuff.
=> Allow template directory

src/Storage.php
When saving a contentype using multiple slugs, the slugs aren't set properly. Instead of using the string 'slug' it should use the $key of each slugfield, making sure each slugfield is checked and filled properly.
=> Fixes checks and creation of slugs when using multiple slugs on saving

src/Application.php, src/Config.php, src/Configuration/LowLevelDatabaseException.php, src/Configuration/LowlevelChecks.php, src/Controllers/Async.php, src/Storage.php, tests/BoltUnitTest.php, tests/Configuration/LowlevelChecksTest.php, tests/Configuration/Mock/Config.php, tests/Controller/BackendTest.php, tests/Library/BoltLibraryTest.php, tests/Storage/StorageTest.php
Depends on #2601.
- Cleans up the parsing methods and makes them more readable
- Adds master / slave connections
- Allows standard Doctrine configuration, while maintaining BC
- Uses pathogen for SQLite paths
See Config changes in #2530.
=> Refactor DB config parsing

src/Config.php
Request::getPathInfo() always starts with a slash
=> Small clean up for Config::getWhichEnd

composer.json, src/Nut/NutApplication.php, src/Provider/NutServiceProvider.php
This is one for the CLI obsessed.
To use, you just add the following to either your `~/.bash_profile` or `~/.zshrc`
``` bash
source <(cd /my/bolt/directory && ./app/nut _completion --generate-hook)
```
**NOTE:** For BASH v3 you will need to instead use:
```bash
cd /my/bolt/directory && ./app/nut _completion --generate-hook | source /dev/stdin
```
Then when you're in `/my/bolt/directory` you can enter `./app/nut` and double tap the TAB key for command completion.
Added: BASH/ZSH command completion for Nut
=> BASH/ZSH command completion for Nut

.travis.yml
After #2647 Travis no longer requires `xdebug.max_nesting_level = 2000` to pass.  This also makes HHVM tests run again...  For what that is worth.
=> Remove xdebug.max_nesting_level from Travis tests

tests/Extensions/ExtensionsProviderTest.php
A few less warning messages on the HHVM tests.
=> Correct case on DOMDocument::preserveWhiteSpace

src/Content.php, src/Events/StorageEvent.php, src/Exception/StorageException.php, src/Storage.php, tests/Content/ContentTest.php, tests/Events/StorageEventTest.php, tests/Storage/StorageTest.php
So, you know when you start looking at a bug like #2484 and you think, "how hard can this be?", and 6 hours later you've fixed the problem... and several others along the way?
* StorageEvent refactored and now extends GenericEvent
* Move content related functionality out of Storage::saveContent() into Content (still needs larger refactor)
* Refactored insertContent() and updateContent()
* Bunch of docblock and type hinting
* saveContent() heavily refactored in the process...  Down from 101 lines to 53
* StorageEvents::PRE_SAVE no longer cares about event loops as Content object data can be modified before the database commit
* Fixes #2484 
Fixed: StorageEvents::PRE_SAVE now allows proper on-the-fly modification of data (see #2484)
=> Bolt\Storage, Bolt\Events\StorageEvents and Bolt\Content surgery

app/config/config.yml.dist, src/Controllers/Upload.php
The maintainer of siriusphp/upload added the ability today to provide a sanitisation callback for the upload handler.  This PR adds config options to allow us to use this.
Might be worth thinking about deprecating `accept_file_types:` key and making it part of `upload:`.
Fixes #1249 and #2237
=> Allow setting of regex pattern, replacement and case of uploaded file names

src/Application.php, src/Controllers/Async.php, src/Controllers/Backend.php, src/Nut/ConfigSet.php, src/YamlUpdater.php
* Compete & remove obsolete @todo tasks
* Implemented YAML verification and optional backup of target file in YamlUpdater
* Make config file backup and option for nut config:set
Added: nut config:set now has an optional --backup parameter that creates a backup of the target config file
=> Compete & remove obsolete @todo tasks

src/Library.php, src/TwigExtension.php, tests/Library/BoltLibraryTest.php
Library::fixPath() had only three remaining users:
* `Library::loadSerialize()`
* `Library::saveSerialize()`
* `TwigExtension::menuHelper()`
Both `loadSerialize() and `saveSerialize()` are only called from `Bolt\Config` and the paths are constructed fine.
`TwigExtension::menuHelper()` was a bit of fun, it now handles menu `path:` keys a lot better (I hope).
The following permutations all work:
* `{contenttype}`
* `{contenttype}/`
* `/{contenttype}`
* `/{contenttype}/`
* `{contenttype}/{id|slug}`
* `/{contenttype}/{id|slug}`
Also if someone (mis)configures `path:` with any of the following, they will create working links, but get an error logged in the system log:
* `http://`
* `https://`
* `//`
**NOTE:** If none of these match, `menuHelper()` will just assume that whatever the string …
=> R.I.P. Library::fixPath() 

src/Application.php, src/Config.php, src/Controllers/Backend.php
This is caused by Config::checkConfig being called for ajax requests. Flash bag messages are only removed when the backend twig template pulls them. So every ajax request will add one error, which will build up until they are flushed with a backend twig response.
For example, here's a request list:
1) /bolt -> removes all errors (now 0)
2) /async/latestactivity -> +1 error (now 1)
2) /async/latestactivity -> +1 error (now 2)
3) /bolt -> +1 error (now 3). They are flushed here, so 3 errors are rendered and the list is reset.
I moved `Config::checkConfig` call to only on the `Backend` controller, since this is the only time they will be rendered.
Although the could be rendered on the Frontend as well, should I call be added there as well?
=> Bugfix multiple flash messages

src/Application.php
Simply bumping the version will invalidate the cached config, ensuring the config files are reloaded which allows Bolt to pick up the correct values.
=> Fix the "mysql was selected but is not supported" error notice.

app/view/twig/components/panel-system.twig
This happens when updating: Before the user gets a chance to update the DB, Bolt shouldn't crash on non-present values before they get a change to update the DB.
=> Don't crash the backend when log.ownerid doesn't exist (yet).

app/view/js/lib.min.js, app/view/lib/jquery-watchchanges/jquery-watchchanges.js
Yet another one.
Sidenote: we should move ``jquery-watches`` to our own sourcetree and add it to init.js as it is 30% patched anyway and no updates are to expected
=> Fixes "Uncaught ReferenceError: CKEDITOR is not defined"

app/config/config.yml.dist, src/Application.php, src/Config.php, src/Controllers/Login.php, src/Users.php
Removing confusion from the SSL config. I removed the setting for cookies_https_only and instead use enforce_ssl throughout the app. Additionally, if enforce_ssl is set, the login page will automatically redirect to https.
=> Enforce SSL Config Change

src/Controllers/Backend.php, src/Users.php, tests/BoltUnitTest.php
Fixes #2763
* Splits first user creation out of editUser into its own method
* Move test for a user being enabled into Backend::before() to catch as early as possible
- Fixed: Logged in user can no longer disable themselves
- Fixed: Disabling a logged in user with force a logout
=> Adjust the logic that checks if a user is enabled

src/Content.php, src/Field/Base.php, src/Field/FieldInterface.php
Fixes #2591 
I've done what I have described in the issue, but this is a breaking change for all current extensions that create new fieldtypes as I have added a new method to the FieldInterface.
I was wondering if there was any advice as to how I could make this change non-breaking? I don't PHP often so I don't know what is considered black magic - would taking the function out of the interface and then checking if the method exists using [`method_exists`](http://php.net/manual/en/function.method-exists.php) be something worth doing?
This also breaks the excerpt function for some reason, and all html tags have escaped brackets. Trying to get to the bottom of that one.
**Edit**: Part of me also wants to do something similar to the `setValues` function as I think that would allow for …
=> [WIP] Allow extensions to leverage getDecodedValue

src/Configuration/ResourceManager.php, tests/Configuration/ResourceManagerTest.php
Fixes #2610. Ugly, but does the job until this is refactored out.
=> debug_print_backtrace() returns void and can't be passed to a variable

app/config/permissions.yml.dist, app/view/twig/components/panel-change.twig, app/view/twig/components/panel-system.twig, app/view/twig/dashboard/_aside.twig, test/_data/permissions.yml
* Add changelog and systemlog default roles to permissions
* Use changelog & systemlog permissions for panels
Fixes: #2795
Fixes: #2797
* Change: System activity and change log permissions have changed and users now require `systemlog` and/or `changelog` permissions in `permissions.yml`
=> Log UI permissions

src/Extensions.php, src/Extensions/Snippets/Location.php
To make the situation in https://github.com/bolt/bolt/issues/1129 clearer I've added the following lcoations for snippets:
* beforeheadmeta
* afterheadmeta
* beforeheadcss
* afterheadcss
* beforeheadjs
* afterheadjs
* beforebodycss
* afterbodycss
* beforebodyjs
* afterbodyjs
The locations are essentially aliases for startofhead, endofhead, startofbody and endofbody because in daily usage those will be all you need.
In the theoretical case where the specific ordering must be even more controlled we'll have to switch to simpledom parsing or something similar.
(Docs will be updated after merge)
=> added extra snippet locations

src/TwigExtension.php
url_generator already rawurlencodes paths, no need for lib::safe name as well
=> Twig thumbnail, remove double encoding paths

app/config/config.yml.dist, src/Application.php, src/Config.php
Fixes #2814. Changelog line: 
- Change: The 'X-Frame-Options' header is now only sent for backend pages, and can be disabled in `config.yml` (See #2825)
=> Make X-Frame-Options configurable.

app/config/config.yml.dist, app/view/twig/_base/_panel.twig, app/view/twig/components/panel-news.twig, app/view/twig/dashboard/_aside.twig, src/Controllers/Async.php
:fire:
Note: Merge #2829 first.
Changelog: 
- Change: Bolt now distinguishes between 'regular news' and 'alerts' on the Dashboard screen. This way, we can better notify people in case of an urgent security issue. (See #2830)
=> Allow differentation between "news" and "alerts". Fixes 2828

src/Controllers/Frontend.php
Fixes #2727
Changelog: 
- Change: You can now use `{id}` in routes for records instead of `{slug}`, if you wish to have links to records using the id. (See #2832)
=> Allow {id} in routes, as fallback for {slug}. Fixes #2727

app/load.php
That snippet assumed it was in the webroot. /app is not the webroot.
=> Fix PHP builtin webserver serving static files

app/view/twig/editcontent/fields/_image.twig
It seems that preview block got over the buttons so it was impossible to click them (click was triggered on preview instead of buttons).
This will fix the layout without breaking anything.
=> Fix for #2627.

src/Storage.php
Quick fix to prevent the search query from growing too large when there are lots of records.
This isn't a permanent solution, but should hold things over until the 2.2 refactor/rewrite of this bit of code.
Cheers!
=> prevent search query from growing too fast (fixes #2850)

app/view/lib/bolt/make-uri-slug.js, src/Controllers/Async.php, src/Storage.php
When using multiple slugs the backend previously depended on the 'slug' field. When using multiple slugs (or even a different named slug) you could create content with duplicate uri's.
With this fix we send the slugfield through AJAX/Async.php to the getUri (in Storage.php) function. Instead of using a hardcoded 'slug' in the query we can use slugfield. 'slug' is still being used as fallback and when an invalid slugfield is provided.
Please use grunt to recreate the minified bolt.min.js
=> Bugfix/bolt Adding support for multiple slugs when creating uri through ajax

src/Controllers/Backend.php
Don't tell a user to login if they are requesting the login page.
For the record I don't like what Backend::before is turning into. 
We should be applying the the middleware to routes that need it, not adding it all routes and excluding certain parts of the them for certain routes. 
It just needs to be split up better. Partly my fault for not creating Login::before.
=> Fix login redirect loop

app/view/Gruntfile.js
=> Don't call Grunt subtask that doesn't exist

app/view/lib/bolt/extend.js
=> Don't display 'null' for extension's without a description

src/Controllers/Backend.php
The check is also done in `usersEdit` and `users`, so it’s not needed
here.
=> Remove unneeded check for `checkUserRoleHierarchy`. Fixes #2894

src/Permissions.php
Derped. checkPermission wants current user's roles not current user.
This wouldn't happen if we had actual classes and not arrays. 2.2 can't come soon enough :)
=> Fix permissions check

app/view/twig/editcontent/editcontent.twig
Tab id's are now slugified and prepended by tab numbers to prevent collisions when necessary.
* Fixes #2904
=> Fixes #2904 (Tab groups with spaces in their name won't open)

app/config/permissions.yml.dist, src/Controllers/Backend.php, src/Permissions.php, src/Users.php
Ok this should fix #2927 #2893 #2892.
Additionally:
- It removes the role "everyone" from user's roles list in Backend.
- All roles are shown in useredit form, but unmanipulatable ones are disabled. (this is accounts for #2927)
I did change the permissions config. I think the spot it is now is better suited for the future. Possibly if we want to break out _manipulate_ into _add_, _edit_, _enable/disable_, _delete_, etc.
=> Fix role permissions

app/view/twig/editcontent/fields/_file.twig, app/view/twig/editcontent/fields/_filelist.twig, app/view/twig/editcontent/fields/_image.twig, app/view/twig/editcontent/fields/_imagelist.twig, src/Controllers/Backend.php, src/Filesystem/Local.php
Fix for #2455 
Checks for private visibility and show error message if path is inaccessible.
Adds a new check for `readonly` and shows normal listing but with upload form disabled.
=> Upload UX improvements

src/Content.php
In the content search functionality, the result weighting code would
produce a warning message and incorrect behavior when non-scalar fields
(e.g. images, files, addresses...) were included in the search.
This fix first checks for arrays and implodes them as needed.
=> Fixed warning and incorrect weighting when searching

app/config/config.yml.dist, src/Application.php
Do not merge yet!!!
This is a proposed alternative solution to #2863 / #2864. It makes the selection for either 'smtp' or 'mail()' explicit. It needs some more testing (on actual linux machines) to see if it works as intended. 
Comments/critiques welcome.
=> Alternative solution to fix #2863

app/view/twig/files_ck/_files.twig, app/view/twig/files_ck/files_ck.twig
Fixes #2947 as reported by @cooperaj 
+ Fixes #2947 (Adding image to wysiwyg html editor from stack fails.)
=> Fix for #2947 (Adding image to wysiwyg html editor from stack fails.)

run-functional-tests
There was a problem introduced with #2957 that was shown in the Codeception results, but the script we run exits with it's own value.  This fix captures and exits the script with that return value so that Travis will fail.
This is — obviously — going to trigger a Travis failure itself until #2961 is fixed, but can we please merge it once we know that the PHPUnit tests pass to prevent anything further from sneaking in.
=> Have ./run-functional-tests exit with the return code from the Codeception run

src/Configuration/LowlevelChecks.php
=> Handle safe_mode being set in PHP 5.3 with a string or a boolean (credit @Umbrielsama)

src/Config.php
Fixes #2975. Fixes #2977. Does not break #2874 again. 
And, it also fixes a logic-error: Before this change, a request to 'frontend' would have access to templates in `app/view/twig`, if `file_exists($themepath)` was false.
=> Make sure 'async' has access to the template files in `app/view/twig`

.gitignore, phpunit.xml.dist, tests/scripts/coverage.php
This change removes the code coverage from every PHPUnit run, and instead allows execution of a PHP script to test against both `master` and a PR's branch (plucked from a PR number).
```bash
php tests/scripts/coverage.php 3023
```
Optionally you can give the name (or path) of at directory in `tests/phpunit/`:
```bash
php tests/scripts/coverage.php 3023 Configuration
```
or a specific file:
```bash
php tests/scripts/coverage.php 3023 tests/phpunit/Configuration/ResourceManagerTest.php
```
And if changes in coverage are calculated, it will output to the console Mardown that can be pasted into the PR's discussion:
| Classes | Methods | Lines |
|---------|---------|-------|
| 15 | 24 | 13 |
| Class | Methods | Statements |
|-------|---------|------------|
| \Bolt::Application | 12 | 11 |
| …
=> Manual coverage testing

tests/scripts/coverage.php
Fix this:
```
PHP Fatal error:  Call to a member function write() on a non-object in /www/jirimedved/bolt/tests/scripts/coverage.php on line 603
PHP Stack trace:
PHP   1. {main}() /www/jirimedved/bolt/tests/scripts/coverage.php:0
PHP   2. Bolt\Tests\CoverageCommand->__construct() /www/jirimedved/bolt/tests/scripts/coverage.php:706
PHP   3. Bolt\Tests\CoverageCommand->getOpts() /www/jirimedved/bolt/tests/scripts/coverage.php:560
PHP   4. Bolt\Tests\CoverageCommand->help() /www/jirimedved/bolt/tests/scripts/coverage.php:625
```
=> Fix coverage print help

src/Composer/ExtensionInstaller.php
I'm proposing to revert this back to how it was pre Jan 20th. I've not been able to get any extension scripts to install with either the type-hinting passed and additionally the current package info:
$event->getComposer()->getPackage();
seems to always return the root package, not the package of the just installed package. Has anyone who changed and tested this got any more details as to how the current code can run correctly?
=> Fixes broken extension installer

composer.json
Add composer branch alias. This allows composer installers to require `2.1.*@dev` and always have the latest version of this branch
=> Add composer branch alias

composer.json
Add composer branch alias. This allows composer installers to require `2.2.*@dev` and always have the latest version of this branch
=> Add composer branch alias for 2.2

src/Controllers/Frontend.php, src/Library.php
Should fix #3082.
I would rather figure out a better way to handle this, but this will work for now. 
If we are at /bolt we should just match Backend::dashboard.
=> [2.1] Fix redirect for backend trailing slash redirect (/bolt -> /bolt/). 

src/Controllers/Frontend.php, src/Library.php, src/Provider/RoutingServiceProvider.php, src/Routing/ControllerCollection.php, tests/phpunit/Controller/ExtendControllerTest.php, tests/phpunit/Controller/LoginTest.php
This removes trailing slashes from `/bolt` and `/bolt/extend`
This is the 2.2 fix for #3082.
=> Who likes trailing slashes anyways?

src/BaseExtension.php, src/Extensions.php
**UPDATED**
The `addJavaScript()` function now:
* Takes an $option array parameter (handles deprecated calls)
* Allows extensions to defer, or asynchronously load their added JavaScript assets, e.g.:
```php
$this->addJavascript('js/jquery.min.js', array('late' => true, 'priority' => 10, 'attrib' => 'async defer'));
```
Produces something similar to:
```html
<script src="/js/jquery.min.js" async defer></script>
```
* Changed: The extension function now takes an option parameter `array('late' => true, 'priority' => 10, 'attrib' => 'async defer')`
* Added: Ability for extensions to defer, or asynchronously load JavaScript
=> Allow either 'defer', or 'async' attribute to be added to JavaScript loading in extensions

.gitattributes
As suggested in this article (not the original idea but the update):
https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/
=> Update .gitattributes to use a union merge for the changelog.md file.

app/src/js/extend.js, src/Controllers/Extend.php
This changes fix theme generation / copy bug in extension installer.
Fixes #3107 
Changelog
* Fix: theme name placeholder (fix: Copy to theme folder button)
* Fix: Assign only an extension object from data array (fix: name not visible)
* Added: Prevent empty theme name for generateTheme() in Extend-Controller (other suggestions?)
My first pull request. Any feedback welcome :)
=> Bugfix extension theme installer

app/config/config.yml.dist, src/Application.php
I found that datelocal was not actually using the locale that I had
configured. This seems to be caused by environment specific issues. A
way to solve it is by specifying additional locales. This change adds an
optional config parameter where additional locales can be configured. If
configured they are appended to the local array. Using this, adding
"Dutch_Netherlands" I could get Dutch dates (which did not work by
simply setting nl_NL as the locale)
=> New config setting additional_locales

src/Extensions.php
Fixes #3158 
I blame the :koala:
=> When Extensions::addJavascript() is passed a pre-2.2 parameter we need to account for all 2.2 options

src/Config.php, src/Configuration/Composer.php, src/Configuration/ResourceManager.php
When in composer, the root app/view/twig isn't added to the Twig renderer, so you can't use custom listing templates (or, override any template if you want to).
This PR fixes that.
This is a fix for 2.1, I'll now work on a master fix
=> Composer custom backend listing

codeception.yml, tests/codeception/_bootstrap.php, tests/codeception/_constants.php, tests/codeception/acceptance/_bootstrap.php, tests/codeception/extensions/CleanupExtension.php, tests/codeception/extensions/CodeceptionEventsExtension.php
This should (hopefully) now allow acceptance tests to run/pass on `bolt/composer-install` installs
=> Properly support both git and Composer install paths for Codeception

.travis.yml, tests/scripts/travis-db-config
This takes us to:
* Acceptance tests for git **and** Composer install types
* Acceptance tests for all three database platforms, for both install types
I'm going to get some :beers: now.
=> Add composer install acceptance tests

src/Storage.php
I was trying to put date operations in a `setcontent ... where {'date ||| other_date': '>today ||| >today'} but it wasn't having it.
This fixes that (and most likely some other cases).
=> Allow ||| queries to be more complex

src/Controllers/Frontend.php, src/Storage.php
Only log content not found errors if slug isn't numeric, since next it next checks by id.
Fixes first part of #3176
=> Only log content not found errors if slug isn't numeric, since next it next checks by id.

src/Storage.php, tests/phpunit/unit/Storage/StorageTest.php
- Use sort order from contenttype if none is explicitly specified
- Set limit to 1 if returning single.
=> Fix Storage not using sort from contenttype

src/Content.php
Bolt was calling ParsedownExtra in a way that meant it was getting a Parseodown instance and consequently the functionality that ParsedownExtra provides was not made available. Namely definition lists and footnotes.
I've also made sure that the correct definition list tags were included in the allowed tags. Since 'dh' is incorrect and what is needed is 'dt'
Fixes #3195
=> Fixed ParsedownExtra usage.

src/Controllers/Backend.php
At the moment any upload validation errors go by without being reported to the user.
This only affects uploads from the /bolt/files upload form, ajax uploads via content editing do report the correct error.
=> add error messages to the session flash if an upload fails

src/Application.php, src/Content.php, src/Controllers/Frontend.php
- Set the canonical correctly for pages like `/entry/12`
- If we're on the homepage record, _and_ it's rendered with the same template, set the canonical to root.
=> Set the canonical correctly. Fixes #3201

changelog.md
As much as I'd like, this feature was a master feature and not a 2.1.x feature.
=> Remove upload UX improvements from 2.1 changelog

src/Controllers/Backend.php, tests/phpunit/unit/Controller/BackendTest.php
Gonna do these in two parts because it's a monster class.
This takes test coverage of the Backend controller close to 50% with 100% coverage for the following controller actions:
connect()
dashboard()
dbCheck()
dbUpdate()
clearCache()
systemLog()
changeLog()
changeLogRecordAll()
changeLogRecordSingle()
omnisearch()
prefill()
overview()
relatedTo()
Part 2 coming soon....
=> Part 1: Backend controller tests

app/view/twig/nav/_secondary-content.twig
We _almost_ had this functionality in core already, using the `show_in_menu: false` option in `contenttypes.yml`. This PR cleans it up a bit. 
Before: 
After:
=> Nicer 'sub menu' for "Other content". Fixes #3120.

app/view/twig/components/panel-change-record.twig
For when records are created with Nut's prefill prior to a user being added to the database.
Fixes #3236
=> Provide a default value for item.username

phpunit.xml.dist, tests/phpunit/BoltListener.php, tests/phpunit/bootstrap.php, tests/phpunit/unit/Logger/ChangeLogTest.php, tests/phpunit/unit/Storage/StorageTest.php
* Allows for set/clean up functionality
* Bootstrap is globalised for suites, arrange it as such
* Generate a (currently) basic report in `/app/cache/phpunit-test-timer.txt` on individual test times:
```php
278.43		Bolt\Tests\Composer\Action\ShowPackageTest::testRootEnquiry
4.4571		Bolt\Tests\Composer\Action\CheckPackageTest::testUpdateCheck
2.9635		Bolt\Tests\Composer\FactoryTest::testFindVersion
2.2779		Bolt\Tests\Controller\BackendTest::testPrefill
1.7578		Bolt\Tests\Composer\Action\CheckPackageTest::testConstruct
1.7444		Bolt\Tests\Composer\Action\CheckPackageTest::testNewlyAdded
0.9341		Bolt\Tests\Composer\Action\UpdatePackageTest::testRun
0.9012		Bolt\Tests\Composer\FactoryTest::testSSLDowngrade
0.8987		Bolt\Tests\Composer\FactoryTest::testGetComposer
0.8855 …
```
=> Implement a PHPUnit listener

src/Content.php
This is a fix for the fix (#3214) for #3201 
https://github.com/bolt/bolt/commit/9ed06a0f7aba358dbd7646db93f8a4dbfb87ffa9#diff-41eef01f213bbe09b595d7594b6f199dR956
Was checking `[singular_slug] / [id]` twice instead of `||`ing with `[slug]`
=> Fix typo/copy paste oopsie in homepage test

tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php, tests/codeception/acceptance/101-BackendEditor/BackendEditorCest.php, tests/codeception/acceptance/102-BackendDeveloper/BackendDeveloperCest.php, tests/codeception/acceptance/103-BackendManager/BackendManagerCest.php, tests/codeception/extensions/CodeceptionEventsExtension.php
* Only login Codeception users once per user class run
* Local acceptance tests dropped from an average of 103 seconds to ~55 seconds per run
* Turn up Twig's anger ratio on acceptance tests (strict_variables: true)
=> Codeception speed tweaks

src/Nut/DatabaseExport.php, src/Nut/DatabaseImport.php, src/Provider/NutServiceProvider.php
* Fixes #3241
* Make the experimental nature of Nut import/export clear
* Will skip records with duplicate slugs
* Should be moved into Bolt\Database class once final approach is agreed upon
Import/Export files must have the `.yml` or `.yaml` extension and use the format:
```yaml
pages:
- title: Home
slug: home
content: Blah blah blah
- title: Contact Us
slug: contact
content: Blah blah blah
entries:
- title: A Very Important Blog Post
slug: most-important
content: This must be on every site install
```
* Added: [Experimental] Ability to import and export Contenttype records via Nut
=> Add experimental Nut commands for database import/export

src/BaseExtension.php
=> Make BaseExtension::initialize() non-abstract again to deal with PHP <5.3.10

app/view/twig/nav/_secondary-content.twig
=> Allow 'name' in contenttype to override translation, for 2.1.x

app/src/js/modules/ckeditor.js
This bug is mentioned in as an aside in #3256
Example configs and documentation establish a standard of having the px unit, for example
```
html:
type: html
height: 150px
```
We need to parse this value as an int to avoid unexpected NaN values.
NaN value in this case prevents CKeditor from autoGrowing properly and results in a missing scrollbar.
something about m&ms
=> Fix CKeditor autoGrow scroll bug by parsing value as int

app/src/js/modules/editcontent.js
This fixes the primary bug reported in #3256
The underlying textarea used by CKEditor wasn't being updated when changes were made.
=> Fix #3256: ensure CKEditor fields save when changed

app/src/js/modules/editcontent.js
This fixes the remaining issue reported by @EJanuszewski on #3256 where templatefields of `type: html` would cause the page navigation confirmation to display despite having saved.
=> Reset dirty check after updating ckeditor field. Fixes #3256

tests/phpunit/unit/Extensions/BaseExtensionTest.php, tests/phpunit/unit/Library/BoltLibraryTest.php
This PR adds  a PHPUnit annotation '@requires extension xdebug' and '@requires extension f_xdebug' on tests that require xdebug.  Facebook is still trying to implement it for HHVM, and [Derick Rethans](https://github.com/travis-ci/travis-ci/issues/2480#issuecomment-75029742) is on the job for PHP 7, but it will still be a while away.
* Now passes both unit and acceptance tests! :tada: 
* ~~One remaining error on unit tests~~
* Now passes unit tests! :tada: 
* Acceptance tests require update to Guzzle 5 (used by Codeception only)
* See https://github.com/guzzle/guzzle/issues/1015 & https://github.com/guzzle/RingPHP/issues/22  (Drupal have this as a release blocker on v8)
=> Unit test fixes for PHP 7 & HHVM

tests/codeception/acceptance/101-BackendEditor/BackendEditorCest.php, tests/codeception/acceptance/103-BackendManager/BackendManagerCest.php, tests/codeception/acceptance/200-Frontend/FrontendCest.php
@GawainLynch for some reason when saving a page with title `Contact Page`, it is getting saved with `CONTACT PAGE`. Does this have something to do with the save hooks?
Regardless, this tests for working templatefields
=> Add tests for templatefields

app/view/twig/overview/_panel-actions_overview.twig, app/view/twig/overview/overview.twig, src/Controllers/Backend.php
It even works with paging, and it 'sticks' when using 'save and return to overview'. ^_^ 
See screenshot:
=> Allow for filtering on 'taxonomies' on the overview pages.

src/Controllers/Async.php, src/Controllers/Backend.php, src/Controllers/Frontend.php, src/Response/BoltResponse.php, src/TwigExtension.php
I think this should be all that's necessary to remove the __toString method from BoltResponse.
The affected areas on the Dashboard seem to render ok for me too.
=> remove __toString from BoltResponse

src/Response/BoltResponse.php
This should be a decent compromise between the two problems.
The __toString method is restored so extensions that depend on it will continue to function identically.
Whilst PHP disallows exceptions being thrown in the __toString method it seems to be fine with triggering normal errors so, we can catch the original exception and trigger an error with the original exception message.
=> Restore BoltResponse __toString with nicer error handling

src/Controllers/Routing.php
This adds support for the use of methods in the routing.yml
The code is based on the example from symfony: http://symfony.com/doc/current/book/routing.html#adding-http-method-requirements
> your-route:
>   path: /mypage
>   defaults:  { _controller: 'Bolt\Controllers\Frontend::listing' }
>   methods:  [POST]
You can use multiple methods:
>   methods:  [POST|GET]
=> Adds support for methods in routing

composer.json, src/Application.php, src/Composer/PackageManager.php, src/Controllers/Async.php, src/Provider/GuzzleServiceProvider.php, src/Provider/PrefillServiceProvider.php, src/Storage/Prefill.php, tests/phpunit/unit/BoltUnitTest.php, tests/phpunit/unit/Controller/BackendTest.php, tests/phpunit/unit/Storage/PrefillTest.php
This is a follow up to #3280.
> Codeception pulls in Guzzle 5, so in preparation for us dropping PHP 5.3 support later in the year, this allows PHP 5.4.0+ to use Guzzle 5 and PHP 5.3 stays on Guzzle 3.
@rossriley I'll need some follow up help to get BackendTest::testPrefill() back online.
=> Guzzle 5 — take 2

app/view/twig/dashboard/_quicklinks-buttons.twig, app/view/twig/dashboard/_quicklinks-dropdown.twig
When allowing a user to create a contenttype but without view permission (perhaps create it with a custom extension). An exemple is a resource contenttype. I've added a check to make sure the user is able view the contenttype.
Another check that might be handy for the future is a check on show_on_dashboard: false
=> Add extra check for view permission for quicklinks

.travis.yml, tests/phpunit/BoltListener.php
Allows PHPUnit tests to be run on a fresh clone… 
…and allows me to recover from the heart attack of thinking master was b0rken :stuck_out_tongue_winking_eye:
=> [Tests] Move PHPUnit resource creation into the listener

.scrutinizer.yml, composer.json
Apparently we don't have our PHP source files in `app/src/` any longer… who went and did that?
…this should be fun!
=> Scrutinizer config

src/Application.php
Fixes #3302
[date_default_timezone_get](http://php.net/manual/en/function.date-default-timezone-get.php) checks value from `date_default_timezone_set` first, then `date.timezone` from ini, then system timezone, then falls back to 'UTC'. So we don't need to check ini ourselves, we just need to not override the value.
I think this change aligns more with the purpose of the config option. We only want to override the default timezone if it is provided in the config. If someone else wants to call `date_default_timezone_set` and override it themselves they can just leave the config entry out and we won't clobber them.
Note: A strict warning is now emitted though if `date.timezone` isn't set in ini and `timezone` isn't set in config.
=> Only setting default timezone if config provides it

src/Filesystem/Local.php
This more than likely will have a few holes on systems without posix functions, but it should be better than breaking completely.
=> add selective handlers for looking up user and group id

tests/phpunit/BoltListener.php, tests/phpunit/bootstrap.php
@rossriley a note on the `global $CLASSLOADER;`. 
It was introduced in 1c5973da0f6554695a25c0badded0af19c8dd69c and your 2.1 test work removed the need for it.
=> Have PHPUnit listner clear the cache on test start/finish

index.php
**Problem**
When you use PHP's built-in server the requests to files are not resolving correctly.
The condition to detect if it's file doesn't generate `$filename` correctly:
if (php_sapi_name() == 'cli-server') {
$filename = dirname(__DIR__) . preg_replace('#(\?.*)$#', '', $_SERVER['REQUEST_URI']);
if (is_file($filename)) {
return false;
}
}
This causes these file requests to be like `http://localhost:8000/app/view/img/bolt-logo.png/bolt/userfirst`.
**Solution**
I changed
$filename = dirname(__DIR__) . preg_replace('#(\?.*)$#', '', $_SERVER['REQUEST_URI']);
with
$filename = __DIR__ . preg_replace('#(\?.*)$#', '', $_SERVER['REQUEST_URI']);
As PHP version is checked in `index.php` previously there is no problem with `__DIR__`.
=> Fixed to handle correctly file requests with built-in server

.gitignore, app/src/Gruntfile.js, app/src/README.md, app/src/grunt/concat.js, app/src/grunt/remove.js, app/src/grunt/sass.js, app/src/grunt/uglify.js, app/src/package.json
:warning:  Generation of sourcemaps is now switched off by default.
Add ``app/src/grunt.json`` and enter
```json
{
"sourceMap": {
"css": true,
"js": true
}
}
```
there to get them generated. That file is ignored by git.
:warning: Generated css and js files should be committed without sourcemaps from now on!
=> Allow local overriding of grunt options (especially generation of sourcemaps)

app/src/js/modules/stack.js
This fixes an issue where you would need to open the modal, close it, then open it again before anything worked.
Using "shown" was trying to bind events directly to elements that didn't exist yet, we need to do it after the contents have loaded.
=> Fixed action intiialisation for stack modals

app/src/js/init.js, src/Controllers/Backend.php
This PR adds the ability to batch multiple items together for deletion in a single request.
This is achieved by accepting a comma-delimited list of IDs as a URL and function parameter:
`/bolt/content/deletecontent/pages/1,2,3`
`$controller->deleteContent($app, 'pages', '1,2,3')`
Currently, on an overview page if you select `n` items and "Delete selected" it will trigger `2n` HTTP requests, one to delete and one to "refresh" per item. 
This is quite inefficient and could possibly cause browser/server pain depending on the amount of items you're trying to delete.
Batching these deletes together, this process will only ever trigger 2 requests regardless of the number of items being deleted.
Current functionality will not change - making a request with a single ID will simply be treated as a …
=> [RFC] Delete multiple items more efficiently

app/view/twig/editfile/editfile.twig
Do not set required html tag on editfile textareas to allow editing of
empty files.
=> Allow editing of empty files.

phpunit.xml.dist, tests/phpunit/BoltListener.php
This is off by default. However it's greatest potential use, presently, is for extension unit testing. They can specify our listener and a relative path to a theme and that will get installed and configured.
e.g. An extension's phpunit.xml.dist would just add this:
```xml
<listeners>
<listener file="vendor/bolt/bolt/tests/phpunit/BoltListener.php" class="Bolt\Tests\BoltListener">
<arguments>
<boolean>true</boolean>
<boolean>true</boolean>
<boolean>true</boolean>
<string>vendor/bolt/bolt/theme/base-2014</string>
</arguments>
</listener>
</listeners>
```
=> [Tests] Add optional parameters to PHPUnit listener to copy/remove a theme directory

app/view/twig/activity/changelog.twig, app/view/twig/activity/systemlog.twig, app/view/twig/components/panel-change.twig, app/view/twig/components/panel-system.twig, src/Content.php, src/Controllers/Backend.php, src/Logger/ChangeLogItem.php, src/Permissions.php, src/Storage.php, src/Twig/Handler/UserHandler.php, src/Twig/TwigExtension.php, src/Users.php, tests/phpunit/unit/BoltUnitTest.php, tests/phpunit/unit/Controller/BackendTest.php, tests/phpunit/unit/Logger/ChangeLogItemTest.php, tests/phpunit/unit/Users/UsersTest.php
I was looking at an error on password reset where we were calling getUserByEmail() but that wasn't implemented.  Looking further the getUser*() function it seems we can just consolidate them.
@StevendeVries this affects you guys, the core functionality remains unchanged, jut dropping those new functions… can you chime in if you see any issues.
=> Consolidate user lookup functions

src/Application.php
Follow up to #3333 & #3334 
Fixes #3377
=> Always have a fallback for a timezone when it isn't set in either php.ini or config.yml

app/src/Gruntfile.js, app/src/grunt/aliases.yml, app/src/grunt/jsdoc.js, app/src/grunt/phpdocumentor.js, app/src/package.json
Adding PHPdocumentor task, run by ``grunt docPhp``.
:warning: For now this is for **internal usage** only and not meant to define and document a public API.
=> Adding PHPdocumentor task

src/Application.php, src/Config.php, src/Controllers/Frontend.php, src/Database/IntegrityChecker.php
The statics were introduced in 2a5c9d28700ce0eb2e8925426e7f5c522b511d1e for #692. 
The dependency loop that those commits worked around were, in effect, created by overloading the constructor needlessly.
This one is for you, @rossriley :grinning:
=> Less statics for Database\IntegrityChecker

web.config
For Issue #3422
Add in IIS URL Rewrite module drop in replacement for Apache .htaccess
file. URL rewriting is handled, as is the woff2 file definition, but I
had to disable the cache access and yml,db,twig,md deny rules as they
interfered with the CMS backend.
WARNING: In order to have this work on IIS you must have the IIS URL
Rewrite module. You will also need to alter the permissions on the files
folder and the PHP extension php_fileinfo will need to be enabled.
Instructions to follow in the documentation repository.
=> Add IIS web.config

src/Application.php
**NOTE:** This is ugly, and a workaround for all involved parties until we nail what is causing this to not react correctly to Symfony Response handling
Related to #3425
Fixes #3413
=> Make Application::unsetSessionCookie() optional and BC friendly

app/view/twig/editcontent/fields/_slug.twig
Currently the slug says "permalink" regardless of whether the contenttype is viewless or not. When there is no page for a contenttype, this can be misleading.
This just adds a simple check for a viewless contenttype and changes 'Permalink' to 'Unique Alias' if that check is true.
=> Change slug label when contenttype is viewless

src/Database/InitListener.php
DBAL pgsql sending `options` parameters in connect but it is won't affect client encoding settings but breaks other middlewares like pgbouncer. 
With DBAL 2.5.2 this should be removed! 
See https://github.com/doctrine/dbal/pull/828 for details.
=> PGSQL encoding settings in post connect event until doctrine/2.5.2 is out

app/view/twig/editcontent/fields/_select.twig
Tiny little feature that allows you to specify an optional filter when the values for a select field are pulled from a contenttype.. eg:
relatednews:
type: select
multiple: true
values: pages/title
filter: {categories:news}
autocomplete: true
=> add optional filter to select field with contenttype values

.gitignore, app/src/Gruntfile.js, app/src/README.md, app/src/grunt-tasks/pages.js, app/src/grunt/aliases.yml, app/src/grunt/bootlint.js, app/src/grunt/concat.js, app/src/grunt/htmllint.js, app/src/grunt/sass.js, app/src/grunt/uglify.js, app/src/package.json
- Local grunt options are now stored in single Javascript files inside ``grunt-local/``. This enables us to use real comments and regular expressions.
- Bolts backend pages can now be linted for HTML errors with the command``grunt lintHtml``.
- Bolts backend pages can now be linted for Bootstrap errors with the command``grunt lintBoot``.
For the linting you can define in ``grunt-local/pages.js`` which files you get from your local server. These are stored in ``tmp/pages`` and then are used for linting. For more information on this see ``Readme.md``.
:warning: Don't forget to ``npm install``
:warning: Convert your local settings in ``grunt.json`` to the new system and remove the file as this file will be removed from the grunt ignore list in the future.
=> Local grunt options changed and enabling linting of HTML/Bootstrap

app/src/grunt/watch.js
Adding ``grunt-local`` there makes grunt reload (local) configuration. Until now cached versions of local configs were used until restart of grunt. Now the cache is dumped on reload.
=> Also watch for changes in grunt-local

src/Storage.php
This allows pagination for using search in `Storage->getContent` calls (in Extensions) as well as `{% setcontent ... %}` calls in Twig. I have no idea why a fallback limit of 2000 was picked, but I've kept everything as it was just in case.
There also seems to be redundant params, e.g. `$decoded['parameters']` and `$parameters`. Not sure if there might be any duplicate functionalities, if you compare with the global front-end search in https://github.com/bolt/bolt/blob/master/src/Controllers/Frontend.php#L317
=> Fix pagination for searching via getContent() or {% setcontent %}.

src/Controllers/Backend.php
Hi,
just a pretty minor fix. I think that the expected behaviour of the backend in case the "extensions" directory does not exist should be to catch the FileNotFoundException exception and show the error "The folder '%s' could not be found, or is not readable." instead of returning a 500 Internal Server Error.
Regards,
Giovanni
=> Handle Flysystem exception correctly when a file is not found.

src/Storage.php
This solves a rather unusual bug whereby on Postgresql saving of a contenttype containing a boolean set to false would fail with a fatal error.
Looking deeper it seems that Doctrine handles native booleans by casting the values to strings, meaning that `false` gets converted to `''`
To convert properly the Doctrine platform adapter requires one of these options:
```php
private $booleanLiterals = array(
'true' => array(
't',
'true',
'y',
'yes',
'on',
'1'
),
'false' => array(
'f',
'false',
'n',
'no',
'off',
'0'
)
);
```
So the easiest way to handle this, rather than explicitly casting each contenttype to a type is to handle casting to one of the above before sending to save.
=> Cast booleans to integer to force correct PDO handling

app/src/js/modules/liveeditor.js
I've attempted to ensure the features match the equivalent backend field, the main goals being allowing newlines (for cases like running the value through the nl2br twig filter) and getting rid of random cruft (`&nbsp;`s) added by the browser.
Browser default behaviour on enter is to wrap an HTML element (div, p etc.), I've changed this to insert `<br>`s whilst editing which are then converted into newline characters when the live editor is closed.
Ping for Cap'n Liveedit, @Pinpickle, in case he needs to weigh-in.
=> Enable live editing for textarea fields

tests/phpunit/BoltListener.php
Prevents errors being thrown by sorting a non-array should the tracker be empty.
=> initialise tracker as empty array

src/Render.php
Render.php checks if the user is logged in incorrectly on line 173.
$this->app['users']->getCurrentUsername() returns null for users that are not logged instead of an empty string.
=> Request cache fix

src/Content.php
If you make a Twig typo, such as `{{ record.title }]`, then your front-end explodes. I believe it may be better to show the unparsed content. Though this behaviour does need to be documented.
=> Add a try-exception when parsing `allowtwig` fields.

src/Database/IntegrityChecker.php, src/Entity/Content.php, src/Field/Type/FieldTypeBase.php, src/Field/Type/FieldTypeInterface.php, src/Field/Type/Filelist.php, src/Field/Type/Geolocation.php, src/Field/Type/Image.php, src/Field/Type/Imagelist.php, src/Field/Type/Relation.php, src/Field/Type/Select.php, src/Field/Type/Slug.php, src/Field/Type/Taxonomy.php, src/Field/Type/Video.php, src/Mapping/MetadataDriver.php, src/Provider/EventListenerServiceProvider.php, src/Provider/StorageServiceProvider.php, src/Storage/EntityManager.php, src/Storage/EntityProxy.php, src/Storage/Hydrator.php, src/Storage/Loader.php, src/Storage/Persister.php, src/Storage/QuerySet.php, src/Storage/Repository.php, src/Twig/Handler/RecordHandler.php, tests/phpunit/unit/Mapping/MetadataDriverTest.php, tests/phpunit/unit/Provider/StorageServiceProviderTest.php, tests/phpunit/unit/Storage/ContentRepositoryTest.php, tests/phpunit/unit/Storage/FieldLoadTest.php, tests/phpunit/unit/Storage/FieldSaveTest.php, tests/phpunit/unit/Storage/StorageTest.php
Ok, lets do this.
Phase One of the new storage engine, for an overview of the philosophy there's much more in the new docs: https://docs.bolt.cm/storage/introduction
May contain: :koala: :koala: 
Whilst hopefully stable, in that the new system shouldn't interfere or break any existing code, it's probably not wise to build anything too strictly to this API since the next phase involves refactoring Bolt internals to take advantage of the new API, as we do so it's very likely that both the API and the implementation may change.
There's also quite a few field specific formatting / cleaning code that still has to be implemented on the new field types, so it's not 100% ready to replace the old storage class as yet.
=> Storage refactor

src/Nut/Extensions.php
Hi guys,
I've stepped into this issue when the internet connection is down the Nut command line will throw exceptions or fatal errors if you try and run extension related commands because the package manager has not been set up correctly (`$app['extend.online']` is false or `$app['extend.manager']->factory` is null). I think the expected behaviour is to show the error messages instead.
Example, instead of:
> PHP Fatal error:  Call to a member function getIO() on a non-object in /home/ggioffreda/Development/-/vendor/bolt/bolt/src/Composer/PackageManager.php on line 200
> PHP Stack trace:
> ...
> 
> PHP Fatal Error: Bolt Generic
Error: Call to a member function getIO() on a non-objectFile:  vendor/bolt/bolt/src/Composer/PackageManager.phpLine:  200
> * http://docs.bolt.cm/installation - …
=> Show error messages instead of throwing cryptic exceptions or fatals.

src/BaseExtension.php, src/Provider/NutServiceProvider.php, tests/phpunit/unit/Provider/NutServiceProviderTest.php
The whole point of `NutServiceProvider::addCommand` was to make it easier to register nut commands **without** invoking/creating every command.
Currently if I have even a _single_ extension that adds a _single_ command, **ALL 21** (20 core + 1 extension) commands will be created for _every_ web request even though they aren't used.
Pimple's extend and share syntax is very verbose (fixed in v3.0) and this shortcut was to help with that.
Even though the method was static it still used the app object passed in; not a static variable (like `Library` or `ResourceManager`). It had no negative effect to unit tests.
----
Perhaps the purposed change could be a compromise?
=> Performance improvement for registering nut commands

src/Config.php, src/Controller/Zone.php, src/EventListener/ZoneGuesser.php
Updated Config::getWhichEnd to use ZoneGuesser and deprecated it.
Also, deprecated `$app['end']`, but there is no way to note that other than the comment.
I tried to document a clear way foward for those trying to use it.
Note: _cli_ is not a Zone, because this doesn't really make sense. It is a simple check and completely unrelated to Request.
Config::getTwigPath is next :gun:
**Ninja Edit:** :koala: is :gun:
=> Deprecate Config::getWhichEnd

composer.json, src/Application.php
`symfony/locale` component is deprecated and just calls to `symfony/intl`, requiring that component instead.
Stub files are autoloaded [here](https://github.com/symfony/Intl/blob/master/composer.json#L38-L39).
=> Replace deprecated symfony/locale with intl. Remove loading intl stubs

src/Content.php
A slightly more robust implementation of the idea put forth in #3540. This also takes into account filtering it out from the 'excerpt' snippet, and it also allows you to concatenate fields: 
```
title_format: [ firstname, lastname ]
```
If merged in, I'll port it to master / 2.3 
**EDIT:** Closes #3540
=> Implement title_format

src/EventListener/SnippetListener.php
Affects generator, canonical and favicon.
Fixes #3622 & #1129 & #2786.
=> Move generator and related tags to END_OF_HEAD

app/view/toolbar/bolt.html.twig
Symfony 2.7 switched from a bitmap to an SVG. Fix the CSS accordingly.
=> Fixes the overlay of the Symfony Icon in our debug toolbar.

tests/phpunit/unit/Helper/MenuBuilderTest.php
- If $content is empty link comes from $item
- If $content is set link comes from content
This difference has been added
=> Improve MenuBuilderTest to check $item[link]

tests/phpunit/bootstrap.php
With v2.2.x the delete/copy test.db was removed. When running a testsuite it will only work correctly the first time, the second/third/etc the previous data still exists.
Using resetDb() in the Setup gives the following error:
unlink(/vagrant/vendor/bolt/bolt/bolt.db): Text file busy
Restoring the unlink/copy fixes this issue.
=> Fixes unittest by doing a replace db with testdb foreach phpunit run using bootstrap

src/Storage/Repository.php
This adds two nice little helper methods that hydrate the results fetched from a QueryBuilder object.
Bonus points for the first person to use.. `$repo->findOneWith($theUniverse);`
=> add hydrating find commands to the base repository

src/Extensions.php
`$force` defaults to false and currently isn't ever set otherwise, the conditional in there meant it will always his that return and never check the autoloaders.
=> Fix force logic on checkLocalAutoLoader

src/Controller/Frontend.php
I needed to search for a specific contenttype.
Usage: *routing.yml*
```yaml
blogsearch:
path:       /blog/search
defaults: { _controller: 'Bolt\Controllers\Frontend::search', 'contenttypes': ['posts'] }
pagesearch:
path:       /search
defaults: { _controller: 'Bolt\Controllers\Frontend::search', 'contenttypes': ['posts', 'pages', 'jobs'] }
```
=> Add the possibility to use the search for spcific contenttype(s)

src/Storage/Entity/Entity.php
Allows hydrated entities to have property access via `$entity['val']` as well as `$entity->val`
=> Add array access to base Entity

app/src/js/bind-fileupload.js
Client reported this one, they were trying to copy from Excel into input fields (title etc.) but on paste fileuploader was kicking in thinking they were trying to upload something and popping dialogs up.
There is a similar fix in place already over here: https://github.com/bolt/bolt/blob/release/2.2/app/src/js/upload-files.js#L188
=> Fix paste issue with fileuploader

src/Provider/AssetServiceProvider.php
This fixes an asset hashing bug that made itself known as nice big flashy warnings in the live editor while running under the php server.  Turns out the `substr` wasn't doing too much there.
Looks like the koala slipped on some wet :leaves:!
Cheers!
=> fix fullpath file hashing

src/Storage/Persister.php, src/Storage/Repository.php
Adds the ability to toggle persistence of an individual field.
`$repo->getPersister()->disableField('password');`
`$repo->getPersister()->enableField('password');`
=> Allow readonly fields via Perister customisation

tests/phpunit/unit/Extensions/AssetsProviderTest.php
Was causing corner-case test failures on some systems
=> [Tests] Change global functions for Assets provider tests

src/Storage/Database/Schema/Manager.php
The database platform's method getCreateTableSQL creates only indexes default, however foreign keys also can be added by the documentation: http://doctrine-dbal.readthedocs.org/en/latest/reference/schema-representation.html
We just have to add the second parameter to getCreateTableSQL call.
This also affects stable branches. I can make PRs to them/it as well if you accept this.
Source and documentation for AbstractPlatform for quick reference: http://www.doctrine-project.org/api/dbal/2.4/source-class-Doctrine.DBAL.Platforms.AbstractPlatform.html#1010
=> Update Integrity Manager

src/Twig/SetcontentNode.php
Hi folks,
I have a project requirement which has me redefine the `storage` service in `Bolt\Application`, for filtering results globally based on some criteria.
The fact that a `Bolt\Storage` standalone object is instantiated here bypasses the service in the container, so in my opinion it had to be fixed.
Is there a particular reason why the `storage` service wasn't used here, especially when Twig can get access to the container via `$context['app']`?
=> Replace Storage hardcoded instantiation with container reference

app/bootstrap.php, src/Exception/LowlevelException.php, src/Extensions.php, src/Nut/ExtensionsAutoloader.php, src/Provider/NutServiceProvider.php, tests/phpunit/unit/Configuration/LowlevelChecksTest.php
* **[General]** Added a very early shutdown function to pre-catch errors that occur before the application object is built. Hopefully less *White Screens of Death*
* Added a nut command to force the rebuild `./app/nut extensions:autoloader`
* When a fatal error occurs in an extension that is a result of a missing class, we will try to rebuild the autoloader and then either redirect to the intended page, or display the full error:
=> [2.2] Local extension autoloader enhancements

app/bootstrap.php, src/EventListener/WhoopsListener.php, src/Exception/LowlevelException.php, src/Extensions.php, src/Nut/ExtensionsAutoloader.php, src/Provider/NutServiceProvider.php, src/Provider/WhoopsServiceProvider.php, tests/phpunit/unit/Configuration/LowlevelChecksTest.php
* **[General]**  If vendor/autoload.php is missing, include LowlevelException.php manually.
* **[General]** Added a very early shutdown function to pre-catch errors that occur before the application object is built. Hopefully less *White Screens of Death*
* Added a nut command to force the rebuild `./app/nut extensions:autoloader`
* When a fatal error occurs in an extension that is a result of a missing class, we will try to rebuild the autoloader and then either redirect to the intended page, or display the full error:
=> Local extension autoloader enhancements

src/Storage/RecordModifier.php, tests/phpunit/unit/Controller/Backend/RecordsTest.php
This restores our unit tests to a full 100% pass with a green light!
=> Don't flush output buffers for tests

tests/phpunit/unit/Controller/BackendTest.php
This brings the 2.2 branch PHPUnit tests back to 100% pass
=> [2.2] Reenable BackendTest::testPrefill

src/Controllers/Backend.php
Currently in `2.2`, the **New Bolt website** e-mail is sent to any new user that gets created in the backend. This message should only be sent to the root account e-mail address upon first user creation, as it's just a confirmation that the `mailer` service is working correctly, which normal users don't care about, and don't really have to know about.
What's more is that the Twig template used for generating the message content doesn't use translation, and I don't really feel like explaining to my French-speaking clients why they're receiving unintelligible e-mails in English when I create their account in the backend :sweat_smile:
I'm pull requesting this against `release/2.2` as I consider this behavior a bug.
As far as I can tell, the problem is solved in `master`.
=> Send "New Bolt site" e-mail upon first user creation only

app/view/twig/editcontent/fields/_geolocation.twig
:warning::warning::warning: This is a binary compatibility breaking change.
Bug was introduced with [2.2.4](https://github.com/bolt/bolt/commit/5b402492ee470ac3a85292cc04f8d26de119836f#diff-7deb55152c7f64965d4f60501f1e0c21R36) and you can't even blame the :koala: this time.
If you use the the formatted address in the frontend like this:
```
{{ record.values.geolocation._address }}
```
it has to be changed back to the correct call:
```
{{ record.values.geolocation.formatted_address }}
```
This patch should be backported!
PS: values in the database were saved with the wrong key "_address" and would stay this way even after this patch and would have to be written again to be correct. Is there need provide both values on read for 2.2.x versions?
PPS: reported by @SahAssar
=> Regression in Geolocation: Change value "_address" back to "formatted_address"

app/resources/translations/de_DE/messages.de_DE.yml, app/resources/translations/en_GB/messages.en_GB.yml, app/view/twig/editcontent/fields/_markdown.twig
>You can use all UIkit components by just adding data-uk-* attributes to your HTML elements without writing a single line of JavaScript. This is UIkit's best practice of using its components and should always be considered first.
Let's do it the easy (and prefered) way for now. Later we can move it to field initialisation. We could set it global, but as we have to set the height option anyway …
While at it i also made translation of Markdown/Preview buttons possible.
- Fixes #3818
- Markdown/Preview buttons translatiable
=> Issue 3818 – Update JS Markdown Options to match Parsedown

src/AccessControl/Permissions.php, src/Twig/Handler/UserHandler.php, src/Users.php, tests/phpunit/unit/Storage/StorageTest.php, tests/phpunit/unit/Users/UsersTest.php
As pointed out by @rossriley: No need to fetch users every single time. This PR fetches them once, and returns from memory if possible. This yields a significant improvement in queries / time taken. 
Before: 
After:
=> Optimisation for backend by caching requests for users.

.travis.yml, src/Permissions.php, src/Twig/Handler/UserHandler.php, src/Users.php, tests/phpunit/unit/Storage/StorageTest.php, tests/phpunit/unit/Users/UsersTest.php
=> Optimisation for backend by caching requests for users. [2.2]

src/Helpers/MenuBuilder.php, src/Provider/RoutingServiceProvider.php, src/Routing/UrlGeneratorFragmentWrapper.php, src/Storage/RecordModifier.php, tests/phpunit/unit/Routing/UrlGeneratorFragmentWrapperTest.php
`Lib::path` and `Lib::redirect` both have an _add_ parameter which takes a string and appends it onto the end of the generated url. An example:
```php
$add = 'foo=bar#derp'; // I'm just an unstructured blob :(
$path = Lib::path('dashboard', [], $add);
echo $path; // /bolt?foo=bar#derp
```
As this class is deprecated (or trying to be :gun:), we need a new way to handle this functionality. 
Symfony's UrlGenerator will already take extra parameters (not needed in path) and add them to the query string of the generated url. This only leaves the _fragment_ part of the url functionality missing. 
I created a wrapper for the UrlGenerator that will take a `#` key from the parameters and append it. This also keeps the same interface/object, so no need for a "helper" method. 
New way:
```php …
```
=> Handle "add" parameter for url generator a new way

phpunit.xml.dist, tests/phpunit/BoltListener.php, tests/phpunit/bootstrap.php
This (should) make the unit test environment fully configurable for configuration files, theme and Sqlite database.
The biggest win here is for extension authors that want to unit test extensions with customised configuration (routes/contenttypes/etc) and Sqlite databases. Of course if you don't want to use Sqlite, that will be overridden in the passed in `config.yml` file.
There is an update to the docs [pending in a branch here](https://github.com/bolt/docs/compare/bolt:master...GawainLynch:update-phpunit-docs?expand=1) for once this is merged and back-ported into `release/2.2`, including the work in and #3850.
Special thanks go out to the :koala: who was busy eating :leaves:  and left me alone long enough to finish this today!
Ping @slahav… this should be exactly what you all need. …
=> Unit test parameter handling

src/Permissions.php
Fixes #3883 
If we try to get permissions for `pages/` (for a new record, without existing id), don't get stuck in a loop where we retrieve all records for that contenttype.
=> Break here if $contentId is `` or `0` instead of only on strictly `null`

src/AccessControl/Permissions.php
Fixes #3883 for 'master'.
If we try to get permissions for pages/ (for a new record, without existing id), don't get stuck in a loop where we retrieve all records for that contenttype.
=> [master] Break here if $contentId is `` or `0` instead of only on strictly `null`

src/Content.php
This fixes #3712.
Now `$config['uses']` is checked for existence _and_ explicitly converted to an array in case it's originally a single string.
=> Avoid a missing array key from displaying a warning

app/src/.jshintrc, app/src/grunt-tasks/pages.js, app/src/grunt-tasks/sass.js, app/src/grunt/bom.js, app/src/grunt/bootlint.js, app/src/grunt/concat.js, app/src/grunt/copy.js, app/src/grunt/endline.js, app/src/grunt/eol.js, app/src/grunt/htmllint.js, app/src/grunt/jsdoc.js, app/src/grunt/jshint.js, app/src/grunt/modernizr.js, app/src/grunt/phpdocumentor.js, app/src/grunt/postcss.js, app/src/grunt/remove.js, app/src/grunt/sass.js, app/src/grunt/uglify.js, app/src/grunt/watch.js, app/src/js/.jshintrc
- Moved the jshint config into ``js/.jshintrc``
- Added ``.jshintrc`` for grunt files
- Removed inline jshint directives for globals
- Added ``jshint:grunt`` grunt target
- Fixed two small issues
Now IDEs and editors can make use of ``jshint`` with Bolts settings.
=> Add .jshintrc

app/view/twig/_base/_listing.twig, app/view/twig/_sub/_editable_record_list.twig, app/view/twig/dashboard/_recently_edited.twig, app/view/twig/omnisearch/omnisearch.twig, app/view/twig/overview/overview.twig, app/view/twig/relatedto/relatedto.twig, src/AccessControl/Permissions.php, src/Controller/Backend/BackendBase.php, src/Controller/Backend/General.php, src/Controller/Backend/Records.php, src/Controller/Backend/Users.php, src/Omnisearch.php
Provide a `Permissions::getContentTypeUserPermissions()` function to get a user's permissions 
* 'create', 'edit', 'delete', 'publish', 'depublish', 'view' and 'change-ownership'
Allows
* Permissions to be passed into the Twig context as a variable.
* Remove repeated use of `isallowed()` in Twig
* Allows for use cases such as when user doesn't have `edit` permission, but can be granted `publish` permission
* Fixes #3802 for master (2.2 backport to come)
**Note:** In master this will require further clean up before v2.3.0 and I am sure @rarila will want to refactor some Twig stuff :+1: 
Ping @bnelson-cainc
=> Permissions streamline

src/Database/IntegrityChecker.php
This PR is related to #3745. That change added foreign keys only on table creation leaving alters out. So I added few more lines to handle new or modified foreign keys after creation.
I don't know for sure if this is needed in master branch.
=> Add foreign key checks to IntegrityChecker

src/Controller/Frontend.php, theme/base-2014/config.yml
Hi, 
this PR aims to provide a theme override for `listing_records`, `listing_sort` and `search_results_records`.
Fixes #3951
=> Issue 3951 theme config override

app/resources/translations/pt/messages.pt.yml
This PR fixes #3992 issue, it just corrects the key name.
=> Fix for #3992 Invalid messages yaml for pt translation 

src/Application.php, src/Config.php, src/DataCollector/BoltDataCollector.php, src/Provider/NutServiceProvider.php
This is in an effort to not couple our code to `Bolt\Application`
=> Deprecated App::getVersion in favor of container parameter

src/Permissions.php
The missing parameter was preventing `Bolt\Storage::getContent()` to bypass the forced `published` status for retrieved records.
I've seen this "trick" being used in `Bolt\Controllers\Backend` for example.
Please see #3466 for the full discussion.
=> Fix record retrieval for ownership checking

app/src/js/modules/video.js
Fixes #3976
This is all that `ack "['|\"]\/\/" src/ app/src/js/ app/view/twig/` found in both branches
=> Use HTTPS for embed.ly calls

app/resources/translations/fr_FR/messages.fr_FR.yml
Fix for JS in extensions page. When in french, messages are broken because of quotes.
=> [I18N] Fix for quotes in JS messages

app/view/twig/editcontent/fields/_imagelist.twig
The info text for `imagelist` fields pointed to the text for `filelist` fields.
I sent a PR for `master` as well : #4052
=> [2.2] Fix the info text for imagelist fields

app/view/twig/editcontent/fields/_imagelist.twig
The info text for `imagelist` fields pointed to the text for `filelist` fields.
I sent a PR for `release/2.2` as well : #4051
=> Fix the info text for imagelist fields

app/view/twig/editcontent/_aside-status.twig, app/view/twig/editcontent/_buttons.twig, app/view/twig/editfile/editfile.twig
Hey folks,
I don't consider this a bug or an improvement, it's just some proposed changes.
Basically, the `%b %e, %H:%M` date-time format is used throughout the backend. The "problem" is that it puts the month number before the day number, which is not the way to go in French for example, as we normally put the day number before the month number. I personally don't mind this so much, but I can see how this can be a problem for some of my picky clients.
So I propose to use the `%c` format instead, even though I know it's not ideal, because it's a bit verbose, but it's the only _l10n-friendly_ format available for `strftime()`.
What do you think?
=> [RFC] Change used date-time format to a more i18n-friendly format

src/Controller/Frontend.php
=> Don't sort getContent in listing view, when the contenttype has a taxonomy that has a sortorder.

app/view/twig/editfile/editfile.twig, src/Controllers/Frontend.php
Fixes #3977 for `release/2.2`.
=> [2.2] Don't sort getContent in listing view, when the contenttype has a taxonomy that has a sortorder.

app/src/package.json
Perhaps temporary, if they fix it properly on Modernizr's end of things. See: Modernizr/grunt-modernizr#118
Fixes #4094
=> Fix for breakage after Modernizr 3.0.

.gitignore
This prevents the :koala: from committing a theme when working on a core repo…
=> Ignore theme directory except for base-* and default

src/EventListener/ExceptionListener.php
[Logger] If exception is a client error reduce log level to warning. Implemented LoggerAware so the logger can be overridden later.
=> [Logger] If exception is a client error reduce log level to warning

src/Pager.php
Pager doesn't work with array as query parameter. This issue is solved with help of http_build_query().
=> Allow non-strings as query parameters with pager. issue #4109

app/view/twig/editcontent/_taxonomies.twig, src/Controllers/Async.php
Backport of #4125 for 2.2
Not sure if you want to merge this in 2.2 or not. To me this seems like a fix that anybody would want, but it does change the way the tagging widgets work.
=> Use tag names instead of slugs for autocomplete and tag cloud [2.2]

src/Provider/NutServiceProvider.php, tests/phpunit/unit/Extensions/BaseExtensionTest.php, tests/phpunit/unit/Provider/NutServiceProviderTest.php
Updated nut.commands.add shortcut to accept callable. Also added example usage.
```php
$app['nut.commands.add'](function ($app) {
return new Command1($app);
});
$app['nut.commands.add'](function ($app) {
return [
new Command1($app),
new Command2($app),
];
});
```
=> Updated nut.commands.add shortcut to accept callable. Also added example usage.

src/EventListener/GeneralListener.php
Only show notice when logged on. Fixes #4126. Fixes #3905.
=> Fix: Don't show notice about `mailoptions` when not logged on. 

src/Application.php
Only show notice when logged on. Fixes #4126. Fixes #3905.
=> [2.2] Fix: Don't show notice about `mailoptions` when not logged on.

src/Application.php, src/Events/MountEvent.php, src/Provider/ControllerServiceProvider.php
Updated `Application::mount` to forward to our mount event. This ensures low priority (less than 0) controllers are last.
Cleaned up some of the Controller SP as well.
=> Controller mounting tweaks

src/Legacy/Storage.php, src/Storage/Query/Handler/OrderHandler.php
Modified the legacy and upcoming storage system to allow for multi sort in the setcontent query. Now queries can be used as follows to sort on multiple columns. 
Ex.:
```twig
{% setcontent 'entity' orderby('-name, title') %}
```
**Edit**
Fixes #1255
Fixes #2234
=> Enhancement - Added the ability to allow for Multi Sort Functionality in getContent

app/view/twig/editcontent/_relations.twig, src/Controllers/Backend.php
This is a nasty bug that only reveals itself if you have `strict_variables: true`. It appears to have been introduced in 2.2.9 or 10.
How to reproduce:
* Set `strict_variables: true` in `config.yml`.
* Add a relation to `pages` in the `entries` content type.
* Create a page.
* Create an entry that references the page.
* Edit the page. You should get *Variable "permissions" does not exist in "_base/_listing.twig" at line 3*.
I actually haven't tested this in master, so I don't know if it needs to be ported.
Happy friday!
=> Fixed missing variable permissions in _relations.twig. [2.2]

app/view/twig/nav/_macros.twig
So, I don't know if there was a reason for the element's `class` not being output when `allowedamount == 1`, but it produces the following visual bug:
This fixes it, but I hope it doesn't have any side effects?
I sent a PR for `release/2.2` as well: #4173
=> Fix secondary nav element's class not being output in certain cases

app/view/twig/editcontent/editcontent.twig
Strip tags from title in editcontent. I used striptags instead of escape since this mimics the behaviour in backend listings and the backend menu. Fixes #3590
=> Strip tags from title in editcontent. Fixes #3590

src/Content.php
=> [2.2] Use hydration for `{{ record.previous() }}` and `{{ record.next() }}`.

src/Storage.php
When using status updates with contenttypes with multiple taxonomies
and one taxonomy is defined with `grouping` all taxonomy values are set
to the value of the `grouping` taxonomy.  By passing the taxonomy type
to `getIndexedTaxonomy()` non-grouped item values are preserved.
Example to replicate.  Consider a taxonomy as follows:
```
region:
name: Region
slug: region
multiple: false
behaves_like: categories
options: [ North, South, East, West ]
listing_template: listing.twig
types:
name: Types
slug: types
singular_name: type
singular_slug: type
behaves_like: grouping
multiple: false
options: [ Article, Gallery, Video, Event ]
listing_template: listing.twig
```
If a contenttype refers to both taxonomies and the status is changed via the dashboard or article list, all taxonomies are set to …
=> Fixes #3868 - Taxonomies being wiped on status change using grouped taxonomy

app/config/contenttypes.yml.dist, tests/phpunit/unit/Storage/FieldLoadTest.php
This was causing errors to be thrown on the dashboard, due to the fact
that "repeat" is a reserved word in MySQL.
Fixes #4272.
Mentioning brown M&Ms, as per the contributing doc!
=> Renamed example repeat field.

.htaccess
If you copy paste this in a standard terminal it will put the text "the section below" to a new line. This will result in a fault in .htaccess. That's why "the section below" is maby better on a new line.
=> Update .htaccess 78 characters for terminal

src/Helpers/Image/Image.php, src/Helpers/Image/Thumbnail.php, src/Twig/Handler/ImageHandler.php, src/Twig/TwigExtension.php, tests/phpunit/unit/Twig/BoltTwigHelpersTest.php, tests/phpunit/unit/Twig/Handler/ImageHandlerTest.php
This brings `\Bolt\Twig\Handler\ImageHandler` to 100% test coverage and breaks out the logic into a couple of `\Bolt\Helper` classes along the way.
=> Twig image handler tests & reorganisation

src/Application.php, src/Configuration/ResourceManager.php, tests/phpunit/nutty
Fixes #4295 
**Note:** This is already both done differently, and handled correctly, in `master`
=> Don't insert Bolt meta tags on AJAX requests

tests/phpunit/unit/DataCollector/TwigDataCollectorTest.php
Our unit tests are throwing this warning, which is a distraction.
```
PHP Warning:  filemtime(): stat failed for vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(290) : 
eval()'d code in vendor/twig/twig/lib/Twig/Environment.php on line 769
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:44
PHP   3. PHPUnit_TextUI_Command->run() vendor/phpunit/phpunit/src/TextUI/Command.php:100
PHP   4. PHPUnit_TextUI_TestRunner->doRun() vendor/phpunit/phpunit/src/TextUI/Command.php:149
PHP   5. PHPUnit_Framework_TestSuite->run() vendor/phpunit/phpunit/src/TextUI/TestRunner.php:440
PHP   6. PHPUnit_Framework_TestSuite->run() vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
PHP   7. …
```
=> [2.2] Silence warning notice

app/config/config.yml.dist, src/Application.php
I think relying on some magic content in the database for a not found page is a bad thing. The error404 page should work, especially when the database is empty (for whatever eason). So working with a template seems the better option since it will always work.
A default template may also be added if desired, something like:
```
{% include '_header.twig' %}
<article>
<h1>Page not found</h1>
<p>The requested URL "{{ app.request.getRequestUri }}" was not found.</p>
</article>
{% include '_footer.twig' %}
```
This is just for 2.2 since I don't have a master/2.3 setup and notfound handling seems changed in master.
=> Not found using a template instead of a database record

app/view/twig/editcontent/fields/_geolocation.twig
Fixes #4310 (hopefully)
And I even can't blame the :koala: …or, can I?!
=> Fixes #4310 – Geolocation fields no longer able to be used in templatefields.

app/view/twig/editcontent/fields/_geolocation.twig
=> [2.2] Fixes #4310 – Geolocation fields no longer able to be used in templatefields.

src/Controller/Async/FilesystemManager.php
Check each record type that appears in the record browser popup to make sure it's not viewless before adding its links to the list. Prevents appearance of brown M&Ms.
**Edit**
Fixes #4120
=> hide viewless from record browser popup #4120

composer.json, phpunit.xml.dist
As [described here](http://symfony.com/doc/current/cookbook/upgrade/major_version.html) and [announced here](http://symfony.com/blog/new-in-symfony-2-7-phpunit-bridge).
This is some more awesome by Nicolas to enable notifications on deprecations… presently master only gives us:
```
$ php70 vendor/bin/phpunit 
New value for theme: base-2014 was successful. File updated.
Deleted 1 files from cache.
Cache cleared!
PHPUnit 4.8.16 by Sebastian Bergmann and contributors.
.....I..S......................................................  63 / 933 (  6%)
............................................................... 126 / 933 ( 13%)
......................................................SS....... 189 / 933 ( 20%)
............................................................... 252 / 933 ( 27%) …
```
=> [Tests] Deprecation notices

tests/phpunit/unit/Events/ControllerEventsTest.php, tests/phpunit/unit/Events/CronEventTest.php, tests/phpunit/unit/Events/MountEventTest.php, tests/phpunit/unit/Events/StorageEventTest.php
Missing (single) line of code is ControllerEvents being singleton, which is tested, but can't show up in PHPUnit coverage… 'cause… no further comment… :stuck_out_tongue_winking_eye:
=> [Tests] Bolt\Events

src/Extensions.php
Priority did not work because it was converted to boolean if the variable priority was set. The methods affected are addCss and addJavascript. 
A dump of the variable $files in the method  processAssets shows  this:
```
array:2 [▼
"ebb081dd3fe3d1e6b08d5f11c5e01ac3" => array:4 [▼
"filename" => "/extensions/vendor/bolt/editable/assets//ckeditor/ckeditor.js"
"late" => true
"priority" => true
"attrib" => false
]
"dcb1cb7e3145c3508a7ee333d2803159" => array:4 [▼
"filename" => "/extensions/vendor/bolt/editable/assets//ckeditor/startup.js"
"late" => true
"priority" => true
"attrib" => false
]
]
```
=> Fixed priority issue in assets. Fixes #4319

src/Asset/File/FileAssetBase.php, src/Asset/File/FileAssetInterface.php, src/Asset/File/JavaScript.php, src/BaseExtension.php, src/Extensions.php, src/Extensions/AssetTrait.php, src/Provider/AssetServiceProvider.php
**Summary**
* Fixes #4332
* Allows file asset objects to be created with file name, skipping fluency if desired
**Documentation**
This cleans up and fixes some derps from the asset refactor, and widget implementation branches. Below is an example of what now **can** be done, 2.0 & 2.2 behaviour is still valid.
* In the front-end "zone" we simply inject a JavaScript and CSS files with default options, exactly the same as `addCss('assets/css/foo.css')` `addJavascript('assets/js/foo.js')` 
* In the back-end "zone" we create the object and set whatever other options we do/don't want.
```php
use Bolt\Asset\File\JavaScript;
use Bolt\Asset\File\Stylesheet;
use Bolt\BaseExtension;
use Bolt\Controller\Zone;
class Extension extends BaseExtension
{
public function initialize()
{ …
```
=> Asset handling fixes/tweaks

composer.json
Fixes #4265
I changed the global _minimum stability_ to stable, because it's way easier to see which packages need a lower stability. At this point, `composer/composer` is the only one.
Because our _minimum stability_ in stable now, _prefer-stable_ isn't needed
=> Set composer/composer to dev stability

src/Application.php, src/Cache.php, src/Configuration/Environment.php, src/Nut/SetupSync.php, src/Provider/ConfigServiceProvider.php, src/Provider/NutServiceProvider.php
* New class to manage install environment/checks
* Moved version check / cache flush from `Bolt\Cache`
* If web root is writeable the relevant `app/view/` directories are synchonised
* Added nut command where web user has no write access:
* Multi-site set up just got a lot easier and smoother updates.
* Fixes #3551 for composer install updates
=> Environment update handling

src/Application.php, src/Exception/LowlevelException.php
I had a problem this morning setting up a PostgreSQL install. I was able to use `psql` from the CLI and access the configured database, and the HBA access was set liberally… 
Why couldn't I access my database? Bolt would just tell me to check my connection… and I had! :stuck_out_tongue_winking_eye: 
With this PR, if you have debug logging enabled, something similar to this will end up in `app/cache/bolt-debug.log`
```
[2015-10-30 05:10:16] logger.system.DEBUG: An exception occured in driver: SQLSTATE[08006] [7] FATAL:  no pg_hba.conf entry for host "46.17.0.55", user "koala", database "bolt_master", SSL off {"event":"exception","exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] FATAL:  no pg_hba.conf entry …
```
=> DBALException logging tweaks

src/Extensions.php
When the HTML is minified, the regex for the insertion of snippets stops working, my change has been instead of this:
```
preg_match("~^([ \t]*)</head~mi")
```
I have used this:
```
preg_match("~([ \t]*)</head~mi")
```
I removed the caret ^ and the snippets are inserted correctly even if I minify the HTML, if I don't remove the caret the snippets which contain the meta "generator" or the sitemap are inserted after the body, because it is the behaviour it has when the pattern does not match:
````
if (preg_match("~([ \t]*)</body~mi", $html, $matches)) {
.............................
} else {
// Since we're serving tag soup, just append it.
$html .= $tag . "\n";
}
```
So that you can see the difference, look at this regex with the current Bolt regex: 
https://regex101.com/r/qU3tX7/2
It works …
=> Regex that insert snippets not working when </head> does not starts the line

theme/base-2014/_header.twig
=> Replace ☰ for ≡ for better supported unicode on Android.

app/theme_defaults/_sub_menu.twig, theme/base-2014/_sub_menu.twig, theme/base-2016/_menu.twig
Making the default `_sub_menu.twig` templates a bit more legible.
- Added comments
- Added whitespace
- Uses way less `{% ifs %}`
- Removed deprecated `_self`
- Works with `strict_variables: true` now.
Funtionality-wise nothing has changed.
=> Making _sub_menu.twig more legible.

app/theme_defaults/_sub_menu.twig, theme/base-2014/_sub_menu.twig
Making the default _sub_menu.twig templates a bit more legible.
- Added comments
- Added whitespace
- Uses way less {% ifs %}
- Removed deprecated _self
- Works with strict_variables: true now.
Funtionality-wise nothing has changed.
=> [2.2] Making _sub_menu.twig more legible.

app/theme_defaults/widgetjavascript.twig
Ideally, we'll make this script "vanilla", so it doesn't require jquery at all. Until that time, this will have to do. At least it doesn't break when JQuery isn't present.
=> Don't break if Jquery is not present.

src/Composer/BootstrapGenerator.php, src/Configuration/Composer.php, src/Configuration/Environment.php, src/Configuration/ResourceManager.php, src/Configuration/Standard.php, src/Provider/ConfigServiceProvider.php
This PR fixes #4386 by introducing a `view` path into `ResourceManager`, so we now properly sync both composer-install and multi-site set ups back-end assets on a version change. 
Side note… What this fixes bit me when I set up a Composer install to test this. Starting with a 2.2 install,  then updating that to a master via composer leaves 2.2 `lib.min.js` where in 2.3 `lib.js` is needed.
So thank you @Boorj for nagging me, and @rossriley for his suggested approach.
=> Fix environment view sync for all install types

src/Nut/UserAdd.php, src/Nut/UserResetPassword.php, tests/phpunit/unit/Nut/UserAddTest.php, tests/phpunit/unit/Nut/UserResetPasswordTest.php
Neither  `nut user:add` or `nut user:reset-password` currently work… this fixes that and add tests (and a tiny deprecation refactor)
Oh and user name and email address duplication messages work now:
```
$ ./app/nut user:add koala "Drop Bear" drop.bear@koala.com.au GumL3@ve$ root
Successfully created user: koala
$ ./app/nut user:add koala "Drop Bear" drop.bear@koala.com.au GumL3@ve$ root
Error creating user:
* User name 'koala' already exists
* Email address 'drop.bear@koala.com.au' already exists
```
=> Nut password handling

src/Storage/ContentRequest/Edit.php
This should remove the need to manually create file upload directories. Before, if the directory did not already exist, the upload button would be disabled for the affected field, with the text "Upload is not allowed". This change will automatically create the needed directory, and only show the "Upload is not allowed" text if creation fails.
=> Automatically create upload directories for contenttype fields - Fixes #4405

app/view/twig/editcontent/fields/_select.twig, src/Twig/Handler/RecordHandler.php
As @rarila pointed out: 
> The first child option element of a select element with a required attribute and without a multiple attribute, and whose size is “1”, must have either an empty value attribute, or must have no text content.
This PR should fix that. Fixes #4353
=> Make 'required' for `type: select` fields work. 

src/Users.php
Backport of #4413: Limit user agent strings to 128 characters on persist
=> [2.2] Backport of #4413: Limit user agent strings to 128 characters on persist

src/Profiler/DatabaseDataCollector.php
Only the two "information_schema" ones are added. I just moved it around a bit. 
before: 
after:
=> Don't list queries in the profiler that are only seen as noise.

src/Storage/Repository/UsersRepository.php
Makes quite a diffference in the querycount. 
Before: 
After:
=> Retrieve single users only once.

src/Application.php
Use reflection to determine the location of the web profiler bundle, thereby removing the guesswork of configuring twig with the location of the web profiler bundle's templates.
I also don't like brown M&Ms.
=> Fixes problem of web profiler bundle template location by using reflection. Fixes #4431

src/Storage/Database/Schema/TableModifier.php
Under certain conditions, Sqlite can lose data if table processing is allowed to continue…
=> Don't continue processing a table after exception is hit

src/Asset/Widget/Queue.php
Widget::process() only inserts a JavaScript snippet if any of the
widgets are deferred.
Whereas unlike files, the output is done in render() and the sorting
should be done here.
=> Sort widgets on render() not process()

src/Composer/PackageManager.php, src/Controller/Async/General.php
When news.bolt.cm is unreachable, php-fpm timeouts because connection_timeout of curl options does not work.
according to guzzlehttp 5.3 documents, it shoule be set like this:
http://docs.guzzlephp.org/en/5.3/http-messages.html#request-config
and curl options should be constants instead of string.
Fixed :D
Also I found in PackageManager.php it uses guzzle request options to set timeout time, but when fetch bolt news it use raw curl options, maybe should be consistent?
=> fix wrong guzzle curl options

.travis.yml, composer.json, tests/codeception/acceptance/101-BackendEditor/BackendEditorCest.php, tests/codeception/acceptance/103-BackendManager/BackendManagerCest.php, tests/codeception/acceptance/200-Frontend/FrontendCest.php
We were asserting that we **see** text which is in an `<input value="">`.
These started getting stripped https://github.com/Codeception/Codeception/issues/2249 https://github.com/Codeception/Codeception/issues/2461.
**seeInSource** doesn't strip tags https://github.com/Codeception/Codeception/pull/2465
=> Fix codeception tests

src/Config.php, src/Controller/Backend/Users.php, src/Provider/DatabaseSchemaServiceProvider.php, src/Storage/Database/Schema/Builder/BaseBuilder.php, src/Storage/Database/Schema/Builder/BaseTables.php, src/Storage/Database/Schema/Builder/ContentTables.php, src/Storage/Database/Schema/Builder/ExtensionTables.php, src/Storage/Database/Schema/Table/BaseTable.php
No matter what charset was set in config, bolt created tables in utf8 and utf8_unicode_ci in mysql during installation, because it's doctrine dbal default:
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L478
btw utf8mb4 and utf8mb4_xxx_ci works fine.
=> Use db charset and collate set in config file to generate table creation sql

src/Exception/LowlevelException.php, src/Library.php, tests/phpunit/unit/Configuration/ComposerConfigurationTest.php, tests/phpunit/unit/Configuration/LowlevelChecksTest.php, tests/phpunit/unit/Library/BoltLibraryTest.php
This prevents multiple exceptions being output in a single request cycle… Bring on the lifting of feature freeze.
=> Move echo out of constructor into shutdown function

src/Storage/Entity/ContentSearchTrait.php
=> Don't let the 'slug fields' override explicitly defined searchweights.

app/src/js/modules/secmenu.js
There is an issue where the sidebar resizes larger as the content size increases, but the content size decreasing is not resizing the sidebar. This fix sets the sidebar height to 0 before calculating the sidebar height to ensure that the document height is pulled in correctly for the calculation.
This is a fix for issue #4573 and should be pulled into master, 3.0 and 2.2
=> Issue #4573: added default height of 0 to the navpage secondary outer (3.0)

app/src/js/modules/secmenu.js
There is an issue where the sidebar resizes larger as the content size increases, but the content size decreasing is not resizing the sidebar. This fix sets the sidebar height to 0 before calculating the sidebar height to ensure that the document height is pulled in correctly for the calculation.
This is a fix for issue #4573 and should be pulled into master, 3.0 and 2.2
=> Issue #4573: added default height of 0 to the navpage secondary outer (2.2)

src/Storage/Field/Collection/RepeatingFieldCollection.php
When flattening the existing values, index the array keys numerically so that subsequent groups dont overwrite the previous.
=> Fix for save / overwrite error on repeating fields

.travis.yml
We have been passing tests on PHP 7 since PHP 7-RC4 and 7.0.0 is now GA.
=> [Travis] Require pass from PHP 7

src/Application.php
Fix 'JavaScipt' typo, and change initialise to initialize in order to be consistent with the majority of the file, as well as with the method naming.
=> Extremely minor comment tweaks

src/EventListener/NotFoundListener.php, src/Render.php
Can't find where @Boorj was complaining about this, but this is less hacky.
=> [NotFoundListener] Check if template exists instead of string ending with ".twig"

src/Controller/Backend/FileManager.php
When I want to open a empty extension config file in the backend, I get a exception "The file 'extensions/clientprofiles.bolt.yml' doesn't exist, or is not readable."
$file->read() returns false if file can't be read. At the moment $file->read() returns a empty string and this is checked as false.
Fixes #4636
=> Prevent exception empty extension config files

app/view/twig/nav/_macros.twig
Fix: submenu is missing if `show_in_menu` is set
A little bugfix for 2.2.15 - have a happy new year! :boom: :tada: :beers:
=> Template bugfix for backend menu

app/view/twig/_macro/_buic.twig
In buic-select an empty option was added to non multiple selects regardless of if there already ways an empty option included. That produced an output like this:
```html
<select><option value="" label="–"></option><option selected></option>…
```
Now we check for empty values for correct output.
=> Fix selects with empty values

src/Provider/NutServiceProvider.php, tests/phpunit/unit/Provider/NutServiceProviderTest.php
=> Move NutSP::addCommand to $app['nut.commands.add'] so it's not "static"

src/Extensions.php, src/Filesystem/Manager.php
These paths are referencing the `app` directory relative to bolt's install, which could mean trying to write to a vendor subdirectory in a composer install.  Using the cache location configured in resources fixes this.
=> don't try writing to vendor on composer installs (2.2)

src/Config.php
Fixes #4687
(or rather: It will, after #4686 has been resolved)
=> Fix fatal error when missing "fields" in contenttype.

src/Controller/Frontend.php
Hey guys, thanks for this great CMS.
I'm facing a case where I want to define differents amounts of records for multiple kind of taxonomies.
For my articles I have a taxonomy called **Thematic**, for which I want 2 records fetched in the full view of the taxonomy **Thematic**, but I also have a taxonomy **levelofDifficulty** and for that one I want 6 records per pages.
Therefore I made a little fix that override the theme's specific or theme's global config. Do you agree about that ? Or do you have a better way to handle that ?
PS : I wanted also include the listing option, but I contents doesn't have the same fields, it can make some issues. So nevermind about listing order. ^
PS2 : Carry on buddy !
=> [Feature] Added capability to set a record amount for specific kind of taxonomy

src/Storage/Field/Type/RepeaterType.php
Fixes #4692 
Still creates redundant SQL: there is one GROUP_CONCAT per repeater field, each returning the same values (all field values of all repeater fields of the respective contenttype).
Only tested on sqlite.
=> fix multiple repeater fields

tests/phpunit/unit/Library/BoltLibraryTest.php
Recent :koala: based changes caused a whole lot of these to be generated on Travis PHP 7 tests:
```
Bolt - Fatal Error
File is not readable!The following file could not be read: [snip]/non/existent/path/data.php
Try logging in with your ftp-client and make the file readable. 
Else try to go back to the last page.
This is a fatal error. Please fix the error, and refresh the page.
Bolt can not run, until this error has been corrected. 
Make sure you've read the instructions in the documentation for help. If you
can't get it to work, post a message on our forum, and we'll try to help you
out. Be sure to include the exact error message you're getting!
* https://docs.bolt.cm/installation - Bolt documentation - Setup
* https://discuss.bolt.cm/ - The Bolt discussion forum
* …
```
=> Fix false test fatal errors on PHP 7 

composer.json, src/Composer/PackageManager.php, src/Provider/GuzzleServiceProvider.php, tests/phpunit/unit/Controller/Async/GeneralTest.php, tests/phpunit/unit/Controller/Backend/GeneralTest.php, tests/phpunit/unit/Storage/PrefillTest.php
With the agreement in the development meeting 2016-01-12 to have Bolt 3 require PHP 5.5.9, we are now able to use Guzzle 6 as our default.
This PR creates a compatibility layer for projects that still require Guzzle 5 in their root project, but for everyone else… PSR-7 is here. :grin:
=> Guzzle 5 & 6

src/Controller/Frontend.php
Fixes a bunch of notices for listing pages.
=> Make sure we fetch the contenttype, even if no records were fetched.

src/Legacy/Storage.php, src/Storage/Field/Type/RepeaterType.php, src/Storage/Repository/FieldValueRepository.php
This makes repeating fields available in templates. Note that this PR doesn't actually implement the output of these fields, just makes them available in the resulting `record` object.
The field values are different to standard value based fields in that the field contains an iterable collection, so you will need to do two for loops one to loop the sets and then a further inner loop to list each of the fields within a set.
=> Add repeater fields to legacy content objects

composer.json, src/Application.php, src/Debug/Caster/AbstractCasterProvider.php, src/Debug/Caster/FilesystemCasters.php, src/Filesystem/Handler/NullableImage.php, src/Provider/DumperServiceProvider.php, src/Provider/TwigServiceProvider.php, src/Twig/DumpExtension.php, src/Twig/Handler/ImageHandler.php, src/Twig/Handler/UtilsHandler.php, src/Twig/TwigExtension.php, tests/phpunit/unit/Twig/Handler/ImageHandlerTest.php, tests/phpunit/unit/Twig/Handler/UtilsHandlerTest.php, tests/phpunit/unit/Twig/TwigExtensionTest.php
Working backwards: This fixes #4679. The `imageinfo` twig function now returns a filesystem image, which has image info as one of its properties. Note that BC is mostly kept with magic calls. [`NullableImage`](https://github.com/CarsonF/bolt/blob/bugfix/twig-dump/src/Filesystem/Handler/NullableImage.php) was needed to return an empty `Image\Info` where there is a problem, since twig cannot catch exceptions.
The other problem @SahAssar was bringing up is that `dump()` doesn't show all the properties he is expecting (lazy getters and getters that don't have properties). Symfony's VarDumper has a nifty way to extend the data pulled from objects called _Casters_. I created [`FilesystemCasters`](https://github.com/CarsonF/bolt/blob/bugfix/twig-dump/src/Debug/Caster/FilesystemCasters.php) to …
=> VarDumper, Casters, and Image Info! Oh my!

app/resources/translations/en_GB/messages.en_GB.yml, app/resources/translations/sv_SE/messages.sv_SE.yml, app/view/twig/_sub/_messages.twig, app/view/twig/dashboard/_aside.twig, app/view/twig/omnisearch/_aside.twig
Move noscript message to a danger flash message, which makes it appear on every page and also make it more clear that JS isn't really optional. Fixes #4615, but will require updates of all translations.
=> Move noscript message to a danger flash message

src/Extension/DatabaseSchemaTrait.php, src/Storage/Database/Schema/Builder/ExtensionTables.php
Allows:
```php
/**
* {@inheritdoc}
*/
protected function registerExtensionTables()
{
return [
'my_table' => new MyTable(),
];
}
```
**DISCLAIMER:** This is the shorthand version (that will still work), however tables should ideally be DI objects.
=> [Extension] Add a trait to simplify extensions to add tables

app/view/twig/editcontent/_relations.twig, app/view/twig/editcontent/fields/_relationship.twig, src/Storage/Collection/Relations.php, src/Storage/ContentRequest/Edit.php, src/Storage/Entity/MagicAttributeTrait.php, src/Storage/Entity/Relations.php, src/Storage/Field/Type/RelationType.php
This takes care of maintaining backwards compatibility with Bi-directional related records. For example where pages is related to entries and entries related to pages. 
The current behaviour operates on a first-come first-saved system for determining the direction of the relation and once saved there's no distinction between a page that's related to an entry, or an entry related to a page.
This PR attempts to replicate this, whilst leaving open the ability to deprecate in future when we are ready to move to uni-directional relations.
=> Fix Handling of Bi-directional relations

src/BaseExtension.php
The methods to add custom filters and functions for Twig have hardcoded context so the developer can only write his handlers in the Extension.php file. This change will allow to set any context so the handlers can be moved to separate classes which will improve the code organization.
With this change functions and filter can be added in two new ways:
```
$twigHandlers = new TwigHandlers();
$this->addTwigFunction('my_twig_func', array($twigHandlers , 'myTwigFunc'));
```
```
$twigHandlers = new TwigHandlers($this);
// inside TwigHandlers class:
$this->extension->addTwigFunction('my_twig_func', array($this, 'myTwigFunc'));
```
Of course this pull request is backward compatible so when a string with method name is passed then the default context is used.
=> Allow to set context for custom Twig functions and filters

app/view/twig/editcontent/fields/_date.twig, app/view/twig/editcontent/fields/_datetime.twig, app/view/twig/editcontent/fields/_float.twig, app/view/twig/editcontent/fields/_integer.twig, app/view/twig/editcontent/fields/_relationship.twig, app/view/twig/editcontent/fields/_text.twig, app/view/twig/editcontent/fields/_textarea.twig
- partially fixes #4743
- planning to fix #4526 (default value for **geolocation**)
I see that default values are generally unused, but i often need that. PR adds an usage of `default` property of field setup in contenttypes (not so verbose). In **date** and **datetime** it was implemented but using incorrect variables.
Also i'm planning to add `placeholder` and `default` value for **markdown** and, probably, **html** fields. Does anyone have objections?
By the way, it would be nice to mention in docs, that for date and datetime you can use "now" as default value (`"now"|date("Y-m-d")` works)
=> Default values for fields in contenttypes

app/resources/translations/nl_NL/contenttypes.nl_NL.yml
The word "verwijdere" does not exist
=> Fixed typo in dutch translation

composer.json
Partial / preliminary fix for #4796
=> Using `1.x-dev` for monolog/monolog.

src/Legacy/Storage.php
Introduces an option `allow_numeric_slugs` in contenttypes.yml. 
See issues #3001 #4770 .
Docs (Contenttypes and records > Defining contenttypes > available options):
* `allow_numeric_slugs`: By default, Bolt prefixes slugs that would be purely numeric with the contenttype slug in order to prevent conflicts with routes of form /{contenttypeslug}/{id}. If this option is set to `true`, numeric slugs remain unprefixed. Care has to be taken not to use routes with IDs in the frontend.
Or something like this.
=> option to allow numeric slugs

src/Provider/StorageServiceProvider.php, src/Storage/Entity/ContentValuesTrait.php, src/Storage/Field/Base.php, src/Storage/Field/Type/FieldTypeBase.php, src/Storage/Field/Type/SlugType.php, src/Storage/FieldManager.php, src/Storage/QuerySet.php
This is mainly some helper syntax to make it  easier to add custom fields.
Bolt 3 needs to keep both the new and the old FieldManager in operation since not everything has been ported over to the new system.
So this PR adds access to the old manager to the new one, so that a call to `$app['storage.field_manager']->addFieldType('mycustomfield', $myCustomFieldObject)` will take care of adding to both the new and the old one.
One thing to note, that shouldn't have any impact on BC, is that this PR also adds a hydrate pass of new custom fields to the legacy content hydration. So if you add a new-style field that does something fancy in the hydration step then it will show up in old-style `Content` objects.
=> Improve process for adding custom fields to new storage layer

src/Composer/ScriptHandler.php
So here goes my first pull request, please help me out if I'm doing something wrong.
I posted the issue this weekend in the bolt/composer-install repository, see https://github.com/bolt/composer-install/issues/7. I also described the solution to this problem put forward by this PR.
**Quick summary**
*Problem*: "I want to install Bolt in separate directory, but I can't do this when doing a composer install non-interactively."
*Solution*: "Do a composer install instead with a slightly modified version of the composer.json file, where an extra option named 'bolt-separate-web-dir' can be set."
This PR also modifies the default values so that by default the web root is installed as a separate directory. This way the code reflects the recommendations from [the …
=> Fixes "non-interactive configuration" of composer-install by providing extra vars in composer.json

src/Provider/DatabaseServiceProvider.php, src/Storage/Database/Connection.php, src/Storage/Database/MasterSlaveConnection.php, tests/phpunit/unit/BoltUnitTest.php
This PR adds some per-request database query caching which should reduce unnecessary multiple queries for the same item.
To do this it uses the built-in functionality of Doctrine DBAL, which is triggered by passing in a `QueryCacheProfile` instance to the standard `executeQuery` method.
I've also built in the future potential to allow user-level opt-in to the cache (via Bolt's standard `$app['cache']`) although this is for now a secret feature because it warrants some more testing at production scale.
=> DB Query Optimisations

src/Controllers/Async.php
fix dashboardnews 504 Gateway Time-out
=> fix dashboardnews 504 Gateway Time-out

src/Config.php
=> Use the computed slug as key for the contenttypes array

src/Storage/Entity/Authtoken.php, src/Storage/Entity/Content.php, src/Storage/Entity/Cron.php, src/Storage/Entity/Entity.php, src/Storage/Entity/FieldValue.php, src/Storage/Entity/LogChange.php, src/Storage/Entity/LogSystem.php, src/Storage/Entity/Relations.php, src/Storage/Entity/Taxonomy.php, src/Storage/Entity/Users.php, src/Storage/Field/Base.php, src/Storage/Field/FieldInterface.php, tests/phpunit/unit/Field/BaseFieldTest.php
This updates the **base table** entities away from `@method` annotations to using getter/setters, and updates a bunch of PHPDoc in the process… hopefully making debugging easier, and understanding the classes easier for those that aren't @rossriley and @gawainlynch :wink: 
@rossriley when you're done with :beers: for the day, can you give a "yay" or "nay" on 3c652b992d439da77958b6de7895255e7b2cc6a1 please… my preference would be to have it as is, but if there is a valid design decision behind mixing them, I am all ears.
=> Less entity magic

src/Storage/ContentRequest/Edit.php, src/Storage/Repository/ContentRepository.php
Fixes #4830. 
(only one `!empty()`, and I think it’s legitimate. ;-) )
=> Get more fields for the "select dropdowns", if specified in the 'format: '.

app/resources/translations/pt/messages.pt.yml
The correct translation to  "enable" is "habilitado". "desabilitado" is the translation to "disable".
=> mistake translation of enable word

src/Controller/Async/FilesystemManager.php
Deleting files through the file manager always resulted in an error as the result of the void method `\Bolt\Filesystem\Manager->delete()` was used to check whether the deletion was successful or not. This fixes #4854.
I decided to not include the exception itself in the error message as that would make the error very verbose.
=> Return the correct response after deleting a file

src/Controller/Async/FilesystemManager.php, tests/phpunit/unit/Controller/Async/FilesystemManagerTest.php
I've updated `\Bolt\Controller\Async\FilesystemManager` to work properly with Bolt 3.0's filesystem API and I've improved its responses by returning more proper status codes where possible, logging any errors to the system log (as suggested by @GawainLynch in #4882) and returning a file path instead of an empty JSON object (`{}`) on success. I've also added missing tests so that every controller action is covered.
There are a lot of commits (I was feeling generous) so I could probably squash some of them.
Fixes: #4886
=> Rework the FilesystemManager controller and add tests

app/view/twig/editfile/editfile.twig
After Logging in and selecting 
**File Management** > **View/Edit templates**
Doing a Ctrl+F for search does not load the search dialog like it does when editing a page from a content type. As you may know using the native browser search does not work with codemirror for any longer than a couple of pages.
Added the search dialog plugin script resource to the template
=> Added the search dialog to the standalone file editor interface

src/Provider/EventListenerServiceProvider.php
In theme.yml, we can currently override most of the templates, optionally: 
```
maintenance_template: maintenance_default.twig
homepage_template: index.twig
record_template: record.twig
listing_template: listing.twig
search_results_template: listing.twig
```
The only one we can't override, is `notfound:`:
```
notfound: notfound.twig
```
This PR makes the behaviour consistent.
=> Allow for overriding `notfound` in theme.yml

src/Storage/Entity/ContentRelationTrait.php
=> In `.related()` only get published items, unless explicitly stated otherwise.

app/view/twig/_base/_listing.twig
when strict variables is on and there is only a single relation  the loop.last is empty.
this sets the loop last to the same as loop first in that case - which prevents the error
=> missing loop.last gives fatal error in strict mode

src/Provider/NutServiceProvider.php, tests/phpunit/unit/Provider/NutServiceProviderTest.php
This is a major version so this is valid. 
Argument: It is way easier for a user to re-add this if needed vs having bolt override another console service.
=> Removed BC for $app['console'] forwarding to $app['nut']

app/view/twig/editcontent/fields/_date.twig, app/view/twig/editcontent/fields/_repeater-group.twig, src/Storage/Field/Type/RepeaterType.php
Pinging @bobdenotter @EJanuszewski for test please.
Hopefully Fixes: #4907 
Adds some auto defaults to the base default array that should prevent Twig choking in strict mode.
Also fixes an access issue for the date field which was also causing a failure in strict mode.
=> Fixes for Twig strict-mode with repeater groups

app/view/twig/dashboard/_aside.twig
=> Since the Configuration notices are the most "actionable", it makes sense to put them at the top of the aside.

app/view/twig/files_async/files_async.twig
Fix the checkbox not showing in the modal when using filelist type, this got missed and was only showing for imagelist type.
=> Fix checkbox not showing on filelist modal

app/config/config.yml.dist
Peter bumped into an issue on bolt 2.2.18, where the composer code was inserting warnings in ajaxy requests.
See screenshot: 
This proposed fix 'resolves' it, but i'm not certain it's the right way to go. The offending code is not ours, so we can't easily fix it.
=> [RFC] Set default error reporting to ignore 'warnings'

app/view/twig/editcontent/_templatefields.twig
This is a bit of an edgecase: Let's say you have a field with `group: template`, but the currently selected template doesn't have any actual 'templatefields'. You'll get this nice error:
This PR fixes that.
=> Better check for templatefields in 'editcontent'

src/EventListener/StorageEventListener.php, tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php
As pointed out by @EJanuszewski in #4899 
> The database message also stays popped up after updating it(on the database update page), I might open a separate issue for this.
This PR fixes that, as soon as #4912 is also fixed.
=> Don't show "Update DB" notice, when we're already updating the DB.

src/YamlUpdater.php
Fixes: #4934 
As dangerous as: #1555
Details
-------
Found that the problem with #4934 only happened when another key (as part of a different block) was present in the same file. Hence in the case of the database update this meant that the 'mailoptions: username' caused the regex not to parse properly.
Despite the two character diff this makes the regex less greedy so it only traverses down a single block rather than the whole file.
=> Fix Config Setting for certain options in config.yml

app/view/toolbar/bolt.html.twig, app/view/twig/about/about.twig, app/view/twig/checks/checks.twig, app/view/twig/dashboard/_aside.twig, src/Application.php, src/Composer/JsonManager.php, src/Composer/PackageManager.php, src/Config.php, src/Controller/Async/General.php, src/Controller/Backend/Extend.php, src/Profiler/BoltDataCollector.php, src/Provider/ConfigServiceProvider.php, src/Provider/NutServiceProvider.php, src/Twig/TwigExtension.php, src/Version.php, tests/phpunit/unit/Profiler/BoltDataCollectorTest.php, tests/phpunit/unit/Twig/TwigExtensionTest.php
There's no reason to have the current version in DI container since it doesn't change. This just makes us require an app container in places we may not necessarily have it.
The approach everyone else is doing, if they are, is a `Version` class with a constant in it for the current version.
=> Version class

app/view/twig/_base/_listing.twig
It's happened a bunch of times now, where people have been confused about the icon used for `Order:`. It looks too much like something you can interact with, but that's not the purpose of it. This icon still indicates it's to do with ordering, but looks less like something you'd except to be able to drag.
=> Replace "sort" icon.

src/Provider/TranslationServiceProvider.php, tests/phpunit/unit/Provider/TranslationServiceProviderTest.php
Although translator should not be invoked before boot, there is a chance that it is. In this case not all of the translations resources have been applied to it. 
This moves them to be added when the translator is invoked, so they are added regardless of when that is.
=> Fix translation resources not being applied

app/view/twig/_nav/_footer.twig
=> Shorter version notation in the 'tiny footer'.

src/Storage/ContentRequest/Edit.php
Some repeater fields were not correctly initialiased
Fixes: #4953
=> Fixes #4953 – Repeater field won't show unless there's also an 'html' field

app/src/js/.jshintrc
Remove some unused globals from jshint config:
- "Backbone"
- "baseurl"
- "bindFileUpload"
- "rootpath"
- "site"
- "confirm"
Replaces deprecated jshint option ``es3`` with ``"esversion": 3``.
=> Remove some jshint globals definitions and replace es3 option

src/Config.php
this PR adds the ability to use service container parameters in your configuration files.
imagine you have this:
```php
$app['debug'] = true
$app['mysql-host'] = "lolcathost"
```
you can then use this vars in your yaml files like this
```yaml
debug: %debug%
database:
host: %mysql-host%
```
this is useful if you configure your application through environment variables (e.g. with this tool: https://github.com/ivoba/dotenv-service-provider)
=> added config var replacement ability

src/Configuration/ResourceManager.php
/blog?page_blog=1 isn't really paging, it's the same as /blog, so only match numbers higher than 1 when checking if the request is paging.
=> Prevent duplicate content for paging requests

src/Pager/PagerManager.php
Forward-port of #4981: /blog?page_blog=1 isn't really paging, it's the same as /blog, so only match numbers higher than 1 when checking if the request is paging.
=> [master] Prevent duplicate content for paging requests

src/Controller/Frontend.php, tests/phpunit/unit/Controller/FrontendTest.php
This should fix the reported issue, without causing side-effects. This way `records` always contains an actual "array of records", instead of just 'one record'. See screenshot for what `homepage: pages/21` gets you now: 
Fixes: #4980
=> Add 'single record' as an array to 'records'.

src/Cache.php, src/Provider/FilesystemServiceProvider.php
Fixes two things related to #4960:
- Don't attempt to initialise the `thumbs` folder, if we're not using it.
- ~~Show a nice 'configuration notice' instead of breaking~~
Fixes: #4960
=> Don't attempt to initialise the `thumbs` folder, if we're not using it.

app/view/twig/editcontent/fields/_checkbox.twig
Line 17 was added in #4869. Without the comma on line 16 I get an error:
```
Twig_Error_Syntax
A hash value must be followed by a comma. Unexpected token "name" of value "value" ("punctuation" expected with value ",") in "editcontent/fields/_checkbox.twig" at line 17.
```
...I do not like brown M&M's. :smile_cat:
=> Add a missing comma to _checkbox.twig

app/bootstrap.php, app/nut, index.php, src/Application.php, src/Configuration/ResourceManager.php, tests/phpunit/unit/Configuration/ResourceManagerTest.php, tests/phpunit/unit/Filesystem/FilesystemProviderTest.php
Another major release… another re-do of `index.php` and `app/bootstrap.php`… where would we be without them ;-)
This might be a little contentious for some, but we're moving to a Composer based archive install for v3, and want to keep bootstrapping for the average user to catch problems.
This PR changes  `app/bootstrap.php` to return a closure instead of an `Application` object. The closure when called accepts an array of paths and then returns the `Application` object, e.g.:
```php
$bootstrap = require_once '../vendor/bolt/bolt/app/bootstrap.php';
$app = $bootstrap([
'themebase' => 'public/theme',
'web'       => 'public',
'files'     => 'public/files',
'view'      => 'public/bolt-public/view',
]);
$app->run();
```
=> Configurable bootstrap

app/view/twig/editcontent/fielddata/_markdown.twig
Fixes:
```
Twig_Error_Syntax
Unknown "bolt" function in "@bolt/editcontent/fielddata/_markdown.twig" at line 4.
```
=> Use `asset()` instead of `bolt()`.

app/src/js/widgets/fields/fieldRepeater.js, app/view/twig/editcontent/fields/_repeater-group.twig
Adds Move Up and Move Down buttons for repeaters, also takes into account if it's the first/last item and disables the relevant buttons.
Fixes: #4975
=> Repeater move buttons

app/view/twig/editcontent/fields/_meta.twig
Fixes: #5007 
Add a default publish date in _meta.twig, @GawainLynch is looking into whether we need to change the backend controllers or not for when the status is transitioned.
=> [WIP] Add default date publish

src/Storage/ContentRequest/ListingOptions.php
By default when filtering on a taxonomy you get a query string like this: "?taxonomy-chapters=main&filter=" which then makes bolt "filter" the content with a empty string, which means that you get this:
=> Don't filter on empty strings

src/Helpers/Excerpt.php
Fixes: 
- 'Object of class Bolt\Legacy\Content could not be converted to string' error
- Don't use 'datepublish' and 'datedepublish' in excerpts
- Omit fields like 'image' and 'geolocation'
=> Fixes some quirks related to `excerpt`

app/view/twig/editcontent/_relations.twig, src/Storage/ContentRequest/Edit.php
First removes the if clause (introduced [here](https://github.com/bolt/bolt/commit/2063fcdc5cb3251386387286e82ef817003388ef)) from the for loop as twig has unpredictable behavior on the loop variable then. That finally is a correct fix for #4901 as that one introduced an almost random generation of ``<tbody>``s which then caused #5000 and #5008 .
Next fix is to decide on the filtered list if the listing should be output and not on the full unfiltered list.
Additional some business logic was moved from twig to php and another bug was fixed that wasn't noticed sofar: Custom listings can have a different column count so it doesn't work to list them in them on in table. Also UIX wise it makes sense to have them in distinct tables.
fixes #4901 
fixes #5000 
fixes #5008
=> Multiple fixes to related contenttype listings

src/Composer/PackageManager.php
While running nut:extensions I got an error:
> Warning: Creating default object from empty value in xxx\src\Composer\PackageManager.php on line 613
followed by a callstack. 
Line 613 is:
`$this->getFactory()->downgradeSsl = true;`
Some quick debugging showed the factory is not yet initialized when this is called, so `$this->getFactory()` returns NULL. 
The factory is initialized at the end of the setup method. However if `$this->app['extend.writeable']` is true  `$this->ping(true);` is called before the factory is initialized, which as far as I can see triggers the error on line 613.
This pull request moves the factory initialization to the start of the setup method, before the `$this->app['extend.writeable']` block to ensure the factory is initialized before it is used.
=> Move create factory to the start of setup in src/Composer/PackageManager

src/Cache.php, src/Configuration/Environment.php, src/Controller/Backend/General.php, src/Events/CronEvent.php, src/Nut/CacheClear.php, tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php, tests/phpunit/unit/BoltUnitTest.php, tests/phpunit/unit/Cache/CacheTest.php, tests/phpunit/unit/Controller/Async/GeneralTest.php, tests/phpunit/unit/Controller/Backend/GeneralTest.php, tests/phpunit/unit/Events/CronEventTest.php, tests/phpunit/unit/Nut/CacheClearTest.php
There was a miscommunication between @GawainLynch and I with his last changes to `Bolt\Cache`.
This corrects it by using `flushAll()` from Doctrine's Cache interface, instead of making `doFlush()` public and using it which isn't any better than the deprecated `clearCache()` method. Now the cache implementation can replaced with any Doctrine Cache implementation.
=> Fix our Cache implementation to follow Doctrine's interface.

tests/codeception/extensions/CodeceptionEventsExtension.php
This will just prevent some noise after an acceptance test is run when you have display errors turned up to 11
=> [Tests] Rebuild extension autoloader after clean up

app/view/twig/editcontent/fields/_tags.twig, src/Storage/Collection/Relations.php, src/Storage/Collection/Taxonomy.php, src/Storage/ContentRequest/Save.php, src/Storage/Field/Type/RelationType.php, src/Storage/Field/Type/TaxonomyType.php
This fixes the issue where the save wasn't being called on the field if an empty post was sent for that field.
There's also a fix for another edge case where large contenttypes (with lots of relations, taxonomies and repeaters) was leading to an overflow of the maximum select column size which on MySQL seems to be 1024 characters. 
Adding distinct to the query, rather than just doing it in the code afterwards will stop this length from getting as big.
Fixes: #5036 #5037
=> Fix Deleting last relations and taxonomies

src/Storage/ContentRequest/Save.php
This is mainly the fault of statics in general :wink: 
On ajax saves the timestamp was incorrect, showing as midnight of the day, not precise to the time.
It was caused by us re-instantiating the Carbon date object from the format, which has been overriden elsewhere in the app using a static call on the class.
Because we already have datachanged instantiated as a Carbon object with the correct time then this patch just calls the format method on the instance directly.
The old behaviour is left in since presumably it is possible for a non-carbon instance to arrive here too.
=> Fix incorrect timestamp results for Ajax saves

src/Config.php
As figured out by @GDmac 
Fixes: #5065
=> Default timestamp on `extensions.yml` to '0' as well.

app/resources/translations/en_GB/contenttypes.en_GB.yml, app/resources/translations/en_GB/messages.en_GB.yml, src/Translation/TranslationFile.php, tests/codeception/acceptance/102-BackendDeveloper/BackendDeveloperCest.php
Various fixups:
- Only use translatables in contenttypes.yml.dist for generation
- Removal of unused messages
- Untranslated messages set to "translated"
- Fix of an test that had checked for an removed key
- Fix detection of key based translations which didn't detect keys with just two parts
- Adding translations for block contenttype
=> Translations correction

app/nut, app/web.php, composer.json, index.php
Currently `index.php` in composer-install doesn't handle files with php webserver or check minimum php version. This moves that logic to `app/web.php` so updates can be applied (since it isn't copied to actual installs).
Also, bolt/thumbs and filesystem beta. Woot!
=> Update filesystem and thumbs to beta. Prep index.php for composer-install fix.

src/Config.php, src/Provider/ConfigServiceProvider.php
This PR offers some optimisation of the config replacement functionality as well as some enhancements to make it much more useful.
References: #5071 
Details
-------
This PR does the compilation of config replacements just once at boot time, rather than on every call to `config->get()`
As an additional bonus it also now respects callables so if your replacement is a callable, eg:
`somepathconfig: %twig.path%`
Then the service will be called and the result returned.
=> Improve config replacement performance

src/Storage/Mapping/MetadataDriver.php
Ok, this ended up being a silly, but hard to find error. 
Metadata for repeating fields was being corrupted by one of the inner loops which was writing back to the parent metadata, rather than the data for the repeating field.
Fixes: #5072
=> Fix overwriting of key variable for repeating field metadata

src/Twig/Handler/ImageHandler.php, tests/phpunit/unit/Twig/Handler/ImageHandlerTest.php
when image/popup is called with an empty filename. It can cause weird breaks in templates when we do, so instead return an empty string.
=> Don't return nbsp in ImageHandler

theme/base-2016/partials/_aside.twig
=> Suggestion for better text in case the 'about-us' block is missing.

src/Application.php
We set the cache-control here:
https://github.com/bolt/bolt/blob/2236c27440a4c52ca47591b1fba338cbc641f406/src/Render.php#L102 so if it is not set to a max-age we can be sure that we need to add the snippets.
=> Only skip htmlsnippets if we are returning a cached response

src/Storage/Field/Type/RelationType.php, src/Storage/Field/Type/TaxonomyType.php
This improves the queries across the relations and taxonomy queries. Originally they could be selected DISTINCT using the db engine but with the addition of extra fields this often gives unwanted behaviour.
So the DISTINCT call has been removed and the cleaning is all done in the `normalizeData()` method instead.
Fixes: #5084
=> Improve Select Queries Across Joins

src/Twig/Handler/RecordHandler.php, tests/phpunit/unit/Twig/Handler/RecordHandlerTest.php
This makes it so that named templates are just named, everything else is the same as if you hadn't named any templates at all. Filtering works, it shows unnamed templates, and we don't need to burn anything down :wink: 
Fixes #5119, #4577 
Closes #5126
=> Fix named templatefields without burning the whole thing down 🚒

src/Twig/Handler/UtilsHandler.php, tests/phpunit/unit/Twig/BoltTwigHelpersTest.php
- Don’t show dump when user not logged on.
- Honor `debug_show_loggedoff` setting
- Apply the same for `firebug` and `backtrace`. Not just `dump`.
Fixes #5122
=> Fixes for {{ dump() }}

app/view/twig/_base/_listing.twig
This patch should have been in #5022. I guess the :dog: has eaten it.
=> Fix contenttype listing blocks

src/Config.php
Default cookie domain value can't contain server's http port number.
Resolves partially #5014 and resolves #5114
=> Fix domain cookie value with http port

src/EventListener/PagerListener.php, src/Pager/PagerManager.php, src/Provider/EventListenerServiceProvider.php, src/Provider/PagerServiceProvider.php
In #5094 we have Pimple warnings by invoking raw service factory without parameters. Moreover I found that code wasn't really really clear and self describing in actual implementation. 
Fixes: #5094
=> Cleaner pager manager factory with resolving Pimple warning

src/Storage/ContentRequest/Edit.php
This reassigns the result of the `canUpload` check back to the fields array so that the check can be done on the field in the template.
Fixes: #5134
=> Fix Upload Button for Templatefields

src/Asset/Snippet/Snippet.php, src/Asset/Snippet/SnippetAssetInterface.php, tests/phpunit/unit/Extensions/AssetsProviderTest.php, tests/phpunit/unit/Extensions/Mock/BadExtensionSnippets.php, tests/phpunit/unit/Extensions/Mock/Extension.php, tests/phpunit/unit/Extensions/Mock/SnippetCallbackExtension.php
This was only left in place for 2.3… now that we've ripped out the old extension classes this stuff is just wasted space.
=> Assets… Remove outdated v2 functionality

src/Provider/SessionServiceProvider.php
This is currently causing a few problems out-of-the box.
=> Set session.save_path to a hidden directory, to persist after flush

app/resources/translations/en_GB/messages.en_GB.yml
Details
-------
'release/2.2' for Bolt 2.2.19.
String near line 312 
"System cURL library doesn't support TLS, or the Certificate Authority setup has not been completed (...)
is missing a space after the URL
=> Missing space after URL

src/Composer/PackageManager.php
Details
-------
- 'release/2.2' for Bolt 2.2.19.
Missing space after URL
See line 616 - Translation string already fixed (Related to PR https://github.com/bolt/bolt/pull/5157 )
=> Missing space after URL - PackageManager file

app/config/contenttypes.yml.dist
It's been deprecated since about 3 years back (I couldn't be bothered to blame all the way through the history, but #420 from May 18, 2013 references it as deprecated).
=> Remove number from contenttypes.yml

app/src/js/widgets/fields/fieldRepeater.js
Reset moved ckeditor instances in repeaters.
Fixes: #5162 
Details
-------
CKEditor doesn't bode too well when moved, due to the way some events are bound in it.  Because of this, sorting a repeater would break any ckeditor moved within.  Simply destroying and re-adding the instance after a move keeps things working.
=> Reset moved ckeditor instances in repeaters

src/Events/SchemaEvent.php, src/Events/SchemaEvents.php, src/Storage/Database/Schema/Manager.php
The concept/use-case here is that extensions might want to add data to tables after their own tables have been created. 
This would allow them to listen & react hen the update has been completed.
=> Schema events on updating

src/Controller/Backend/BackendBase.php
We'll address this better in 3.1-dev
=> Temporary hack to get the permission name associated with the route

src/Storage/Field/Type/RepeaterType.php
This fixes a nasty recursion bug in the repeating field query. Each select is now aliased and restricted to the name of the field.
Fixes: #5214
=> Fix for recursive join bug in repeaters

src/AccessControl/AccessChecker.php
Corner case, but happens when you drop tables with cookies still set.
=> Don't throw a fatal exception on missing table

app/view/twig/editcontent/fields/_filelist.twig, app/view/twig/editcontent/fields/_imagelist.twig
This is a little bit hacky. ``context.content.get(key)`` should always be set and and return a working default. At the moment it returns an empty string instead of an empty array. So the correct fix would be to change that on the part and remove those ``|default([])`` afterwards. But this should work meanwhile.
:bell: Ping @rossriley 
Fixes #5218
=> Fix #5218 – Bad default values for list types

src/Nut/ServerRun.php, src/Provider/NutServiceProvider.php
To replace `./serve` script #5227
=> Created server:run nut command

src/Storage/Field/Collection/RepeatingFieldCollection.php, src/Storage/Mapping/MetadataDriver.php
This handles the metadata parsing for repeater fields so that fields with `multiple: true` are typed to the `selectmultiple` field type.
There's also a fix that allows moving between the two types on config change. 
Fixes: #5225
=> Fix for multiple select fields in repeater collection

src/Storage/Repository.php
No need to overwrite the select parameters since this is handled by the `getLoadQuery` method.
This fixes an error where the ids of rows were being overwritten in some cases.
=> Fix error for repository findBy query

app/config/config.yml.dist
Removes the never implemented `viewSourceRoles` option.
I'm also waiting for confirmation on if the `allowedContent` option actually does something in it's current iteration, otherwise there might be reason to remove that from `config.yml` too.
EDIT: allowedContent was confirmed to do nothing either, so it's offed. This closes #3998
=> Remove the viewSourceRoles option that does not work

src/Legacy/Storage.php
This prevents the bug whereby users upgrading to 3.0 with an old db were getting a fatal error on the dashboard. If the table is missing now it will be silently caught and the normal 'Database needs to be repaired' error will show.
Fixes: #5199
=> Handle exception when table is missing

src/Storage/Mapping/MetadataDriver.php
This takes care of the error where database hydration was happening in a case-insensitive manner meaning that only lowercase column names were correctly hydrated.
This defers to the original column name rather than the key generated by doctrine dbal.
Fixes: #5117
=> Fix case error in entity hydration

app/resources/translations/fi/messages.fi.yml
Details
-------
- Updated from 2.2.19-pl1 to 2.2.20. The dashboard's main view looks like this, before and after the fix:
Before:
After:
---
I checked other languages/translations, and they all have `%contenttypes%` (so no need for fixing).
=> Fix invalid translation (Finnish)

app/view/twig/_base/_listing.twig
In the dashboard, the links have trailing whitespace and it looks ugly on hover. While at it, I also removed the redundant `<strong>` tags.
This had been bothering me way too much. :smile: 
Details
-------
- Bolt 2.2.20. Bolt 3 probably needs this fix as well (the code is almost the same), though I haven't installed it so I'm not sure.
Before:
After:
=> Trim <a>'s text content and remove redundant <strong>

app/config/config.yml.dist
The base-2016 theme doesn't really support it, and I don't recall ever having seen a third-party theme in the wild that does.
=> [RFC] Should we disable the "live editor" by default?

src/AccessControl/PermissionParser.php, src/AccessControl/Permissions.php
Just to avoid BC lock-in for 3.x, and make trapping stuff easier
=> Tweak exception classes thrown for access control

src/Configuration/YamlUpdater.php
Change the YAMLupdater regex to be non-greedy. Example below:
If you have `canonical: 'https://example.com'` in a config the current regex matches `canonical: 'https` as the key as it is is greedy and will therefore create invalid YAML (that is not written to file, but instead exits nut with an error message).
The same issue seems to apply for `example: { test: test }` as it will there read `example: { test` as the key.
=> Change YAMLupdater regex to be non-greedy

src/Storage/ContentRequest/Save.php, src/Storage/Entity/FieldValue.php, src/Storage/Repository/BaseLogRepository.php, src/Storage/Repository/ContentRepository.php, src/Storage/Repository/UsersRepository.php, tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php
Fixes #5288
**Note to future self:** Some versions of MySQL can't handle defaults and some platforms won't handle allowing NULLs … so we're setting a default array on the `value_json_array` property.
=> FieldValue json_array

app/src/js/upload-files.js
Bug recreation:
* Have a imagelist with two images. (they will have the id's 0,1)
* Remove the first image. (the remaining image still has the id 1)
* Add one image. (bolt will try to assign it the id 1 since the list length is 1)
* Bolt will silently fail to add the image since one with the id already exists.
The fix is to sort the list, get the last image and increment it's id by one.
This bug only seems to be in 2.2, not 3.0 and master
=> Set list id to last id + 1 instead of list.length in file/imagelists

app/resources/translations/en_GB/messages.en_GB.yml, src/Composer/Action/CheckPackage.php, src/Controller/Backend/Extend.php
This should remove the Extend page dependency on Whoops being enabled, as well as preventing random useless garbage like:
=> Extend Page Exceptions

src/Extension/Manager.php
I know we all hate using the `@` silencer, but when removing an extension manually things get annoying and the warnings are note useful in this context… 'cause PHP.
```
PHP Warning:  include([snip]extensions/vendor/composer/../clippy/clippy/src/ClippyExtension.php): 
failed to open stream: No such file or directory in [snip]vendor/composer/ClassLoader.php on line 412
PHP Stack trace:
PHP   1. {main}() [snip]app/nut:0
PHP   2. require() [snip]app/nut:14
PHP   3. call_user_func:{[snip]app/bootstrap.php:131}() [snip]app/bootstrap.php:131
PHP   4. Bolt\{closure}() [snip]app/bootstrap.php:131
PHP   5. Bolt\Application->initialize() [snip]app/bootstrap.php:127
PHP   6. Bolt\Application->initExtensions() [snip]src/Application.php:116
PHP   7. Bolt\Extension\Manager->addManagedExtensions() …
```
=> Don't emit autoloader warnings from class_exists()

src/Storage.php
Fixes #5283
Due to inconsistent use of `-` vs `_` in taxonomies, the values weren’t checked correctly before deleting. 
This fix isn’t pretty, but it should fix the problem for Bolt 2.2. 
I’ll check to see if this is also a problem in Bolt 3.
=> Before removing existing taxonomies, check the slugified value too.

src/Storage/Field/Type/RelationType.php, src/Storage/Field/Type/TaxonomyType.php
Takes care of force casting id fields to strings so they can be concatenated in Postgres.
Fixes: #5335 
Closes: #5344
=> fix postgres string aggregation to force cast

src/Legacy/Content.php
Fixes #5271.
Note, this is related to #5339. If we change that, We’ll need to update this accordingly. 
Also, this change will shift responsibilities: Before, the cleaner cleaned _after_ snippets were applied, breaking extensions. This fix changes the order, so that cruft passed in by extensions will de passed on into the rendered page. I don’t think this is a problem, but it needs to be considered.
=> First clean, then parse {{ twig }} snippets.

src/Storage/QuerySet.php
Fix for the lastInsertId functionality on Postgres which requires a sequence name to be passed in to fetch the ID.
=> Add last insert id support for Postgres

src/Storage/Database/Schema/Table/ContentType.php
Fixes #5251
OK… Not really a fan of this approach, but DBAL currently `\Doctrine\DBAL\Platforms\SqlitePlatform` still uses `\Doctrine\DBAL\Platforms\AbstractPlatform::getJsonTypeDeclarationSQL` which just returns `CLOB`… 
@SahAssar & @rossriley if you could sanity check on available platforms. Adding any array field type to an **existing** table (with records) will trigger the problem.
=> Handle json_array for Sqlite separately

composer.json
=> Lock paragonie/random_compat at 1.x, to keep it from breaking shit.

app/view/twig/editcontent/_taxonomies.twig
=> Update _taxonomies.twig, correctly add fields with `group: taxonomy` in contenttypes break.

app/config/config.yml.dist
The sentence was cut in the middle.
Side note: this header is obsoleted by Content Security Policy level 2 (cf. https://www.w3.org/TR/CSP11/#frame-ancestors-and-frame-options)
=> Unfinished sentence

src/Helpers/Image/Thumbnail.php
=> Cast to string in thumbnail handling, prevent "substr() expects parameter 1 to be string"

src/Storage/Mapping/MetadataDriver.php
Introduce a normalisation step which will allow us to iron out any format inconsistencies for class lookups on the MetadataDriver.
Fixes: #5338
=> Fix for lookup failures on hyphenated data names

src/Storage/Query/ContentQueryParser.php, src/Storage/Query/Handler/IdentifiedSelectHandler.php, src/Storage/Query/SearchQuery.php, src/Storage/Query/SelectQuery.php, tests/phpunit/unit/Storage/Query/ContentQueryParserTest.php
This implements the missing named record select in the new storage engine.
It includes the intelligence to drop into single record mode where appropriate and thus means the following queries will all work correctly.
`$page = $app['query']->getContent('pages/2'); // returns a single page with an id of 2`
`$page = $app['query']->getContent('pages/lorem-ipsum'); // returns a single page with aslug of 'lorem-ipsum'`
`$pages = $app['query']->getContent('pages,entries/2'); // returns multiple records where id is 2`
Fixes: #5395 
There's also corresponding test updates to reflect these changes, which should have no BC implications since it was functionality that was not correctly implemented before.
=> Refinements for content fetching 

app/config/config.yml.dist, app/view/twig/_nav/_footer.twig, src/Config.php, src/Helpers/Html.php, src/Profiler/BoltDataCollector.php, tests/phpunit/unit/Helper/HtmlTest.php, tests/phpunit/unit/Profiler/BoltDataCollectorTest.php
~~WIP: Don't merge yet, needs some tests for the new bit of code.~~ 
Allow for using URLs as well as email addresses in the `branding` part of `config.yml`. Fixes #5343
=> Setting 'provided_link', allowing for more flexibility in "branding"

app/config/menu.yml.dist
Fixes the link to the docs in the comments. I notice that some of the other links in the other config files also link to 404 page. Would you like those corrected as well?
[contenttypes.yml.dist](https://github.com/bolt/bolt/blob/release/3.0/app/config/contenttypes.yml.dist#L2)
[permissions.yml.dist](https://github.com/bolt/bolt/blob/release/3.0/app/config/permissions.yml.dist#L3)
=> Use the correct version for link to the docs

app/view/twig/editcontent/fields/_select.twig
When Bolt uses MySQL database (or MariaDB), and we have a select field populated with records of given content type, then opening the record edit page throws an nasty SQL error like this:
> An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT bolt_entries.* FROM bolt_entries ORDER BY `t` LIMIT 500': SQLSTATE[42S22]: Column not found: 1054 Unknown column 't' in 'order clause'") in "@bolt/editcontent/fields/_select.twig" at line 25.
**How to reproduce it**
1. Configure Bolt to use MySQL-like database
2. Add to any content type a select field which lists some records
3. Try to edit or create a record of this content type
Example select field configuration:
```
manual:
type: select
multiple: false
values: books/title
label: Select a …
```
=> MySQL error in select fields populated from content types

src/Storage/Field/Type/RepeaterType.php
Fixes a bug whereby the parsing of the select query was failing on hyphenated and underscored repeating field names.
Fixes: #5348
=> Fix hyphenated field names for repeating fields

src/Composer/EventListener/PackageDescriptor.php
If an (local) extension's `composer.json` is missing `"require": { "bolt/bolt": "x.y" }` a cryptic exception will be thrown.
=> Don't evaluate an empty constraint

src/Controller/Backend/FileManager.php, src/Filesystem/FilePermissions.php, src/Filesystem/Plugin/AdapterPlugin.php, tests/phpunit/unit/FilePermissions/FilePermissionsTest.php, tests/phpunit/unit/Filesystem/Plugin/AuthorizedTest.php
This PR set correct mount point / namespace in AdapterPlugin before plugin methods executes.
Fixes: #5449 
Details
-------
- Add test to check correct namespace authorization over Authorized Plugin.
Questions / Remarks
--------
- If plugin method from an filesystem object is invoked, then `setFilesystem` is called. I think its right place to fix this here. 
- Parameter `namespace` in AdapterPlugin constructor is not used anymore (insofar as I can evaluate all code :wink: ).
- Suggestion: Filesystem manager should mount a filesystem object only once, otherwise mount point is overwrite and end in a wrong behaviour, too.
=> Hotfix filesystem plugins

src/Storage/Field/Type/RepeaterType.php
There may be a #1555 lurking in here.
Fixes: #5462
=> Postgres Fix: add missing second parameter to string_agg call

src/Nut/UserAdd.php, tests/phpunit/unit/EventListener/StorageEventListenerTest.php, tests/phpunit/unit/Nut/UserAddTest.php
Currently, if you try and register a user with a short name, you get the following error:
```
./app/nut user:add admin admin admin@example.com admin admin
Error creating user: admin
```
Which is not very helpful. By letting the exception get thrown:
```
[Bolt\Exception\AccessControlException]                           
Can not save a password with a length shorter than 6 characters!
```
We could show the exception message, but I personally prefer to let exceptions be thrown, especially here as you can get their stack trace with `--verbose`. But happy to change.
=> Do not catch exception when adding user with Nut

app/config/config.yml.dist, app/view/twig/editcontent/_includes-data.twig
Backport of #5492, the docs should have been PR'ed to 2.2 instead of 3.0, but I'll backport them too.
=> Add google maps api key option

src/Events/HydrationEvent.php
Override the hydration event to support subject being passed by reference and thus can be modified in extensions.
=> Allow pre-hydration data to be modified in event

app/view/twig/components/panel-stack.twig, app/view/twig/editcontent/fields/_file.twig, app/view/twig/editcontent/fields/_filelist.twig, app/view/twig/editcontent/fields/_image.twig, app/view/twig/editcontent/fields/_imagelist.twig
If a site's admin area is served over strict HTTP2 certain URLs are generated with `http://`. This forces the `{{ url() }}` call to return a relative schme to work around this
See [upstream](https://github.com/symfony/twig-bridge/blob/2.8/Extension/RoutingExtension.php#L48-L51)
=> [2.2] Enforce relative schema on Twig {{ url() }} calls

src/Events/HydrationEvent.php, src/Storage/Repository.php
Apologies, this is a replacement for #5510 the approache used there wasn't successful since the GenericEvent in symfony was dereferencing the subject.
This is a better approach, since it ensures that the object will always be passed by reference down the line.
=> Refactor the hydration event to use an ArrayObject

src/Composer/Action/BaseAction.php
=> Tokenise PHP version string to remove `-extra` on Debian

app/config/config.yml.dist, src/Provider/TranslationServiceProvider.php, tests/phpunit/unit/Provider/TranslationServiceProviderTest.php
If you develop extensions and work with translation files, it's tiring to clear cache all the time.
Now you can set `general/caching/translations` to `false` if you need it. Recommend only for extension development. Cache is enabled by default.
=> Translation cache option

src/Storage/EntityManager.php
This allows a callable factory to be registered as a Repository. It should hopefully allow a workaround for scenarios such as in #5506 where you may want to return a different repository instance based on the contenttype.
=> Allow callables to be registered as repository classes

app/view/twig/editcontent/fields/_repeater-group.twig
This fixes the various bugs reported relating to HTML fields (and possibly others that use js in some way)
doubling up when a normal field and a repeater field have the same name.
Now the repeater field will generate a unique id eg `repeater_0_body` so there's no chance of a duplicate id appearing elsewhere.
=> Ensure the id is unique in repeater fields

app/view/twig/components/panel-news.twig
See https://github.com/bolt/bolt/blob/858d652e49c3b61fef7e0f66f47750a4fe97d766/src/Controller/Async/General.php#L93-L117 for more info
Fixes issue reported in slack where disabling the news via config.yml does not work anymore.
=> Disable the news. We want the film now!

app/view/twig/users/_userlist.twig
Fixes another issue reported in slack. We can't tell people that we know the future...
The issue was that a null in the lastseen column gave the current date when run through the date filter, which moment.js then turned into "in a few seconds".
Oh, and this fixes #5546
=> Hide that we know the future in userlist (fix null in lastseen on user displaying as `now()`)

src/Storage/Field/Type/RepeaterType.php, src/Storage/Mapping/MetadataDriver.php
This is a temporary solution to enable repeater fields to work inside templatefields. Storage is via JSON rather than the new field value storage system, but this can then be refactored when we tackle a bigger templatefields fix.
Fixes: #5320
=> Enable Use of repeaters inside Templatefields

src/Extension/SimpleExtension.php, src/Extension/TranslationTrait.php
At the current time translations are not automatically included by Bolt extensions. With this PR it allows for automatic inclusion of all translations included in the `translations` directory. They will need to follow standard filenames, otherwise it will default to ''. For example, the translations filename must be called `en.yml` or `sv.yml`,
Details
-------
- Bolt Version 3.1+
=> [Feature] Automatic Translation Inclusion for Extensions

app/src/package.json
This makes it so that you don't need to have grunt installed globally to be able to run the backend JS/CSS build. Instead of `grunt` one can (optionally) run `npm run grunt` or `npm start`. You can also run the subscripts by doing `npm start -- prepareCkeditor` or `npm run grunt -- prepareCkeditor`.
Of course it will still work if one wants to use the global version, but this makes it easier if someone has multiple projects that require different versions of grunt.
This is how it's setup in base-2016, see #5189
ping @rarila
=> Add scripts to run grunt without global

src/Storage/Database/Schema/Comparison/BaseComparator.php, src/Storage/Database/Schema/Comparison/Sqlite.php
See:
*  https://github.com/doctrine/dbal/pull/242
*  https://www.sqlite.org/foreignkeys.html
=> Remove the Foreign Key Constraint properties from diffs when supportsForeignKeyConstraints() is false

src/Exception/InvalidRepositoryException.php, src/Storage/EntityManager.php
Small patch for issue discussed in #5537. 
Gives a more descriptive error message when an invalid repository is loaded.
=> Create custom exception for invalid repo, and throw this when accessed

src/Storage/Query/ContentQueryParser.php
This would allow you to skip over certain directives when running the function `runDirectives`. The reason behind this is say I want to create a new query handler based upon the original query without some directive. For example, a paging handler - the Paging handler allows you to paginate the select query. In the query I want to find a count of all results so my simple query might be `SELECT COUNT(*) FROM bolt_pages;`. Then I want to add a few directives in there, like the `WHERE` clause. The only way to do that would be to `runDirectives`, clone the query, set maxResults and firstResults to `null`, and then then run the query. If we could ignore some directives, then we could skip over a directive and run that directive later with our main query.
Code Example of How it would be done …
=> Add the ability to skip over certain directives

src/Storage/Query/Handler/SearchQueryHandler.php
When searching multiple content types in the Bolt V3 storage layer, it is being overwritten by the previous query. This should correct the issue by cloning a fresh instance of `SearchQuery` to be used each time in the `foreach` loop.
Fixes: #5391
=> Fixed issue when searching multiple contentypes in Bolt V3 Storage Layer

src/EventListener/DoctrineListener.php
I've been seeing some issues with the repeater content type; in essence, adding more than 10 or so bits of content seems to cause it to fail to save properly – repeater sections end up missing.
@rossriley did some investigation after I brought this up on Slack (thanks Ross!) and reached the conclusion that this was due to the result of a GROUP_CONCAT() operation exceeding 1024 bytes in MySQL. When this happens, by default MySQL silently starts chopping off extra bytes from the result of the query. 
This adds an extra query to the `postConnect()` callback of `EventListener\DoctrineListener` which increases the GROUP_CONCAT() result limit to 100,000 bytes if we're connected to a MySQL server, which should mitigate this from happening.
There could be a better (and somewhat less hacky) way of …
=> Increase MySQL group_concat_max_len variable

tests/phpunit/unit/Storage/Query/ContentQueryParserTest.php
This is in reference to issue https://github.com/bolt/bolt/issues/5391 and PR https://github.com/bolt/bolt/pull/5575. 
It should test for this scenario with Bolt V3 storage layer now. (You can close https://github.com/bolt/bolt/issues/5391)
=> Added test to search through multiple content types.
