src/Controller/Backend/Upload.php

Set correct route permission in before()

---

src/Storage/Database/Connection.php
src/Storage/Database/MasterSlaveConnection.php
src/Storage/EntityManager.php
src/Storage/EntityProxy.php

One bug fix, a few PHPDoc bits

Storage PHPDoc

---

app/view/twig/dbcheck/dbcheck.twig
src/Controller/Backend/Database.php
src/Provider/DatabaseSchemaServiceProvider.php
src/Storage/Database/Schema/Comparison/BaseComparator.php
src/Storage/Database/Schema/Comparison/MySql.php
src/Storage/Database/Schema/Manager.php

* Simplify the constructor for the comparator
* Enable diff object dumping in the database check debug mode

Schema DI & table debugging

---

src/Storage/ContentRequest/Edit.php

Add filesystem mount if not already set

---

src/Helpers/Excerpt.php
src/Storage/Database/Schema/Table/BaseTable.php
src/Storage/Database/Schema/Table/ContentType.php

Fix missing field errors

---

app/resources/translations/en_GB/messages.en_GB.yml
src/Config.php

Handle incorrect keys in contenttypes.yml

---

app/view/twig/async/browse.twig
app/view/twig/files/_files.twig
app/view/twig/files_ck/_files.twig
tests/codeception/acceptance/102-BackendDeveloper/BackendDeveloperCest.php

As pointed out by @CarsonF in https://github.com/bolt/bolt/pull/4786#issuecomment-184706715

Using 'width' and 'height' instead of 'dimensions'

---

.travis.yml

Slightly overdue back port of #4819 for stable

[Travis] Update config for Nginx for Composer stage

---

app/theme_defaults/_sub_fields.twig

Allow for `allowtwig` in `{{ fields() }}`-tag.

---

src/EventListener/WhoopsListener.php

Don't show Whoops! screens for regular 404's. Fixes #4888

---

app/view/twig/users/_sessions.twig

Slightly improve legibility of user agents.

---

app/view/twig/edituser/edituser.twig
app/view/twig/firstuser/firstuser.twig
src/Controller/Backend/Users.php

Stop chrome from doing autocomplete on new passwords.

---

app/src/js/modules/editcontent.js
app/src/js/widgets/buic/buicBrowser.js
app/src/sass/buic/_browser.scss
app/view/twig/_macro/_macro.twig
app/view/twig/async/browse.twig
app/view/twig/editcontent/fields/_file.twig
app/view/twig/editcontent/fields/_filelist.twig
app/view/twig/editcontent/fields/_image.twig
app/view/twig/editcontent/fields/_imagelist.twig
src/Controller/Async/FilesystemManager.php

[WiP] Async file browser multiselect

---

app/view/twig/editcontent/fields/_select.twig

On multiple wish of one individual ;-)

Add "require" option to select fields

---

src/Debug/Caster/FilesystemCasters.php
src/Filesystem/Handler/NullableImage.php

Fix NullableImage throwing exception

---

app/view/twig/_sub/_configuration_notices.twig
app/view/twig/_sub/_messages.twig
app/view/twig/dashboard/_aside.twig
src/AccessControl/Password.php
src/Composer/PackageManager.php
src/Config.php
src/Controller/Backend/BackendBase.php
src/EventListener/GeneralListener.php
src/Extension/ConfigTrait.php
src/Legacy/Storage.php
src/Logger/FlashLogger.php
src/Logger/FlashLoggerInterface.php
src/Translation/TranslationFile.php
src/Translation/Translator.php
src/Users.php
tests/phpunit/unit/AccessControl/PasswordTest.php

Fixes #4712. Fixes #4757. Fixes #4899.

Making a "Configuration notices" aside.

---

app/config/config.yml.dist

Mandrill is no longer free, so send people to sendgrid.com/free instead.

[master] Mandrill is dead to us!

---

app/config/config.yml.dist

Mandrill is no longer free, so send people to sendgrid.com/free instead.

Mandrill is dead to us!

---

app/view/twig/_buic/_select.twig

Fixes: #4917 ;
This PR fixes the taxonomy encoding bug in template reported on issue #4917.

Fixes taxonomy encoding in template

---

app/src/js/upload-files.js

Fixes: #4923(please refer to an existing issue number, that this PR fixes)
There's so many different ways to check what the tag is, are you happy with this way?

Fix for image/file list blur #4923

---

src/Controller/Backend/Users.php

I know it's pretty late in the cycle for 3.0, and this is a significant change. Perhaps we should bump this to 3.1 or even 4.0? ;-)

[RFC] Change 'info' to 'success'

---

app/src/js/widgets/base/baseField.js
app/src/js/widgets/base/baseInterval.js
app/src/js/widgets/fields/fieldCategories.js
app/src/js/widgets/fields/fieldFile.js
app/src/js/widgets/fields/fieldFilelist.js
app/src/js/widgets/fields/fieldGeolocation.js
app/src/js/widgets/fields/fieldHtml.js
app/src/js/widgets/fields/fieldMarkdown.js
app/src/js/widgets/fields/fieldMeta.js
app/src/js/widgets/fields/fieldRelationship.js
app/src/js/widgets/fields/fieldRepeater.js
app/src/js/widgets/fields/fieldSelect.js
app/src/js/widgets/fields/fieldSlug.js
app/src/js/widgets/fields/fieldTags.js
app/src/js/widgets/fields/fieldTemplateselect.js
app/src/js/widgets/fields/fieldText.js
app/src/js/widgets/fields/fieldTextarea.js
app/src/js/widgets/fields/fieldVideo.js

**You won't believe it, …**
… I just found that old branch I started a while ago and somehow forgot about. It does nothing for now but I thought I would probably a good idea to get that merged in now before it lands in rebase hell :fearful:
**What's in there?**
We base all field widgets on a base field widget.
**Why?**
We can put functionality common to all field widgets in that base field widget.
**What functionality?**
The reason I started this was adding a ``hasChanged()`` function to field widgets. That would be done by remembering default and initial field values on widget initialisation. Using that enables nice things like an undo or reset function or setting a ``changed`` class on the field widget to signal changed fields to the user.
**When?**
Huhhh …  :scream:

Base field widget

---

app/theme_defaults/_sub_fields.twig
src/Twig/Handler/RecordHandler.php
src/Twig/TwigExtension.php
theme/base-2014/extrafields.twig
theme/base-2014/index.twig
theme/base-2014/record.twig

Making {{ fields() }} work with templatefields as well.

---

src/Legacy/Storage.php

Check zone from request

---

theme/base-2014/record.twig

Correct Twig variable

---

app/view/twig/_base/_page.twig
app/view/twig/editcontent/fielddata/_html.twig
app/view/twig/editcontent/fielddata/_markdown.twig
app/view/twig/editfile/editfile.twig
app/view/twig/editlocale/editlocale.twig

Apply cachehash to includes in the backend.

---

composer.json

c.f. https://github.com/composer/composer/releases/tag/1.0.0-beta1

Set the Composer requirement to ^1.0@beta

---

composer.json

c.f. https://github.com/composer/composer/releases/tag/1.0.0-beta1

[2.2] Set the Composer requirement to ^1.0@beta

---

src/AccessControl/AccessChecker.php

Only show "You have been logged out." flash if there are users in the DB

---

src/Twig/Handler/ImageHandler.php
src/Twig/TwigExtension.php

Standardizes the params for all the image functions and makes sure that all the functions uses the config.yml defaults where appropriate. Also some minor restructuring of popup and showimage
fixes #4964

Imagehandler updates and bugfixes

---

src/Config.php
src/Controller/Backend/Records.php
src/Controller/Backend/Users.php
src/EventListener/StorageEventListener.php
src/Helpers/Html.php
src/Provider/FormServiceProvider.php
src/Storage/ContentRequest/Edit.php
src/Storage/Database/Schema/Table/BaseTable.php
src/Storage/Entity/ContentValuesTrait.php
src/Storage/EntityManager.php
src/Storage/Field/Type/FieldTypeBase.php
src/Storage/Field/Type/RepeaterType.php
src/Storage/FieldManager.php
src/Storage/QuerySet.php
src/Twig/Handler/HtmlHandler.php

* OCD
* More OCD
* Even more OCD

Coding style pass

---

src/Twig/Handler/ImageHandler.php
src/Twig/TwigExtension.php
tests/phpunit/unit/Twig/Handler/ImageHandlerTest.php

Forward-port of #4973, I've tested that it produces the same results as 2.2.X does now. Ping @CarsonF and @GawainLynch for checking :smile:

[master] Fix image defaults/config

---

src/Controller/Backend/Extend.php
src/Version.php

Don't return suffix in Composer version

---

src/AccessControl/Login.php
src/AccessControl/Password.php
src/Controller/Backend/Authentication.php
src/Controller/Backend/Users.php
src/Events/AccessControlEvent.php
src/Events/AccessControlEvents.php
src/Users.php
tests/phpunit/unit/AccessControl/LoginTest.php
tests/phpunit/unit/AccessControl/PasswordTest.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Users/AuthenticationTest.php

This is a follow up to #4883 & #4878 for master. Late, but low impact.
@CarsonF your concerns from #4883 should have been adequately addressed. As for Symfony Security, that's targeted for Bolt v4.
Ping @ToBe998

Access control events

---

src/EventListener/AccessControlListener.php
src/EventListener/StorageEventListener.php
src/Provider/EventListenerServiceProvider.php
src/Storage/EntityManager.php

Invalidate user sessions on disable/delete

---

src/Nut/ExtensionsDumpAutoload.php
src/Nut/ExtensionsUpdate.php
src/Provider/NutServiceProvider.php
tests/phpunit/unit/Nut/ExtensionsDumpAutoloadTest.php

* Bring the autoload command in-line with Composer's
* Add a command to update one or all extensions
@jadwigo can you remind me in a couple of hours to update internal scripts… 'cause I just know I'll forget :grin:

Nut updates for extension management

---

src/Composer/Action/BaseAction.php
src/Composer/PackageManager.php

Extensions install SSL downgrade

---

app/resources/translations/en_GB/messages.en_GB.yml

String value was incomplete - see line 438:
We were unable to generate the theme

String not complete

---

app/config/config.yml.dist
src/Provider/ThumbnailsServiceProvider.php

Fixes: https://github.com/bolt/bolt-thumbs/issues/25

Thumbnails save files fix and caching switch

---

src/Extension/StorageTrait.php

This simplifies the process for advanced extensions.

Simplify adding extension repositoiries

---

src/Extension/DatabaseSchemaTrait.php

Doing the docs on this showed that there are just too many sharp edges to our current approach.

Simplify adding extension tables

---

src/Extension/AbstractExtension.php

Fixes error on variable check for AbstractExtension

Fix variable check

---

src/Twig/Handler/RecordHandler.php

Check if global record is set. 

---

src/Extension/StorageTrait.php

Extend services… and actually return the service

---

src/Extension/StorageTrait.php

Really… some days :disappointed:

Loop inside the closure

---

composer.json
serve
src/AccessControl/Login.php
src/AccessControl/Password.php
src/EventListener/StorageEventListener.php
src/Provider/AccessControlServiceProvider.php
src/Provider/StorageServiceProvider.php

Update user's password on login if their stored hash is not using the blowfish algorithm.

Migrate password hash on login

---

src/Provider/MenuServiceProvider.php

Prefix branding path with root URL

---

src/Storage/ContentRequest/Edit.php

Properly check if templatefields are still present.

---

src/Provider/TwigServiceProvider.php
src/Twig/DumpExtension.php
src/Twig/Handler/UtilsHandler.php
tests/phpunit/unit/Twig/Handler/UtilsHandlerTest.php

Don't `dump()` unless logged on, or debug_show_loggedoff is set.

---

src/Config.php

Prioritise HTTP_HOST over SERVER_NAME

---

.travis.yml
tests/travis/README.md
tests/travis/composer-setup

This move the Travis Composer install test set-up to use a "real" Composer project, that includes updated vendor directories and theme.

[Travis] Composer install testing

---

app/view/twig/files_ck/_folders.twig
app/view/twig/files_ck/files_ck.twig

Bug not created, already fixed.
When in field type html open insert image.

Fix bug show folders in ck_files template

---

src/Controller/Frontend.php

Don't re-fetch record on preview

---

app/resources/translations/en_GB/messages.en_GB.yml

Details: Bolt 2.2.x.
String value fix

Truncated value

---

app/src/js/upload-files.js

Fixes issue with imagelists not updating due to event checking (introduced in #4925).
.

Fix issue with imagelists not updating due to event checking

---

app/config/contenttypes.yml.dist
app/config/taxonomy.yml.dist
src/Storage/Entity/ContentRouteTrait.php
tests/phpunit/unit/Controller/Backend/RecordsTest.php
tests/phpunit/unit/Storage/FieldLoadTest.php
tests/phpunit/unit/Storage/Query/SearchConfigTest.php
tests/phpunit/unit/Storage/Query/SearchQueryTest.php

Per #5164 to conform with the other examples.

Rename chapter taxonomy example to group

---

app/config/contenttypes.yml.dist

Alternative to #5168
Moves "Possible field types" above "Using YAML repeated nodes".

Move "Possible field types" in config.yml

---

src/Storage/Entity/Authtoken.php

XSS issue: Thank you @sjord, for bringing this to our attention.

Strip tags from useragent.

---

src/Users.php

XSS issue: Thank you @sjord, for bringing this to our attention.

[2.2] Strip tags from useragent.

---

app/view/twig/components/panel-activity-system.twig

Show better log message.

---

app/config/config.yml.dist
app/view/twig/_base/_page.twig

Remove livereload settings from config.yml and _page.twig per #5164 and irc.

Remove livereload settings from config.yml and _page.twig

---

app/view/twig/omnisearch/_aside.twig
app/view/twig/omnisearch/omnisearch.twig

So that the Omnisearch works again.
Fixes #5191

Use right syntax for Omnisearch templates

---

.travis.yml

* Cut over to using GCE
* Make PHP 7 passes mandatory
* Increase PHP memory limit

[Travis][2.2] Various updates

---

.travis.yml

* Cut over to using GCE
* Increase PHP memory limit

[Travis] Updates 

---

app/view/twig/components/panel-system.twig

Back port of #5177 for 2.2 as it is really annoying me too now.

Better log messages for failed login attempts

---

app/view/twig/editcontent/fields/_image.twig
app/view/twig/editcontent/fields/_imagelist.twig
app/view/twig/editcontent/fields/_textarea.twig

.control-label for image, imagelist and textarea part1

---

tests/codeception/acceptance/104-BackendAuthor/BackendAuthorCest.php

To catch things like #5202 and #5191

Add omnisearch test

---

tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Users/CreateUsersTest.php

Added some tests for creating new users. Also modified the addNewUser function to enable/disable new users.
Related to #5190

Tests for issue #5190

---

src/Controller/Backend/Users.php
src/EventListener/StorageEventListener.php

Fixes #5190 … and apparently give the :koala: some special :leaves: according to @rarila

Only force enabling user entity on first user creation

---

src/AccessControl/Login.php
src/Storage/Database/Schema/Table/ContentType.php
src/Storage/Database/Schema/Table/FieldValue.php
src/Storage/Database/Schema/Table/LogChange.php
src/Storage/Database/Schema/Table/LogSystem.php
src/Storage/Database/Schema/Table/Users.php

Database contraints

---

src/Twig/Handler/RecordHandler.php

Look for template files in deeper folders.

---

src/Storage/Database/Schema/Table/ContentType.php
src/Storage/Database/Schema/Table/FieldValue.php
src/Storage/Database/Schema/Table/LogChange.php
src/Storage/Database/Schema/Table/LogSystem.php
src/Storage/Database/Schema/Table/Users.php

Follow up to #5207… as… well… DBAL.

Have json_array fields use an empty JSON array string as a default

---

app/view/twig/editcontent/fields/_filelist.twig

Use correct key

---

src/Storage/Database/Schema/Table/ContentType.php
src/Storage/Database/Schema/Table/FieldValue.php
src/Storage/Database/Schema/Table/LogChange.php
src/Storage/Database/Schema/Table/LogSystem.php
src/Storage/Database/Schema/Table/Users.php
src/Storage/Entity/Content.php

Yeah, so about that… MySQL sucks like a Dyson.
OK, third attempt. This just moves to giving the templatefields getter always return an array
Fixes #5165
Fixes #5213
Fixes #5222

More fun with constraints

---

app/view/twig/editcontent/_field.twig
app/view/twig/editcontent/fields/_not_found.twig

Handle custom fields with incorrectly namespaced field templates

---

src/Menu/AdminMenuBuilder.php
tests/phpunit/unit/Extension/MenuTraitTest.php

Fix typo induced inconsistency

---

src/Composer/EventListener/PackageEventListener.php

Hack to get web path for local extensions on a git install

---

app/view/twig/dashboard/_recently_edited.twig

Set a CSRF token for dashboard recently edited

---

src/AccessControl/AccessChecker.php
src/AccessControl/Login.php
src/Controller/Backend/Authentication.php
src/Controller/Backend/BackendBase.php
src/EventListener/RedirectListener.php
src/Events/AccessControlEvent.php
src/Events/AccessControlEvents.php
src/Provider/AccessControlServiceProvider.php
src/Users.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Controller/Backend/AuthenticationTest.php

Dispatch more events during access control inspections to better debug problems in that subsystem.
**Note:** [Audit extension](https://github.com/bolt/Audit/) has been updated to use this functionality

ACL Events

---

app/resources/translations/fr/messages.fr.yml
app/view/twig/extend/extend.twig

On the page : bolt/extend
Unescaped quote in a translation hurt the javascript.

Fixed bug with FR translation

---

src/Asset/Injector.php

More than a slight performance gain on this one :-/

Only regex match from beginning of multi-line

---

.travis.yml

[Travis] Update hirak/prestissimo constraint

---

theme/base-2016/css/theme.css
theme/base-2016/source/package.json
theme/base-2016/source/scss/theme.scss
theme/base-2016/styleguide.twig

Fix view height for header photo in base-2016.

---

app/config/routing.yml.dist

change address of routing documentation

---

src/Legacy/Storage.php
tests/phpunit/unit/Storage/StorageTest.php

This is a port of #5298 for the release/3.0 branch.
Fixes: #5298

Fix contenttype slugs with underscores not loading correctly

---

app/view/twig/recordbrowser/recordbrowser.twig

Fixed: Bind correct name, fixes 'select from server' in CKeditor.

---

src/Controller/Frontend.php
src/Legacy/Storage.php
theme/base-2016/search.twig

Fixes: 
- Lowercasing search input (Fixes #5373)
- handle html and entities better (sanitize, instead of relying on escaping in the template)

Tweak search input.

---

app/view/toolbar/config.html.twig

Fix missing PHP icon in webdev Toolbar.

---

app/view/twig/_base/_listing.twig
app/view/twig/_macro/_macro.twig
app/view/twig/_nav/_primary.twig

Replace deprecated trimtext with excerpt.

---

app/view/twig/extend/extend.twig

Use path that includes subdirectories

---

src/Configuration/LowlevelChecks.php

We're going to re-do exception handling soon… but this will stop the corner-case when someone sets up a site locally and moves it, from biting.

Handle site root directory moves on Sqlite

---

src/Composer/Action/CheckPackage.php
src/EventListener/PagerListener.php
src/Nut/ServerRun.php
src/Pager/PagerManager.php
src/Provider/PagerServiceProvider.php
src/Storage/ContentRequest/Save.php
src/Storage/Field/Type/RelationType.php
src/Storage/Field/Type/TaxonomyType.php
src/Storage/Mapping/MetadataDriver.php
src/Storage/Query/Handler/IdentifiedSelectHandler.php
src/Storage/QuerySet.php

Code style pass

---

src/Controller/ConfigurableBase.php

Also bugfixes host and methods

Set configured schemes from routing.yml

---

src/Storage/QuerySet.php

Fixes #5411
Not pretty, but we can try for better in 3.1.

Don't trigger an exception on PostgreSQL if no table sequence is defined

---

app/config/contenttypes.yml.dist
app/config/permissions.yml.dist

Follow up for https://github.com/bolt/bolt/pull/5413

Fix for remaining doc links pointing to the incorrect version

---

src/Asset/File/FileAssetBase.php
src/Asset/File/Queue.php
tests/phpunit/unit/Extensions/AssetsProviderTest.php

The is the 3.0 workaround for the problem where isLate() is misbehaving and FileAssetInterface objects are missing location setters/getters.
I will submit a later PR to update the interface for master/3.1
ping @cdowdy @rossriley @CarsonF

File asset priority & location

---

src/Asset/AssetInterface.php
src/Asset/File/Queue.php
src/Asset/Snippet/SnippetAssetInterface.php
src/Asset/Widget/WidgetAssetInterface.php

This moves the location contract into AssetInterface and simplifies the processing logic accordingly.

[3.1] Asset location selection

---

src/Composer/Action/BaseAction.php
src/Composer/Action/CheckPackage.php
src/Composer/Action/RequirePackage.php
src/Composer/Action/SearchPackage.php
src/Composer/Action/ShowPackage.php
src/Composer/Action/UpdatePackage.php
src/Composer/PackageManager.php
src/Configuration/Environment.php

Move the assignement of COMPOSER_HOME to BaseAction::getComposer()

---

app/resources/translations/fr/messages.fr.yml

[BUG] [L10N] contenttypes.generic.none-available wrongly translated in
vendor/bolt/bolt/app/resources/translations/fr/messages.fr.yml #5432 
Fixes #5433

Fix for https://github.com/bolt/bolt/issues/5432

---

app/view/twig/editcontent/fields/_categories.twig

Fix #5437 – Select all button visible when taxanomy multiple set to false for category behaviour

---

theme/base-2016/partials/_fresh_install.twig

fix wrong link to edit template in base-2016 theme

---

src/Controller/Backend/FileManager.php

Be more user friendly with file manager edit failures

---

src/Storage/Query/ContentQueryParser.php

Information can be viewed about this PR in #5419.
Fixes: #5419

[FEEDBACK] Call addOperation in addHandler

---

src/Composer/Action/RequirePackage.php

Find best version candidate based on requested version/constraint

---

composer.json

See #5484 
See #5495
See #5492 fails

Lock lstrojny/phpunit-function-mocker to 0.3.0 for PHP 5.5 support

---

app/config/config.yml.dist
app/src/js/modules/app.js
app/view/twig/_base/_page.twig

See https://github.com/bolt/bolt/wiki/Dev-meeting-2016-06-28 for more info.

Add option for google maps api key

---

src/Storage/Database/Schema/Builder/ContentTables.php
tests/phpunit/unit/Nut/DatabaseCheckTest.php
tests/phpunit/unit/Nut/DatabaseRepairTest.php

Hyphen vs underscore … :koala: vs :koala: … there can only :leaves: one

---

.travis.yml

[2.2][Travis] Disable Composer install test

---

.travis.yml

[Travis] Disable Composer install test

---

src/Storage/Repository.php

Just a small improvement to allow pre-hydrate events to work correctly on newly created entities.
Fixes: #5464

Improve logic of hydration events on create

---

src/Configuration/ResourceManager.php

fix-windows-path

---

src/Twig/Handler/ImageHandler.php

Fix comment on default image sizing

---

src/Nut/UserAdd.php
src/Nut/UserManage.php
src/Provider/NutServiceProvider.php
tests/phpunit/unit/Nut/UserManageTest.php

[3.1] Nut user handling

---

app/view/twig/dashboard/_quicklinks-dropdown.twig
app/view/twig/overview/_panel-actions_overview.twig

And check if one is allowed to create in any contenttype before outputting the dropdown on dashboard
Fixes #5429

Check isallowed on new page buttons

---

app/view/twig/components/panel-news.twig

fixes test failures introduced by #5544

fix test failure on news

---

src/Pager.php

fix #5346 [Bug] Using Html 'base' tag breaks pagination links

fix #5346 [Bug] Using Html 'base' tag breaks pagination links

---

src/Extension/TranslationTrait.php
tests/phpunit/unit/Extension/MenuTraitTest.php

Just a bit of clean up and test fixing

Extension translation

---

src/Extension/Manager.php

Alternative approach to #5485 and #5319
#5319 was a quick workaround, that we need to handle better. @dantleech proposed dropping it in #5485 which leads to stuff like:
```
PHP Warning:  include([snip]/extensions/local/bolt/members/src/MembersExtension.php): failed to open stream: No such file or directory in [snip]/vendor/composer/ClassLoader.php on line 412
PHP Stack trace:
PHP   1. {main}() [snip]/app/nut:0
PHP   2. require() [snip]/app/nut:14
PHP   3. call_user_func:{[snip]/app/bootstrap.php:131}() [snip]/app/bootstrap.php:131
PHP   4. Bolt\{closure}() [snip]/app/bootstrap.php:131
PHP   5. Bolt\Application->initialize() [snip]/app/bootstrap.php:127
PHP   6. Bolt\Application->initExtensions() [snip]/src/Application.php:116
PHP   7. Bolt\Extension\Manager->addManagedExtensions() …
```

Be very select about extension autoloader error/exception emitting

---

.github/CONTRIBUTING.md

This is a start … let me know if there is something to add/remove.

Update features section in CONTRIBUTING.md

---

src/EventListener/StorageEventListener.php

Skip schema check only on _wdt (profiler) & dbupdate routes

---

src/Controller/Backend/Records.php
src/Storage/EntityManager.php

Set a flash and redirect to to dashboard if ContentType doesn't exist fetching repository

---

app/config/config.yml.dist
src/Composer/Action/Options.php
src/Composer/JsonManager.php
src/Provider/ExtensionServiceProvider.php
tests/phpunit/unit/Nut/ExtensionsDumpAutoloadTest.php
tests/phpunit/unit/Nut/ExtensionsSetupTest.php

Closes #5499
@SahAssar: I was back-and-forth on what to do with `app/config/config.yml.dist`, but opted to add some of the useful bits here now, and it can get caught up in a bigger sweep later.

Setting Extensions Composer options

---

src/Controller/Backend/BackendBase.php
src/Menu/AdminMenuBuilder.php

Use URL generator where appropriate

---

src/Controller/Async/FilesystemManager.php

Folder handling doesn't need parent value concatenated

---

src/EventListener/StorageEventListener.php
src/Provider/StorageServiceProvider.php
tests/phpunit/unit/EventListener/StorageEventListenerTest.php

Only check for timed (de)publish periodically, or after cache flush

---

app/theme_defaults/_sub_fields.twig
src/Twig/Handler/RecordHandler.php
src/Twig/TwigExtension.php

Add support for missing `skip_uses` parameter

---

src/Provider/SessionServiceProvider.php

First, as an implementer of Bolt, I would expect Bolt would use my default session settings set in my `php.ini` file. If for some reason I was using a crappy hosting service or was held back by a grumpy sysadmin, this PR would also let me override those session settings in my `config.yml` file.
It fixes #5534 for me because I wouldn't need to extend `Bolt/Application` to switch away from storing all sessions in `app/cache/.sessions/`. I could just make changes in my `php.ini` file or in my `config.yml` file.

Session settings

---

app/src/js/modules/extend.js
app/view/twig/extend/_package.twig
app/view/twig/extend/extend.twig

Fixes #5600 
Looks like this now:

Some minor UI tweaks for the Extends screen.

---

app/config/config.yml.dist
src/Config.php
src/Legacy/Content.php
src/Provider/StorageServiceProvider.php
src/Storage/Field/Sanitiser/Sanitiser.php
src/Storage/Field/Sanitiser/SanitiserAwareInterface.php
src/Storage/Field/Sanitiser/SanitiserAwareTrait.php
src/Storage/Field/Sanitiser/SanitiserInterface.php
src/Storage/Field/Sanitiser/WysiwygAwareInterface.php
src/Storage/Field/Type/DateTimeType.php
src/Storage/Field/Type/DateType.php
src/Storage/Field/Type/FieldTypeBase.php
src/Storage/Field/Type/HtmlType.php
src/Storage/Field/Type/ListTypeBase.php
src/Storage/Field/Type/MarkdownType.php
src/Storage/Field/Type/TextAreaType.php
src/Storage/Field/Type/TextType.php
src/Storage/FieldManager.php

Feature: Better sanitization of content on save.

---

tests/phpunit/unit/Storage/Query/SearchQueryTest.php

Fix test, should've been part of #5617

---

src/Twig/Handler/RecordHandler.php

Get correct path to compare in 'current' filter, when Bolt is in a subfolder/

---

app/view/twig/_base/_listing.twig
app/view/twig/editcontent/_aside-status.twig
app/view/twig/editcontent/_buttons.twig
app/view/twig/editfile/editfile.twig
theme/base-2016/partials/_recordfooter.twig

Replacing deprecated localdate with localedatetime.

---

src/Session/SessionStorage.php

Closes #5625
Fixes a number of problems we were seeing, such as on the extension store, with session directories getting too large.

Adjust probability formula for session garbage collection

---

src/Composer/Action/RequirePackage.php

Update composer.json before and after run

---

src/Permissions.php
src/Storage.php

These ones came up on the internals pahts

[2.2] More PHPDoc fix-ups

---

src/Legacy/Storage.php
src/Storage/Database/Schema/SchemaCheck.php
src/Storage/Repository/BaseLogRepository.php

`release/3.x` version of #5646

[3.0] More PHPDoc fix-ups

---

src/Provider/SessionServiceProvider.php
src/Session/SessionListener.php

Fixes #5650 - Realm is only appended to session name once
Fixes memcached session handler mentioned in #5658

Fix memcached session handler and session duplicate realms in name

---

src/EventListener/BootInitListener.php
src/EventListener/NotFoundListener.php
src/Extension/Manager.php
src/Provider/EventListenerServiceProvider.php
tests/phpunit/unit/Extensions/AssetsProviderTest.php
tests/phpunit/unit/Twig/Handler/WidgetHandlerTest.php

More exceptions work

---

app/bootstrap.php
src/Exception/BootException.php

First commit is all in your imagination … it was never there! :stuck_out_tongue_winking_eye:

Early boot exception

---

app/view/twig/_macro/_macro.twig
app/view/twig/files/_upload.twig
src/Configuration/ResourceManager.php
src/Controller/Backend/FileManager.php
src/Provider/UploadServiceProvider.php
tests/phpunit/unit/Controller/Backend/UploadTest.php

Fixes #5678 
This fix is a bit hackish. Open to better suggestions. :-)

Fix for uploading to `themes/` folder in backend.

---

src/Storage/Entity/Builder.php
src/Storage/Field/Collection/FieldCollection.php
src/Storage/Field/Manager.php
src/Storage/Field/Type/FieldTypeBase.php
src/Storage/Field/Type/HtmlType.php
src/Storage/Mapping/MetadataDriver.php

This PR improves Repeater fields to make sure that both custom and built-in Bolt fieldtypes are correctly hydrated.
Fixes #5403

Improve Hydration Process in Repeaters

---

src/Translation/TranslationFile.php

exclude  'bower_components', 'node_modules' folders in theme

exclude  'bower_components', 'node_modules'

---

changelog.md
src/Version.php

Preparing for the 3.1 release.

Updating changelog and version

---

src/Logger/Handler/SystemHandler.php

More on this: https://github.com/bolt/bolt/issues/5707

Fix incorrect ownerid when no user is authenticated

---

src/Config.php

Update config default for profiler redirection

---

src/Configuration/Validation/Apache.php

[FIX] Honour disable apache checks flag

---

app/src/package.json
app/src/sass/modules/_bolt.scss
app/src/sass/modules/_textstyles.scss
app/view/twig/exception/_trace.twig
app/view/twig/exception/database/_driver.twig
app/view/twig/exception/database/_failed-connect.twig
app/view/twig/exception/database/_invalid-path.twig
app/view/twig/exception/exception.twig
app/view/twig/exception/pre-boot/_config-read.twig
app/view/twig/exception/pre-boot/_config-write.twig
app/view/twig/exception/system/_apache.twig
app/view/twig/exception/system/_cache.twig
app/view/twig/exception/system/_configuration.twig
app/view/twig/exception/system/_magic-quotes.twig
app/view/twig/exception/system/_safe-mode.twig

Fixes #5690
I think this is all of them. I couldn't easily trigger all of them, but this should be it. :-)

Updated: Styling for Exception pages.

---

app/view/twig/_base/_listing.twig

Fixed: Viewless contenttypes no longer have a 'view on site' button.

---

src/Legacy/Content.php

Fix Markdown parsing in frontend.

---

app/config/config.yml.dist

Add 'alt' and 'title' to `allowed_attributes`.

---

app/src/sass/modules/_bolt.scss
app/view/twig/exception/exception.twig

Fixes #5777 
At least it should. Needs testing [after this lands](https://github.com/psyrendust/grunt-eol/pull/4), because right now i can't rebuild the CSS and JS assets. :-/

Fixed wrapping in exception screens.

---

src/Storage/Field/Type/TextAreaType.php
src/Storage/Field/Type/TextType.php

Fixed: Don't sanitise 'text' and 'textarea' type fields.

---

app/src/js/modules/app.js

Been there, seen it, fixed it …
#1555 anyone?

Fix very minor JS docu

---

LICENSE.md

[Prefix your PR title with [WIP], if it's a 'work in progress', 
or if you're looking for feedback before merging.]
A brief description of the Pull Request goes here. If you haven't yet done so,
please read the 'contributing guidelines' thoroughly. 
See: https://github.com/bolt/bolt/blob/master/.github/CONTRIBUTING.md
Fixes: #1555 (please refer to an existing issue number, that this PR fixes)
Details
-------
Please list any details for the PR, that might be relevant. Some pointers:
- Please include tests with your PR. If you do, we will love you for it.
- Check if the change in the PR is a good fit for Bolt, or if it would be
better off as an extension.
- Make sure you're doing the PR to the correct branch: 'master' for 3.0, or
'release/2.2' for Bolt 2.2.x.

Licence was out of date

---

app/src/package.json

Prevent using bearded software in our toolchain.

Fix node/npm minimum requirements

---

src/Storage/Mapping/MetadataDriver.php

Fix isset checks on ConfigurationValueProxy

---

app/src/js/modules/extend.js
app/view/twig/extend/_package.twig

Add a 'manage' dropdown for uninstalled extensions.

---

src/Storage/Field/Type/FieldTypeBase.php

Better parsing of the db data so underscored taxonomy names don't break, 
fixes #5837

Fix loading of taxonomies with underscores

---

app/src/sass/nav/_secondary.scss

Fixes: Set min-width for title of modal popups.

---

app/src/js/widgets/fields/fieldImage.js
app/view/twig/editcontent/fields/_image.twig

Cropping images in imagefield differently, less 'chopped off' parts.

---

src/Storage/Entity/MagicAttributeTrait.php

As mentioned in #5787 this is the other bugfix.

Fix underscored field serialization

---

src/Provider/SessionServiceProvider.php
src/Session/Handler/MemcacheHandler.php

Fix memcache session handler closing connection

---

app/config/config.yml.dist
app/view/twig/components/pager.twig
src/Config.php
src/Configuration/ConfigurationValueProxy.php

As discussed on Slack, this morning. I have a slight suspicion that things tests will break on this PR, though.

Stricter settings for developers, to get higher visibility for potential issues.

---

src/Provider/SessionServiceProvider.php

Memcache is stewpid. Extension hasn't even been updated since 2013. 
Fixes #5855

Fix memcache connection creation to only pass weight if it is > 0

---

src/Storage/Mapping/ContentTypeTitleTrait.php

Fixed Runtime Notice: Only variables should be passed by reference

---

src/EventListener/ExceptionListener.php

This refine the handling of AJAX requests and always returns JSON that can be consumed by the caller.

JSON exception listener

---

src/EventListener/BootInitListener.php
src/EventListener/ConfigListener.php
src/Provider/BootServiceProvider.php
tests/phpunit/unit/Twig/TwigExtensionTest.php

Relevant to conversation in https://github.com/bolt/bolt/commit/a81d1e2b581de21073deeba069dc9ac0acade925#commitcomment-19294256
This work for you @CarsonF ?

Rename BootInitListener to ConfigListener

---

app/src/sass/modules/_bolt.scss
app/src/sass/modules/_textstyles.scss
app/view/twig/exception/_request.twig
app/view/twig/exception/_trace.twig
app/view/twig/exception/exception.twig
src/Controller/Exception.php
src/Controller/Frontend.php

Note: This PR also ensures that this info won't be shown to non-logged in users. 🕵️
See screenshot:

Improve Look&Feel of the new Exception pages

---

app/view/twig/exception/exception.twig

Better title for exception page

---

app/view/css/bolt_exception.css
app/view/js/bolt_exception.js
app/view/twig/exception/_request.twig
app/view/twig/exception/exception.twig

Obfuscate session, cookie data in the Exception screen.

---

app/view/twig/_base/_page-no_nav.twig
app/view/twig/_nav/_primary.twig
app/view/twig/_nav/_secondary.twig
app/view/twig/about/about.twig
theme/base-2016/listing.twig
theme/base-2016/partials/_aside.twig
theme/base-2016/partials/_footer.twig
theme/base-2016/partials/_fresh_install.twig
theme/base-2016/partials/_header.twig
theme/base-2016/partials/_master.twig
theme/base-2016/partials/_topbar.twig
theme/base-2016/search.twig

This is a cherry-pick of @CarsonF's #5836 clean up on `base-2016` for 3.x
I've put the branch on the  org repo, so "go for it" wrt to tweaks as needed, I'll merge branches again on Monday before we tag 3.2-RC

Replace paths string concat with path() route and asset() generation.

---

src/Composer/Action/AbstractDependencyAction.php
src/Composer/Action/ProhibitsPackage.php
src/Config.php
src/Configuration/Validation/Validator.php
src/Controller/Backend/Authentication.php
src/Controller/Backend/BackendBase.php
src/Controller/Backend/FileManager.php
src/Controller/Exception.php
src/Debug/ShutdownHandler.php
src/EventListener/ExceptionListener.php
src/EventListener/StorageEventListener.php
src/Logger/Manager.php
src/Profiler/DatabaseDataCollector.php
src/Provider/EventListenerServiceProvider.php
src/Provider/TranslationServiceProvider.php
src/Request/ProfilerAwareTrait.php
src/Storage/ContentRequest/Save.php
src/Storage/Entity/Builder.php
src/Storage/Entity/MagicAttributeTrait.php
src/Storage/EventProcessor/TimedRecord.php
src/Storage/Field/Manager.php
src/Storage/Field/Type/FieldTypeBase.php
src/Storage/Field/Type/HtmlType.php
src/Storage/Field/Type/ListTypeBase.php
src/Storage/Mapping/ContentTypeTitleTrait.php
src/Storage/Mapping/MetadataDriver.php
src/Storage/Query/ContentQueryParser.php
src/Twig/Handler/ArrayHandler.php
src/Twig/Handler/ImageHandler.php

Codebase clean pass

---

.travis.yml
app/bootstrap.php
src/Composer/ScriptHandler.php
src/Configuration/Composer.php
src/Exception/BootException.php

As discussed in Slack #development today.
Fixes #5894 
Closes #5909
Closes bolt/composer-install#16

Revert hidden file changes

---

src/Configuration/ComposerChecks.php
src/Configuration/LowlevelChecks.php
src/Exception/BootException.php
tests/phpunit/unit/Configuration/ComposerConfigurationTest.php

Clean up BootException and some exception messages

Clean up BootException and some exception messages

---

src/Provider/TranslationServiceProvider.php

Re-add translation cache

---

src/Controller/Base.php
src/Controller/Frontend.php
src/Legacy/Storage.php

- Replaced utilphp with builtin methods.
- Simplified taxonomy slug name lookup.

Remove utilphp

---

src/Storage/Field/Type/HiddenType.php

Fix for hidden fields inside a repeater block

---

changelog.md
src/Version.php

Don't merge yet, please. We should merge this, when we're really ready to tag it.

[WIP] Bumping version to 3.2.0 RC 1, updated changelog.

---

app/resources/translations/cs_CZ/infos.cs_CZ.yml
app/resources/translations/en_GB/infos.en_GB.yml
app/resources/translations/es_ES/infos.es_ES.yml
app/resources/translations/fr/infos.fr.yml
app/resources/translations/it/infos.it.yml
app/resources/translations/ja/infos.ja.yml
app/resources/translations/nl_NL/infos.nl_NL.yml
app/resources/translations/pl_PL/infos.pl_PL.yml
app/resources/translations/pt/infos.pt.yml
app/resources/translations/pt_BR/infos.pt_BR.yml
app/view/twig/about/about.twig

Making license link to the MIT License on docs.

---

src/Legacy/Storage.php

Fixed: Set the slug after filling the object, prevent breakage.

---

app/view/twig/dbcheck/dbcheck.twig

Ensure response strings context variable exists and is iterable

---

src/Controller/Frontend.php

Fixes #5984
This would have been spotted if the change was done using PhpStorm, or we were using objects, or insane levels of nesting weren't used.
… do I sound like @CarsonF now, or what! :stuck_out_tongue_winking_eye:

Ensure parameter is set

---

src/Storage/Mapping/MetadataDriver.php

In Metadatadriver set an additional alias for when the slug doesn't match the CT name

---

app/bootstrap.php
src/Application.php
src/Configuration/Environment.php
src/Controller/Exception.php
src/Debug/ShutdownHandler.php
src/EventListener/ExceptionListener.php
src/Provider/CacheServiceProvider.php
src/Provider/TwigServiceProvider.php

As per agreement, @bobdenotter

Custom exception handler revised

---

src/Storage/Entity/Builder.php
src/Storage/Entity/Content.php

Fix empty title exceptions

---

src/Provider/StorageServiceProvider.php
src/Storage/EventProcessor/TimedRecord.php

This was actually requested by @CarsonF recently (read: two months ago), and it slipped my mind.

Timed record tweak

---

src/Storage/Field/Type/HiddenType.php

Causing exception when using hidden fields.

Add missing use statement to HiddenType

---

src/Provider/TwigServiceProvider.php

Fixes #5998 … @bobdenotter last one for 3.2.0 :+1:

Cache Twig relative to the defined theme

---

src/Canonical.php
src/Composer/PackageManager.php
src/Configuration/ResourceManager.php
src/Controller/Async/Stack.php
src/Controller/Backend/FileManager.php
src/Controller/Backend/Upload.php
src/Controller/Frontend.php
src/EventListener/SnippetListener.php
src/Exception/FileNotStackableException.php
src/Filesystem/Plugin/Parents.php
src/Filesystem/Plugin/ToJs.php
src/Helpers/Str.php
src/Stack.php
src/Storage/ContentRequest/Edit.php
src/Twig/Handler/ImageHandler.php

Mostly to quieten down Sami :wink:

PHPDoc fixes & code tidy

---

src/Controller/Frontend.php

Fixes #6011
Credit: @jkazimir :koala: Spotters Inc.

Prevent 404 on missing ContentType for homepage

---

app/src/sass/buic/_modal.scss

Add max-width to images in modals

---

src/Twig/Handler/ImageHandler.php

Allow aliased thumbnails for image 'arrays'.

---

app/src/js/modules/editcontent.js

Show "saving" indication on different types of 'save' actions.

---

src/Storage/Mapping/MetadataDriver.php

Fix check for alias if ContentType uses a custom `tablename`.

---

app/config/config.yml.dist

Per discussion in https://github.com/bolt/docs/pull/573

Remove advanced performance settings from default config

---

src/Application.php
src/Config.php

I'll add a PR to docs if/when this is agreed upon

Enable HTTP Cache to be passed configuration options

---

theme/base-2016/theme.yml

[ Insert another copy of beaker.gif ]

Use indentation of 4 spaces for consistency.

---

src/Helpers/Excerpt.php

Welcome to 3.2, hang your hat, grab a drink, get ready for more fun!

Fix excerpts exception with no found highlights

---

src/Storage/Field/Type/RepeaterType.php

Missed these ones in the last PR

Some more events need silencing for repeater collection updates

---

src/Storage/Query/Adapter/PostgresSearch.php
src/Storage/Query/ContentQueryParser.php
src/Storage/Query/Filter.php
src/Storage/Query/Handler/FirstQueryHandler.php
src/Storage/Query/Handler/IdentifiedSelectHandler.php
src/Storage/Query/Handler/LatestQueryHandler.php
src/Storage/Query/Handler/NativeSearchHandler.php
src/Storage/Query/Handler/RandomQueryHandler.php
src/Storage/Query/Handler/SearchQueryHandler.php
src/Storage/Query/Handler/SelectQueryHandler.php
src/Storage/Query/Query.php
src/Storage/Query/QueryParameterParser.php
src/Storage/Query/QueryResultset.php
src/Storage/Query/SearchConfig.php
src/Storage/Query/SearchQuery.php
src/Storage/Query/SearchQueryResultset.php
src/Storage/Query/SearchWeighter.php
src/Storage/Query/SelectQuery.php

* A bunch of PHPDoc 
* Some code readability
* Branding and PSR-2
* `\Bolt\Storage\Query\QueryParameterParser::parseValue()` will throw an exception if invalid parameter is passed … a valid array is currently assumed where it is used, and let's not go down that road again :laughing:

Query ~~OCD~~ tidy

---

app/view/twig/files/_upload.twig

This one unlocks a special surprise!
…details to follow after merge :wink:

Mais um … para cuidado camino

---

composer.json

Matches **formatting** of `master` in upcoming #6083

Clean up formatting of composer.json

---

src/Provider/TwigServiceProvider.php
src/Twig/Handler/RoutingHandler.php
src/Twig/TwigExtension.php

Not sure what to call this, beyond :koala: 
This is another part of the missing backport of #5836 that "someone" was supposed to take care of, and didn't do a good job of … we're looking at **you**, Kenny :koala: !!!
**Edit:** Obviously credit goes to @CarsonF for this work!

Backport "canonical" Twig function

---

src/Storage/CaseTransformTrait.php
src/Storage/Entity/MagicAttributeTrait.php
src/Storage/Field/Type/FieldTypeBase.php

This adds some improvements to the Entity serializer to fix some problems with saving fields that contained underscores next to numbers.
Fixes #6082

Fix problems saving fields with underscores and numbers

---

src/Config.php
src/Legacy/Storage.php

This is the first of a couple of PRs to fix some underscores / slug / key naming problems.
This one fixes #6051

Fixing issues with underscores

---

app/src/package.json

Boltgunning jshint

---

app/src/js/widgets/fields/fieldSelect.js
app/view/twig/editcontent/fields/_select.twig

Fixed: Sortable select fields now also work inside repeaters.

---

src/Application.php
src/Canonical.php
src/Provider/CanonicalServiceProvider.php
tests/phpunit/unit/Canonical/CanonicalTest.php
tests/phpunit/unit/Configuration/ResourceManagerTest.php
tests/phpunit/unit/Provider/CanonicalServiceProviderTest.php

So from #5836 there was a part that was missed in #6092 that would cause a #1555 … 
For that mater a #1, #2, #1000, #1024, #2000, #2048, #3000, #3072, #4000, #4096, #5000, #5128, #6000 … luckily #6144 hasn't happened yet so …
More credit to @CarsonF for both the original work, and relentless facepalming at me for not paying enough attention.

Now Carson tells me! ;-)

---

src/Storage/Field/Type/RepeaterType.php

Bug introduced by move around of metadata storage.
Fixes #6046

Fix metadata lookup in repeaters

---

app/resources/translations/ru/messages.ru.yml

22 new translations in Extensions section done.
Corrected "Запустить все обновления" на "Обновить всё" because old phrase was too long and dropdown button wrapped to the second line. Now everything looks perfect.

Update messages.ru.yml - 22 new translations done

---

src/Storage/Entity/ContentRelationTrait.php

Change function setRelation where arrray_unique and sort on every call can be very slow with big array.
sort has been moved to getRelation.

Performance issue fixing in ContentRelationTrait

---

app/src/js/modules/secmenu.js

Port of #6123 to Bolt `release/3.2`. Thanks again, @bnelson-cainc.

Fix adjustSidebarHeight so it's not adjusting when it shouldn't

---

src/Legacy/Content.php
src/Provider/TwigServiceProvider.php
src/Render.php
src/Twig/Runtime/HtmlRuntime.php
tests/phpunit/unit/Controller/FrontendTest.php
tests/phpunit/unit/Twig/Runtime/HtmlRuntimeTest.php

See https://github.com/twigphp/Twig/pull/2282

Fix sandbox not being disabled when exception is thrown

---

app/view/twig/_sub/_configuration_notices.twig
app/view/twig/dashboard/_aside.twig
src/Application.php
src/EventListener/GeneralListener.php
src/Twig/Extension/BoltExtension.php
tests/phpunit/unit/Twig/BoltExtensionTest.php

Adds a configuration notice when running "debug" in PROD. Comments welcome.

Configuration check helpers

---

app/src/js/widgets/fields/fieldRepeater.js

Fixes #6120 
Thanks go out to @maetthu for suggesting this fix here: https://github.com/bolt/bolt/issues/6120#issuecomment-264663516

Fixed: Re-ordering for repeaters when there are more than 10.

---

app/view/twig/components/panel-activity-system.twig

Fixed: HTML Overflow in system log fixed.

---

app/src/js/modules/secmenu.js

Applying #6145 to `release/3.2`. Thanks again, @bnelson-cainc.

Fixed:  tweaked `adjustSidebarHeight` for short pages.

---

app/theme_defaults/_sub_fields.twig
app/view/twig/editcontent/fields/_relationship.twig

Replace deprecated `|twig` filters with `template_from_string`.

---

app/resources/translations/en_GB/messages.en_GB.yml
app/view/twig/_nav/_secondary-extensions.twig
app/view/twig/_nav/_secondary.twig
app/view/twig/extend/extend.twig
src/Controller/Backend/Extend.php
src/Extension/MenuTrait.php
src/Menu/AdminMenuBuilder.php
src/Omnisearch.php
src/Provider/ControllerServiceProvider.php
tests/codeception/acceptance/102-BackendDeveloper/BackendDeveloperCest.php
tests/phpunit/unit/Extension/MenuTraitTest.php

Fixes #6143.
While working on this I stumbled upon an issue with backend pages added by extensions, so we should hold this one until #6151 is fixed.

Change: changing 'Extends' menu to 'Extensions'.

---

src/Twig/SecurityPolicy.php

`Twig_Sandbox_SecurityPolicy` has been made `final` as of https://github.com/twigphp/Twig/commit/a73280e69f66c7a5922ee926dcbb6913cff0402a so this PR just implements the `Twig_Sandbox_SecurityPolicyInterface` and imports the setters from the old parent.

Twig Sandbox pro-activity

---

src/Configuration/ResourceManager.php
src/Provider/AssetServiceProvider.php

(cherry picked from commit c934d55)
Fixes #6071

[3.2] Backport fix for assets double applying base path.

---

CHANGELOG.md

Basically sums up #6079 & #6083 so that we don't start losing stuff early :smile: 
@bobdenotter I've put the branch of the org, so we can massage layout (or add/remove) and then merge after that.

[4.0] Update changelog

---

app/src/js/widgets/fields/fieldSlug.js

Slug generation with multiple fields ordering

---

tests/phpunit/unit/Menu/MenuEntryTest.php

Quietens 4.x branch tests :wink:

[Tests] [Deprecation] getMock to getMockBuilder

---

tests/codeception/acceptance/102-BackendDeveloper/BackendDeveloperCest.php

[Tests] Update expected element for submit button

---

src/Application.php

Goes with https://github.com/bolt/starter-kit/pull/6

Change name from Starter to ConfigurationNotices

---

src/Configuration/ResourceManager.php

Only prepend base path if url is a path

---

src/Storage/Entity/ContentValuesTrait.php

Resolve template for template fields

---

.travis.yml

This should also take a minute or two off the workier build time

[Travis] Clean-up

---

src/Configuration/Validation/Configuration.php
src/Configuration/Validation/FlashLoggerAwareInterface.php
src/Configuration/Validation/Validator.php
src/Provider/ConfigServiceProvider.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Configuration/Validation/AbstractValidationTest.php
tests/phpunit/unit/Configuration/Validation/ConfigurationTest.php
tests/phpunit/unit/Controller/ControllerUnitTest.php

Fixes #6248 where #6249 doesn't apply

Flash logging configuration validation failures

---

app/view/toolbar/bolt.html.twig

Make sure the Bolt nub has no background or border.

---

src/Storage/Entity/ContentValuesTrait.php

Don't hydrate extension fields that haven't implemented it. 

---

src/Storage/Field/Type/RepeaterType.php

This PR changes the way that repeater fields are fetched from the database, addressing a problem where very complex contenttype structures could cause engine difficulties, especially in MySQL which seemed to struggle on complex join clauses.
The downside of this is that it adds one extra query per repeater field, but there is not too much of an effect on performance overall with most queries coming in under 50ms on a local db.
Whilst it would be good to offer more optimised fetching for those that are speed conscious it is probably better to offer this as an option and take this approach that works slightly more slowly, but more reliably as the default built in strategy.
Tested in MySQL, Postgres and SQLite as far as I can see with no other side effects. @graham73may be good if you could …

Optimise Queries for Repeater Fields

---

changelog.md
src/Version.php

Should be GTG for 3.2.6 release tomorrow.

Updating Changelog and Version to 3.2.6

---

src/Legacy/Storage.php

Whoops, looks like I've been responsible for wasting a lot of internet electricity.
@graham73may watch your query count go down after this one.

Move the getRepeaters call into the nohydrate block

---

app/src/js/widgets/buic/buicListing.js
app/view/twig/_base/_page.twig
app/view/twig/_sub/_record_list.twig

Fixes #5885 
JS does need to be rebuilt...

Fix not being able to delete records from dashboard

---

src/Canonical.php
src/EventListener/SnippetListener.php
tests/phpunit/unit/Canonical/CanonicalTest.php

Fix snippets on redirection

---

src/Twig/Handler/AdminHandler.php
tests/phpunit/unit/Twig/Handler/AdminHandlerTest.php

Fix ymlink twig filter for multiple matches.

---

app/view/twig/editcontent/fields/_textarea.twig

Weird, but there was no placeholder ...

Placeholder in textarea

---

src/Twig/Runtime/AdminRuntime.php

Class property tweak

---

README.md

Matches up with https://github.com/bolt/docs/pull/639

Move 3rd part install & test instructions to docs

---

src/Configuration/Environment.php

A single character missed from #6303 …
Fixes https://github.com/bolt/bolt-distribution/issues/27

Add a missing slash

---

app/src/sass/editcontent/fields/_repeater.scss
app/view/twig/editcontent/fields/_repeater.twig

Reset styles for last field in repeater since its in its own panel

---

src/AccessControl/Permissions.php

Clarify message in system log, and don't log the message for user root.

---

src/Provider/SessionServiceProvider.php
src/Security/Random/Generator.php
src/Session/Generator/NativeGenerator.php
src/Session/Generator/RandomGenerator.php

The commit messages say it all :smile:

Random randomness

---

app/view/twig/editcontent/fields/_select.twig

Fixed: Maintain order for multiple-select fields.

---

.github/CONTRIBUTING.md

Fixed the link to the manifesto in the contributing doc.

Fixes broken link in contributing doc.

---

src/Config.php

Also see https://github.com/bolt/filesystem/pull/43 and https://github.com/bolt/bolt-thumbs/pull/38

Support SVGs

---

src/Storage/Entity/Builder.php

This should fix the problems raised in these tickets 
Fixes #6276
Fixes #5957
Fixes #5765
If the field has been renamed or deleted we don't try to build it any more.

skip the field setup if there is no longer a mapping for it

---

src/Asset/Widget/Queue.php
src/Composer/ScriptHandler.php
src/Controller/Base.php
src/EventListener/ConfigListener.php
src/EventListener/ExceptionListener.php
src/Exception/Configuration/Validation/System/AbstractSystemValidationException.php
src/Exception/Configuration/Validation/System/ApacheValidationException.php
src/Exception/LowlevelException.php
src/Helpers/Arr.php
src/Helpers/Excerpt.php
src/Provider/SessionServiceProvider.php
src/Storage/Entity/ContentValuesTrait.php
src/Storage/Entity/FieldValue.php
src/Storage/EntityManager.php
src/Storage/Field/Collection/LazyFieldCollection.php
src/Storage/Field/Collection/RepeatingFieldCollection.php
src/Storage/Field/Type/FieldTypeBase.php
src/Storage/Field/Type/RepeaterType.php
src/Storage/Field/Type/TemplateFieldsType.php
src/Storage/Field/Type/TextType.php
src/Storage/FieldManager.php
src/Storage/Mapping/MetadataDriver.php
src/Storage/Query/ContentQueryParser.php
src/Storage/Query/Query.php
src/Storage/Repository/CronRepository.php
src/TemplateChooser.php
src/Twig/Runtime/ImageRuntime.php

Mostly PHPDoc, and a couple of concrete getters on entities.

[3.3] OCD boredom … Erm, I mean clean ups

---

tests/phpunit/unit/AccessControl/AccessCheckerTest.php

[3.3][Tests] Restore last incomplete unit test

---

src/Cache.php
src/Composer/Action/Options.php
src/Configuration/Validation/Configuration.php
src/Debug/Caster/AbstractCasterProvider.php
src/Debug/Caster/FilesystemCasters.php
src/Provider/ExtensionServiceProvider.php
src/Provider/LoggerServiceProvider.php
src/Provider/TwigServiceProvider.php

[3.3] PHPDoc & dead code removal

---

src/Twig/Handler/ImageHandler.php

Duplicated failsafe check from not alias version to this function.
May also needed in other branches.

fail safe for missing file

---

src/Provider/StorageServiceProvider.php
src/Storage/ContentRequest/Save.php

[3.3] Slugify slugs on edit save

---

src/Asset/CallableInvokerTrait.php
src/Extension/StorageTrait.php
src/Storage/Migration/Import.php
src/Storage/Repository/BaseLogRepository.php

Replacing deprecated function calls

---

app/bootstrap.php

[3.3] Remove unused import

---

src/Configuration/ResourceManager.php

Deprecate old theme_path

---

app/view/twig/editcontent/_relations.twig

Fixes #6369, while still not triggering the error that #5772 fixed.

Don't require outgoing relations to show incoming relations 

---

src/Cache.php

Spotted in the wild, one :koala:

[3.3] Use correct class for deprecation notice

---

src/Cache.php

Today's tally:
:koala: — 2 
Gawain — 0

[3.2] Ensure config-cache.json gets flushed

---

src/Composer/ScriptHandler.php
src/Storage/Collection/CollectionManager.php
src/Storage/Entity/Content.php
src/Storage/EntityManager.php
src/Storage/Field/Collection/RepeatingFieldCollection.php
src/Storage/Field/Type/RepeaterType.php
src/Twig/Runtime/ImageRuntime.php

[3.3] PHPDoc

---

src/Twig/Handler/UserHandler.php

Fixed: Missing "Delete" button appears when it should.

---

app/config/config.yml.dist

update config.yml timezone info

---

src/Storage/Entity/Builder.php

This is another check to avoid breaks on old FieldInterface

[3.3] Add an interface check around the set method

---

src/Provider/TwigServiceProvider.php

Fixed: prepending theme path instead of appending, fixing template priority order.

---

src/AccessControl/AccessChecker.php
src/Controller/Backend/BackendBase.php
src/Storage/Repository.php
src/Storage/Repository/UsersRepository.php
src/Users.php
tests/phpunit/unit/AccessControl/AccessCheckerTest.php

[3.2] First check user

---

app/resources/translations/de_DE/messages.de_DE.yml

One char typo

---

tests/phpunit/unit/AccessControl/AccessCheckerTest.php
tests/phpunit/unit/AccessControl/LoginTest.php
tests/phpunit/unit/AccessControl/PasswordHashTest.php
tests/phpunit/unit/AccessControl/PasswordTest.php
tests/phpunit/unit/AccessControl/TokenGeneratorTest.php
tests/phpunit/unit/AccessControl/TokenTokenTest.php
tests/phpunit/unit/Library/BoltLibraryTest.php

:koala: spotted hanging around `master`

[4.0][Tests] Move PasswordHashTest and correct related namespaces

---

src/Helpers/Image/Thumbnail.php

[3.2] Fix assignment logic

---

src/AccessControl/Password.php
src/Composer/Satis/QueryService.php
src/Controller/Async/General.php
src/Controller/Backend/Log.php
src/Controller/Backend/Users.php
src/Controller/Base.php
src/Cron.php
src/EventListener/AccessControlListener.php
src/Events/StorageEvent.php
src/Logger/Handler/RecordChangeHandler.php
src/Nut/UserAdd.php
src/Nut/UserManage.php
src/Provider/LoggerServiceProvider.php
src/Storage/Field/Type/RelationType.php
src/Storage/Field/Type/RepeaterType.php
src/Storage/Field/Type/TaxonomyType.php
src/Users.php
tests/phpunit/unit/AccessControl/LoginTest.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Nut/UserManageTest.php
tests/phpunit/unit/Nut/UserResetPasswordTest.php
tests/phpunit/unit/Storage/Repository/AuthtokenRepositoryTest.php
tests/phpunit/unit/Storage/Repository/LogChangeRepositoryTest.php
tests/phpunit/unit/Storage/Repository/LogSystemRepositoryTest.php
tests/phpunit/unit/Storage/Repository/UsersRepositoryTest.php

* More class name resolution instead of strings
* Switch FormBuilder to type hint on the interface only
* [Guzzle function derp](http://docs.guzzlephp.org/en/5.3/http-messages.html?highlight=getBody#body), I guess comes copy/pasta from Guzzle 3 use internally … in the dark ages
* Clean-up of the general kind

[3.3] Tidy up v2

---

app/view/twig/editcontent/fields/_image.twig

Ensure default for image.file in preview

---

app/view/twig/editfile/editfile.twig

So calling #1555 on this.
Fixes #6513

Related has items when its count is greater than zero

---

src/Provider/ThumbnailsServiceProvider.php

Fixes #5347 
@GawainLynch I'll merge 3.2 into 3.3 since the logic changed on 3.3.

Helpful exception when default thumbnail images are not found

---

src/Provider/ControllerServiceProvider.php
src/Routing/CallbackResolver.php

As [requested](https://github.com/bolt/bolt/pull/6519#issuecomment-289830898) by @CarsonF in #6519

[3.3] Add deprecation notices for $app['controller.classmap']

---

src/Configuration/LowlevelChecks.php

Fix LowlevelChecks::disableApacheChecks() not passing value to RM

---

app/src/js/init.js

Few minor fixes that was causing the lint task to fail.

[3.4] Fix JS Linting Errors

---

src/Legacy/Storage.php

Fixes #5882 (well, the remainder that hadn't already been cleaned up)

[3.2] prefill breaks on PostgreSQL

---

src/Storage/Collection/Taxonomy.php
src/Storage/Field/Type/JoinTypeBase.php
src/Storage/Field/Type/RelationType.php
src/Storage/Field/Type/TaxonomyType.php

Just some clean up, and following things though got tricky.
* Change to `src/Storage/Collection/Taxonomy.php` is to match signature of `src/Storage/Collection/Relations.php`
* Return eary when we already have a Collection
* PHPDoc

PHPDoc and logic tidy

---

app/deprecated.php
app/view/twig/prefill/_blocks.twig
app/view/twig/prefill/prefill.twig
src/Config.php
src/Controller/Backend/General.php
src/Legacy/Storage.php
src/Nut/DatabasePrefill.php
src/Provider/PrefillServiceProvider.php
src/Storage/Database/Prefill/ApiClient.php
src/Storage/Database/Prefill/Builder.php
src/Storage/Database/Prefill/RecordContentGenerator.php
src/Storage/Repository.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Controller/Backend/GeneralTest.php
tests/phpunit/unit/Logger/ChangeLogTest.php
tests/phpunit/unit/Mocks/LoripsumMock.php
tests/phpunit/unit/Storage/Database/Prefill/ApiClientTest.php
tests/phpunit/unit/Storage/Database/Prefill/BuilderTest.php
tests/phpunit/unit/Storage/Database/Prefill/RecordContentGeneratorTest.php
tests/phpunit/unit/Storage/StorageTest.php

This gets 227 lines of the pre-fill logic out of legacy … and as a starting point to its own service with limited API exposure.
… and adds unit tests for new classes!
* Naming
* Visibility
* Most changes
* Re-writing the per-field logic

[3.4] Pre-fill service

---

src/Nut/DebugEvents.php

Guess who is trying to document (and update existing docs), and think though, use of these things ;-)

[3.3] Option to get short listing of event names

---

tests/phpunit/unit/Nut/DatabaseCheckTest.php
tests/phpunit/unit/Nut/Helper/ContainerHelperTest.php
tests/phpunit/unit/Nut/Style/NutStyleTest.php

Coverage for some recent changes in PRs

[3.3][Tests] Nut coverage

---

app/view/twig/editcontent/fields/_block.twig
src/Storage/Mapping/MetadataDriver.php

Just a couple of fixes for strict variables mode used with repeaters. credit @eduardomart for spotting.

Strict mode fixes for Repeater Blocks

---

app/theme_defaults/_sub_fields.twig
theme/base-2016/partials/_sub_fields.twig

Fixing the link to docs.bolt.cm/templating/fields-tag

---

app/view/twig/editcontent/fields/_date.twig
app/view/twig/editcontent/fields/_datetime.twig

Use getter to get id. Fixes exception when using datetime in repeater fields

---

composer.json
src/Nut/DatabaseRepair.php
src/Nut/SetupRun.php
src/Provider/NutServiceProvider.php
tests/phpunit/unit/Nut/DatabaseRepairTest.php

This gives us a `setup:run` command, that will either run first time set-up, or updates if certain criteria are met … like existing/connecting DB, existing users.

Nut command to perform Bolt set-up (first time, or post-update) tasks

---

src/Controller/Async/General.php

Grab news over https.

---

CHANGELOG.md
src/Twig/Extension/HtmlExtension.php
src/Twig/Runtime/HtmlRuntime.php
tests/phpunit/unit/Twig/Runtime/HtmlRuntimeTest.php

[4.0] Remove {{ link() }} as it now is used upstream

---

src/Asset/Snippet/Snippet.php
src/EventListener/ConfigListener.php
src/EventListener/ExceptionListener.php
src/Extension/TwigTrait.php
src/Legacy/Content.php
src/Provider/TwigServiceProvider.php
src/Render.php
src/Response/BoltResponse.php
src/Storage/Entity/ContentValuesTrait.php
src/Storage/Field/Collection/FieldCollection.php
src/Twig/FilesystemLoader.php
src/Twig/Runtime/DumpRuntime.php
src/Twig/Runtime/RecordRuntime.php
src/Twig/Runtime/WidgetRuntime.php
src/Twig/SwitchNode.php
tests/phpunit/unit/Extensions/Mock/TwigExtension.php
tests/phpunit/unit/Provider/TwigServiceProviderTest.php
tests/phpunit/unit/Twig/Runtime/DumpRuntimeTest.php
tests/phpunit/unit/Twig/SetcontentTokenParserTest.php
tests/phpunit/unit/Twig/SwitchTokenParserTest.php

What remains from here is either for PHPUnit annotations, as it doesn't see the import. Or being ripped out already in `master`

[3.4] More Twig imports & aliases

---

app/view/twig/editcontent/editcontent.twig

Use `singular_slug` instead of `slug` for "New [..]".

---

app/src/sass/editcontent/_fieldset.scss

No margin or borders for hidden field placeholders.

---

src/Storage/Repository/AuthtokenRepository.php
src/Storage/Repository/BaseLogRepository.php
src/Storage/Repository/LogChangeRepository.php
tests/phpunit/unit/Storage/Repository/AuthtokenRepositoryTest.php
tests/phpunit/unit/Storage/Repository/LogChangeRepositoryTest.php
tests/phpunit/unit/Storage/Repository/LogSystemRepositoryTest.php

Don't turn on change logging in 3.3 HEAD right now :wink: … all good after this ;-)

[3.3] Remove createQueryBuilder() override where not needed

---

app/view/twig/_base/_fieldset.twig
app/view/twig/editcontent/fields/_date.twig
app/view/twig/editcontent/fields/_datetime.twig
app/view/twig/editcontent/fields/_file.twig
app/view/twig/editcontent/fields/_filelist.twig
app/view/twig/editcontent/fields/_float.twig
app/view/twig/editcontent/fields/_grouping.twig
app/view/twig/editcontent/fields/_hidden.twig
app/view/twig/editcontent/fields/_html.twig
app/view/twig/editcontent/fields/_image.twig
app/view/twig/editcontent/fields/_imagelist.twig
app/view/twig/editcontent/fields/_integer.twig
app/view/twig/editcontent/fields/_markdown.twig
app/view/twig/editcontent/fields/_meta.twig
app/view/twig/editcontent/fields/_slug.twig
app/view/twig/editcontent/fields/_text.twig
app/view/twig/editcontent/fields/_textarea.twig
app/view/twig/files/_upload.twig

I didn't want to do this yet … but it is driving everyone's OCD mad, and today is not a day I want to feel OCDed out :laughing: 
@bobdenotter I know I asked you to not attack those, as I wanted to take a consolidated approach … but when I saw the tiny changes needed to get hundreds of deprecation notices to disappear, I changed my mind :wink:

[3.3][Deprecations] Import Twig macro template where used

---

CONTRIBUTING.md

This [comment](https://github.com/bolt/bolt/issues/6649#issuecomment-300804371) made me realise we're missing one of these.

[3.2] Add a CONTRIBUTING.md file to the repo root, pointing to docs

---

src/Provider/PrefillServiceProvider.php
src/Storage/Database/Prefill/RecordContentGenerator.php

Break out field type setting logic, and where appropriate use nulls

[3.4] Prefill updates

---

app/view/twig/_base/_fieldset.twig

* :koala:
* #1555
* :woman_facepalming:

[3.3] Use ternary logic on block to prevent printing blocks

---

codeception.yml
tests/codeception/acceptance.suite.yml
tests/codeception/functional.suite.yml
tests/codeception/functional/_bootstrap.php
tests/codeception/unit.suite.yml
tests/codeception/unit/_bootstrap.php

[Tests][Codecption] Tweaks

---

src/Controller/Backend/FileManager.php

[3.4][Deprecation] Add missing $form->isSubmitted()

---

src/Provider/TwigServiceProvider.php

[4.0] Remove outdated Twig form extension override

---

tests/phpunit/unit/Composer/PackageTest.php
tests/phpunit/unit/Debug/FilesystemCastersTest.php
tests/phpunit/unit/Provider/AccessControlServiceProviderTest.php
tests/phpunit/unit/Provider/DumperServiceProviderTest.php

Working on some tests for 3.3 and realised these are suitable for 3.2, so might as well start there :wink:

[3.2][Tests] More coverage

---

src/Exception/FilesystemException.php

[Deprecation] \Bolt\Exception\FilesystemException

---

src/Embed/GuzzleDispatcher.php
tests/phpunit/unit/Embed/GuzzleDispatcherTest.php
tests/phpunit/unit/Embed/ResolverTest.php

SUT Class now at full coverage.

[3.2] Embed tests & corner case minor hotfix

---

app/view/twig/editcontent/_aside-save.twig
app/view/twig/editcontent/_aside-status.twig
app/view/twig/editcontent/_aside.twig
app/view/twig/editcontent/_buttons.twig
app/view/twig/editcontent/editcontent.twig

Replace a few `slug` with `singular_name` in "Edit record" page.

---

app/view/twig/_base/_listing.twig
app/view/twig/_base/_page.twig
app/view/twig/_macro/_macro.twig
app/view/twig/_macro/_panels.twig
app/view/twig/_nav/_footer.twig
app/view/twig/_nav/_primary.twig
app/view/twig/_nav/_secondary-content.twig
app/view/twig/_sub/_messages.twig
app/view/twig/activity/changelog.twig
app/view/twig/changelog/_blocks.twig
app/view/twig/components/panel-activity-change.twig
app/view/twig/dashboard/_quicklinks-buttons.twig
app/view/twig/dashboard/_quicklinks-dropdown.twig
app/view/twig/dashboard/dashboard.twig
app/view/twig/editcontent/_taxonomies.twig
app/view/twig/editcontent/fields/_meta.twig
app/view/twig/extend/extend.twig
app/view/twig/files/_files.twig
app/view/twig/mail/passwordreset.twig
app/view/twig/overview/_panel-actions_overview.twig
app/view/twig/recordbrowser/_navigation.twig
app/view/twig/users/_userlist-actions.twig
app/view/twig/users/_userlist.twig
src/Controller/Backend/BackendBase.php
src/Provider/TwigServiceProvider.php
src/Twig/Runtime/RecordRuntime.php
theme/base-2016/listing.twig
theme/base-2016/partials/_aside.twig
theme/base-2016/partials/_header.twig
theme/base-2016/partials/_master.twig

Follow-up on discussions in Slack & #6685

[3.3] Update global use

---

app/src/js/widgets/fields/fieldFilelist.js

Fixes #6542 
Thanks to @xiaohutai and @robbie2491 for pointing out and identifying the problem.

Fix JS error in IE for Filelist fieldtype

---

src/Storage/Collection/Relations.php
src/Storage/Collection/Taxonomy.php
src/Storage/ContentRequest/Save.php
tests/phpunit/unit/Storage/FieldLoadTest.php
tests/phpunit/unit/Storage/FieldSaveTest.php

[3.2] Fix tag slug generation

---

app/config/permissions.yml.dist

Fixes: #6688
The longer URL required a re-wrap of the comment.

Update permissions.yml documentation link (issue #6688)

---

changelog.md
src/Version.php

Prepare Bolt 3.3.0 beta 8 release.

---

app/src/js/widgets/buic/buicListingPart.js

Only adding record to the list, if it wasn't already selected before.

---

app/view/twig/editcontent/fields/_repeater.twig
src/Storage/ContentRequest/Edit.php

Get fields from repeater, even if repeater isn't last. Obsoletes hackish include of HTML field.

---

app/src/sass/editcontent/fields/_repeater.scss

Minor visual changes to repeater blocks: Make them stand out a bit less, better alignment on page.

---

tests/phpunit/unit/Composer/Script/BootstrapYamlUpdaterTest.php
tests/phpunit/unit/Storage/Query/QueryTest.php
tests/phpunit/unit/Twig/Runtime/DumpRuntimeTest.php

Yep, I missed it in review … I shall eat one less stroopwafel today as self-punishment :stuck_out_tongue_winking_eye:

[3.3][Tests] Update mock builder to be forward-compatible

---

src/Controller/Backend/Users.php

* Give more useful notifications 
* Fix a silent bug … :koala:

[3.4] Update message & exception handling for Users::notifyUserSetupEmail

---

src/Provider/ThumbnailsServiceProvider.php

Fix BC for old thumbnail config paths

---

src/Storage/ContentRequest/Modify.php

[3.2] Audit delete record

---

app/bootstrap.php
src/Composer/Script/DirectoryConfigurator.php
src/Composer/Script/DirectorySyncer.php
src/Composer/Script/PathCustomizer.php
src/Configuration/PathResolver.php
src/Exception/BootException.php
src/Nut/Output/NutStyleInterface.php
src/Nut/Style/NutStyle.php
src/Nut/Style/OverwritableStyleInterface.php

Further follow up to script handler refactor.

Script handler refactor follow up

---

changelog.md
src/Application.php

[2.2] Prepare for minor release

---

src/Provider/FilesystemServiceProvider.php

Closes #6740 
Related to #5460

[3.3] Skip symlinks instead of throwing exceptions on local filesystems

---

tests/phpunit/unit/Composer/Action/CheckPackageTest.php
tests/phpunit/unit/Composer/Satis/QueryServiceTest.php

This makes the tests a few seconds faster overall (the 3 query tests were in my first 10 on the timing record and are now down near the bottom), and moves the query test to a SUT only test.
Things you're inspired to do when your Internet connection is flaky :rofl:

[3.2][Tests] Guzzle mocks

---

tests/phpunit/unit/Nut/ExtensionsSetupTest.php

* Remove old local extension test
* Only test SUT command, not app
PHPUnit run time saving on my laptop 5.5 seconds

[3.3][Tests] Need for speed

---

changelog.md
src/Version.php

Should be the last beta, before we move to RC.

Preparing Bolt 3.3.0 beta 10.

---

src/Legacy/Storage.php

Fix "search with setcontent" when using stricter settings.

---

src/Bootstrap.php

Relevant to https://github.com/bolt/docs/pull/753#issuecomment-309031662

[3.3] Allow .bolt.php to return extension objects

---

tests/codeception/extensions/CodeceptionEventsExtension.php
tests/phpunit/BoltListener.php
tests/phpunit/unit/Asset/AbstractExtensionsUnitTest.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Controller/Backend/UploadTest.php
tests/phpunit/unit/Nut/ConfigGetTest.php
tests/phpunit/unit/Nut/ConfigSetTest.php

Missed stuff last time around … I blame the :koala:

[4.0][Tests] Updates for var/

---

src/Storage/Query/ContentQueryParser.php

Backport of #6764 for `release/3.2`

[3.2] Implement missing `hasParameter` method.

---

theme/base-2016/extrafields.twig
theme/base-2016/page.twig
theme/base-2016/readme.md
theme/base-2016/record.twig

Some tweaks to `sub_fields` blocks.

---

src/Twig/Extension/RecordExtension.php
src/Twig/Runtime/RecordRuntime.php

Post-merge follow up for #6788

[4.0] Remove deprecated Twig fields() function

---

src/Storage/ContentRequest/Edit.php

Follow up tweak to #6799
/cc @ToBe998

[3.2] Tweak parameter location

---

app/resources/translations/cs_CZ/messages.cs_CZ.yml
app/resources/translations/de_DE/messages.de_DE.yml
app/resources/translations/el/messages.el.yml
app/resources/translations/en_GB/messages.en_GB.yml
app/resources/translations/es_ES/messages.es_ES.yml
app/resources/translations/fi/messages.fi.yml
app/resources/translations/fr/messages.fr.yml
app/resources/translations/hu/messages.hu.yml
app/resources/translations/id/messages.id.yml
app/resources/translations/it/messages.it.yml
app/resources/translations/ja/messages.ja.yml
app/resources/translations/nb/messages.nb.yml
app/resources/translations/nl_NL/messages.nl_NL.yml
app/resources/translations/pl_PL/messages.pl_PL.yml
app/resources/translations/pt/messages.pt.yml
app/resources/translations/pt_BR/messages.pt_BR.yml
app/resources/translations/ru/messages.ru.yml
app/resources/translations/sv_SE/messages.sv_SE.yml
app/resources/translations/zh_CN/messages.zh_CN.yml
app/resources/translations/zh_TW/messages.zh_TW.yml
app/view/twig/_sub/_record_list_data.twig
app/view/twig/editcontent/_aside-delete.twig
app/view/twig/editcontent/fielddata/_filelist.twig
app/view/twig/editcontent/fielddata/_imagelist.twig
app/view/twig/editcontent/fields/_meta.twig
app/view/twig/files/files.twig
app/view/twig/overview/overview.twig
app/view/twig/users/_userlist-actions.twig

This is where I got to with this over the weekend, and as I am refocusing on config and merges today I thought I'd just send this in to get it caught in said merges.

[3.3] More translation strings updates

---

app/theme_defaults/_sub_field_blocks.twig
app/theme_defaults/_sub_fields.twig
src/Provider/TwigServiceProvider.php
src/Twig/Runtime/HtmlRuntime.php
theme/base-2016/extrafields.twig
theme/base-2016/page.twig
theme/base-2016/partials/_sub_field_blocks.twig
theme/base-2016/partials/_sub_fields.twig

So, funny story, right … I was working on a "ready-to-go" branch for 4.0 when I found a bug I though came from 3.3, so I ran up this and grabbed the deprecations that go with it, and during the monkey-testing of this was when I found more bug(s) that lead to #6811
… a day and a bit later. :tada: 
This should go in _after_ we agree on the approach in #6811, but _before_ I need to do the branch merge, as the differences are substantial and the merge conflicts are just ugly. The life of being a merge :princess: 
When I merge these all down, then I can send in the PR for 4.0.

[3.3] More Twig deprecations

---

app/src/js/widgets/fields/fieldTags.js

If you have a lot of tags, like 15/20k the fieldTags takes a lot cause of select2 load. It could take something as 60 seconds and that is not good.

Performance in tags load

---

app/src/js/widgets/fields/fieldTags.js

Fix #6817 for when tags contain spaces. See https://github.com/bolt/bolt/pull/6817#issuecomment-315411274 for more info

Fix for tags with spaces

---

README.md

[3.3] Reduce README to bare minimum, and point to official documentation

---

src/Asset/File/FileAssetBase.php
src/Asset/Snippet/Snippet.php
src/Asset/Widget/Widget.php

Doesn't change existing functionality, but for those that know what this is for, it is a useful shortcut. :wink: 
If we're in agreement that we can sneak this in, I'll add some docs to 3.3, if we'd prefer 3.4 I'll target there. 
**Edit:** I've only been continually forgetting to PR this for 18 months now, not a huge delay :rofl:

[3.3] Add asset factory short-cut methods

---

changelog.md
src/Version.php

Assets were rebuilt post-branch merge this morning. So this is the CHANGELOG & version bump.

Preparing 3.3.0 RC 1

---

changelog.md
src/Version.php

Due for tagging/release tomorrow.

Prepare Bolt 3.3.3 RC 2.

---

src/Bootstrap.php
tests/phpunit/BoltListener.php
tests/phpunit/unit/Bootstrap/BootstrapTest.php

This is a prequel to @lenvanessen's work in #6839

[3.3] Bootstrap tests & a couple of minor bug fixes

---

app/view/twig/_base/_fieldset.twig

[3.3] Hack around macro abuse

---

app/view/twig/editcontent/_templatefields.twig
app/view/twig/editcontent/fields/_image.twig
app/view/twig/editcontent/fields/_select.twig
src/Form/Resolver/Choice.php
src/Storage/ContentRequest/Edit.php
tests/codeception/_support/YamlHelper.php
tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php
tests/codeception/acceptance/101-BackendEditor/BackendEditorCest.php
tests/codeception/acceptance/102-BackendDeveloper/BackendDeveloperCest.php
tests/codeception/acceptance/_bootstrap.php
tests/codeception/extensions/CodeceptionEventsExtension.php
tests/phpunit/unit/Form/Resolver/ChoiceTest.php

Can someone on the team test & review urgently please … ~~This needs to be agreed on and merged in the next hour or so.~~
Follow up to #6841
I'd like to dedicated the work on this to Chester Bennington … For a lot of us, you got us though some hard times. R.I.P.

[3.2] Fix for TemplateField select options

---

app/src/sass/_base.scss
app/src/sass/modules/_footer.scss

tl;dr I want my debug bar working :stuck_out_tongue_winking_eye: 
This PR:
* Adjusts z-index as .sf-toolbarreset now uses 99999
* Annoys people with real talent for SASS/CSS :rofl: 
* Fixes #6823

[4.0] Fix debug bar display

---

src/Legacy/AbstractPager.php
src/Legacy/PasswordLib/PasswordLibFactory.php
src/Legacy/PasswordLib/PasswordLibRandomGenerator.php

[3.3] Add missing PHPDoc deprecations in legacy classes

---

app/view/twig/editcontent/fields/_repeater-group.twig
src/Form/Resolver/Choice.php
tests/phpunit/unit/Form/Resolver/ChoiceTest.php

Fixes: #6864
Related: #6841 & #6845 
Happiness: @zomars

[3.2] Fix for select fields in repeaters

---

changelog.md
src/Version.php

WIP, because not certain when we'll release this exactly.

Preparing Bolt 3.2.18 release

---

src/Twig/Extension/BoltExtension.php
src/Twig/SetcontentTokenParser.php
tests/phpunit/unit/Twig/SetcontentTokenParserTest.php

Two :koala: derps that were my fault while helping out. 
Follow up to me being "helpful" in #6622

[3.4][Tests] Setcontent

---

tests/phpunit/unit/Form/Resolver/ChoiceTest.php

Follow up to #6878, doing my job properly this time.

Add test to check correct sorting gets applied

---

composer.json
src/Composer/Script/BootstrapYamlUpdater.php
src/Configuration/YamlUpdater.php
src/Response/TemplateResponse.php
src/Response/TemplateView.php
tests/phpunit/unit/Composer/Script/BootstrapYamlUpdaterTest.php
tests/phpunit/unit/Response/TemplateResponseTest.php
tests/phpunit/unit/Response/TemplateViewTest.php

Self-explanatory, and covered in the last few dev meetings.
Hang off merging as this will need an rebased & update to `composer.json` once we tag `bolt/collection` v1.1.0 (probably later today).

[3.3] Update to Collection 1.1

---

src/Provider/StorageServiceProvider.php

[3.3] Invert logic on timed record cron setting

---

.gitignore
src/Provider/NutServiceProvider.php

Here we go … [Screen cast](https://asciinema.org/a/133437) of an SFTP run.
To play, update a project's `composer.json`:
```
"require": {
"php": "^5.5.9 || ^7.0",
"bolt/bolt": "3.4.x@dev",
"bolt/simple-deploy": "dev-master@dev",
"passwordlib/passwordlib": "^1.0@beta"
},
```

[3.4] Nut Simple Deploy

---

src/AccessControl/AccessChecker.php
src/Twig/Extension/BoltExtension.php

[3.4] Invert logic so setcontent legacy is on by default

---

src/Controller/Async/General.php

Fixes #6902
Credit: @rossriley

[3.4] Correct order parameter to use minus sign

---

app/view/twig/activity/systemlog.twig

Fix Systemlog Filter by Context = extension

---

composer.json

Just playing "Keep up with Sebastian" … nothing much to see here.

[4.0] Update sebastian/phpcpd requirement to ^3.0

---

src/Asset/Widget/Widget.php
src/Composer/EventListener/PackageEventListener.php
src/Composer/JsonManager.php
tests/phpunit/unit/Asset/AssetsProviderTest.php
tests/phpunit/unit/Composer/JsonManagerTest.php
tests/phpunit/unit/Configuration/Validation/ConfigurationTest.php
tests/phpunit/unit/Configuration/Validation/DatabaseMySqlTest.php
tests/phpunit/unit/Configuration/Validation/DatabasePostgresTest.php
tests/phpunit/unit/Configuration/Validation/DatabaseSqliteTest.php
tests/phpunit/unit/Controller/Async/GeneralTest.php
tests/phpunit/unit/Controller/FrontendTest.php
tests/phpunit/unit/Extension/ManagerTest.php
tests/phpunit/unit/Filesystem/UploadContainerTest.php
tests/phpunit/unit/Storage/EntityBuilderTest.php
tests/phpunit/unit/Storage/StorageTest.php

Clean up some of the tests that are marked as "Risky" and driving me mental

[3.4][Tests] Risky Business

---

src/Controller/Backend/General.php

:koala:  `<insert self-facepalm here>`

[3.4] Swap Bag for MutableBag

---

src/Composer/EventListener/PackageEventListener.php

Something … something … autoloader

[3.4] Use native JSON handling for Composer CLI

---

src/Extension/ConfigTrait.php

Follow up to #6951 … 'cause :koala: 
ping @ToBe998

[3.3] Refactor fields trait to extend the type service with new fields

---

src/Controller/Frontend.php

[3.3] Don't try to use empty array, and only use objects as objects

---

changelog.md

I put "WIP" on this one just because 1) I didn't manually check every link, and 2) y'all may not be a fan of my six commits. Sorry, I wasn't sure how to squash these and wasn't sure if that was necessary anyway.
Fixes: #6974 
Just for kicks, here's basically the Vim regex I used to update these.
`:%s/#\([0-9]*\)$/[#\1](https:\/\/github.com\/bolt\/bolt\/issues\/\1)/gc`
Replaces all #xxxx at the end of the line with a link to issue #xxxx.

Fix broken links, add links to changelog.md

---

app/view/twig/editcontent/fields/_repeater-group.twig

[3.3] Add FileMatcher to repeater context

---

src/Storage/Database/Schema/Table/FieldValue.php
src/Storage/Entity/FieldValue.php
src/Storage/Field/Collection/LazyFieldCollection.php

[3.3] Handle mismatch between type & column names for json_array to json 

---

app/view/twig/editcontent/fields/_textarea.twig

I know this is not a huge deal and it's okay if is not accepted but I like my backend nice and tidy.

Add inline variant to textarea field

---

.github/CONTRIBUTING.md

Fixes not working page-jumps in the contributing guide

[3.3] Page-jumps in the contributing guide

---

src/EventListener/SnippetListener.php

Accidental regression introduced in #6230
Re-fixes #4295

[3.3] Fix AJAX detection logic in snippet listener

---

app/view/twig/prefill/_blocks.twig
app/view/twig/prefill/prefill.twig
src/Controller/Backend/General.php
src/Legacy/Storage.php
src/Nut/DatabasePrefill.php
src/Storage/Database/Prefill/Builder.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Controller/FrontendTest.php
tests/phpunit/unit/Storage/Database/Prefill/BuilderTest.php
tests/phpunit/unit/Storage/FieldLoadTest.php
tests/phpunit/unit/Storage/FieldSaveTest.php
tests/phpunit/unit/Storage/Query/QueryFieldDelegationTest.php
tests/phpunit/unit/Storage/StorageTest.php

Nut's pre-fill command was throwing an exception on PHP 7.2 … so while I was there :wink:

Migrate pre-fill builder to use Bags

---

src/Nut/Cron.php
src/Nut/DatabaseUpdate.php
src/Provider/NutServiceProvider.php
tests/phpunit/unit/Nut/CronTest.php
tests/phpunit/unit/Nut/DatabaseUpdateTest.php

Been annoying me for years :wink:

[4.0] Nut class name consistency

---

src/Helpers/Excerpt.php
src/Menu/Resolver/RecentlyEdited.php

Cherry-picked from an upcoming branch in `master` to smooth the way … 
OK, truth be told — I had to rip something out after all that DBAL fun today … and this was collateral damage :wink:

[3.4] FC tweaks

---

app/view/twig/editcontent/_aside-save.twig

Remove dropdown options for singleton

---

app/config/permissions.yml.dist
src/Controller/Async/FilesystemManager.php
src/Controller/Backend/FileManager.php
src/Filesystem/Listing.php

Fixes #6899
Could we hang off merging this until after the 11th when Carson is back from vacation. I have a feeling he'll trigger on this, but before we release the next major of `bolt/filesystem` we can't modify the interface, and my OCD (potentially) can't handle the overhead of a method check … so … let's see :crossed_swords: :wink:

[3.4] Don't show files & directories that start with a dot

---

src/Controller/Backend/General.php
src/Menu/Resolver/RecentlyEdited.php

[3.4] Fix crashes on new ContentTypes

---

app/resources/translations/en_GB/messages.en_GB.yml
app/resources/translations/nl_NL/messages.nl_NL.yml
src/Provider/PrefillServiceProvider.php
src/Storage/Database/Prefill/Builder.php
tests/phpunit/unit/Storage/Database/Prefill/BuilderTest.php

[3.4] When prefilling, add only one record to singletons. 

---

src/Menu/Resolver/RecentlyEdited.php

[3.4] Catch TableNotFoundException for new ContentTypes

---

app/view/twig/_base/_listing.twig
src/Storage/ContentRequest/Listing.php
src/Storage/Entity/MagicAttributeTrait.php

[3.4] Reset 'ORDER BY' on pager count queries

---

app/view/twig/files/_files.twig
app/view/twig/files/_folders.twig
app/view/twig/files/files.twig

Use JavaScript context escape for file & directory paths in data-action

---

src/Form/FormType/AbstractUserType.php

Fixes the BC break on username case handling in forms.

[3.4] Add transformer on username field

---

app/view/twig/dashboard/_recently_edited.twig
app/view/twig/dashboard/dashboard.twig

UI BC break in 3.3
… must … not … refactor …

[3.3] Use humanised strings for ContentType names

---

src/Controller/Backend/Records.php
tests/codeception/acceptance/101-BackendEditor/BackendEditorCest.php

Use 'singular_name' instead of slug.

---

app/config/routing.yml.dist

See: https://github.com/bolt/docs/issues/834

Fix incorrect link to Routing docs.

---

app/view/twig/files/_folders.twig

Don't require double confirmation on deleting folders.

---

src/Twig/Runtime/ImageRuntime.php

Fixes #7080.
Before, if debug was disabled, it would just show the "whoops something went wrong", which is not very user friendly. Now it falls back to the pleasant 404 image, while maintaining the exception for when you're in development (debug) mode.

Fixed: Handle images that aren't found a bit more gracefully.

---

src/Helpers/Arr.php

Same change as https://github.com/bolt/bolt/pull/7094 in a different place

Remove import for Deprecated in Arr.php too

---

app/view/twig/_base/_listing.twig

Fixes #7104 
Thanks, @eduardomart

Fixed: Contextual menu in listing should show `singular_name`

---

composer.json

[3.4] Change bolt/requirements to a stable constraint (^1.0)

---

src/Menu/MenuEntry.php

[3.4] Handle parent URIs with query parameters

---

src/Twig/Extension/ImageExtension.php
src/Twig/Runtime/ImageRuntime.php
tests/phpunit/unit/Twig/Runtime/ImageRuntimeTest.php

As requested by @CarsonF in  https://github.com/bolt/bolt/pull/7084#discussion_r144878078

[3.3] Use Twig's debug setting

---

src/Storage/ContentRequest/Edit.php

This change will allow you to do this, for example:
```yml
relations:
entries:
label: "Choose an entry"
format: "{{ item.status != 'published' ? '(Not published) ' : '' }} {{ item.title|escape }} (№ {{ item.id }})"
```

Add 'status' to `querySelectList()`, so it can be used in relations.

---

src/EventListener/NotFoundListener.php

[3.3] Assume front-end zone in NotFoundListener

---

src/Storage/Database/Prefill/Builder.php

Currently, if the **first** ContentType is a singleton then only one record for the remaining ContentTypes was being created.
This moves the logic out of the loop, and hopefully, makes it a bit more obvious — :koala:

[3.4] Move build logic out of loop, and account for first CT being a singleton

---

composer.json
src/Twig/SafeEnvironment.php
src/Twig/SecurityPolicy.php
src/Twig/SetcontentNode.php
src/Twig/SetcontentTokenParser.php
src/Twig/SwitchNode.php
src/Twig/SwitchTokenParser.php
src/Twig/TwigEnvironmentWrapper.php

Just a few more that have had aliases assigned/fixed in the last 6 or so months … otherwise "nothing to see here"

[3.4] More Twig namespaces

---

src/Controller/Backend/Authentication.php
src/Controller/Backend/FileManager.php
src/Controller/Backend/Records.php
src/EventListener/NotFoundListener.php
src/Form/FormType/ContentEditType.php
src/Nut/Init.php
src/Provider/FormServiceProvider.php
src/Provider/PrefillServiceProvider.php
src/Provider/ValidatorServiceProvider.php
src/Storage/Collection/Taxonomy.php
src/Storage/ContentRequest/Edit.php
src/Storage/ContentRequest/Listing.php
src/Storage/Entity/TemplateFields.php
src/Storage/Field/Manager.php
src/Storage/Field/Type/JoinTypeBase.php
src/Storage/Mapping/MetadataDriver.php
src/Storage/Query/QueryResultset.php
src/Twig/Runtime/RecordRuntime.php
tests/codeception/_support/YamlHelper.php
tests/phpunit/unit/Controller/Backend/AuthenticationTest.php
tests/phpunit/unit/Extension/MenuTraitTest.php

A few less squiggly lines in PhpStorm

[3.4] CS clean-up

---

app/src/js/modules/editcontent.js
app/view/twig/editcontent/_aside-save.twig

Fix "save and return" and "save and new" buttons.

---

app/view/twig/_sub/_record_list.twig
app/view/twig/components/panel-lastmodified.twig
app/view/twig/dashboard/_quicklinks-buttons.twig
app/view/twig/dashboard/_quicklinks-dropdown.twig
app/view/twig/editcontent/fields/_meta.twig
app/view/twig/overview/_panel-actions_overview.twig

It is a simple PR.
It is just to improve Content Types readability on the Administration Panel on some templates.

Improve content types titles in some templates

---

src/Provider/WebProfilerServiceProvider.php

Related: #7154
Upstream: https://github.com/symfony/symfony/pull/24851

Revert TwigDataCollector workaround

---

src/Controller/Backend/Authentication.php
src/Controller/Backend/FileManager.php
src/Controller/Backend/Users.php

[3.4] Check form has submitted before valid

---

app/theme_defaults/pager/default.twig

Implements very basic aria roles for pagination in the frontend templates. fixes #6383
Based on http://www.a11ymatters.com/pattern/pagination/

Basic accessibility in pagination

---

app/view/twig/users/_sessions.twig

Fixed: Display username from users, instead of from sessions.

---

src/Storage/Field/Type/TemplateFieldsType.php

This one falls in the same category as #7218.
I bumped into this one when updating a site to 3.4, and the old content had a reference to a `templateselect`'ed template which didn't exist anymore. IMHO, the backend should just "not show the missing templatefields" anymore, instead of breaking with the following cryptic exception:

Fixed: Don't break the backend if a file with templatefields has gone missing

---

src/Controller/Async/General.php

Fixes #7229.
Note: I'm using `json_decode($fetchedNewsData, true)` because it seems that it's dependant on the format of the feed whether or it's an object or an array. Using `true` makes sure we get an array, and the check for `$newsVariable` doesn't break.

Only use `news_variable` from `config.yml`, if it's actually present in the news feed.

---

src/Storage/Database/Prefill/RecordContentGenerator.php

Don't prefill a field with `type: templateselect`

---

app/resources/translations/en_GB/messages.en_GB.yml
app/resources/translations/nl_NL/messages.nl_NL.yml
src/Config.php

Show a friendly warning if fields with consecutive underscores are found

---

src/Storage/ContentRequest/Listing.php

If taxonomy has sortorder then use that in the Backend Overview

---

changelog.md
src/Version.php

Assets are OK, so no rebuild needed on those. 🚢

Prepare release 3.4.4, update changelog.md and Version.php

---

.travis.yml

Slight improvement in Travis runtime as a result.

[Travis] Adjust Composer cache directories

---

src/Storage/ContentRequest/Listing.php

Fix proper sortorders for groupings

---

src/Storage/Field/Type/RelationType.php

The other side of the coin for #7218

Edge-case fix for old, missing relations.

---

src/Controller/Backend/Extend.php

Apply the same fix to resolve the path as in #7267, basically

Use PathResolver to make path relative in Extend controller

---

app/src/js/modules/extend.js
app/src/js/widgets/fields/fieldEmbed.js

- Allow console errors from an extension installation exception
- Assign thumbnail URL

Update core JavaScript

---

app/view/twig/_sub/_messages.twig

[UI] Fix flash message margins

---

composer.json
src/Controller/Backend/General.php
src/Controller/Backend/Users.php
src/Nut/SetupRun.php
src/Provider/ConfigServiceProvider.php

DI `BoltRequirements` and pass `PathResolver`
Maybe a more descriptive service name would be better?

BoltRequirements DI and pass PathResolver

---

src/Twig/Runtime/UserRuntime.php

Fix reference to concrete CsrfTokenManager instead of its interface

Fix reference to concrete CsrfTokenManager instead of its interface

---

src/Storage/ContentRequest/Save.php
src/Twig/Runtime/TextRuntime.php

Fix reference to concrete `Slugify` instead of its interface

Fix reference to concrete Slugify instead of its interface

---

app/config/routing.yml.dist

Quote value to be interpreted as string literal

---

src/Storage/Database/Schema/Builder/ContentTables.php
src/Storage/Database/Schema/Builder/ExtensionTables.php
src/Storage/Database/Schema/Comparison/BaseComparator.php
src/Storage/Database/Schema/Comparison/DiffUpdater.php
src/Storage/Database/Schema/Comparison/IgnoredChange.php
src/Storage/Database/Schema/Comparison/MySql.php
src/Storage/Database/Schema/Comparison/PostgreSql.php
src/Storage/Database/Schema/Comparison/Sqlite.php

These were missed in the rush/stress of getting these out the door initially.

[3.4] Add missing @internal PHPDoc tags

---

src/Storage/Field/Type/RepeaterType.php
src/Storage/Query/QueryParameterParser.php

This adds a missing part of the query syntax which was originally talked about in #6073.
The brief summary is that you can now add subfield parameters to `getContent` searches assuming you are using the new storage engine.
The syntax is as follows:
```php
$res = $app['query']->getContent('showcases', ['repeater' => ['repeattitle'=> '%test%', 'repeatcontent'=>'%testing%']]);
```
By way of explanation. `repeater` is the main field name and `repeattitle` is the sub-field name. The result is that showcase records will only be selected if they have a repeater/repeattitle field that contains `test` _AND_ a repeater/repeatcontent field that contains `testing`.
There are a few limitations in this initial version all of which can probably be improved upon with a bit more time and creativity. 
1. …

Add missing repeater search to query parser

---

src/Storage/QuerySet.php

Something … something … :zipper_mouth_face:

[3.4] Add return early for Postgres sequence look up failures

---

src/Storage/EventProcessor/TimedRecord.php

Fixes #7323
Afaik the code is compatible up to 3.4. I can submit a separate PR to 3.4 if needed.

fix for reset of where conditions in times queries

---

src/Controller/Backend/Authentication.php

Fixes #7320
Added in #6624 and outdated by #7056

Remove outdated cookie clearing logic

---

app/src/js/modules/editcontent.js
app/src/js/modules/extend.js
app/view/twig/editcontent/_aside-preview.twig
app/view/twig/editcontent/_buttons.twig

Update link to "View on site" after save.

---

changelog.md

[Prefix your PR title with [WIP], if it's a 'work in progress', 
or if you're looking for feedback before merging.]
A brief description of the Pull Request goes here. If you haven't yet done so,
please read the 'contributing guidelines' thoroughly. 
See: https://github.com/bolt/bolt/blob/master/.github/CONTRIBUTING.md
Fixes: #1555 (please refer to an existing issue number, that this PR fixes)
Details
-------
Please list any details for the PR, that might be relevant. Some pointers:
- Please include tests with your PR. If you do, we will love you for it.
- Check if the change in the PR is a good fit for Bolt, or if it would be
better off as an extension.
Choosing a target branch
------------------------
Bolt has a branching strategy that follow these rules: 
* `release/3.X` — "stable" …

Update date/year: 2017  -> 2018

---

changelog.md

[Prefix your PR title with [WIP], if it's a 'work in progress', 
or if you're looking for feedback before merging.]
A brief description of the Pull Request goes here. If you haven't yet done so,
please read the 'contributing guidelines' thoroughly. 
See: https://github.com/bolt/bolt/blob/master/.github/CONTRIBUTING.md
Fixes: #1555 (please refer to an existing issue number, that this PR fixes)
Details
-------
Please list any details for the PR, that might be relevant. Some pointers:
- Please include tests with your PR. If you do, we will love you for it.
- Check if the change in the PR is a good fit for Bolt, or if it would be
better off as an extension.
Choosing a target branch
------------------------
Bolt has a branching strategy that follow these rules: 
* `release/3.X` — "stable" …

Update date/year: 2017 -> 2018

---

src/Nut/UsersList.php
src/Provider/NutServiceProvider.php
tests/phpunit/unit/Nut/UsersListTest.php

Nut command to list all users

---

src/AccessControl/AccessChecker.php
src/AccessControl/Login.php
src/Storage/Repository/AuthtokenRepository.php

Fixes #7355
:egg: :koala: :beers:

[3.4] Be consistent with session & IP address handling
