app/view/twig/editcontent/fields/_select.twig

Fixes #5517.
The valuefield is the last one, not the first one, and we can't assume that `lookupfieldlist` is set so, unfortunately we need some defaultception until this code is rewritten.
Also prevents certain twig errors in some cases because of that defaultception.

(In select fields with content values) the valuefield is last and defaultception

---

src/Storage/Query/ContentQueryParser.php
src/Storage/Query/Directive/GetQueryDirective.php
src/Storage/Query/Directive/HydrateDirective.php
src/Storage/Query/Directive/LimitDirective.php
src/Storage/Query/Directive/OrderDirective.php
src/Storage/Query/Directive/PagingDirective.php
src/Storage/Query/Directive/PrintQueryDirective.php
src/Storage/Query/Directive/ReturnSingleDirective.php

This isn't an issue, just a refactoring. This could break V3 extensions if they extend upon any of the current directives.
The purpose of this is to separate the logic from `Handlers` and `Directives`. I think the two should be split up since they do different things. Here are my definitions of `Handlers` and `Directives`:
*Handlers* - Short segments of code that execute queries AND returns data from the db
*Directives* - Short segments of code that manipulate queries
Thoughts?

[FEEDBACK] Separated `Directives` from `Handlers`.

---

src/Storage/Entity/ContentRouteTrait.php

Fixes #5466
I took out the taxonomy based routing because as far as I can tell it hasn't worked in 2.2 or 3.0 (tried with tags and groups, seems to not have worked for quite a while), but if there is some quick way to get it to work or if I'm wrong then please let me know.

Fix attempts to access values via $this->values in storage

---

src/Storage/Mapping/ContentTypeTitleTrait.php

Prevents errors like `An exception occurred while executing 'SELECT id, as title FROM bolt_kommentarer kommentarer': SQLSTATE[HY000]: General error: 1 near "as": syntax error`. in relations in editcontent when bolt can't find a column to use as title.

Always return something in getTitleColumnName

---

composer.json
src/Nut/DatabaseCheck.php

This relates to Issue 5995 - implemented an option for database:check
which will cause the database statements to be output on the console
with nut.
Changes include:
- Adding jdorn/sql-formatter to composer, so that queries are more
legible
- Making changes to DatabaseCheck, to add the new option and outputs.
Future enhancement could include using the SqlFormatter class within the
web backend to achieve formatting and colourized output in
/dbcheck?debug=1.  Unfortunately, I'm not good enough with the way Twig is used in the backend to get that integrated.

Implement a new option in nut's database:check

---

src/Storage/CaseTransformTrait.php
src/Storage/Entity/MagicAttributeTrait.php
src/Storage/Field/Type/FieldTypeBase.php
src/Storage/Mapping/MetadataDriver.php
tests/phpunit/unit/Storage/EntityTest.php

This is a feature that will improve the code consistency when accessing and setting attributes on an entity.
It separates the db column name eg:`bolt_field_example` from the entity attribute `boltFieldExample` and defaults to underscores for the db column but camel case for the entity attribute.
This means that extension developers making their own entities can now use camel case for attributes without needing to match the format of the database column.
Test included for new functionality, updates to the internal entities to use this new syntax will follow in a separate PR.

Add support for separate entity attribute, versus db column names.

---

app/src/sass/editcontent/_field.scss

The color of the input.title elements is set to a dark gray. With dark desktop themes, the default background color of input elements is often a similar shade, resulting in nearly-illegible text 
This commit explicitly sets the background-color of the input.title elements to a more suitable color, overriding any default styling:

Avoid dark-on-dark text by explicitly setting background-color

---

app/src/js/widgets/buic/buicListing.js
src/Legacy/Storage.php

Fixes #5085 and #5468
This does two things:
1. check if the request is safe (status change) or unsafe (delete) in listing actions and only ask the user to confirm if it is unsafe.
2. Allow unpublished records in the async zone, since all async routes are also backend routes (right?) and should therefore show unpublished too.
Since it's a bugfix I targeted release/3.0, lemme know if this should go in 3.1 instead.

Fix backend publish process quirks (#5085)

---

src/Storage/Repository.php
tests/phpunit/unit/Controller/Backend/LogTest.php

Minor fix to return an iterable empty array rather than false from the result of a `findWith` query.
Fixes: #5555

Return an empty array rather than false from findWith

---

tests/phpunit/unit/Storage/Query/QueryFieldDelegationTest.php

This test had potential to not be useful since the added taxonomy was random and the count was more likely to be zero than predictable.
This forces the taxonomy to be added to two records so the test can behave predictably.

Fix to inconsisten test behaviour

---

src/Twig/TwigExtension.php
tests/phpunit/unit/Twig/TwigExtensionTest.php

Listcontent was removed in https://github.com/bolt/bolt/commit/66a21490ea9a38ee5a37e1cf2f9c44bfb99c6045 but still remained in TwigExtension. This removes that and the associated test.
~~Still, I have no idea why tests were passing while the test in TwigExtensionTest was still there, can anyone enlighten me?~~ Ah, I see it now. The test didn't actually test anything.
See #5628

Remove the last references to listcontent

---

app/view/twig/editcontent/fields/_select.twig

This fixes an issue raised in slack, caused by a pretty huge derp from me (I think?).
basically, having multiple fields as the value in a select field didn't work. I think it's been buggy for a while  (since #5407 I think, but not sure), and it seems like #5587 basically made it break always instead of sometimes...
This file really needs a refactor, too... Almost all of this should be in php IMO.

Fix issue with multi-value value selects

---

app/view/twig/editcontent/fields/_repeater-group.twig
app/view/twig/editcontent/fields/_repeater.twig

This addrresses a bug whereby HTML fields in repeaters would fail if they appear early in the order before ckeditor initialisation has happened.
Fixes: #5596

Bugfix for HTML fields inside repeaters

---

src/Twig/Handler/ImageHandler.php

In some cases, the `Reader` return `false` and of course, the rest of the method cant work cause it try to use `$exif` as an object but it is a `boolean`.
Only an error on `2.2` cause the method is changed on `3.0`.

Fix ImageHandler imageInfo method for some rare cases.

---

src/Asset/Widget/Queue.php

This PR fixes two issues related to deferred widgets:
- It makes deferred widgets work in the backend
- It prevents deferred widgets from being rendered twice (once during the initial request, and again when fetched ajaxy)

Fix two issues with deferred widgets.

---

src/Storage/Collection/Relations.php

Fixes part of #5636, where intra-contenttype relations will show as related to themselves.

Incoming relations must be checked with both contenttype and id.

---

app/view/twig/editcontent/_relations.twig
app/view/twig/editcontent/fields/_relationship.twig
src/Storage/Collection/Relations.php
src/Storage/Field/Type/RelationType.php

Fixes #5636 and (in my testing at least) #5541.
This makes bidirectional relations work as they did in 2.2 (one could show/delete relations from either record if they both had the relation defined), fixes intra-contenttype relations, and also introduces a number of checks to make sure that multiple relations on the same contenttype don't affect one another.

Fix bidirectional relations and relations affecting each other

---

src/Controller/Backend/BackendBase.php

Modify `checkFirstUser` to check for a valid logged in user, to prevent expensive test. 

---

src/Controller/Frontend.php

Logged in users, and pages using forms won't use cached pages.

If session started, don't set the response to public

---

src/Storage/Entity/ContentValuesTrait.php

This is done very much like https://github.com/bolt/bolt/commit/e28c253ad5d07f07c75f896a41c8634099071e8d in #5542, so hopefully this is mostly correct.
I've tested that it works with multiple repeaters in the same templatefields and that normal repeaters are uneffected.
This also removes the `populateTemplateFieldsContenttype` call since that method was removed in 	2f28f16 in the original template specific fields PR.

Hydrate repeater in templatefields

---

app/resources/translations/en_GB/messages.en_GB.yml
src/Config.php
src/Controller/Backend/BackendBase.php
src/Storage/Collection/Taxonomy.php

Fixes #5673
In taxonomy slugs we basically allow any character (since we do not slugify them). One way to test this is to add a tag with a bunch of special chars or with a taxonomy like this:
```yaml
categories:
name: Categories
slug: categories
singular_name: Category
singular_slug: category
behaves_like: categories
options: {'test&%¤': test}
```
The only character that we cannot use or have is a slash since that denotes a separation of url portions.
This PR removes any slash found in a taxonomy slug (since that's how we do it in record slugs) and shows a warning flash message if a slash is put in a slug in taxonomy.yml.
PRing into 3.0 since this is a bug fix, let me know if I should retarget to 3.1.

Fix slash in taxonomies

---

app/resources/translations/en_GB/messages.en_GB.yml
src/Controller/Backend/FileManager.php
src/Filesystem/UploadContainer.php
src/Provider/UploadServiceProvider.php
tests/phpunit/unit/Controller/Backend/UploadTest.php

@CarsonF pointed out that doing this check during the service construction creates a two+ requests for the filesystem … which on local is no big deal, but on remotes like S3 it's a different story.

Upload exceptions

---

src/Provider/SessionServiceProvider.php

- Fixes parsing url (`save_path`) when scheme is omitted, by defaulting it.
- Prevent `save_path` for a different `save_handler` from bleeding into options.
- Use default connection if not specified with `save_path` or `connection(s)`.

More session save_path bugfixes

---

src/Storage/Repository/UsersRepository.php
tests/phpunit/unit/Storage/Repository/UsersRepositoryTest.php

For the record, I am 1,000% **against** this being done in core.
Nonetheless this implements the database check for the username case-insensitively.
Closes #5695

Case-insensitive username lookup at login

---

src/AccessControl/Login.php
tests/phpunit/unit/AccessControl/LoginTest.php

.. because at this point we don’t know yet if the account is enabled, only that the user wasn’t fetched. To keep the notice vage, we should return the generic “username or password incorrect”.

Show correct error message.

---

src/Storage/Entity/ContentRouteTrait.php
src/Storage/Entity/ContentTaxonomyTrait.php

This reintroduces taxonomies in contentlinks which was ripped out in #5593 because it seemed to not work. It contains one case for legacy and one for the new storage as opposed to the old one removed in 5593 which only worked in legacy. The issue was reported on slack by techwilk.
Example route:
```
category:
path: /{groups}/{slug}
defaults:
_controller: controller.frontend:record
contenttypeslug: pages
groups: none
requirements:
groups: [ controller.requirement:singleTaxonomy, [groups] ]
contenttype: pages
```

Allow taxonomies in contentlinks again

---

app/config/config.yml.dist

While nice for a small amount of people, the redirection will change the route, disabling `F5`'s practicality when stepping though a problem.

Default profiler exception redirection to false

---

src/Routing/CallbackResolver.php

When loading `routing.yml` if a controller is referenced that doesn't have `before` and `after` methods, an exception would be thrown. This fixes that to just do nothing in those cases.

Fix loading controllers without before/after middlewares

---

app/bootstrap.php

.bolt files should be allowed to specify application as string. This fixes the check to ensure the string is a class name that extends Silex\Application.

Fix .bolt being allowed to specify application as string

---

.htaccess

[WIP] Removes index.php from urls. Nginx would need documentation done for bolt.cm/docs.
Fixes URL'ls like:  
https://site.com/index.php  -> https://site.com
https://site.com/index.php/page/zenonis-est-inquam-hoc-stoici -> https://site.com/page/zenonis-est-inquam-hoc-stoici
Fixes: #5578
Details
-------
I don't know, or think at least that the part dealing with http authorization would be needed by bolt. I don't think it does but I left it there because I don't know haha. Figured you all would be better suited to determine that. 
```
RewriteCond %{HTTP:Authorization} .
RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]  
```

[WIP] removes index.php from URL's for #5578

---

src/Storage/Repository.php

Small fix to ensure there's always an entity param passed into storage events even if it sometimes isn't the subject.
Fixes #5692

Ensure entity is always named as a parameter in storage events

---

app/config/config.yml.dist

Hi,
while creating my first bolt project i noticed that the link in the config.yml which should list the available locales is 404-ing.
PS: For what it's worth, i don't like brown M&M's 😂

fix link to available locales

---

app/bootstrap.php

Credit to @helman for this one.
Fixes #5725

Allow use of string class names in app bootstrap

---

app/src/sass/modules/_bolt.scss

Fixes #5715
This selector was catching the tooltip arrow too.
In the end we'd probably want to not use any of these generic selectors, but this should be "good enough for now™".

fix too generic selector in filescreenuploader

---

src/Config.php

With this line present, Bolt will fall back to 'page/1' as the homepage, regardless of whether it exists or not. This is black magic, because to the end user it's not clear at all why this happens, if you explicitly _remove_ `homepage:` from your `config.yml`.

We shouldn't assume 'page/1' is the homepage.

---

src/Controller/Async/General.php

Fixed: Add `'name'` to query to fetch popular tags, to prevent SQL error.

---

src/Configuration/ResourceManager.php
src/Filesystem/Plugin/PublicUrl.php

Fixes: #5759, until a better solution lands.

Fixed: Files without recognised extensions don't break the file browser. 

---

src/Controller/Async/General.php
tests/phpunit/unit/Controller/Async/GeneralTest.php

Fixed Guzzle options and made them work with other handlers besides cURL. Caching errors as well so each request doesn't have to wait 10 secs if the server is down. Cleaned up method with early returns.
The only thing I'm not sure about is proxy option. Specifically if `general/httpProxy/host` has a `http://` prefixed or not and if it's needed in final string. Can someone with a proxy test? Either way it was broken before so this wouldn't introduce a break to that.

Fix dashboard news timeout

---

app/view/twig/exception/_trace.twig

add "is_defined" check to be compatible with strict_variables: true
else it breaks badly !

add compatibility with strict_variables params

---

src/AccessControl/Password.php

( and this is fixing the bolt backend forget password feature )

get the passwordreset.twig content instead of the bolt Response

---

app/bootstrap.php
src/Composer/ScriptHandler.php

As discussed in #5729 Check for alternative non-dot versions of `.bolt.yml` and `.bolt.php`.
There's an additional minor improvement here and that allows a `bolt.php` file to just return a pre-constructed application rather than array. This is optional but simplifies the flow of php bootstrap files that will normally take care of creating an instance of `Bolt\Application`.

Update bootstrap to check non-hidden config files

---

app/src/package.json

An upstream fix makes [grunt-eol](https://github.com/psyrendust/grunt-eol) install on windows again.
PS: The two remaining ones with grunt v1.0 problems (``grunt-phpdocumentor`` and ``grunt-remove``) have pull requests in the pipeline but seem somewhat abandoned. As a workaround you can use ``npm`` v3 to turn the install error into a warning.

Bumping grunt-eol to v1.1.3

---

src/Storage/ContentRequest/Edit.php

Fixed: Don't display 'ungrouped' tab, if no groups are defined.

---

src/Storage/Entity/ContentValuesTrait.php

Fix some warnings, if an image field is defined, but not set up yet. See screenshot:

Fixed: Check for existence of `$this->values[$key]` to prevent warnings.

---

app/view/twig/editcontent/fields/_text.twig
app/view/twig/editcontent/fields/_textarea.twig
src/Storage/Field/Type/FieldTypeBase.php

Hopefully this fixes #5795, only add a default value on real null values, not if we've replaced with an empty text field.

In fields, only apply the default to an actual null value

---

app/config/contenttypes.yml.dist

The current link doesn't link to any relevant information. I believe https://docs.bolt.cm/contenttypes/intro this is the correct link for more information about `contenttypes`.

Updated docs link..

---

src/Composer/ScriptHandler.php

This PR is part of #5752
When running `composer create-project`, all default choices result in default locations for the files and folders. The last question feels like it's the other way around: The default option overwrites the existing `.gitignore` with the one from `bolt/bolt`, instead of keeping the one in `bolt/composer-install`. 
I'd like 'n' to be the default, so that this is what it does when running the packaging script for the "end users".

[RFC] Set the 'default' choice to overwrite the .gitignore to 'no'.

---

app/config/config.yml.dist
src/Config.php
src/Provider/ThumbnailsServiceProvider.php
src/Twig/Handler/ImageHandler.php
theme/base-2016/theme.yml

Changes to the default configuration and to the twig filters image and thumbnail to allow aliases for image resolutions as discussed in #3703. 
The new config value `restrict_alias` is set in all the old style `$app["myconfig param name"] things in the providers to keep it in line with current code. **But** the code will only use the $app->["config"]->get()` methods to access them like the new code does.

Bolt changed to make image aliases work #3703

---

src/Storage/ContentRequest/Save.php
src/Storage/Field/Type/TemplateFieldsType.php
src/Twig/Handler/HtmlHandler.php
tests/codeception/_support/AcceptanceHelper.php
tests/codeception/_support/WorkingSilex.php
tests/codeception/acceptance.suite.yml
tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php
tests/codeception/acceptance/102-BackendDeveloper/BackendDeveloperCest.php
tests/codeception/acceptance/105-BackendLemmings/BackendLemmingsCest.php
tests/codeception/acceptance/AbstractAcceptanceTest.php
tests/codeception/extensions/CodeceptionEventsExtension.php
tests/scripts/run-codeception-tests

This is a back port of the Codeception changes from #5836 
These changes do not affect production, only acceptance tests, with the exception of two small changes to _not_ fatal during debug/test if fields are not included in a POST.
…and one small assassination of a super global.
Obviously 99% of the work on this was @CarsonF … so props there :+1:

Codeception fixes backport

---

app/config/config.yml.dist
src/Application.php
src/Config.php
src/Configuration/Validation/Apache.php
src/Controller/Exception.php
src/Provider/DumperServiceProvider.php
src/Provider/EventListenerServiceProvider.php
src/Provider/TranslationServiceProvider.php
src/Provider/TwigServiceProvider.php
src/Session/Handler/FilesystemHandler.php
tests/phpunit/unit/Provider/TwigServiceProviderTest.php
tests/phpunit/unit/Twig/Handler/UtilsHandlerTest.php

The idea here is to not assume Bolt is configuring the system, but that it is a part of something bigger. So instead of applying defaults from our config, we don't set them if they aren't provided.
These config values are:
- debug
- error_level
- timezone
- locale
- twig's strict_variables
Tweaked `dump()` (PHP function, not Twigs) so it won't dump anything if debug is false.
Changed most of our event listeners to check if they are set before subscribing them. This way they can be disabled by unsetting them.
If debug was disabled we had a hardcoded error_level we set: https://github.com/CarsonF/bolt/commit/d116895fdfcbd5ebde336e862be997a8e9507359. I made this configurable with a new config key, `production_error_level`. It's disabled by default though, since we want to assume the system …

Less assumptions for configuration

---

app/view/twig/exception/exception.twig

Fixes #5714 (at least, we think it does)

Fixed: No `extends` in exception handler template, because we're not sure we have `{{ app }}` yet..

---

src/Extension/StorageTrait.php
src/Storage/EntityManager.php
src/Storage/Mapping/MetadataDriver.php
src/Storage/Repository/ContentRepository.php

Please look this PR carefully because it allows great things :)
I'll try to explain my best ( even if it's quite long ) what I tried to do and how I came to that PR
What was I trying to achieve without success before this PR : 
I wanted to be able to use contenttype.yml to define a content type, for example "races"
and defined many fields in it... 
Using contenttype.yml is a "must have" because we can then use the existing backend controllers to do all the CRUD stuff.
Then I wanted to be able in my own extension to define a custom repository to manage advanced operations ( custom select / update queries ) on "Race" entities which was extending Bolt\Storage\Entity\Content.
Details
-------
The normal way to define a repository mapping in our own extension is using : 
```
protected function …
```

adjust alias resolve logic to be able to use a custom repository with  a custom entity using contenttype.yml to define fields

---

src/Composer/JsonManager.php
src/Config.php
src/Extension/ConfigTrait.php
src/Helpers/Arr.php
src/Storage/Migration/Import.php
tests/phpunit/unit/Helper/ArrTest.php

- Added `Arr::replaceRecursive` which handles lists smarter than `array_replace_recursive`
- Added `Arr::isAssociative` and `Arr::isIndexed` - this one catches a couple edge cases.
- Deprecated `Arr::mergeRecursiveDistinct` and `Arr::isIndexedArray`

Fix Config parsing lists

---

src/Storage/Field/Type/CheckboxType.php

The current CheckboxType Field was under the hood using the "String" Storage Type ... but the (Mysql) database column tied is 'tinyint (1)' ( ie : boolean )... If we use 0 / 1 as value it's working but ... if we use true or false it's not working because it tries to convert 't' or 'f' to tiny int ... 
Moreover, according to doctrine doc, [the boolean field type seems supported by all DB engines](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrix) 
( please dont ask me why i'm using true or false instead of 0 or 1 :) )
I tried to persist a new content type with a checkbox type field using the boolean storage type it's working ... but I did not try with sqlite.

switch checkbox field storage type from "string" to "boolean"

---

app/view/twig/editcontent/_aside.twig

Fixes the display of the aside delete button on editcontent views for 'editor' user roles. `isAllowed` is checking for a slug, legacy Content, or a string.

fix context for isallowed permissions check

---

src/Config.php
src/EventListener/ConfigListener.php

If theme file is not valid with the cache, the cache is invalidated but the file isn't loaded to cache new data. After that the cache file is rewritten with the old data. So the new data in theme file is never picked up. This fixes that.
/ping @GawainLynch

Fix theme.yml cache

---

app/view/twig/exception/_request.twig
app/view/twig/exception/_trace.twig
app/view/twig/exception/exception.twig
src/Controller/Exception.php

- Add a 'Google this exception' button. 
- Shows correct line numbers in snippet
- Abbreviates the classname of the Exception that was thrown
- Should fix the failure if `Request` doesn't exist (yet), as reported by @CarsonF (see #5891)

Fixes and Tweaks to exception page.

---

app/src/js/modules/ckeditor.js
app/src/js/modules/liveeditor.js
app/src/js/modules/utils.js
src/Legacy/Content.php

- Don't parse Twig for live editor as it saves the compiled HTML.
- Set Twig syntax as protected source for CKEditor.
- Handle protected source in live editor.
- Fix JS error when switching CKEditor to source view. Credit to @dadaxr.

Fix twig in live editor

---

app/src/js/modules/ckeditor.js

This can still be opt in, but I don't feel like it should be default.
@bobdenotter - as we discussed.

Revert 94ecd7e as it hides twig in ckeditor view.

---

src/Provider/StorageServiceProvider.php
src/Storage/EntityManager.php
src/Storage/Repository/ContentRepository.php

Fix a bug introduced with : [PR 5862](https://github.com/bolt/bolt/pull/5862)
All the Repositories extending the ContentRepository must have (for now) a "LegacyService" configured to handle correctly "Content Entities" ( content entities defined with the contenttype.yml file )
The previous PR was not always  setting that legacy service and it could (not always) end up with a bolt exception page when editing a content with the default backend UI.
This PR just ensure that the legacy service is set when retrieving a repository.

Set LegacyService for all Repo extending ContentRepository

---

src/Controller/ConfigurableBase.php

- Fix middleware array definitions and strings with `classname::method` and `service:method`.
- Fix default middleware definition, `::before`, with controller that is class name string with an `__invoke` method.

Fix edge case bugs with routing.yml

---

app/view/twig/editcontent/_relations.twig

This fixes a problem where the custom fields cannot be displayed when setting the group of a field to `relationships`.
``` yaml
my:
fields:
foobar:
label: Foo Bar
type: checkbox
group: relations
```

Show custom fields in "Relationships" tab

---

composer.json
src/Provider/LoggerServiceProvider.php

A lot of xdebugging Composer later … Credit to @CarsonF for the SP changes
This was the error:
```
> Bolt\Composer\ScriptHandler::installAssets
[Symfony\Component\Debug\Exception\FatalThrowableError]  
Call to a member function findFile() on string           
Exception trace:
() at [snip]/vendor/symfony/debug/DebugClassLoader.php:168
Symfony\Component\Debug\DebugClassLoader->loadClass() at n/a:n/a
spl_autoload_call() at n/a:n/a
class_exists() at [snip]/vendor/silex/silex/src/Silex/Provider/MonologServiceProvider.php:34
Silex\Provider\MonologServiceProvider->register() at [snip]/vendor/silex/silex/src/Silex/Application.php:178
Silex\Application->register() at [snip]/vendor/bolt/bolt/src/Provider/LoggerServiceProvider.php:82
Bolt\Provider\LoggerServiceProvider->register() at …
```

Fix installAssets Failure

---

tests/phpunit/unit/Configuration/ResourceManagerTest.php

Fixes #5913
I dropped the static app test, as it was problematic, has been deprecated since 2.1, and if you're using it and something breaks … you can keep both pieces … time to move on.

[Tests] Reset config files, and drop static test

---

app/config/config.yml.dist
src/Config.php
src/Controller/Exception.php
src/EventListener/ExceptionListener.php
src/Provider/EventListenerServiceProvider.php

The profiler page was a nice idea, but it remove the ability to just refresh the page and attempt next step debugging.
Also, for a number of us, having the stack trace at the bottom of the page means we have to modify the bootstrap to disable Bolt's exception handler as it is just too much scrolling every few page refresh and not suitable for the BEs.
So this give the "pretty" crowd what they needs, and the rest of us can just fallback to Symfony.
Also, I don't want to go into RC and lock in BC on this.
Ping @CarsonF

[3.2][RFC] Switch profiler target option to Symfony's target

---

src/Storage/ContentRequest/Edit.php

Fixed: Optional `order` in relationship shouldn't throw an exception.

---

src/Storage/Database/Schema/Builder/ContentTables.php

I'm guessing this bug was us depending on unsupported behaviour, but in recent DBAL versions the  type is no longer standardised to the `getName()` value of the Type.
This was manifesting itself in custom fields where a `getStorageType()` is specified.
Hopefully fixes the issue at: https://github.com/nbehier/bolt-field-geojson/issues/9

Standardise the Doctrine Types used by custom fields

---

src/EventListener/StorageEventListener.php
tests/phpunit/unit/EventListener/StorageEventListenerTest.php

Handle user entity pre-save events very early to mitigate passwords not being hashed if another event stop propagation
Fixes #5947

Handle user entity pre-save events very early to mitigate passwords not being hashed if another event stop propagation

---

src/Config.php

Fixes #5961 
Note: We don't have to check for the case where _both_ `name` and `slug` aren't set. That's already handled here: 
https://github.com/bolt/bolt/blob/hotfix/set-name-from-slug-if-not-defined/src/Config.php#L545-L554

If `name:` or `singular_name:` isn't set in 'contenttype.yml', generate something semi logical from the slug.

---

src/Configuration/ConfigurationValueProxy.php
src/Storage/Mapping/MetadataDriver.php

This is a problem that was papered over by the fact we always used to write the slug back to the contenttype key. This behaviour was removed in #5939 and so this nasty little bug revealed itself.
We were using the table alias, rather than the original contenttype name to load in the contenttype structure to the entity, so in cases where they differ this was incorrect.
The main difference here is that we consult the original `contenttypes.yml` data to find the key for a given table alias, no longer assuming they are the same.
Fixes #5965

Fix Issues Caused By Slug/Key inconsistencies

---

src/Storage/Mapping/MetadataDriver.php

Use the contenttype name not the tablename to register an alias.
Fixes #5960

use the contenttype name, not the tablename

---

src/Controller/Frontend.php

This makes it so that listing_records and sort in a CT takes precedence over theme.yml, just like with record_template, listing_template and so on.

fix listing_records and sort in theme.yml

---

app/view/js/bolt_exception.js
app/view/twig/exception/_trace.twig
app/view/twig/exception/_tracedumps.twig
app/view/twig/exception/exception.twig

I've moved the trace nearer to the top of the page (by request). The actual `dump()`s of the arguments are loaded _after_ the rest of the page, and injected into the trace after loading. The result is a page, that appears on screen much sooner.

Change order on exception page, and show page before dumps have loaded.

---

src/Storage/Repository/FieldValueRepository.php

Related to PR #5976, but for frontend.
In this case repeater fields were ordered by some id, which is subject to change on repeater field update.
Ordering by grouping ensures everything is displayed properly.

fix order of content repeater fields in frontend

---

app/config/routing.yml.dist

Removes the routing examples that do not work since a while back. fixes #5211 and see #5593 for context.

Remove record taxonomy based routes from example

---

app/config/config.yml.dist
src/Config.php
src/Cron.php
src/EventListener/AccessControlListener.php
src/EventListener/StorageEventListener.php
src/Events/CronEvent.php
src/Provider/StorageServiceProvider.php

This makes the parameters for timed publishing checks independent of caching.
**[RFC]**
This PR introduces the `performance` configuration key, as a grouping for these types of parameters, with a sub key of `dispatchers` … thoughts on naming?
These should be considered advanced user territory.

Timed publish tweak

---

composer.json
src/Twig/FilesystemLoader.php
tests/phpunit/unit/Twig/SetcontentTest.php

Lesson leared today, read the darn changelog :wink:

Fix for Twig ^1.27

---

src/AccessControl/AccessChecker.php
src/AccessControl/Login.php
src/AccessControl/Token/Generator.php
src/AccessControl/Token/Token.php
src/Provider/RandomGeneratorServiceProvider.php
src/Security/Random/Generator.php
src/Session/Generator/RandomGenerator.php
tests/phpunit/unit/AccessControl/TokenGeneratorTest.php
tests/phpunit/unit/Session/RandomGeneratorTest.php

In an effort to get PHP 7.1 a happening thing, and per RFC #5893 … removal of `RandomLib` use in core.
This PR maintains a service under `$app['randomgenerator']` for BC. 
There is a corner-case BC break with this PR, where someone is type hinting on the service itself, which would be pretty rare. 
```
use RandomLib\Generator;
```
to:
```
use Bolt\Security\Random\Generator;
```
In the case of a fully namespaced function hint:
```
function foo(\RandomLib\Generator $generator)
{
}
```
to
```
use Bolt\Security\Random\Generator;
// …
function foo(Generator $generator)
{
}
```
Would generally suffice.

[3.3] Replacing RandomLib

---

src/Storage/Field/Sanitiser/Sanitiser.php

Fixes: #6005
Details
-------
Our sanitiser inserts HTML entities for non-correctly used ones when saving user input to the database. For example, `Foo & Bar` becomes `Foo &amp; Bar`.
With this fix: 
`Foo & Bar` stays `Foo & Bar`.
`<b>Foo &amp; Bar</b>` stays `<b>Foo &amp; Bar</b>`.
`<b>Foo &amp; Bar & Baz</b>` becomes `<b>Foo &amp; Bar &amp; Baz</b>`.
This fix checks if the input contains improperly encoded `<`, `&`, etc., and reverts the cleanup on these. This just applies to sanitising just before fields of type `text`, `html`, `textarea` and `markdown` get inserted into the DB only.
@CarsonF I've gone over this with @GawainLynch. If you have a better solution, i'm all ears. For now, this seems to fix it, and it's pretty much contained.

Prevent encoding of entities "On save" in text fields.

---

src/Storage/Field/Type/RepeaterType.php

PR fixes a notice and warning caused by all repeater fields.
Notice: Undefined index: fields in C:\MAMP\htdocs\nuffieldtrust.org.uk\vendor\bolt\bolt\src\Storage\Field\Type\RepeaterType.php on line 86

Fix for Notice and subsequent warning related to repeater fields

---

src/Provider/ThumbnailsServiceProvider.php

Readded two missing config values for the thumb-aliases change already integrated into 3.2.
These got "lost" somewhere down the git train, no clue why.

readded missing alias config and default sizes

---

src/Nut/ExtensionsSetup.php
src/Provider/NutServiceProvider.php
tests/phpunit/unit/Nut/ExtensionsSetupTest.php

This re-adds Nut's extension:setup command, minus the local extension ~~mess~~ functionality

Re-add extension:setup command

---

src/AccessControl/Password.php
src/Asset/Widget/Queue.php
src/Configuration/Check/EmailSetup.php
src/Controller/Backend/General.php
src/Controller/Backend/Users.php
src/Debug/ShutdownHandler.php
src/Nut/Extensions.php
src/Provider/AssetServiceProvider.php
src/Twig/SetcontentNode.php
src/Twig/SetcontentTokenParser.php
src/Twig/SwitchNode.php
src/Twig/SwitchTokenParser.php

* Switch choices key/values around and set choices_as_values to true
* When upgrading to Symfony 3, we'll need to remove choices_as_values
* Don't catch **errors** (still catching exceptions) on CLI
* Update Nut extensions command
* Remove use of `Bolt\Render` where a `BoltResponse` is neither needed nor appropriate
* Only use `Twig_Node`s for `setcontent` where parameters
* Remove deprecation from `SwitchNode` and fix a bug

Upstream deprecations

---

src/Storage/Field/Type/RepeaterType.php

Credit to @Maelstromeous for finding this one.

When saving field values for repeaters, do not trigger additional events.

---

src/Storage/Field/Type/RelationType.php
src/Storage/Field/Type/TaxonomyType.php

Similar to the last PR, same issue was occuring with saves on taxonomies and relations. Any manipulation should be handled from the master entity so these events should be suppressed.

Silence events when saving relations and taxonomies

---

src/Storage/Entity/Content.php
src/Storage/Field/Type/RelationType.php

This fixes an inconsistency with how the relation collection is hydrated.
At the moment if you call `$entity->getRelation()['entries']` you get pointers to the actual entry entity whereas if you call `$entity->getRelation('entries')` which is the preferred method you get a collection of the actual `bolt_relation` entities which is not expected behaviour.
This PR standardises these cases and also does the same for the shorthand access of `$entity->getEntries()`

Fix relation collection hydration

---

src/Storage/Query/Handler/SelectQueryHandler.php
src/Storage/Query/SelectQuery.php

Fixes #6050
This adds a fix for this kind of getContent query: `$app['query']->getContent(('pages','events','reports'), ['tags' => 'soapbox']);` to handle the fact that one or more of the contenttypes may not have a tags field, if that is the case, the contenttype returns zero results rather than carrying on and performing a query.

Fix queries on multiple content types

---

src/Application.php

The parameters passed to http_cache.options must always be an array, cached config can cause an exception to be thrown

HTTP cache options

---

app/view/twig/components/panel-activity-system.twig

Fix for issue #6069 
There is HTML in the logs that gets displayed.

Output the log.message as raw as the logs contain HTML.

---

src/Provider/TwigServiceProvider.php

Fixes #6090
Add the missing Twig functions `{{ absolute_url() }}` and `{{ relative_path() }}` in the process.
Aiming at 3.2 as this is definitely a bug due to oversight on the `\Symfony\Bridge\Twig\Extension\AssetExtension` constructor.
c.f. http://symfony.com/blog/new-in-symfony-2-7-the-new-asset-component#template-function-changes

Add missing HttpFoundationExtension Twig extension

---

app/src/sass/modules/custom/_select2.scss
app/view/twig/editcontent/fields/_select.twig

Fixes empty multiple & sortable select fields to have blank item, by preventing bogus items in array.

---

composer.json

This is the same as we use for the Composer installs … and would prevent PHP 8 until we know what that is, and that we can support it :-)

Use consistent semantics for PHP version

---

app/src/sass/modules/custom/_select2.scss
app/view/twig/editcontent/fields/_tags.twig

Fixed: Don't stretch tags to full width

---

app/view/twig/activity/systemlog.twig

Nicer listing overview for System Log.

---

src/Storage/Query/Handler/SelectQueryHandler.php

This PR should fix #6115.
We've added a check to `$valueSelect` to make sure it is a string. If not, we set the `$stack` empty. This is to prevent calling `preg_split()` on `$valueSelect` in the situations where it is an object.

Fix for #6115: Added a check on $valueSelect to see if it is a string. 

---

src/Storage/Field/Type/FieldTypeBase.php

Handles an inconsistency in the result from the JSON parser across 5.x and 7.x of PHP whereby empty strings give different results.

Fix json parse inconsistency

---

app/src/js/modules/secmenu.js

This is a fix for a problem that we saw with our nested content and very long templates here at Curriculum Associates.  It's probably not a pressing problem for users of more "average" sites, but still the performance improvement is there in case you need it.
The problem stems from the first line of the function.  It sets the sidebar height to zero (actually goes to 16), which means that the "old" height and the "new" height will never match.  So it's always adjusting the sidebar every 300ms.  Over the summer I saw a tab peg out at around 80-90% usage of the CPU for that tab.  More recently it's been better behaved, but under the old code I still got it to peg out at about 30% (and stay there) just yesterday.
Under the new code, the steady state usage is about 3%.  That's because it uses …

Fix adjustSidebarHeight so it's not adjusting when it shouldn't

---

src/Legacy/Storage.php

This PR fixes #6109 
I put the searched fields and the input in a _LOWER()_ sql function. That way, the search is now case insensitive on every platform.
Lowering the input string might be seen as double job because the string is already lowered in PHP. I see it more like a double security. I let you to remove one the php or sql part if you think it'd be better.
Note that I worked in the Legacy Storage class, not sure if the non-legacy search is yet in use and how to fix it too.

Fixes #6109 - Make content search case insensitive on every platform

---

src/Controller/Backend/General.php
src/Debug/Caster/TransparentProxyTrait.php
src/EventListener/ConfigListener.php
src/Legacy/Content.php
src/Provider/DumperServiceProvider.php
src/Provider/TwigServiceProvider.php
src/Twig/ArrayAccessSecurityProxy.php
src/Twig/DumpExtension.php
src/Twig/Handler/HtmlHandler.php
src/Twig/SafeEnvironment.php
src/Twig/SecurityPolicy.php
src/Twig/SecurityProxyInterface.php
src/Twig/SetcontentNode.php
src/Twig/TwigEnvironmentWrapper.php
src/Twig/TwigExtension.php
tests/codeception/acceptance/_bootstrap.php
tests/phpunit/unit/Provider/TwigServiceProviderTest.php
tests/phpunit/unit/Twig/SetcontentTest.php
tests/phpunit/unit/Twig/TwigExtensionTest.php

This replaces `safe_twig` with Twig's Sandbox extension (BC should be maintained).
It can be used in Twig with the [`sandbox` tag](http://twig.sensiolabs.org/doc/tags/sandbox.html).
The `twig` function/filter has also been deprecated for the [`template_from_string` function](http://twig.sensiolabs.org/doc/functions/template_from_string.html).

Twig Sandbox

---

app/config/config.yml.dist
app/view/twig/exception/_tracedumps.twig
app/view/twig/exception/exception.twig
src/Config.php
src/Controller/Exception.php

This PR fixes two things: 
- It makes the amont of 'dumped' trace data configurable. 
- It makes the exception page show less sensitive data, when people aren't logged in.

Add limit to trace, show less data when not logged in.

---

src/Twig/Handler/RecordHandler.php
tests/phpunit/unit/Twig/Handler/RecordHandlerTest.php

There is a slightly new-ish bug in the `{{ current() }}` Twig function that seems to have been introduced in d56905f9a4d79c31e390525ee315998fdf9bb45b
The short version is that [`Content::offsetExists()`](https://github.com/bolt/bolt/blob/release/3.2/src/Legacy/Content.php#L358) checks the `value` property, and the ContentType was never stored there, rather in its own named property. 
The unit test mocked the Content object therefore hiding the problem, hence the update to the test.
#1555 lives … it is real … it has found us! I warned you all of this day, now it has arrived :stuck_out_tongue_winking_eye:

Hotfix Twig current function

---

app/src/js/modules/secmenu.js

Remember that fix I submitted for the secondary (black) menu on the left last week? I found a small issue with it.
It works great as long as the content is longer than the menu, but when the reverse is true, as it is on some of the admin menus, I saw menu items that weren't in the black anymore. I hardly ever use those menus anymore, which is why I forgot to check them.
This small adjustment to the original change fixes that, and hopefully it's perfect now.
Sorry for the extra churn!

Fix adjustSidebarHeight so it's longer than content for admin menus

---

src/Menu/AdminMenuBuilder.php
src/Menu/MenuEntry.php
src/Provider/MenuServiceProvider.php
tests/phpunit/unit/Menu/MenuEntryTest.php

Fixes #6139 
Most menu entries use the url generator so they will work with query parameters added to url generator. However, not for entries that use a path. Personally, I think we should deprecate using paths and force routes. The menu entries have to be mapped to a controller/route anyways so why even fuss with the path.
/ping @GawainLynch for changes integrating url generator.
FYI, I kept the logic for `$baseUrl` in the service provider because I wanted it to be clear that when this service is invoked the request info is needed. It could probably be fixed with a request listener and a setter on the `uri`.

Fix menu urls and integrate url generator

---

app/bootstrap.php

This allows customization of Bolt at a more advanced level, that still doesn't require you to change the way you bootstrap your app. 
I feel like this is common as any customization that isn't provided in the config needs to subclass `Bolt\Application` or add a `ServiceProvider`. Now that #6133 is in, no services are invoked / loaded as `Bolt\Application` is created, so there's no need to subclass anymore.
One concrete example is configuring S3. There's no way to configure S3 from Config, and maybe there shouldn't ever be. Now you just do your configuration for S3 in a ServiceProvider class and hook it in:
```yaml
services:
- My\Bolt\S3ServiceProvider:
aws.key: 1234
aws.secret: ***
- My\Bolt\AnotherServiceProvider # No params
```

Allow services in .bolt bootstrap config

---

src/Extension/Manager.php
src/Provider/ExtensionServiceProvider.php

Fixes #6151
tl;dr #6133 gone b0rked 'setnshun muntin', :koala: bru!
Early in Application we [register](https://github.com/bolt/bolt/blob/release/3.3/src/Application.php#L51) the extension service provider so that it will be the (closest to) first to boot.
When the extension service provider [boots](https://github.com/bolt/bolt/blob/release/3.3/src/Provider/ExtensionServiceProvider.php#L125-L130) we are now registering the extensions, which in the case of anything based on `\Bolt\Extension\SimpleExtension` will implement `ServiceProviderInterface` therefore requiring both `register()` and `boot()` to be called …
Now for the O.C.D. in the room …
[calling `$app->register()`](https://github.com/silexphp/Silex/blob/1.3/src/Silex/Application.php#L176) during `$app->boot()` will add providers to …

Boot extension registered service providers

---

app/view/twig/_base/_fieldset.twig
app/view/twig/_base/_page-nav.twig
app/view/twig/_base/_page.twig
app/view/twig/editfile/editfile.twig
app/view/twig/editlocale/editlocale.twig
app/view/twig/edituser/edituser.twig
app/view/twig/firstuser/firstuser.twig
app/view/twig/prefill/prefill.twig
src/Controller/Backend/General.php
src/Controller/Backend/Users.php

First off the block is, erm, `block()` … So in Twig 2 (as of current) expects the only valid test to is `block() is defined`, as (apparently) defined [here](http://twig.sensiolabs.org/doc/functions/block.html)
Second just ended up being implementing `form_start` & `form_end` where `form_widget` was being used.
I started toying with the idea of the buttons too, but put that in the "bigger work" category.

Deprecation and associated clean ups

---

app/nut
src/Nut/BaseCommand.php

Recent changes to loading mean that Nut commands registered by extensions will never be registered … Same story at #6157
@CarsonF Yes, I know … Let's get it properly on v4 refactor?

Extension Nut command registration

---

app/view/twig/_nav/_primary.twig
tests/codeception/acceptance/101-BackendEditor/BackendEditorCest.php

This PR is a follow up on #6178. Instead of trying to render the save button on every page in the back-end, only try when we're actually editing content. Otherwise Bolt will break since no contenttype is set.

Only render Live editor save button when content type is set

---

src/Configuration/YamlUpdater.php

Fixes #6138, as suggested by @colorando-de.
This fix might not be perfect, but it's a definite improvement.

Fix regex in yamlupdater.

---

app/bootstrap.php
src/Composer/JsonManager.php
src/Extension/Manager.php
src/Provider/ExtensionServiceProvider.php
tests/phpunit/unit/Extension/ExtensionAddTest.php
tests/phpunit/unit/resources/extensions/local/TestLocalExtension/Extension.php

OK, sorry this took longer than I wanted, had to do some rejigging after the recent extension boot changes.
This adds two new ways to use extensions. Firstly you can register extensions at an application level, that is ones that can be autoloaded via your root composer.json. To do this in your bootstrap, or anywhere else prior to the `$app->initialize()` call:
```
$app['extension']->register(new MyApp\Extensions\CleverExtension());
```
We also add a new root namespace for extensions that are found at `extensions/local`, these can't be instantiated until the extension boot process so these must be registered by class name. If you use a php bootstrap this works like:
```
#bolt.php
...
// This will load a class that is found at extensions/local/MyLocalExtension/ImageProcessExtension.php …
```

Local Extension Replacement

---

tests/codeception/acceptance/000-FirstUser/FirstUserCest.php
tests/codeception/acceptance/200-Frontend/FrontendCest.php
tests/codeception/acceptance/_bootstrap.php

This PR fixes the test for no session cookie, e.g. #6196, that should have been shown up in our acceptance tests, but weren't.
The tests on this PR will fail until https://github.com/bolt/bolt-thumbs/pull/35 is modified & merged.

[Tests] Fix acceptance test checks for session cookies front-end

---

src/Storage/Database/Schema/Table/ContentType.php
src/Storage/Repository.php
tests/phpunit/unit/Storage/EntityTest.php

* Don't add a field to the persistence query if it is not an entity property
To reproduce the problem, the simplest ContentType:
```
koalas:
name: Koalas
singular_name: Koala
fields:
title:
type: text
slug:
type: slug
uses: title
imagelist:
type: imagelist
```
Test PHP code:
```
$repo = $app['storage']->getRepository('koalas');
$entity = $repo->getEntityBuilder()->getEntity();
$entity->set('title', 'Kenny Koala');
$entity->set('status', 'published');
$entity->set('slug', 'kenny-koala');
$repo->save($entity);
```
Result:
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'imagelist' cannot be null
```

Don't persist unset fields on update

---

src/Config.php
src/Configuration/ResourceManager.php
tests/phpunit/unit/Configuration/ResourceManagerTest.php

Also don't include canonical in cached configs if it isn't set, since it can vary per request.
If one has host requirements in the routing.yml one doesn't want to set a canonical for the whole site (because it needs to be autodetected from the request since there are multiple valid hostnames for one site).
This fixes so that:
1. The canonical is only cached if it is set in the config.yml
2. HTTPS detection happens before the canonical is built, so that HTTPS detection for the canonical works.

Fix HTTPS detection for canonical url

---

phpunit.xml.dist
tests/phpunit/unit/AccessControl/AccessCheckerTest.php
tests/phpunit/unit/AccessControl/LoginTest.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Canonical/CanonicalTest.php
tests/phpunit/unit/Configuration/ResourceManagerTest.php
tests/phpunit/unit/Controller/FrontendTest.php

Since .dev is an actual tld we should use a tld reserved for testing, like .test

dot dev is an actual TLD, so use dot test for testing instead

---

app/resources/translations/cs_CZ/messages.cs_CZ.yml
app/resources/translations/de_DE/messages.de_DE.yml
app/resources/translations/el/messages.el.yml
app/resources/translations/en_GB/messages.en_GB.yml
app/resources/translations/es_ES/messages.es_ES.yml
app/resources/translations/fi/messages.fi.yml
app/resources/translations/fr/messages.fr.yml
app/resources/translations/hu/messages.hu.yml
app/resources/translations/id/messages.id.yml
app/resources/translations/it/messages.it.yml
app/resources/translations/ja/messages.ja.yml
app/resources/translations/nb/messages.nb.yml
app/resources/translations/nl_NL/messages.nl_NL.yml
app/resources/translations/pl_PL/messages.pl_PL.yml
app/resources/translations/pt/messages.pt.yml
app/resources/translations/pt_BR/messages.pt_BR.yml
app/resources/translations/ru/messages.ru.yml
app/resources/translations/sv_SE/messages.sv_SE.yml
app/resources/translations/zh_CN/messages.zh_CN.yml
app/resources/translations/zh_TW/messages.zh_TW.yml
app/view/twig/extend/extend.twig

1555 like PR for a missing translation template entry for ``Extend`` -> ``Extension Options`` box title.

Fix label translate in 'Extend' template

---

app/view/twig/exception/_request.twig

Prevents this in Nut:
```
[Twig_Error_Runtime]                                                                                         
Impossible to access an attribute ("all") on a null variable in "@bolt/exception/_request.twig" at line 46.  
```

Set a default as request will not exists on CLI

---

src/Configuration/PathsProxy.php
src/Configuration/ResourceManager.php

This fixes `urlPrefix` (base path) not being used in paths array.

Backport PathsProxy to 3.2

---

src/Provider/SessionServiceProvider.php

When using redis for sessions with errors enabled, Bolt throws the following exception:
Easy fix to get it working again. This also should enable persistent connections to redis again as it would just default to `connect`

Fix 'Notice: Undefined index: persistant' when using redis for sessions

---

src/Application.php
src/Provider/SecurityServiceProvider.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Controller/ControllerUnitTest.php
tests/phpunit/unit/Provider/OmnisearchServiceProviderTest.php

If agreed upon, this PR will add the Silex provider, and a provider of our own for Symfony Security.
This changes nothing about Bolt's current route security behaviour, but makes ` $app['security.firewalls']` and ` $app['security.access_rules']` shareable services that we know will be there from 3.3.0 onward (_read_: extensions)

[3.3][RFC] Adding security service provider

---

src/Routing/UrlGeneratorFragmentWrapper.php

* Fix fragments that have '/' & '?'
* Backport handling of fragment in URL generator @see https://github.com/symfony/symfony/pull/12979/commits/6d79a565e0e56b525134080687eba3961eab1a73

Handling of fragment in URL generator

---

src/Storage/Entity/MagicAttributeTrait.php

Fixes #6242 
The current code wasn't limited to the start of a string, switching to a regex fixes that.

Fix magic attribute parsing to avoid removing parts of field

---

app/resources/translations/en_GB/messages.en_GB.yml
app/view/twig/editcontent/fields/_block.twig
app/view/twig/editcontent/fields/_repeater.twig

Fixes #5972
Also adds the fix to the new named repeaters/blocks functionality

Add labels to translations for repeaters / new block fields

---

app/view/twig/exception/_trace.twig
app/view/twig/exception/_tracedumps.twig
app/view/twig/exception/exception.twig

Alleviates the quirk with #6248, but doesn't actually solve it properly. 
The underlying issue is that a thrown exception here doesn't get caught.
https://github.com/bolt/bolt/blob/release/3.2/src/Config.php#L651

Adding some fallbacks

---

src/Controller/Async/General.php
src/Controller/Backend/Log.php
src/Debug/ShutdownHandler.php
src/Helpers/Html.php
src/Legacy/Content.php
src/Legacy/Storage.php
src/Provider/DebugServiceProvider.php
src/Provider/NutServiceProvider.php
src/Provider/TwigServiceProvider.php
src/Stack.php
src/Storage/Entity/ContentValuesTrait.php
src/Storage/Repository/LogChangeRepository.php
src/Twig/Runtime/AdminRuntime.php
src/Twig/Runtime/RecordRuntime.php
tests/phpunit/BoltListener.php
tests/phpunit/unit/Menu/MenuBuilderTest.php
tests/phpunit/unit/Storage/RepositoryTest.php

[New in Symfony 2.2: Logging of deprecated calls](http://symfony.com/blog/new-in-symfony-2-2-logging-of-deprecated-calls) …
… and now [***new in Bolt 3.3***](.) :tada: :balloon: 
@CarsonF just thought it was easier to throw it up on `bolt/bolt` and PR it, we can work from there.

[3.3] Profiler deprecation notices

---

app/view/twig/_nav/_primary.twig

Fixes occasional "single request crashes" in the back-end with debug enabled.
When the session hits the check timer, the user object can be empty and the nav render still gets called during that redirect. 
We'll address properly with the DTO/REST work.

Set a default on user display name

---

src/Extension/ConfigTrait.php

This is to fix a bug that led to custom fields not being initialised properly since they were only registered with the legacy field manager.
This moves it over to the new system so everything should work correctly.

Fix to incorrect Extension Field Initialisation

---

src/Storage/Field/Type/RepeaterType.php

The join aliased content_id to id but this is no longer the case in the subselect.
This updates the alias to point to content_id

Fix incorrect alias

---

src/Helpers/Arr.php
src/Legacy/Storage.php
tests/phpunit/unit/Helper/ArrTest.php

Fixes #6278
- Implemented `Arr::column`
- Deprecated `Arr::makeValuePairs`

Fix array_column for PHP 5.x

---

app/view/twig/editcontent/fields/_select.twig
src/Twig/Runtime/RecordRuntime.php

This modification allows core's select fields to handle multiple content types. This is already possible within the codebase because `value` is applied directly to the `setcontent` call in the `_select.twig` template. Therefore the first part of `value` could have any valid `setcontent` input. It just didn't work because the existing select field combined all the ID's.
This small change works by checking for the existence of `contenttype` and if it exists, prepending it to the output text and also prepending it to the output values. This will work for singular or multiple content type combinations and has no effect on existing select fields as before declaring `contenttype` would have returned an exception.
An example of the output with `contenttype` declared:
An example of the value/text …

Modded core's select field to accommodate for multiple contenttypes.

---

src/Storage/Mapping/MetadataDriver.php
tests/phpunit/unit/Mapping/MetadataDriverTest.php

Fixes #5385
Adds the table -> entity mapping for setups where the prefix is different than `bolt_`

Fix for setups using different database prefix

---

app/view/twig/editcontent/fields/_select.twig
src/Twig/Runtime/RecordRuntime.php

Continuing on from #6270 and the discussion had with @SahAssar I've modified the original implementation of this slightly so instead of determining the return value based on the existence of `contenttype` it instead does it based on whether multiple contenttypes have been defined. This separates the left hand side of the values string from the right more distinctly and allows more refined choice for the developer.
```yml
featured_items:
label: "Event/Event series"
autocomplete: true
type: select
values: (event,eventseries)/title
```
Would create a select option with `<option value="event/1">Title</option>`.
While
```yml
featured_items:
label: "Event/Event series"
autocomplete: true
type: select
values: event/contenttype,title
```
Would create a select option with `<option value="1">Event …

Modded core's select field to accommodate for multiple contenttypes v2

---

src/Render.php

It is redundant now that Twig events are in the profiler.

Remove bolt.render stopwatch event

---

app/view/twig/editcontent/fields/_relationship.twig

Fixes #6311
Fixes a bug where we were using the slug, not the contenttype name to decide incoming relations.

Fix bug causing missing incoming relations

---

src/Controller/Base.php
src/Render.php
src/Response/TemplateResponse.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Controller/Async/FilesystemManagerTest.php
tests/phpunit/unit/Controller/Async/GeneralTest.php
tests/phpunit/unit/Controller/Async/StackTest.php
tests/phpunit/unit/Controller/Backend/AuthenticationTest.php
tests/phpunit/unit/Controller/Backend/DatabaseTest.php
tests/phpunit/unit/Controller/Backend/ExtendTest.php
tests/phpunit/unit/Controller/Backend/FileManagerTest.php
tests/phpunit/unit/Controller/Backend/GeneralTest.php
tests/phpunit/unit/Controller/Backend/LogTest.php
tests/phpunit/unit/Controller/Backend/UsersTest.php
tests/phpunit/unit/Controller/FrontendTest.php
tests/phpunit/unit/Response/TemplateResponseTest.php

`Render::render` is the last non-deprecated method in the class, and it is now just a shortcut to render template to `TemplateResponse`. As a shortcut, it makes more sense to do the logic in the Base Controller with the other shortcut methods.
It also gets simpler once the globals go away (to be deprecated later in 3.x).
---
I also changed `TemplateResponse` to take template name instead of template object.
Name is really the only thing useful from the object since it's already rendered.
Not to mention `Twig_Template` is marked as internal.

Deprecate Render

---

src/Storage/ContentRequest/Save.php

When no repeater values are posted, make sure that the field is set to an empty value and not skipped.
Closes #6305

Fix Save Errors When Deleting Repeaters

---

src/Storage/Field/Type/RepeaterType.php

Adds an extra check to repeaters to return an empty collection if they are used in Templatefields and are empty.
Fixes #6323

Handle empty repeaters in Templatefields

---

src/Extension/ConfigTrait.php
src/Extension/Manager.php

A couple of fixes to make local extensions behave the same as distributed ones.
These changes make sure that directories are always relative so extensions don't have to be in extensions/vendor to work correctly.

Base Directory Fixes for Local Extensions

---

app/bootstrap.php

Allows locally autoloadable extensions to be added via the bolt.yml file.

Add support for extension definition in bolt.yml file

---

src/Controller/Backend/Extend.php

This allows a BC method to get a base url for extensions since the change from `/extend` to `/extensions` means there isn't a standard call for multiple versions.
Accessing with `$app['url_generator']->generate('extend')` will return the correct url on all 3.x versions of Bolt.

Add BC binding to extend overview page

---

src/Storage/Entity/ContentValuesTrait.php

So I came across @graham73may 's issue while dealing with a bug myself so I thought I'd take a stab at fixing it.
My solution is to try and retrieve the taxonomy options from the config, if it exists apply the `setTaxonomy` method to each taxonomy with values obtained from the options otherwise provide the only value we have `$value` (this is for tags).
All are having the default `sortorder` set to 0 unless it's an array in which case the `sortorder` is set to the index key (is there ever an instance where the key is an associative?).
Fixes #6293

Fix to #6293

---

src/Twig/Extension/ArrayExtension.php

Fix for maintaining key association in `{{ unique() }}`

---

.travis.yml

This should now upload our coverage reports that are configured to run on a daily Travis cron job (when enabled after merge).
Currently only CodeClimate is targeted, but if I can it would be nice to get a hold of the tarball of the HTML report :wink: 
**NOTE:** The branch the cron runs against must change when the default branch changes, that change needs to be notified (currently) at CC.

Travis cron code coverage

---

src/Storage/Entity/ContentValuesTrait.php

In Bolt 3.2.6 I came across a weird instance where preview was not passing a status. This therefore threw an error since it wasn't a defined key in the `$values` array.
Wrapping it in an `isset` fixes the issue but this might be a deeper problem than I realise?

Fixes: Status not passed to `$values` error

---

src/Configuration/ForwardToPathResolver.php
src/Provider/PathServiceProvider.php

If not using `bootstrap.php` and only using new code, then paths are not synced to resources. This fixes that.
My use case:
```php
class Application extends \Bolt\Application
{
public function __construct($siteDir, array $values = [])
{
parent::__construct();
$this['path_resolver.root'] = Common\Config::getProjectDir();
$this['path_resolver.paths'] = [
'site'       => $siteDir,
'cache'      => '%site%/app/cache',
'config'     => '%site%/app/config',
'database'   => '%site%/app/database',
'extensions' => '%site%/app/extensions',
'web'        => '%site%/public',
];
}
}
```

Sync PathResolver paths to ResourceManager without bootstrap

---

app/config/config.yml.dist

For those of us who have clients that write C0<sub>2</sub> all the time.  Donald Trump is firmly opposed to this pull request.

Add sub and super to default allowed tags

---

src/Storage/Field/Collection/FieldCollection.php

Example:
```twig
{{ content.foo }} {# <- works now #}
{{ content.get("foo") }} {# <- for reference #}
```
The thing I can't figure out is in [`RepeatingFieldCollection::addFromArray`](https://github.com/bolt/bolt/blob/release/3.2/src/Storage/Field/Collection/RepeatingFieldCollection.php#L78) the `FieldValue` object is added to the collection as if the `FieldCollection` is a _list_.
But in [`FieldCollection::doInitialize`](https://github.com/bolt/bolt/blob/release/3.2/src/Storage/Field/Collection/FieldCollection.php#L136) the `FieldValue` object is set on the collection like a _hash_.
So is `FieldCollection` supposed to be a list or a hash? I would think the latter, due to the example above. Maybe the line in `RepeatingFieldCollection` is a derp?

Allow "direct" access to fields from FieldCollection in Twig

---

.travis.yml
src/Helpers/RandomLibFactory.php
src/Provider/RandomGeneratorServiceProvider.php

I know this is fixed in 3.3, but Travis won't even finish the runs for 7.1. So this fixes it for the mean time. It won't even be in 3.3.

Fix mcrypt deprecation warning

---

src/Storage/Field/Collection/FieldCollection.php
src/Storage/Field/Collection/FieldCollectionInterface.php
src/Storage/Field/Collection/LazyFieldCollection.php
src/Storage/Field/Collection/RepeatingFieldCollection.php
src/Storage/FieldManager.php
tests/phpunit/unit/Storage/FieldLoadTest.php

This refactors `LazyFieldCollection` out of `FieldCollection`. `FieldCollection` is now just a mapping of `FieldValue` objects with some additional methods. `LazyFieldCollection` handles fetching references from db, hydrating results to `FieldValue` objects, and giving those to a `FieldCollection`. Both implement the new `FieldCollectionInterface`.
The motivation for this was that `FieldCollection::add` and `FieldCollection::set` did different things (as does `ArrayCollection`). `ArrayCollection` can be a `list` or `map`, but `FieldCollection` is always a `map`. Now the `add` and `set` methods of `FieldCollection` do the same thing. This also eliminates the need to override `offsetGet/Exists` since the objects are always stored in the collection correctly. Hopefully, this will reduce …

Refactor lazy logic out of FieldCollection

---

app/theme_defaults/_sub_pager.twig
app/theme_defaults/pager/_base.twig
app/theme_defaults/pager/default.twig
app/theme_defaults/pager/narrow.twig
app/view/twig/components/pager.twig
src/Storage/Field/Collection/FieldCollection.php
src/Twig/Runtime/RecordRuntime.php
tests/phpunit/unit/Twig/Runtime/RecordRuntimeTest.php

This abstracts the logic around creating a pager into simple blocks.
See the [pager/default.twig](https://github.com/CarsonF/bolt/blob/feature/pager-blocks/app/theme_defaults/pager/default.twig) for an example.

Update pager template to use blocks

---

app/bootstrap.php

In cases where someone hasn't enabled/installed PHP's mbstring extension, the following exception will be  thrown:
```
PHP Fatal error: Uncaught Error: 
Call to undefined function Bolt\mb_internal_encoding() 
in /var/www/vendor/bolt/bolt/app/bootstrap.php:31
```
The `Bolt\mb_internal_encoding()` part of the error is confusing as it indicates to the average user that the problem is with Bolt, and not the PHP installation.

[3.2] Force mbstring functions call on root namespace

---

composer.json

Currently master will install vendor requirements fine on a git install where `silex/web-profiler` is required by the root project. But when Bolt is required as a dependency, the Composer SAT gets into a permanent loop with CPU pinned around 99%.
This is a simple hack that will be obvious to remove when we're ready for the Silex 2 cutover, but allow Composer installs for ~~idiots~~ brave people like myself.

[4.0] Use commit hash to prevent SAT resolver loop pre-Silex 2

---

src/Asset/Target.php
src/Cache.php
src/Configuration/ResourceManager.php
src/Controller/Routing.php
src/Extension/AssetTrait.php
src/Extension/Manager.php
src/Extension/MenuTrait.php
src/Extension/NutTrait.php
src/Helpers/Arr.php
src/Legacy/BaseExtension.php
src/Menu/MenuBuilder.php
src/Provider/DatabaseSchemaServiceProvider.php
src/Session/Generator/RandomGenerator.php
src/Storage/Database/Schema/Builder/ExtensionTables.php
src/Storage/Database/Schema/Manager.php
src/Storage/Database/Schema/Table/ContentType.php
src/Storage/Entity/Content.php
src/Storage/EntityManager.php
src/Storage/Field/Manager.php
src/Storage/Field/Type/FieldTypeBase.php
src/Storage/LazyEntityManager.php
src/Storage/Mapping/ContentType.php
src/Storage/Mapping/ContentTypeTitleTrait.php
src/Users.php
src/Version.php

[3.3] Core deprecation notice logging

---

.gitignore
composer.json
src/Nut/PimpleDumpCommand.php
src/Provider/NutServiceProvider.php

As per discussion in RFC #6394 and on Slack.
1. Install the plugin from JetBrains repositories:
* Settings → Plugins → Browse repositories and search for "Silex"
2. Restart PhpStorm/IntelliJ
3. Enable the plugin:
* Per-project:
* Settings → Other Settings → Silex Plugin  → Click "Enable Plugin"
* All projects:
* Default Settings → Other Settings → Silex Plugin  → Click "Enable Plugin"
For more information, the plugin source repository can be [found on GitHub][silex-idea-plugin]
From the project root direction simply run:
```bash
php ./app/nut pimple:dump
```
--- 
[silex-pimple-dumper]: https://github.com/Sorien/silex-pimple-dumper
[silex-idea-plugin]: https://github.com/Sorien/silex-idea-plugin

[3.3] Adding the Pimple dumper as a require-dev & Nut command

---

composer.json
src/AccessControl/Login.php
src/AccessControl/Password.php
src/AccessControl/PasswordHashManager.php
src/EventListener/StorageEventListener.php
src/Exception/AccessControlException.php
src/Exception/PasswordHashException.php
src/Exception/PasswordLegacyHashException.php
src/Provider/AccessControlServiceProvider.php
src/Provider/StorageServiceProvider.php
tests/phpunit/unit/AccessControl/PasswordTest.php
tests/phpunit/unit/EventListener/StorageEventListenerTest.php
tests/phpunit/unit/Nut/UserAddTest.php
tests/phpunit/unit/Nut/UserResetPasswordTest.php
tests/phpunit/unit/PasswordHashTest.php

Open to discussion on pretty much everything.
This simply removes PasswordLib (which is abandoned), and introduces a configurable service that advanced users can customise.
We're still 10 months out from release, but let the dominoes start to fall :wink: 
**UPDATE:** For people referring back to this, the concept of this PR & the `PasswordHashManager` service is a transitory **hack** during 4.0-dev until we can cut over to both Silex 2 & Symfony Security proper.

[4.0] Remove PasswordLib

---

src/Provider/StorageServiceProvider.php
src/Storage/Mapping/MetadataDriver.php

Fixes #6325
Fixes #6336
This is a very temporary fix, since it's already wholly replaced by the Mapping refactor, so this should only have a lifespan of one minor version.
The existing config class does some post processing of fields to change certain values. As a stop-gap I have made an exact copy of that into the MetadataDriver class and placed it in a deprecated method with a warning about its imminent demise.

Field Config Post Processing for Repeaters/Templatefields

---

src/Configuration/Composer.php
src/Configuration/ForwardToPathResolver.php
src/Configuration/PathResolver.php

I deprecated `app` path (months ago) because it was pointing to Bolt's core _app_ directory. This was confusing for users since they also have an _app_ directory. I wanted to reintroduce the path in v4.0 as a user path (always pointing to the users _app_ directory instead of Bolt's). But since core no longer references this path, and it had no use to users previously, this change can happen now.
This also fixes a "bug" where the path is seemingly "out of sync" between PathResolver and ResourceManager.
I still would discourage use of this to resolve paths directly. It should only be used to configure other paths. For example, don't do
```php
$resolver->resolve('%app%/config/foo.yml');
```
but instead reference `config` directly.
```php
$resolver->resolve('%config%/foo.yml');
```
That isn't …

Change app path to always be user directory

---

app/src/package.json

Fixes #5676 for now, we will have to look into unlocking it when 4.0.5 is released.

Lock select2 at 4.0.0

---

app/view/twig/_nav/_secondary-content.twig

Fixes #6183, use the name(s) in the navigation labels, not the slugs.

Fix "Wrong Name in Sub-Navigation for Content"

---

src/Storage/Field/Type/FieldTypeBase.php

Fixes #6413
This is a temporary fix to bridge to 4.0 which allows FieldTypeBase to support both strings and objects returned via the `getStorageType()` method in fields.

Fix to allow extension interface backwards compatibility

---

src/Helpers/Arr.php
src/Storage/ContentRequest/Save.php

On standard fields we do an empty check before saving in the database, problem with repeaters was that although all the fields are empty an array of empty values still evaluates to true on `empty($value)`
This adds a recursive helper to check wether an array is empty and if it is the value of the repeater is set to null.
This solves a bug that a few people have reported whereby in the templates there was no way to check if a repeater collection was empty because there was always one value in it.
With this fix you can go back to using `{% if record.repeaterfield|length %}....` to test whether you have some collections.

Don't save an empty repeater block

---

app/view/twig/files/_files.twig
src/Controller/Async/FilesystemManager.php

Renaming file in sub-subfolders didn't work since we only prepended the namespace, not the parentpath. This fixes that.

Fix renaming files in sub-subfolders

---

src/Helpers/Arr.php
src/Storage/ContentRequest/Save.php

Please please please can we not add this to the API to support in a tagged version.
I get we need something for repeaters, and I don't have a better solution myself but this has support liability attached we don't want to have to live with even for 3.x

[3.2] Mark Arr::isEmptyArray() @internal

---

src/Config.php

Fixes #6431
The only thing this did differently than PHP's default domain is removed
the `www.` prefix allowing the cookie to assigned to `foo.com` and `www.foo.com`.
It was decided this isn't a big enough use case to warrant keeping this logic.
Note that fixing this caching bug would mean moving the logic to 3 different
places (or 2 with larger refactoring).

Remove default value for cookies_domain

---

src/Cache.php
src/Provider/UploadServiceProvider.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Composer/Action/DumpAutoloadTest.php
tests/phpunit/unit/Controller/Backend/GeneralTest.php
tests/phpunit/unit/Nut/CacheClearTest.php
tests/phpunit/unit/Nut/ConfigGetTest.php
tests/phpunit/unit/Nut/ConfigSetTest.php

Remember that time I said there was no more usage of ResourceManager (#6439)? I lied.
**Now** there are no more usages (including tests).

What's a ResourceManager?

---

.scrutinizer.yml

The Bolt org repo hasn't used Scrutinizer for a while, and we've almost finished a cut over to CodeClimate, however I am still running it on my own fork as part of the comparative analysis during said cut-over.
This just removes a little noise from my view while I work on it, and shortly we can just delete this file completely.

[3.2][Scrutinizer] Remove unused metrics

---

src/Provider/SecurityServiceProvider.php

Today's tally:
:koala: — 3
Gawain — 0
@CarsonF I double checked, and no this does **not** resolve the fails on #6428

[3.3] Register Silex provider first, and don't authenticate base route

---

src/Storage/Collection/CollectionManager.php

\Bolt\Storage\Collection\CollectionManager::create() is called from:
* \Bolt\Storage\Field\Type\TaxonomyType::persist()
* \Bolt\Storage\EntityManager::createCollection()
All callers demand an object ot be returned an none of them do, or should have to, check if anything is returned, leading potentially to vague exceptions conditions.
… Smoke 'em if ya got 'em

[3.3] Throw an exception when a collection is created missing a handler

---

src/Legacy/Storage.php

Fixes #6438
The legacy patch that fills in repeaters to old content objects was slacking on the job. We should give priority to the contenttype 'key' property only falling back to the slug if the key isn't set (which also means that the slug is the same as the key)

The continued war on slugs

---

app/view/twig/editcontent/fields/_repeater.twig

As a corresponding configuration to the existing `limit` option this introduces support for the `initial` value to be set.
The current default is 1, which replicates the current behaviour of showing an empty set when a record has no repeaters set.
This is useful as described in #6378 where sets have required fields but you don't want to force at least one set.
Field configuration will look like this:
```yaml
images:
type: repeater
initial: 0
limit: 10
separator: true
fields:
repeattitle:
type: text
required: true
repeatimage:
type: image
```

Allow an initial number to be passed in the repeater field config

---

src/Storage/Entity/Builder.php
src/Storage/Repository.php

This ensures that custom fields that are still using the old interface don't break by wrapping the specific method calls in an `instanceof FieldTypeInterface` check.
Fixes #6420
Also fixes #6273

Ensure fields are using new interface before calling methods

---

src/Provider/SecurityServiceProvider.php
tests/phpunit/unit/Nut/DatabaseCheckTest.php
tests/phpunit/unit/Nut/DatabaseRepairTest.php

This prevents routes from being flushed early.

Change Symfony Security to use lazy url generator.

---

app/theme_defaults/_sub_fields.twig
theme/base-2016/partials/_sub_fields.twig

Raw should only be used on user data when intended (or at all).
I don't think I need to say more.

Raw should only be used on user data when intended

---

.travis.yml
README.md
app/nut
app/web.php
composer.json
src/Application.php
src/Exception/BootException.php

As agreed, and re-confirmed last night, we're implementing Twig 2 for Bolt v4 … and [their minimum PHP `require` is 7.0](https://github.com/twigphp/Twig/blob/v2.0.0/composer.json#L30) … so be ours.
This is an increasing trend too, but keeps us moving forward instead of supporting PHP 5.2+ still kinda thing :wink:

[4.0] Raise minimum requirement to PHP 7.0

---

.travis.yml
composer.json
src/Provider/SessionServiceProvider.php
src/Session/Handler/AbstractHandler.php
src/Session/Handler/DoctrineCacheHandler.php
src/Session/Handler/Factory/AbstractFactory.php
src/Session/Handler/Factory/MemcacheFactory.php
src/Session/Handler/Factory/MemcachedFactory.php
src/Session/Handler/Factory/PredisFactory.php
src/Session/Handler/Factory/RedisFactory.php
src/Session/Handler/FileHandler.php
src/Session/Handler/FilesystemHandler.php
src/Session/Handler/MemcacheHandler.php
src/Session/Handler/MemcachedHandler.php
src/Session/Handler/PsrCacheHandler.php
src/Session/Handler/PsrSimpleCacheHandler.php
src/Session/Handler/RedisHandler.php
src/Session/IniBag.php
src/Session/SessionStorage.php
tests/phpunit/unit/Session/Handler/Factory/MemcacheFactoryTest.php
tests/phpunit/unit/Session/Handler/Factory/MemcachedFactoryTest.php
tests/phpunit/unit/Session/Handler/Factory/Mock/MockMemcache.php
tests/phpunit/unit/Session/Handler/Factory/Mock/MockMemcached.php
tests/phpunit/unit/Session/Handler/Factory/Mock/MockRedis.php
tests/phpunit/unit/Session/Handler/Factory/PredisFactoryTest.php
tests/phpunit/unit/Session/Handler/Factory/RedisFactoryTest.php
tests/phpunit/unit/Session/IniBagTest.php

In my previous attempt, I tried to normalize all connection parameters and options for `Memcache`, `Memcached`, `Redis`, and `Predis`. In reality this became confusing and didn't work well.
Now all that logic has been moved into factory classes. In addition there were several bugs in how each client was configured that have been resolved. All the factories are under unit tests as well 👏 
These do still need to be documented I know. I was hesitant to document the configuration before, because I didn't like how it turned out and wanted to change it. But there's only so much one can handle looking at undocumented PHP C source code 😉 
Now I'm happy(er) with it, and will take a stab at the docs.
Also it's important to note that `predis` is its own type now separate from the `redis` type which …

Session Handlers Phase II

---

src/Legacy/Storage.php

Fixes #6228 
Adds a check to see if the key is different to the slug when deciding how to lookup taxonomy joins.
Note this will need to be reworked slightly for 3.3 as the implementation has changed slightly (dropping util:: functions ) so it may need a separate PR.

Fix frontend taxonomy lookups where key is different to slug

---

src/Nut/DatabaseRepair.php
tests/phpunit/unit/Nut/DatabaseRepairTest.php

This PR adds a `dump-sql` option to the `database:update` command.
Using this option will dump a list of SQL statements *instead* of performing the update on the database.
This is useful when generating migrations.
```
$ app/nut database:update --dump-sql                                                                                                                                                                   
ALTER TABLE bolt_field_value ADD value_boolean TINYINT(1) DEFAULT '0' NOT NULL
DROP INDEX IDX_4C524BC3EA112943 ON bolt_relations
DROP INDEX IDX_4C524BC378CED90B ON bolt_relations
DROP INDEX IDX_4C524BC35ACD2645 ON bolt_relations
DROP INDEX IDX_4C524BC330354A65 ON bolt_relations
CREATE INDEX IDX_4C524BC3EA11294378CED90B ON bolt_relations (from_contenttype, from_id)
CREATE INDEX …
```

Add option to only dump the SQL from the database:update command

---

src/Provider/CanonicalServiceProvider.php
src/Routing/Canonical.php
tests/phpunit/unit/Controller/FrontendTest.php
tests/phpunit/unit/Routing/CanonicalTest.php

`Canonical::setOverride` can now be used _during_ the request cycle to change the canonical url. Absolute and relative paths are resolved with the current request.
It was also refactored to not depend on `RequestStack` and `RequestContext`.
Test coverage is 100%.

Allow Canonical Url to be overridden

---

composer.json
tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php
tests/codeception/acceptance/101-BackendEditor/BackendEditorCest.php
tests/codeception/acceptance/103-BackendManager/BackendManagerCest.php
tests/codeception/acceptance/104-BackendAuthor/BackendAuthorCest.php

This just fixes the blockers that were keeping us locked at Codeception 2.2.1 … and we're on track to get 2.3 working (_hint: PHPUnit updates_) when it drops :wink:

[3.3][Tests] Codeception tweaks

---

app/theme_defaults/_sub_fields.twig
src/Legacy/Content.php
src/Storage/Field/Collection/FieldCollection.php
src/Storage/Field/Collection/FieldCollectionInterface.php
src/Storage/Field/Collection/LazyFieldCollection.php
tests/phpunit/unit/Content/ContentTest.php
theme/base-2016/page.twig
theme/base-2016/partials/_sub_fields.twig

This PR makes sure the vilified-but-necessary `_sub_fields`: 
- don't rely on `|raw`, `|twig`, `template_from_string()` or any such hackishness
- have the same treatment for regular fields, template fields and repeaters
~~Might needs some final touch-ups after #6472 has landed.~~
**Edit:** 
- Works correctly for HTML, text, textarea and Markdown fields now.
- Works correctly for repeaters now. (note: No support for `allowtwig: true` in repeaters. It was never supported, but this PR doesn't add it either)
- Incorporates @rossriley 's changes in #6473. 
- Closes #6472, as this PR provides a viable workaround for that issue, without changing stuff that might have unforeseen consequences. 
After this is merged, I will update the docs for 3.3 accordingly, because iterating over repeaters can …

🚧 🔨 Fix/clean up  sub fields

---

src/Extension/AssetTrait.php

We assume that the action to take is evident, but in practice it needs pointing out quite often.

Clarify error message for missing assets in extensions.

---

app/view/twig/components/panel-stack.twig
app/view/twig/editcontent/fields/_file.twig
app/view/twig/editcontent/fields/_filelist.twig
app/view/twig/editcontent/fields/_image.twig

Use `path()` for ajaxy uploads instead of `url()`.

---

app/view/twig/editcontent/fields/_repeater.twig

Fixes #6086
This adds an empty hidden value to repeater fields which ensures that a value is always posted even if there are no other sets posted.
Fixes a bug where deleting all the sets did not work because the field was not present.

Force saving of repeaters, even when empty

---

src/Version.php

The discussion just didn't sit with me, so test case:
```php
<?php
namespace Koala;
use Symfony\Component\Console\Helper\Table;
use Symfony\Component\Console\Output\ConsoleOutput;
include_once __DIR__ . '/vendor/autoload.php';
final class Version
{
//const VERSION = '3.2.0';
const VERSION = '3.2.0 beta 9';
public static function compare($version, $operator)
{
$currentVersion = str_replace(' ', '', strtolower(static::VERSION));
$version = str_replace(' ', '', strtolower($version));
return version_compare($version, $currentVersion, $operator);
}
}
$operators = [
//'<',
//'>',
//'<=',
'>=',
];
$versions = [
'3.1',
'3.1.0',
'3.2',
'3.2.0-beta8',
'3.2.0-beta9',
'3.2.0',
'3.2.1',
'3.3',
'3.3.0',
];
$output = new ConsoleOutput();
$output->writeln('');
$output->writeln(sprintf('Bolt version: …
```

[3.2] Version compare PHPDoc OCD-off

---

src/Nut/DebugEvents.php
src/Nut/DebugRoutes.php
src/Nut/DebugServiceRegistration.php
src/Provider/NutServiceProvider.php

This adds the following three ommands:
* `debug:events` — System listened events, and target callable debug dumper.
* `debug:routes` — System route debug dumper.
* `debug:services` — System service provider registration boot order debug dumper.
e.g.
```
+-----------------------+----------+-------------------------------------------------------------------------------------+
| Event Name            | Priority | Listener                                                                            |
+-----------------------+----------+-------------------------------------------------------------------------------------+
| kernel.request        | 2048     | Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure         |
| kernel.request        | 1024     | …
```

[3.3] Commands to query views into system operations

---

src/Config.php
src/EventListener/DoctrineListener.php
src/Provider/DatabaseServiceProvider.php
tests/phpunit/database/Entity/AbstractEntityTest.php

Fixes #6430
We'll need to follow up with docs on `utf8mb4` "fun"

[3.3][MySQL] Set database character set & collation as configured

---

src/Provider/DebugServiceProvider.php

This saves about 350ms in a basic front-end with debugging **disabled**
… and #1555

[3.3] Disable the class loader if not specifically enabled during boot

---

src/Storage/Field/Type/JoinTypeBase.php
src/Storage/Field/Type/RelationType.php
src/Storage/Field/Type/TaxonomyType.php

This is just a tidy up to standardise the interface for collection normalisation. For both taxonomies and categories if the value is set to either a string or an integer the values get passed through the `setFromPost` method in the same way that the other Collection fields do.
It will also sort out https://github.com/bolt/boltforms/issues/139 over on boltforms too.

Improve relation and taxonomy normalisation

---

src/Cache.php

When clearing the cache using `app/nut`, some cruft stayed behind: 
```
[🐹::~/Sites/bolt-origin]$ du -h -d1 app/cache
4.0K	app/cache/.sessions
8.0K	app/cache/composer
0B	app/cache/development
8.3M	app/cache/exception
0B	app/cache/profiler
144K	app/cache/trans
8.5M	app/cache
```
This PR flushes those folders as well.

Clear 'exception' and 'translation' too.

---

src/Storage/Repository.php

The `JOIN`s and `GROUP BY` can produce some _interesting_ results. So this just un-sets them in the pre-built query object.

[3.2] Reset GROUP BY and JOIN parameters for count()

---

composer.json
src/Configuration/Check/PhpExtensions.php

It is (optionally) used by ircmaxell/security-lib and PasswordLib/PasswordLib, but neither package require it
Related: https://github.com/bolt/docs/pull/708

[3.3 ] Remove requirement on (optional) gmp PHP extension

---

src/Controller/Backend/General.php
src/Controller/Backend/Users.php

Might was well stay ahead of the game …
```
Form::isValid() with an unsubmitted form is deprecated since version 3.2
and will throw an exception in 4.0.
```

[3.3][Deprecation] Use Form::isSubmitted() before Form::isValid()

---

app/theme_defaults/_sub_searchbox.twig
app/view/toolbar/db.html.twig
app/view/twig/_base/_listing.twig
app/view/twig/_base/_page-nav.twig
app/view/twig/_base/_page.twig
app/view/twig/_buic/_listing.twig
app/view/twig/_nav/_footer.twig
app/view/twig/custom/listing/pages.twig.dist
app/view/twig/editcontent/fields/_relationship.twig
app/view/twig/extend/extend.twig
app/view/twig/files_ck/files_ck.twig
app/view/twig/overview/_panel-actions_overview.twig
app/view/twig/relatedto/_panel-actions_relatedto.twig
theme/base-2016/notfound.twig
theme/base-2016/partials/_fresh_install.twig

The template used the now deprecated global `request('foo')` object, which causes a twig exception when rendering. This exception can not be overridden if happening while rendering a widgets template, causing a crash in the backend.
Replaced (as specified by @CarsonF) with `global.request.get('foo')`.
*Note*: There are other occurrences which use `app.request.query.get('foo')`. Should probably use same new method?

replaced use of deprecated request object

---

app/view/twig/_base/_fieldset.twig

Deprecation:
```
Silent display of undefined block "fieldset_label_info" in template
"@bolt/_base/_fieldset.twig" is deprecated since version 1.29 and will
throw an exception in 2.0.
Use the "block('fieldset_label_info') is defined" expression to test for
block existence
```

[3.3] Use "is defined" to check if a block exists

---

src/Nut/ConfigGet.php

Classifying this as bug-fix, as booleans are currently cast to the string-integer in the UI, and the set command takes `true` and `false` as valid boolean inputs … so "confusement"

[3.2] Report a boolean value as "true" or "false"

---

app/src/js/widgets/fields/fieldRepeater.js

Problem:
Currently, when reaching the `limit` set in a repeater definition, the *[Add new Repeater set]* button gets grayed out but clicking it still adds a new repeater set, and the *[Duplicate set]* button gets wrongly grayed out.
Fix:
The `.disabled` class was being applied to the *[Duplicate set]* buttons, instead of adding the `“disabled”` property to the *[Add new Repeater set]* button.

Fix bug in repeater buttons

---

src/Storage/Entity/LogChange.php
src/Storage/Repository/LogChangeRepository.php

I'm not sure exactly where the bug starts manifesting itself but sometimes the changelog will record a diff for relation and taxonomy fields, even if there are no taxonomy or relations set on a contenttype.
The root cause of this was that the metadata for the field was not set on the LogChange entity although it was expecting the property to be available.
This fixes that issue by injecting the metadata into the entity object after it has been fetched in the Repository.
If the field is not then set, the transformation will be skipped.
I've tested this on 3.3 and 3.4 and this seems to work.

Fix content changelog field handling

---

src/Legacy/Content.php
src/Twig/SecurityPolicy.php

Instead of outputting a SecurityPolicy error for Twig-in-content inline in the HTML, we now throw an exception.

Make thrown SecurityPolicy in Twig-in-content show Exception, instead of outputting HTML on page. 

---

src/Provider/NutServiceProvider.php

Some more tools to help give insight to certain levels of front-enders
```
$ ./app/nut debug:twig 
Functions
---------
* asset(path, packageName = null, absolute = false, version = null)
* url(name, parameters = [], schemeRelative = false)
* widgets(location = null, zone = "frontend", wrapper = "widgetwrapper.twig")
* … etc
Filters
-------
* capitalize
* current
* date(format = null, timezone = null)
* markdown
* … etc
Tests
-----
* constant
* defined
* … etc
Globals
-------
* global = object(Symfony\Bridge\Twig\AppVariable)
*  … etc
```

[3.3] Add debug:twig & lint:twig commands from symfony/twig-bridge

---

src/Nut/PimpleDump.php
src/Provider/NutServiceProvider.php
tests/phpunit/unit/Nut/PimpleDumpTest.php

`PimpleDumpCommand` was the only Nut class to use the "Command" suffix, and my C.D.O. couldn't cope :stuck_out_tongue_winking_eye: 
Also added test coverage.

[3.3] Nut pimple:dump consistency & tests

---

src/Nut/DebugRouter.php
src/Nut/DebugRoutes.php
src/Nut/RouterMatch.php
src/Provider/NutServiceProvider.php
tests/phpunit/unit/Nut/DebugRouterTest.php
tests/phpunit/unit/Nut/RouterMatchTest.php

* Rename `debug:routes` to `debug:router` to match Symfony's
* Added single route information option to match Symfony's
* Ported `router:match` from Symfony full-stack
```
$ ./app/nut router:match /
[OK] Route "homepage" matches
+--------------+---------------------------------------------------------+
| Property     | Value                                                   |
+--------------+---------------------------------------------------------+
| Route Name   | homepage                                                |
| Path         | /                                                       |
| Host         | ANY                                                     |
| Scheme       | ANY                                                     |
| Method(s)    | ANY …
```

[3.3] Nut debug — Phase III

---

src/Configuration/YamlUpdater.php
src/Nut/AbstractConfig.php
src/Nut/BaseCommand.php
src/Nut/ConfigGet.php
src/Nut/ConfigSet.php
tests/phpunit/BoltListener.php
tests/phpunit/unit/Nut/ConfigGetTest.php
tests/phpunit/unit/Nut/ConfigSetTest.php

Cuts out deprecations in SF 3.1+ too

[3.3] [Deprecations] Switch YamlUpdater to use Bolt filesystem for YAML handling

---

src/Nut/DebugEvents.php
tests/phpunit/unit/Nut/DebugEventsTest.php

* Follow upstream use of columns
* Allow a single request by name to be dumped
```
$ ./app/nut debug:events kernel.request
Registered Listeners for "kernel.request" Event
===============================================
+-------+--------------------------------------------------------------------------------+----------+
| Order | Callable                                                                       | Priority |
+-------+--------------------------------------------------------------------------------+----------+
|    #1 | Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure()  |     2048 |
|    #2 | Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest() |     1024 |
|    #3 | Bolt\EventListener\ConfigListener::onRequestEarly() …
```

[3.3] Enable breaking events up into single events

---

src/Controller/Async/General.php

After dd6b99ce25975408ae26d05301c3ecf230a449d0, news items did no longer fall back to 'information', but they remained in the array as 'news'. This PR passes that one into the rendering function too.

Fix News widget on dashboard

---

src/Nut/AbstractConfig.php
src/Nut/BaseCommand.php
src/Nut/ConfigGet.php
src/Nut/ConfigSet.php
src/Nut/DebugEvents.php
src/Nut/NutApplication.php
src/Nut/RouterMatch.php
src/Nut/ServerRun.php
tests/phpunit/unit/Nut/ConfigGetTest.php
tests/phpunit/unit/Nut/ConfigSetTest.php
tests/phpunit/unit/Nut/DebugEventsTest.php
tests/phpunit/unit/Nut/NutCommandTester.php
tests/phpunit/unit/Nut/RouterMatchTest.php

So, when Carson and I split the config commands into a base class, I meant to override the `initialize()` in that abstract, instead I put it into `BaseCommand` … :man_facepalming: 
Anyway, as we're using `OutputStyle` (`SymfonyStyle`) in quite a few places, and I'd guess mroe to come :wink: 
… and it would be good to have consistently formatted output that is logical for the programmer to write, so I am setting a `null` `$output` to a `ConsoleOutput` (normal) wrapped in a `SymfonyStyle`

[3.3] Avoid Nut BC derp

---

src/Nut/DebugEvents.php

For `./app/nut debug:events`
From:
```
|    #4 | Closure                      |        0 |
```
To:
```
|    #4 | Silex\Application {closure}  |        0 |
```

[3.3] Show source class for closures

---

src/Nut/DebugEvents.php

Calling `./app/nut debug:events kernel.response --sort-listener` would correctly sort the columns by the callable name, but leave the order column linear.
Now:
```
$ ./app/nut debug:events kernel.response --sort-listener
Registered Listeners for "kernel.response" Event
================================================
+-------+----------------------------------------------------------------------------------+----------+
| Order | Callable                                                                         | Priority |
+-------+----------------------------------------------------------------------------------+----------+
|    #1 | Bolt\EventListener\FlashLoggerListener::onEvent()                                |     1000 |
|   #12 | Bolt\EventListener\FlashLoggerListener::onEvent() …
```

[3.3] Keep order number consistent to class when using --sort-listener

---

app/config/config.yml.dist
src/Controller/Backend/FileManager.php
src/Controller/Base.php
src/Controller/Frontend.php
src/EventListener/DisableXssProtectionListener.php
src/EventListener/TemplateViewListener.php
src/Provider/EventListenerServiceProvider.php
src/Render.php
src/Response/TemplateResponse.php
src/Response/TemplateView.php
tests/phpunit/unit/BoltUnitTest.php
tests/phpunit/unit/Controller/Async/FilesystemManagerTest.php
tests/phpunit/unit/Controller/Async/GeneralTest.php
tests/phpunit/unit/Controller/Async/StackTest.php
tests/phpunit/unit/Controller/Backend/AuthenticationTest.php
tests/phpunit/unit/Controller/Backend/DatabaseTest.php
tests/phpunit/unit/Controller/Backend/ExtendTest.php
tests/phpunit/unit/Controller/Backend/FileManagerTest.php
tests/phpunit/unit/Controller/Backend/GeneralTest.php
tests/phpunit/unit/Controller/Backend/LogTest.php
tests/phpunit/unit/Controller/Backend/UsersTest.php
tests/phpunit/unit/Controller/ControllerUnitTest.php
tests/phpunit/unit/Controller/FrontendTest.php
tests/phpunit/unit/Response/TemplateResponseTest.php
tests/phpunit/unit/Response/TemplateViewTest.php

In regards to #6382
Working on how this can be done without breaking BC, but it's proving challenging.
The only response method called in Frontend was the `X-XSS-Protection` header in record route. So I moved it out.
Now you can do something like:
```php
class MyFrontend extends Frontend
{
protected function render($template, array $context = [], array $globals = [])
{
return new TemplateView($template, array_replace($context, $globals));
}
}
```
and then replace the `controller.frontend` service with that class.
Open to ideas about how to integrate this further. I don't think changing `Controller\Base::render` directly is wise though, since others can base their controllers on it. But maybe if it's something just for Frontend / Backend classes that would be ok. I'm not sure if a separate …

TemplateView

---

src/Provider/DebugServiceProvider.php

See commit messages for details.
:koala: edit:
* Moved invoking/subscribing handler listener to second phase, so it gets the correct parameters from Config
* Replaced `display_errors` and `reporting_level` with `throw_at` and `log_at` DI parameters
* ErrorHandler's "displayErrors" logic is deprecated and we are instructed to use "throw at" logic instead.
This is also better because instead of a boolean we can specify which errors we want thrown (aka displayed to user).
* Additionally, PHP has `display_errors` ini setting which is similar but not the same as ErrorHandler's "display errors" logic.
This is now automatically disabled (if error handler is enabled) since it is not helpful to users.
You can see the error with the logger you've configured and optionally see it inline as an …

Tweaked Error/Exception Handler Configuration

---

app/view/twig/_buic/_select.twig

_This adds support for the disabled attribute to Bolt's select2 field, this is not a bug fix for any particular issue_
It's not currently possible to set options to disabled, adding the disabled attribute to the `optattr` array allows you to pass `disabled:true` in the `conf.options`.
The disabled attribute is **not** useful from the `contenttypes.yml` config. For example - why would you have `values: [ A, B, C ]` and then set `B` to be disabled. It would be disabled on **all** instances of the field and never selectable. 
The disabled attribute is however useful for extension development - where the values array is being dynamically generated. For example, a field that has options you can only use once. If `Page 1` has selected option `B` then on `Page 2` option `B` can be defined as …

Add disabled attribute support to buic select options

---

src/Storage/Entity/Content.php
tests/phpunit/unit/Storage/EntityTest.php

Fixes #6579
Implements the getValues method to work on the new storage entity in the same way the old Content object did.
Includes test.

Implement getValues in new Storage Entity

---

src/Nut/AbstractUser.php
src/Nut/UserAdd.php
src/Nut/UserManage.php
src/Nut/UserRoleAdd.php
tests/phpunit/unit/Nut/UserAddTest.php
tests/phpunit/unit/Nut/UserRoleAddTest.php

You can still run the command will all the options (even multiple roles)
```bash
$ ./app/nut user:add kenneth "Kenny Koala" kenny@koala.com.au T0pSecret editor admin
Account details for 'kenneth'
=============================
----------- -------------------- -------------- --------------- ---------
User name   Email                Display Name   Roles           Enabled 
----------- -------------------- -------------- --------------- --------- 
kenneth     kenny@koala.com.au   Kenny Koala    editor, admin   false
----------- -------------------- -------------- --------------- --------- 
[OK] Successfully created user: kenneth
``` 
Or, if you omit some, or all parameters — 'cause you know _passwords in your command history_ and all — you will be prompted for all options, but with the ones …

Enable no, partial, or full Q&A on Nut user:add

---

src/Twig/Extension/AdminExtension.php
src/Twig/Extension/ArrayExtension.php
src/Twig/Extension/BoltExtension.php
src/Twig/Extension/DumpExtension.php
src/Twig/Extension/HtmlExtension.php
src/Twig/Extension/ImageExtension.php
src/Twig/Extension/RecordExtension.php
src/Twig/Extension/RoutingExtension.php
src/Twig/Extension/TextExtension.php
src/Twig/Extension/UserExtension.php
src/Twig/Extension/UtilsExtension.php
src/Twig/Extension/WidgetExtension.php

In Twig 2.x, Twig_Simple* classes are deprecated for 3.x, and replaced with a name minus "Simple"
* Twig_SimpleFunction -> Twig_Function
* Twig_SimpleFilter -> Twig_Filter
* Twig_SimpleTest -> Twig_Test
This PR will hopefully create less related merge conflict as 3.x changes cascade down to `master`

[3.4][Deprecation] Add migration for Twig_Simple

---

.travis.yml

The guys at Travis are [EOL-ing `sudo` enabled builds](https://blog.travis-ci.com/2017-04-17-precise-EOL), so this just removes the remnants that remained to keep us on their legacy environment.

[Travis] Remove remaining legacy sudo use

---

app/theme_defaults/_sub_pager.twig

When using `{{ pager() }}` without a template, and falling back to default, I'm now getting 
```
Twig_Error_Syntax in Extends.php line 33:
Multiple extends tags are forbidden in "_sub_pager.twig" at line 4.
```
Works fine on =< 3.3

Multiple extends tags are forbidden

---

src/Extension/Manager.php

This is the same check we make above in `register()` … this one was driving me mental on a broken extension I wanted to disable. :laughing:

[3.3] Don't boot disabled extensions

---

app/src/js/widgets/fields/fieldBlock.js

This is #1555 material but fixes the renumbering of named repeaters due to the regex not being escaped correctly.

Fix incorrect Regex escaping

---

composer.json

c.f. https://github.com/bolt/bolt/commit/2c6ac078e0fcd4a18c265d4f4da38d7195105a45#commitcomment-21963034
This was a 2.2 thing, and no [Windows support](http://php.net/manual/en/intro.posix.php) …
Introduced in #6490

Remove outdated requirement on ext-posix

---

app/view/twig/overview/_panel-actions_overview.twig

As pointed out by @eduardomart today, you can set the `description:` for custom contenttypes, but if you have created your own `pages:` for example, it will _always_ use the baked-in description, without allowing you to override it. This PR changes the order: Use the description in contenttypes.yml, and fall back to the baked-in one if it wasn't set.

Allow overriding `description: ` in `contenttypes.yml`.

---

app/view/twig/editcontent/fields/_select.twig

This fixes the bug on the 3.2 branch. It's looking as though the regular breakages may well be due to competing bugs, so once this one is in, I'm going to try a few more permutations... I think it stems from the fact that we use select fields for lots of varying data formats.

[3.2 only] Fix issue with sortable selects not retaining ordering

---

src/Twig/Extension/HtmlExtension.php
theme/base-2016/partials/_aside.twig

A per last night's meeting, and [upstream changes](http://symfony.com/blog/new-in-symfony-3-3-weblink-component).

[3.3] Deprecate and replace use of {{ link() }}

---

app/config/config.yml.dist
app/src/js/modules/extend.js
app/view/twig/extend/extend.twig
src/Composer/JsonManager.php
src/Controller/Backend/Extend.php

* Fix "option" key handling in `extension/composer.json`
* This sends the "Composer" version of Bolt to the marketplace so it can remove packages without matching version constraints
FYI: `simpleforms` is the one I was testing on, as there is nothing available (even `dev-master` is for < 3.0 as it was retired in place of BoltForms)
**NOTE:** This will need an asset rebuild post-merge

[3.2] Fix incompatible extensions showing

---

app/config/config.yml.dist
src/Composer/JsonManager.php

Un-derping a derp in #6616
c.f. https://getcomposer.org/doc/06-config.md

[3.2] Composer config key is called "config", not "options"

---

.codeclimate.yml

CodeClimate have introduced a [grep engine](https://docs.codeclimate.com/v1.0/docs/grep) that might just solve one of my concerns about keeping track of re-introduction of deprecated, or deprecation prevention, code.
Firstly, I have added a check on new tests for PHPUnit deprecations … we can go from there.
As CodeClimate test on `release/3.3` and PRs only, I am going to use this one as a testing ground until happy, i.e. …

[CodeClimate] Enable grep engine

---

src/Provider/NutServiceProvider.php

This will prevent the classes from building on web requests :woman_facepalming:

[3.3] Only set environment for Nut Twig commands on CLI

---

composer.json
src/Provider/TwigServiceProvider.php

Having the web profiler bundle locked at ^2.8 is holding back a few feature branches, and all paths lead to Silex.
Includes a few "workarounds" that I'll pull out in the Silex 2 branch post-merge … the hacks aren't goin' to production :wink:

[4.0] Update web profiler bundle to Symfony 3

---

app/theme_defaults/_sub_fields.twig
theme/base-2016/partials/_sub_fields.twig

Fixes #6605. Or rather work around it, as we discussed. 
I've hardcoded the message, because: 
- It is temporary, until we complete the transition to Bolt\Storage
- It's very much an edge case.

Show a message for when using Preview if using `fields()` _and_ Repeaters.

---

app/src/js/obj-validation.js
app/view/twig/editcontent/fields/_html.twig

Make sure `wysiwyg` fields have the correct label, strip trailing `:` from alerts.

---

app/theme_defaults/_sub_fields.twig
src/Storage/Entity/ContentValuesTrait.php
theme/base-2016/partials/_sub_fields.twig

Set default values for Video field, prevent exceptions

---

src/Twig/Extension/ArrayExtension.php

Fixes #6561
Reindex merged unique arrays on the key so we have a standard way to check available values
This replicates the setup we currently have in 3.2 and recently fixed.

[3.3] Fix for sortable selects.

---

app/src/js/widgets/fields/fieldVideo.js
app/view/twig/editcontent/fielddata/_video.twig
composer.json
src/Application.php
src/Controller/Async/Embed.php
src/Embed/GuzzleDispatcher.php
src/Embed/Resolver.php
src/Exception/EmbedResolverException.php
src/Provider/ControllerServiceProvider.php
src/Provider/EmbedServiceProvider.php

Does the job, gets us through, relies on the SF Forms token to be valid in editcontent …
… RFC
Fixes #6635

[3.2] Switch Embed.ly to oEmbed API

---

src/Controller/Async/General.php
src/Controller/Async/Stack.php
src/Controller/Async/Widget.php
src/Controller/Backend/Authentication.php
src/Controller/Backend/Users.php
src/Controller/Base.php
src/Controller/Frontend.php
tests/phpunit/unit/Controller/Async/FilesystemManagerTest.php
tests/phpunit/unit/Controller/Async/GeneralTest.php
tests/phpunit/unit/Controller/Async/StackTest.php
tests/phpunit/unit/Controller/Backend/AuthenticationTest.php
tests/phpunit/unit/Controller/Backend/ExtendTest.php
tests/phpunit/unit/Controller/Backend/GeneralTest.php
tests/phpunit/unit/Controller/Backend/UsersTest.php
tests/phpunit/unit/Controller/FrontendTest.php

* Don't crash when TwmplateView is really enabled
* Fix config lookup of "compatibility" config values
* TemplateView BC for routes accessing a rendered response, assuming a Response object
* Render email with Twig, as Swiftmailer messages need strings
* Controller helper to add a middleware that sets the response caching parameters
* Render maintenance mode template directly, as before() is before other listeners
* Dispatch view events for stack add() renders, as they are returned inside JSON
* [Tests] Update for template view, and test legacy on front-end

[3.3] Fix TemplateView handling

---

src/Embed/GuzzleDispatcher.php
src/Embed/Resolver.php
src/Provider/EmbedServiceProvider.php
tests/phpunit/unit/Embed/ResolverTest.php

Time-pressure-free follow up on #6636
* Correctly handle redirected URLs (bug fix)
* Add parameters to the configuration service
* Shrink resolver code
* Implement `GuzzleDispatcher::dispatchImages()` — this isn't (yet?) used internally, but an unfinished interface and Team OCD :stuck_out_tongue_winking_eye: 
* P.S. Not handling Guzzle 5 on this one, did someone say "internal & currently unused"

[3.2] Embed updates

---

src/Storage/Mapping/MetadataDriver.php

Currently you can `$app['storage']->getRepository('bolt_pages')` (or any CT), and the repo will resolve.
This PR allows `$app['storage']->getRepository('bolt_log_system')`, instead of having to `$app['storage']->getRepository(\Bolt\Storage\Entity\LogSystem::class)`

[3.3] Allow lookup of non-ContentType repositories by alias

---

src/Controller/Backend/Log.php
src/Storage/Repository/LogChangeRepository.php
tests/phpunit/unit/Logger/ChangeLogTest.php

[3.3][Deprecation] LogChangeRepository::countChangeLog()

---

src/EventListener/StorageEventListener.php
src/Provider/StorageServiceProvider.php
tests/phpunit/unit/EventListener/StorageEventListenerTest.php

Fixes #6651 by adding a pre-delete event to delete an entity's taxonomy entities.
/me waves at @sbonardt

[3.2] Fix orphan taxonomy entities on delete

---

src/Storage/Mapping/MetadataDriver.php

Invert `$column->getNotnull()` return value as it defines if a column is **not** nullable … I'm calling :koala:

[3.2] Fix metadata nullable assignment

---

src/Storage/Entity/Content.php
src/Storage/Entity/Entity.php
src/Storage/Entity/LogSystem.php

This gives all entities the ability to use `$entity->get($fieldName')` or `$entity->set($fieldName, $fieldValue')`.
Previously only ContentType entities could use this, and the `set()` is preserved in the CT entity as it additionally filters the `$value` array, and while that's fine for our ContentTypes, it is not a decision we should make for other entities.
Also with the current state, should you make the mistake of calling `get()` or `set()` on a non-CT entity currently, the magic method strips the prefix, ending up with an empty key to tray and find a value with.
A note on the forwarding of the calls, a number of entity getters & setters handle mutation.

[3.4] Base entity get()/set()

---

src/Provider/MailerServiceProvider.php

Deprecated upstream, and already gone from their `master`

[3.3][Deprecation] Swift_MailTransport

---

src/Configuration/PathResolver.php
src/Exception/PathResolutionException.php
tests/phpunit/unit/Configuration/PathResolverTest.php

- A `PathResolutionException is now thrown when infinite recursion is detected.
- An `InvalidArgumentException` is now thrown when trying to define a path that references itself.
- Added `names()` which returns a list of defined names.
- Removed `resolveAll()` it wasn't used and if needed one can loop using `names()` method.

Fix PathResolver infinite recursion

---

src/Nut/Helper/QuestionHelper.php
src/Nut/Helper/Table.php
src/Nut/Helper/Terminal.php
src/Nut/Output/Capture.php
src/Nut/Output/OutputWrapperTrait.php
src/Nut/Output/OverwritableOutput.php
src/Nut/Output/OverwritableOutputInterface.php
src/Nut/Style/NutStyle.php
src/Nut/Style/OverwritableStyleInterface.php

This will help in making more interactive console commands. 
It is already used in the incoming composer project configurator changes.
This adds functionality to ask questions and then remove the output.
```php
$io = new NutStyle($input, $output);
$name = $io->askThenRemove('Name?', $default = 'Carson');
$password = $io->askHiddenThenRemove('Password?');
if ($io->confirmThenRemove('Continue?', $default = true)) {}
$color = $io->choiceThenRemove('Pick color', ['red', 'blue'], $default = 'blue');
```
After each answer the question & answer are removed from the terminal.
This also adds a `Table` which can overwrite previous data. 
```php
$table = new Table($output);
while (true) {
$data = []; // determine (new/updated) data
$table->setRows($data);
$table->overwrite();
sleep(1);
}
```
Instead …

Overwritable Output

---

app/view/twig/_base/_listing.twig
app/view/twig/_base/_page.twig
app/view/twig/_nav/_footer.twig
app/view/twig/_nav/_primary.twig
app/view/twig/_sub/_messages.twig
app/view/twig/activity/changelog.twig
app/view/twig/editcontent/_taxonomies.twig
app/view/twig/editcontent/editcontent.twig
app/view/twig/editcontent/fields/_meta.twig
app/view/twig/mail/passwordreset.twig
app/view/twig/users/_userlist-actions.twig
app/view/twig/users/_userlist.twig
src/Controller/Backend/BackendBase.php
src/Controller/Backend/Records.php
src/Legacy/Storage.php
theme/base-2016/extrafields.twig
theme/base-2016/page.twig
theme/base-2016/partials/_sub_fields.twig
theme/base-2016/readme.md
theme/base-2016/record.twig

As per discussion in Tuesday's meeting.
@CarsonF On the `BackendBase` controller one, I know, I know … but scope … believe me they are used all over backend templates, and refactoring the entire backend template logic this close to release is just not on 
… my O.C.D. too :disappointed:

[3.3] Remove remaining Twig global use

---

tests/phpunit/unit/Composer/PackageManagerTest.php

So, I got lazy when writing `PackageManagerTest::testGetAllPackages` and didn't cover extensions that Bolt considers under management … this PR just adds that.
I also made another tiny _boo-boo_ assumption — _invoking the Samuel L. Jackson Laws of Assumption_ — that **never happened**, it was a :koala:

[3.3][Tests] Cover installed Composer extensions in PackageManagerTest

---

composer.json

* `squizlabs/php_codesniffer` is only required by `bolt/codingstyle` so moved there
* `phpmd/phpmd` isn't used, can be downloaded or installed separately, and has a dependency chain that is making me want to :cry:

[3.3] Remove phpmd/phpmd & squizlabs/php_codesniffer from require-dev

---

src/Storage/Repository/ContentRepository.php

Correctly set the ordering for select dropdown lists, so it's not reversed anymore. 

---

app/view/twig/editcontent/fields/_select.twig

Fixes weird default selection of `/` for select fields populated from other contenttypes.

---

src/EventListener/DisableXssProtectionListener.php

According to standard in [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.2.1)
>   Of the request methods defined by this specification, the GET, HEAD,
>   OPTIONS, and TRACE methods are defined to be safe.
So Symfony have [deprecated its use in 3.2](https://github.com/symfony/symfony/commit/34e7b956dd46cc03973ba90ce93523557a26a3e0) without a parameter to indicate spec, or BC.
… just keeping `master` quiet :wink:

[3.3][Deprecation] Use Request::isMethodSafe() according to standard

---

theme/base-2016/search.twig

The include of the pager seemed to be missing, the comment was the only thing there

Add pager to base-2016 search template

---

app/theme_defaults/maintenance_default.twig
theme/base-2016/listing.twig
theme/base-2016/partials/_aside.twig
theme/base-2016/partials/_header.twig
theme/base-2016/partials/_master.twig

I have to admit, "missed" is something of a misnomer as it turned out. I was checking something and found a few of these that were missed in the 3.3 work, and as 3.2 is going to stay open for a while, I figured this bit is safe here as `app.config` and `config` are the same object.

[3.2] Missed 'app.config' to 'config' changes

---

app/resources/translations/cs_CZ/messages.cs_CZ.yml
app/resources/translations/de_DE/messages.de_DE.yml
app/resources/translations/el/messages.el.yml
app/resources/translations/en_GB/messages.en_GB.yml
app/resources/translations/es_ES/messages.es_ES.yml
app/resources/translations/fi/messages.fi.yml
app/resources/translations/fr/messages.fr.yml
app/resources/translations/hu/messages.hu.yml
app/resources/translations/id/messages.id.yml
app/resources/translations/it/messages.it.yml
app/resources/translations/ja/messages.ja.yml
app/resources/translations/nb/messages.nb.yml
app/resources/translations/nl_NL/messages.nl_NL.yml
app/resources/translations/pl_PL/messages.pl_PL.yml
app/resources/translations/pt/messages.pt.yml
app/resources/translations/pt_BR/messages.pt_BR.yml
app/resources/translations/ru/messages.ru.yml
app/resources/translations/sv_SE/messages.sv_SE.yml
app/resources/translations/zh_CN/messages.zh_CN.yml
app/resources/translations/zh_TW/messages.zh_TW.yml
src/Translation/TranslationFile.php

Refresh of the translation keys for 3.2 … others branch will follow on merge.
I have also removed the "generated on" and some whitespace from the generated comment block at the top of the file, as presently this just adds to the size of a language file PR, and it is a potential for conflicts.

[3.2] Translations refresh

---

app/bootstrap.php
src/Bootstrap.php
src/Composer/Script/BootstrapYamlUpdater.php
src/Composer/Script/DirectoryConfigurator.php
src/Composer/Script/DirectorySyncer.php
src/Composer/Script/Options.php
src/Composer/Script/PathCustomizer.php
src/Composer/Script/ScriptHandlerUpdater.php
src/Composer/ScriptHandler.php
src/Configuration/PathDependencySorter.php
src/Configuration/ResourceManager.php
src/Exception/BootException.php
src/Provider/PathServiceProvider.php
tests/codeception/extensions/CodeceptionEventsExtension.php
tests/phpunit/unit/Composer/Script/BootstrapYamlUpdaterTest.php

ScriptHandler updates

---

composer.json

Codeception & Symfony PHPUnit Bridge are both trying to class alias PHPUnit 4/5 classes to v6 namespaced ones, this breaks Codeception tests. :boom:

[4.0] Lock Codeception (again) at version 2.3.1

---

.travis.yml
src/Render.php
tests/scripts/deprecation-check.sh

This adds checks to the Travis tests for use of deprecated Twig & PHPUnit classes, and fixes one instance in `src/`.
See the Travis run for output :smile:

[3.4][Tests] Deprecation use checks

---

src/Composer/Script/DirectoryConfigurator.php
src/Composer/Script/PathCustomizer.php

OK, so this is hours of hammering out different use-cases and debugging minus xdebug :disappointed: 
The `exists()` & `mkdir()`s need to be in both places, as if you don't modify paths, you skip the directory renaming logic, which itself needs to verify/create the target or target's base. Literally a catch-22.
Now the `define()`s were interesting, as my base use-case was to use `%site%/web/` for `web`, and `%web%/bolt-web/view` for `bolt_view`. So we move the parent first, then siblings. That meant that as the `bolt_view` sibling's base had already changed, the resolvers still thought it was located elsewhere. If someone can check my logic a few ways on that, I'd be grateful, it was a lot to think though in a short period of time.
Finally, the `explode()` part is ugly as sin, but it can …

[3.3] Script handler

---

composer.json

The 1.* version requirement pulls in the latest versions of both annotations and collections and these require PHP 5.6 or later.
Specifying 1.2 and 1.3 respectively ensures the versions match the platform requirements of Bolt.

[2.2] Be more specific with DBAL dependency versions

---

app/config/contenttypes.yml.dist

Closes #6736
We've been using `published` internally since at least 2.2, if not earlier, but the changes never cascaded though to the `contenttype.yml.dist` … I blame the :koala:

[3.2] Update legacy default status use

---

.gitignore

* Group ignores contextually … Moar pretty :stuck_out_tongue_winking_eye: 
* Remove `!theme/default` as it is no longer in the repo
* Remove duplicate `!yarn.lock`
* Remove Codeception v1 ignores
* Removed `web`, `/tags` & `.gitignore` … WTF?
* Removed `/bolt.log` as it is written to the cache directory

[3.2] Clean up .gitignore

---

composer.json

Upstream has made sufficient changes that these two versions now work together again.
Lets hope this is the last of this "fun" :wink:

[4.0][Tests] Update Ccodeception to ^2.3.3 & PHPUnit Bridge to ^3.3.2

---

src/Cache.php

**DISCLAIMER:** Team O.C.D. triggers within!
Under edge-case circumstances running `./app/nut cache:clear` would produce the following exception:
```
[UnexpectedValueException]
RecursiveDirectoryIterator::__construct(app/cache/development/data): 
failed to open dir: No such file or directory
```
The `app/cache/` _project _ directory will usually contain a `.version` file, that let's Bolt quickly check (on `boot()`) if the running version matches last boot … if not, it will perform some additional work … such as clearing the cache.
Problem being that our implementation goes on to delete a bunch of other directories, one of which will contain Doctrine's cache directory.
Doctrine's cache only checks for the existence of, and creates if missing, its target directory **on construct**. This is …

[3.2] Fix edge-case cache:clear fails

---

app/bootstrap.php
composer.json

Composer doesn't use any mbstring functions in the autoloader, only in the RFS where it checks for the module. Additionally, from [PHP 5.6 onward](http://php.net/manual/en/ini.core.php#ini.default-charset), UTF-8  is default (see link for more details).
So this PR, removes the requirement from `composer.json`, and moved the function calls to just after the autoloader.

[3.3]  Remove hard requirement on PHP mbstring extension

---

app/bootstrap.php

PHP 5.5 is no longer supported, and from PHP 5.6 the defaults are UTF-8.
Follow-up to #6748

[4.0] Remove mb_internal_encoding() & mb_http_output() from bootstrap

---

.gitignore
app/config/config.yml.dist
src/Composer/Action/BaseAction.php
src/Configuration/PathResolver.php
src/Provider/FilesystemServiceProvider.php
src/Provider/LoggerServiceProvider.php
src/Provider/SessionServiceProvider.php
var/.gitignore

tl;dr Keep volatile/generated data out of `app/` and in `var/` … as it done on real operating systems! (yes @SahAssar, that dig/joke was especially for your amusement :wink:)
In Symfony 3, things got a little more sane as far as the location of different filesystem targets, full details on the [Symfony Best Practices guide](http://symfony.com/doc/current/best_practices/creating-the-project.html#structuring-the-application), but in brief a **project's** layout should look something like this (slightly adjusted for Bolt)
```
%site%/
├─ app/
│  ├─ config/
│  └─ Resources/
├─ bin
│  └─ nut
├─ src/
│  └─ {bundled(s)}
├─ var/
│  ├─ cache/
│  ├─ logs/
│  └─ sessions/
├─ tests/
├─ vendor/
└─ web/
```
Where:
| | Description
|-|----------------
| `app/` | The application configuration, templates …

[4.0] Phase I: Symfony 3 & Silex 2 project filesystem layout

---

src/Legacy/PasswordLib/PasswordLibFactory.php
src/Legacy/PasswordLib/PasswordLibRandomGenerator.php
src/Provider/AccessControlServiceProvider.php

This specifically fixes `/dev/urandom` not being readable. This is all throw away code once we don't need PasswordLib anymore.

Change passwordlib to use random_bytes instead of any of its sources.

---

src/Storage/Entity/ContentSearchTrait.php
tests/phpunit/unit/Storage/StorageTest.php

This PR fixes a bug where a search like "a nice day" will crash the site if there is any content containing "day". 
Details
-------
The crash is triggered because single character search words like "I" or "a" are filtered out before the search in a way that leaves the search words index dirty. When matches are found and the index is used to weight the results, the app crashes.
PS: I don't like brown M&Ms

fix complex search crash bug

---

src/Filesystem/FilePermissions.php

"Edit configuration" links won't work on installed extensions in 3.3-HEAD right now
Fixes: #6763

[3.3] Allow 'extensions_config' as a prefix for FilePermissions checks

---

app/view/twig/editcontent/fields/_filelist.twig
app/view/twig/editcontent/fields/_imagelist.twig
src/Controller/Backend/Records.php
src/Filesystem/Matcher.php

Currently in 3.3-HEAD, if you add a file to a filelist field, and that file is removed afterwards, the page will crash and be un-editable except for directly accessing the database, or replacing (which?) the file :wink: 
```
Twig_Error_Runtime in Template.php line 230:
An exception has been thrown during the rendering of a template ("File not found at path: 2017-06/refactor-wars.png") in "@bolt/editcontent/fields/_filelist.twig" at line 67.
```
This PR:
- Adds a method to the path bridging `Matcher` class to check for the file's existence, prior to accessing it, which if not found **correctly** throws an exception.
- Display's "known" information from the database when not found, and changes the icon to a `?`
- Obviously that is UI, so "go for it" requesting changes to that, I just picked …

[3.3] Prevent filelist exceptions when file not found

---

src/Storage/Field/Type/FieldTypeBase.php
src/Storage/Query/Handler/SearchQueryHandler.php
src/Storage/Query/Handler/SelectQueryHandler.php
src/Storage/Query/SelectQuery.php
tests/phpunit/unit/Storage/Query/ContentQueryParserTest.php
tests/phpunit/unit/Storage/Query/SearchQueryTest.php
tests/phpunit/unit/Storage/Query/SelectQueryTest.php

Fixes #6691
Whenever we build queries in the new storage engine, this prepends a `_` to the contenttype alias which prevents clashes with field names defined in `contenttypes.yml`
Tests also updated to add the underscore.

Fix for queries where fields have the same name as contenttype

---

theme/base-2016/partials/_sub_field_blocks.twig
theme/base-2016/partials/_sub_fields.twig

* With `strict variables: true` and an empty video field, `{{ fields() }}` will exception
* HTML is escaped
The macros were flat out — text book style — abusing the the purpose of them, so I have moved them to blocks.
Honestly after looking at the code in Twig & PHP for this, I am proposing we rip out `{{ fields() }}` in v4 … **Seriously!**

[3.2] base-2016 fixes and facepalms

---

src/Translation/Translator.php

Via a bug reported in Slack channel, if your locale is set to en_gb then we don't want it to count as a fallback locale.
The `transcontenttype` method finds a specific ContentType translation before moving down to the generic one but if your locale is set to en_gb then the specific translation always appears as to be a fallback one and thus gets ignored in favour of the generic.

Fix for specific ContentType translations being ignored

---

app/theme_defaults/_sub_field_blocks.twig
theme/base-2016/partials/_sub_field_blocks.twig

As a followup of db5a488. Looks like some code got duplicated in the merge-down to `release/3.3`, since `release/3.2` is OK.

Remove duplicated code in _sub_fields_blocks.twig

---

app/config/config.yml.dist

Switched out Sendgrid for Sparkpost, because Sendgrid changed their pricing model and now only offer free trails, and Sparkpost is still free up to 100.000 mails

Config update

---

app/theme_defaults/_sub_field_blocks.twig
app/theme_defaults/_sub_fields.twig
src/Twig/Extension/RecordExtension.php
src/Twig/Runtime/RecordRuntime.php
theme/base-2016/extrafields.twig
theme/base-2016/notfound.twig
theme/base-2016/page.twig
theme/base-2016/partials/_sub_field_blocks.twig
theme/base-2016/partials/_sub_fields.twig
theme/base-2016/readme.md
theme/base-2016/record.twig

Let's try again shall we :wink: 
This PR:
- Fully deprecates the Twig function `{{ fields() }}`
- Cut over to full use of blocks in `base-2016`
- Derpy derp on copy/pasta
Matching v4 PR is #6781

[3.3] Deprecate {{ fields() }} and move to a block call

---

app/view/twig/firstuser/firstuser.twig
src/Controller/Backend/Users.php

This PR adds the results of required & recommended checks from `bolt/requirements` to first user screen.
If everything is good:
An example of a recommendation failure, i.e. not super critical, but well advised:
An example of a required setting failure:
---
We obviously need to tweak the heck out of `bolt/requirements` … but that is also dependency of the Nut `setup:run` command, so linked requirements … just puts the motivation in front of a few more eyes :wink: 
Also, I am re-enforcing my disclaimer about Gawain + Visuals … I suck at them … so if we like the "feature", send it in and the UI team can do their magic to make the interface for this kick butt :tada:

[3.4] Requirement & recommended setting checks on first user

---

app/resources/translations/en_GB/messages.en_GB.yml
app/view/twig/_nav/_secondary-configuration.twig
app/view/twig/checks/_aside.twig
app/view/twig/checks/checks.twig
src/Configuration/Check/BaseCheck.php
src/Configuration/Check/ConfigurationCheckInterface.php
src/Configuration/Check/DirectoryAccess.php
src/Configuration/Check/EmailSetup.php
src/Configuration/Check/PhpExtensions.php
src/Configuration/Check/Result.php
src/Controller/Backend/General.php
src/Menu/AdminMenuBuilder.php

We've had this route, and the aysnc controller that isn't even used, since 3.0-dev, so this PR basically just adds it to the menu, and updates the admin route & templates to use `bolt/requirements`
Eye candy (_normal UI team disclaimer_):
**Edit:** The screenshot for #3602 (original PR) is, with hindsight, pretty funny; "Bolt 2.3.0 alpha 1" … 2 years ago

[3.4] Refresh config checks page

---

src/Storage/Entity/Content.php

Fixes #6790
Because we don't send null values to the database to save, we end up not persisting templatefields if all the values are cleared.
This ensures that a null templatefields is converted to an empty array instead and then will get saved to the db.

Always reset null templatefields to an empty array instead

---

src/Helpers/Input.php
src/Storage/ContentRequest/Edit.php
src/Storage/Entity/ContentValuesTrait.php

The current Bolt 3.2 Edit action loads each incoming related record in it's own DB query. If you have more than a couple hundred objects, the edit page will no longer load as you get memory and execution time problems.
After some discussions with @GawainLynch, it seems a "proper" solution using the new storage layers is already available but might not be portable as fast as needed. This quick fix is intended as a temporary solution until the loading is refactored to the new mechanism. (Also keep in mind that rendering 10000 related objects in twig might still not be advisable ;) )

[BUG/CR] 3.2 - Quick fix for content with large lists of incoming relations

---

src/Composer/Script/BootstrapYamlUpdater.php
src/Configuration/PathResolver.php
tests/phpunit/unit/Composer/Script/BootstrapYamlUpdaterTest.php

Fixes #6797
OK, so this was a bit of fun to debug with a brain that is only coming back into business mode … not to mention keeping backward **and forward** compatibility working.  :rofl:
This PR addresses the first problem I hit with `BootstrapYamlUpdater` updating custom path handling:
* Add forward-compatible path resolution for `var/` (it's in active use in the wild on 3.2+ sites)
* Handle FC path updating for use of `var/`
* Don't assume that a path that defaults to being under `app/` is actually under `app/`
* Adds a note on debugging Composer for ageing princesses with memory recall problems :stuck_out_tongue_winking_eye: 
Bolt 3.2.x use/test case, taken from a production site:
```yaml
paths:
var: var
cache: var/cache
config: app/config
database: app/database
web: web
themebase: …
```

[3.3] Fixes for .bolt.yml / .bolt.php custom path handling

---

app/theme_defaults/_sub_field_blocks.twig
app/theme_defaults/_sub_fields.twig
theme/base-2016/extrafields.twig
theme/base-2016/page.twig
theme/base-2016/partials/_sub_field_blocks.twig
theme/base-2016/partials/_sub_fields.twig

So while tracking down a small bug in 3.3, I found several more all stemming from this area. I double checked and they were present from 3.2 onward, so I thought I'd back-port the "two-liner" to 3.2 … and all hell broke lose, wasting several hours of work nobody really has time to waste. :disappointed: 
The differences between 3.2 & 3.3 were substantial enough to make this a long and painful process, exacerbated by the fact that we have:
- `theme/base-2016/partials/_sub_field_blocks.twig` supposed to be identical to `app/theme_defaults/_sub_fields.twig`
- `theme/base-2016/partials/_sub_field_blocks.twig` supposed to be identical to `app/theme_defaults/_sub_field_blocks.twig`
… and #6810 inbound adding a third copy of each, to make this harder to track and keep up-to-date.
Which leave us …

[3.2+] More refactoring of fields blocks

---

src/Cache.php

Closes #6562
This is just a hacky workaround for systems with poorly configured umasks … 'nuf said. We'll pick the rest of this up when we re-do caching soon.
Grabbed the deprecation on `Bolt\Filesystem\AggregateFilesystemInterface` while I was there.

[3.2] Cache directory group permissions

---

app/view/js/uikit/marked.js
app/view/twig/editcontent/fields/_markdown.twig

The workaround to the issue reported on Slack is in the `_markdown.twig` commit, and yeah. As far as hacks go, this one really churns my stomach :disappointed: 
Also, while looking at the upstream project and its 350 open issues & 162 open PRs, I found the one commit that has landed in the last year was an XSS fix in the sanitise method … that the maintainer isn't interested in tagging as he's "out grown" the project and abandoned it for all intensive [sic/humour] purposes.
Granted we don't use the sanitise, but the project is now un-maintained and the project owner is unwilling to take fixed security issues seriously! :fire: 
For all the above reasons, we need to ditch this :hankey: pretty soon.

[3.2] Fix doubled OL button in Markdown editor

---

src/Provider/TranslationServiceProvider.php

Pimple 3.2 was released overnight, bringing with it an `InvalidServiceIdentifierException` exception when extending a protected closure. This makes perfect sense, and was missed in the Silex 2 branch.
This PR is just to keep master running (and testable) until @CarsonF's pending translation refactor lands. "Go you big red fire engine!"

[4.0] Change $app['translator.resources'] to not extend a protected closure

---

src/Asset/AssetSortTrait.php

Closes #6751
Relevant bolt/docs#746
Note that this is a BC break, documentation update to follow.

[4.0] Reverse asset sort priority so higher numbers have higher priority

---

app/view/twig/_base/_fieldset.twig

For 3.3 and up.
Fields of `type: hidden` would still output an "empty" label, showing up as a single semi-column:

Only add the label, when the label isn't empty

---

app/src/lib/Versions.md
app/view/twig/editcontent/fields/_select.twig
src/Form/Resolver/Choice.php
src/Provider/StorageServiceProvider.php
src/Storage/ContentRequest/Edit.php
src/Twig/Handler/ArrayHandler.php
tests/phpunit/unit/Form/Resolver/ChoiceTest.php
tests/phpunit/unit/Twig/Handler/ArrayHandlerTest.php

Closes #6834
Closes #6835
Related: #4865, #5441, #6096, #6291, #6332, #6355, #6561, #6610, #6638, #6834
Test coverage on `ArrayHandler::unique` & `Bolt\Form\Resolver\Choice` at 100% LoC … More data input use-cases needed, but this get a lot of them.

[3.2] Select fields … The sage continues

---

src/Bootstrap.php
tests/phpunit/unit/Bootstrap/BootstrapTest.php

A class thatt doesn't exist can't implement an interface, so this should be checked first.

More descriptive exception when the bundled-extension class does not exist 

---

composer.json
src/Provider/TranslationServiceProvider.php

This PR reverts a change hot-fixed recently due to a patch release derp break in Silex 2.1.x, and bumps the require to ^2.2.

[4.0] Silex 2 upstream fixes

---

src/Form/Resolver/Choice.php
tests/codeception/_support/YamlHelper.php
tests/codeception/acceptance/101-BackendEditor/BackendEditorCest.php
tests/phpunit/unit/Form/Resolver/ChoiceTest.php

[3.2] Keeping `keys:` intact for select fields. 

---

README.md

Tagging as an RFC as I have no great opinion on this one, just having fun and seeing what we can do.
The currently implemented options are:
* ![](https://slack.bolt.cm/badge/active) — Active users
* ![](https://slack.bolt.cm/badge/ratio) — Active/total ratio 
* ![](https://slack.bolt.cm/badge/total) — Total user count

Include Slack channel count badge

---

src/Form/Resolver/Choice.php

Fixes #6877
I think this one must have got lost in the re-org.
When using the following syntax:
```yml
entrylink:
label: Link to Entries
type: select
values: entries/title
sort: -title
multiple: true
```
The selects should be ordered by descending title, default is to sort by ascending column in the values field.

Restore support for sorting in Contenttype Selects

---

src/Composer/PackageManager.php
src/Controller/Backend/Extend.php
tests/phpunit/unit/Composer/PackageManagerTest.php

- Invalid AJAX package queries will be more informative, e.g. the Nginx problem that @bhrobinson hit yesterday 
- Use the Composer CaBundle to check for CA bundles … no more `open_basedir` :hankey: 
Yes, the whole Composer layer needs a redo … just not now!

Smack some sense into extension page failures

---

app/nut
app/web.php
composer.json
src/Application.php
src/Exception/BootException.php

Owing to a [`serialize()`](https://bugs.php.net/72229) bug, [Nicolas has bumped](https://github.com/symfony/symfony/pull/23703) the Symfony PHP 7.0 requirement to 7.0.8.
This just leaves an audit trail in our code :wink:

[4.0] Set minimum PHP requirement to 7.0.8

---

app/view/twig/_base/_listing.twig
src/Helpers/Excerpt.php

Fixes #6897
- The first integer in the excerpt was the sortorder, excluded that from the excerpt filter
- Fixed username not being displayed

Fix listing issues

---

app/view/twig/_base/_listing.twig
app/view/twig/_macro/_macro.twig
app/view/twig/_nav/_primary.twig
app/view/twig/async/browse.twig
app/view/twig/exception/_request.twig
app/view/twig/files/_files.twig
app/view/twig/files/_folders.twig
app/view/twig/files_ck/_files.twig

So while debugging some performance regressions that need to be addressed, the first one to pop up was in `Bolt\Helpers\Excerpt` … it's really slow :disappointed: 
The simple test below shows it to consistently be **5 - 7 times slower** that the native Twig function (+20ms on listing pages with only 5 records).
This PR just replaces its use where it make sense. More PRs to come :wink: 
```php
#!/usr/bin/env php
<?php
include_once __DIR__ . '/vendor/autoload.php';
function excerpt($content, $length = 200, $focus = null)
{
$excerpter = new Excerpt($content);
$excerpt = $excerpter->getExcerpt($length, false, $focus);
return $excerpt;
}
$env = new Twig_Environment();
$subject = 'Bolt is an open source Content Management Tool, which strives to be as simple and straightforward as possible. It …
```

[3.3] Performance: Replace slow |excerpt use with |slice

---

app/view/twig/_base/_page.twig

Fixes #6891
So this one has been laying dormant since #5836 back in September 2016 (c.f. https://github.com/bolt/bolt/commit/fb5a7c65beead0092b24189c2b67cc7fe647e458) … and to think I spent ages swearing at JavaScript, when it was just the locale files not loading :rofl: 
This is turning into a day of "bugs due to a single missing character" :champagne:

[3.3] Fix incorrect date formatting

---

app/view/twig/_base/_listing.twig
app/view/twig/_base/_page.twig
app/view/twig/_macro/_macro.twig
app/view/twig/_nav/_macros.twig
app/view/twig/_nav/_primary.twig
app/view/twig/async/browse.twig
app/view/twig/exception/_request.twig
app/view/twig/files/_files.twig
app/view/twig/files/_folders.twig
app/view/twig/files_ck/_files.twig

While working on what ended up not being needed for #6904, I noticed that we already use `|slice` in several places with shorthand notation, so updated and committed there.
Seeing as nothing more was needed for #6904, I am just sending this in on its own to be included with 3.3.2 that I'll tag today or tomorrow.

[3.3] Twig consistency

---

app/config/config.yml.dist

Looks like a typo - the `<dt>` element wasn't allowed but a `<dh>` element was - as far as I can tell, the `<dh>` element doesn't exist

Allow definition lists

---

composer.json

Dear watchers & internet historians,
- PHP 7.2-beta3 was released yesterday, and will likely be the last beta before RC and planned release in November
- Bolt 3.2 is scheduled to be End Of Life (EoL) on the 24th of August but will have a final release tagged before the EoL is final
- Bolt 3.3 is now in stable release cycle and will EoL with the upcoming release of 3.4 stable next month
For all these reasons we've collectively decided to make the require change to Bolt to have it safely run on PHP 7.2 as part of the upcoming Bolt 3.4 release. This is due to some changes needed being a little more than we're comfortable to put into a (currently) stable release.
When PHP 7.2.0 GA ships in November, stable Bolt releases will support it.

[3.2] Set maximum PHP version to be < 7.2

---

src/AccessControl/AccessChecker.php

Fixes #6915
Follow up to #6670

[3.4] Catch InvalidFieldNameException in revokeSession()

---

.travis.yml

HHVM is basically untestable, and uninstallable  We owe Facebook tremendous thanks for it, as it has pushed the PHP core team to really make huge improvements over PHP 5. However it just sits there and fails testing, nobody except for me has ever tried to get past that, and having it in Travis is just a waste of resources.
This however enables testing against PHP "nightly" builds, which is probably something of a misnomer but is bleeding edge PHP nonetheless, giving us visibility on upcoming breakage faster than waiting on me to update my test environment

[Travis] Drop HHVM and add PHP nightly builds

---

app/resources/translations/cs_CZ/messages.cs_CZ.yml
app/resources/translations/de_DE/messages.de_DE.yml
app/resources/translations/el/messages.el.yml
app/resources/translations/en_GB/messages.en_GB.yml
app/resources/translations/es_ES/messages.es_ES.yml
app/resources/translations/fi/messages.fi.yml
app/resources/translations/fr/messages.fr.yml
app/resources/translations/hu/messages.hu.yml
app/resources/translations/id/messages.id.yml
app/resources/translations/it/messages.it.yml
app/resources/translations/ja/messages.ja.yml
app/resources/translations/nb/messages.nb.yml
app/resources/translations/nl_NL/messages.nl_NL.yml
app/resources/translations/pl_PL/messages.pl_PL.yml
app/resources/translations/pt/messages.pt.yml
app/resources/translations/pt_BR/messages.pt_BR.yml
app/resources/translations/ru/messages.ru.yml
app/resources/translations/sv_SE/messages.sv_SE.yml
app/resources/translations/zh_CN/messages.zh_CN.yml
app/resources/translations/zh_TW/messages.zh_TW.yml
app/view/twig/dbcheck/dbcheck.twig
src/Controller/Backend/General.php
src/Storage/Database/Prefill/Builder.php
tests/phpunit/unit/Storage/Database/Prefill/BuilderTest.php

- Allow for consecutive prefills, with the Lorem Ipsum generator
- Fix logic error in `$form->get('contenttypes')->has('contenttypes')`
- Small UI change: show the "prefill with Lorem Ipsum" button not only after finished DB check.
Fixes #6917.

[3.4] Allow for consecutive prefills. 

---

app/view/twig/_nav/_secondary.twig
src/Extension/MenuTrait.php
src/Menu/Builder/AdminMenu.php
src/Menu/Resolver/RecentlyEdited.php
src/Provider/MenuServiceProvider.php
tests/phpunit/unit/Extension/MenuTraitTest.php

- Follow-up to #6895
- Fixes _Set-up Checks_ menu item showing when when `files:check` permission is given, but the route will deny access
- Fixes recently edited icons
- Allows extension driven menus to appear for the correct permission. Failing continued requests for a decision on this, none came … I'll give it the evening and then :shipit:

[3.4] More menus

---

src/Storage/ContentRequest/Edit.php

Fixes #6930. For [3.3] and up.

Don't show empty 'Taxonomies' tab.

---

src/Composer/EventListener/PackageEventListener.php

Use [followLinks()](http://api.symfony.com/2.3/Symfony/Component/Finder/Finder.html#method_followLinks) on Finder, because on Linux dev environments composer creates symlinks instead copying source.

Use followLinks() on Finder

---

app/view/css/bolt_exception.css
app/view/twig/exception/_request.twig
app/view/twig/exception/_trace.twig
app/view/twig/exception/exception.twig
src/EventListener/ExceptionListener.php
src/Helpers/RequestSanitiser.php
tests/phpunit/unit/Helper/RequestSanitiserTest.php

Sometimes the Exception pages would throw an exception, because we tried to output objects as if they were strings:
```
Catchable Fatal Error: Object of class Bolt\Extension\Bobdenotter\Chmodinator\ChmodinatorExtension could not be converted to string"
```
This would give an obscure, hard to read error, instead of pointing to the correct place where it should be fixed. 
This PR handles that slightly better, as well as makes sure that the output stays within bounds of the screen.
Before: 
After:
Also before: 
Also after:

[3.3] Catch exceptions better, don't break layout.

---

src/Form/Resolver/Choice.php
src/Nut/DatabaseExport.php

As raised by @xiaohutai last night, and the :koala: found by @rossriley minutes later!
That aside, I think we've introduced another regression, @rossriley, with the changes in #6878 … The [`sortable`](https://docs.bolt.cm/3.3/fields/select#making-the-selected-values-sortable) option now does nothing for ContentType selects.
I think this is the legacy of trying to jam too much into Twig at the time, so we need to decide what to do here, update the PHP, or drop the above section from the docs? 
ping @SahAssar ^

Filtered choice

---

src/Form/Resolver/Choice.php
tests/phpunit/unit/Form/Resolver/ChoiceTest.php

Confirmed today with @SahAssar and tested as such:
> `sortable` is drag and drop sorting of selected entries. `sort` is the field to automatically sort entries after a field. 
> So I'd use `sortable` to say "display these three blocks on the front page in an order that the editor can decide" and i'd use `sort` to say "display these five related articles alphabetically by title"
Related #6841 #6845 #6865 #6878

[3.2] Drop use of "sortable" as it is only used in Twig

---

src/Storage/Database/Schema/Manager.php

That one thing that gets missed  :disappointed: … adding `$this->schemaTables =`  to the `return` statement saves about 15-20 ms per request.
:koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala:

[3.2] Fix caching of schema tables and prevent multiple builds per-request

---

src/Storage/Field/Collection/LazyFieldCollection.php

This was an oversight when introducing the separate class for LazyFields in place of the normal FieldCollection, this implements the same method as on the other class.

Implement the getBlock method on the LazyFieldCollection

---

app/web.php

Details
-------
character `#` somehow managed to came into `$_SERVER['DOCUMENT_ROOT']` when runing local server on windows via command `php vendor\bolt\bolt\app\nut server:run` (see the [source code in diff](https://github.com/bolt/bolt/pull/6950/commits/94b40caba02f4875a432c63e6f84bc75f414608f))
Choosing a target branch
------------------------
* current

Fixes regex warnings on Windows when a directory name starts with a 'p'

---

composer.json

I am slowly working my way though CII to get us in compliance (where we might not be currently) for a "pass" level.
While this one does not cover a specific MUST or SHOULD, it does give us some degree of "heads-up" for this:
> <b><i>Publicly known vulnerabilities fixed</i></b>
>
> <ul>
>
> <li><a name="vulnerabilities_fixed_60_days"></a>There MUST be no unpatched vulnerabilities of medium or high severity that have been publicly known for more than 60 days.
> <dl><dt><i>Details</i>:<dt> <dd>The vulnerability must be patched and released by the project itself (patches may be developed elsewhere). A vulnerability becomes publicly known (for this purpose) once it has a CVE with publicly released non-paywalled information (reported, for example, in the <a href="https://nvd.nist.gov/">National …

[3.3][Audit] Add roave/security-advisories to require-dev

---

src/Storage/Mapping/MetadataDriver.php

This will be a series of PRs to fix exceptions when using the new storage layer to run `setcontent` queries.
This allows singular contenttype slugs to work,( eg: `setcontent record='showcase/1'`) the same as the main slug.

New Storage Layer - Allow use of short alias for singular_slug

---

src/Legacy/Storage.php
src/Nut/DatabaseImport.php
src/Provider/PrefillServiceProvider.php
src/Storage/Field/Collection/FieldCollection.php
src/Storage/Migration/Import.php

Just a follow up to #6958 for 3.4

[3.4] Inspection clean ups

---

app/view/twig/components/stack/list-item.twig

Fixes #6873
Introduced in #5836
I think this was a derp in #5836 as the following template files behave this way:
- `app/view/twig/files_ck/_files.twig`
- `app/view/twig/recordbrowser/_content.twig`
- `app/view/twig/components/stack/ck-item.twig`

[3.3] Fix linking for files in CKEditor

---

files/.htaccess

CSS files should be provided with the correct Content-Type from the files directory.
This can be useful e.g. for :
* theme creators (to allow users to upload/edit a small custom CSS file in the backend to manipulate some basic settings such as anchor color)
* authors can provide CSS-files to be used in other sites (e.g. [blog.fefe.de](https://blog.fefe.de/faq.html) offers the option to include a external css)
The change is necessary b.c. if the Content-Type does not match browsers will not use the CSS-file, see [here](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types#Why_are_correct_MIME_types_important.3F)

Added CSS to known extensions for files directory

---

.github/ISSUE_TEMPLATE.md

- Prioritise _"This issue tracker is NOT for support questions"_
- Remove suggestion of adding `[BUG]` prefix as that is a triage task, and also better handled with tags
- Added some more PHP versions
- Illegal white space removed :see_no_evil: :hear_no_evil: :speak_no_evil:  `</humour>`
Something that has been irking me since day 1, is these templates are written with the assumption that the are going to be rendered, not displayed as raw text (see below).
Volunteers please feel free to :hand: 
Also, it might be good to have the "contribution guidelines" ~~be based on~~ located at https://bolt.cm/community and mirrored in the `.CONTRIBUTING.md` file :thinking:

[GitHub] Re-prioritise the issue template slightly

---

src/EventListener/DoctrineListener.php

If you have to work with a lot of relations you can't increase max group_concat_max_len cause DoctrineLister overrides mysql value:
`$db->executeQuery('SET SESSION group_concat_max_len = 100000');`
I came up with that problem so I think is useful to put it in config file if someone wants override it.
With love, Shayla <3

Group Concat settings in config.yml

---

src/Nut/DatabaseOptimize.php
src/Provider/NutServiceProvider.php

Just going to leave this one here for RFC.
I can see it being both useful and dangerous. But I'll leave the call on that for discussion. Also just happy to delete the branch, there is virtually zero work in this one.
Oh, and a note on why the logic is in the Nut class. This is not something we'd otherwise want in the API and there is **zero reason** to ever do this from the UI as we make database calls all over the place and this should only be performed when mutation requests are not being made.

[3.4] Nut command to optimise the configured database

---

src/EventListener/DoctrineListener.php
tests/phpunit/database/Entity/AbstractEntityTest.php

Small potential security hole, introduced in #6978, and not in a tagged release.

[3.3][SEC] Use a prepared statement for group_concat_max_len query

---

app/theme_defaults/_sub_taxonomylinks.twig
src/Controller/Base.php
src/Controller/Frontend.php
src/Legacy/Content.php
src/Storage/Entity/Content.php
src/Storage/Entity/ContentTypeTrait.php
src/Storage/Entity/ContentValuesTrait.php
src/Twig/Extension/RecordExtension.php
src/Twig/Runtime/RecordRuntime.php

This is another set of changes that allow themes to render correctly in TWIG no matter which storage layer provides the objects.
Main additions are moving the field type information into a Trait that can be shared by both objects, adding a Twig filter to post process new-style Taxonomy objects and adding some extra checks to the Frontend controller to handle potential differences between the two object types.

New Storage Layer - Add Compatibility features to allow both systems to work concurrently

---

app/theme_defaults/_sub_taxonomylinks.twig

The `|taxonomy` filter will always return an interable

[3.4] Taxonomy template tweak

---

src/Nut/ConfigSet.php

As requested by @ichag :smile: 
This just makes `./app/nut config:set parameter false|true` save a YAML Boolean, not a string

[3.3] Pass boolean string as boolean to YamlUpdater

---

app/src/js/init.js
app/src/js/widgets/buic/buicUpload.js
app/src/sass/editcontent/_legacy.scss
app/view/twig/editcontent/fields/_file.twig
app/view/twig/editcontent/fields/_filelist.twig
app/view/twig/editcontent/fields/_image.twig
app/view/twig/editcontent/fields/_imagelist.twig

Closes #6925 
I’ve done the following, i’ve gone with a quick solution to make the styling a bit more consistent between the buic dropzone and the lib, but they are still controlled by their original components.

[3.4] Fix styling for image divs

---

app/src/js/modules/editcontent.js

Fixes #6991
An input element is inserted on save, causing the form to think it's changed, and thus preventing the save. Needs sanity check from @GawainLynch since the editcontent.js is long and hard and takes more brainpower than I got left

[3.4] Don't check for changes in dynamically inserted elements

---

src/Config.php
src/Storage/Collection/Taxonomy.php

Fixes #6973
Fixes: Taxonomies get saved as 'slugs', should also be checked as such in the editor when determining the 'selected' one(s).

Fixes: Taxonomies get saved as 'slugs'

---

src/Provider/DatabaseServiceProvider.php
src/Storage/Database/Schema/Comparison/BaseComparator.php
src/Storage/Database/Schema/Comparison/Comparator.php
src/Storage/Database/Schema/Comparison/PostgreSql.php
src/Storage/Database/Schema/Comparison/Sqlite.php
src/Storage/Database/Schema/Manager.php
src/Storage/Database/Schema/Types/JsonArrayType.php
tests/phpunit/unit/Nut/DatabaseCheckTest.php
tests/phpunit/unit/Nut/DatabaseRepairTest.php

Fixes #6994 
~~Tests for PHP 7.1+ requires https://github.com/doctrine/dbal/pull/2865 to be merged & tagged, but the failures are only cosmetic.~~

[3.3] More fixes for DBAL

---

app/view/twig/_nav/_secondary-content.twig
app/view/twig/dashboard/_recently_edited.twig
src/Config.php
src/Controller/Backend/Records.php
src/Menu/Resolver/RecentlyEdited.php

Working off of the proposed solution here https://github.com/bolt/bolt/pull/6309
The twig logic kinda got me off track a bit, but here is what i've come up with so far. Would love some feedback.
Update:
So moved away the logic from the Twig templates, and added some extra features like:
- Don't go back to overview when you delete the singleton, but to create new. You don't need the overview for a singleton
- Still just a PR about aligning the UI with the singleton principle
- Removed the singleton from the recently edited section
Lots of love for koalakiller @GawainLynch for the help

Added: Add support for "Singleton" ContentTypes

---

src/Config.php
tests/phpunit/unit/Configuration/ConfigTest.php

See #6995 .
The numerical check is still required because you can define taxonomies as:
```
- foo
- bar
- baz
```
and
```
foo: Foo
bar: Bar
baz: Baz
```
The code before this pull, would actually save it as:
```
0: foo
1: bar
2: baz
```

Add `is_numerical` check - See #6995

---

src/Form/Resolver/Choice.php
src/Storage/ContentRequest/Edit.php
tests/phpunit/unit/Form/Resolver/ChoiceTest.php

Fixes #7006
This just passes along the default value of order through to a filter unless you set the order your self in the filter.

Pass in the default orderby to a filter on the select fieldtype

---

src/Storage/Query/Directive/OrderDirective.php

Loose compare order parameter as it can't be empty

---

tests/phpunit/unit/Embed/GuzzleDispatcherTest.php

This appeared overnight in `embed/embed` **v3.2.1** — https://github.com/oscarotero/Embed/commit/0641d4a9ee8ff2bb4e60a45e42b9c9f46f8a26f4
To my knowledge we don't use the data URIs, but we can't now :wink: 
4am … pre-:coffee: … Something … something … SemVer.

[3.3][Tests] Fix breakage due to upstream 

---

src/Provider/StorageServiceProvider.php
src/Storage/ContentRequest/Listing.php
src/Storage/Query/ContentQueryParser.php
src/Storage/Query/Directive/OffsetDirective.php
src/Storage/Query/Handler/SelectQueryHandler.php
src/Storage/Query/QueryResultset.php

Fixes #6999 
This finishes off support for pagination, the original query is now exposed via the QueryResultset object and that allows other areas of the codebase to get the query and modify/re-run which will likely be useful in other areas of the code or extensions too.
Also added a dependency injection of the pager manager to the backend content listing action so it can update the pager values accordingly.

New storage layer fixed pagination handling

---

app/view/twig/_nav/_secondary-content.twig
src/Menu/Builder/AdminContent.php
src/Menu/Resolver/RecentlyEdited.php

This is the last bit to make Singletons fully functional in a grouped menu. They were basically working, except the linked to the "overview" page, instead of the first/new record. See Screenshot:

Singletons in submenus need to skip "overview" too.

---

app/view/css/ckeditor-contents.css

Ckeditor gives no styling to headings in the WYSIWYG editor and leaves that to the users' browser. This causes headings in some browsers to be displayed smaller than paragraph text. 
I added font sizes for h1, h2, h3, h4, h5, h6 tags. This improves readability and visual hierarchy in WYSIWYG fields.

Adding font sizes to headings in ckeditor

---

src/Storage/Field/Collection/FieldCollection.php
src/Storage/Field/Collection/LazyFieldCollection.php
src/Storage/Migration/Import.php

Fixing the database:import to allow taxonomies to save correctly. There were a couple of issues, primarily a clash between what was set on the `$entity->taxonomy` property versus the `$entity->field` property so before import this clears the field value and uses the outer taxonomy collection.
Fixes #7037

Fix taxonomies on database:import CLI script

---

tests/codeception/acceptance/100-BackendAdmin/BackendAdminCest.php
tests/codeception/acceptance/200-Frontend/FrontendCest.php
tests/phpunit/unit/Controller/FrontendTest.php

`bolt/themes` 1.0.1 got tagged this morning … that threw up more than one :koala: in our tests :frowning_face:

[Tests] Fixes for "not found" assertions

---

app/view/twig/_macro/_macro.twig
src/Storage/Entity/Content.php
src/Storage/Entity/ContentValuesTrait.php
src/Storage/Mapping/ContentTypeTitleTrait.php

Fixes #6870. Fixes #7064.
This PR makes `title_format` work for the new storage layer, as it did for the old one. The code in `ContentTypeTitleTrait::getTitleColumnNames` is mostly adapted from `ContentValuesTrait::getTitleColumnName`.
I also modified the old implementation in `ContentValuesTrait`, to fix #6870 for places where the old storage layer is used. (like in the "Last modified" block in the right aside.

Fixes for `title_format`

---

src/Storage/Field/Collection/RepeatingFieldCollection.php
src/Storage/Migration/Import.php

Couple of minor adjustments to add serialize support for new named repeaters.
This ensures that both ways of database:import and database:export work correctly.

Fix named repeaters during CLI import and export

---

app/view/twig/editcontent/fields/_block-group.twig
src/Form/Resolver/Choice.php

This fixes #7062 
In the choice resolver we do an extra loop for repeater fields, just need to do the same to the block fields and loop each of the sub-fields.
Couple of minor adjustments to the template file to reflect changes in the equivalent repeater block.

[3.4] Fix select values in new named repeater blocks

---

src/Storage/Entity/Content.php

prevent: 
```
ContextErrorException in Content.php line 348:
Notice: Undefined index: selector
```

Fixed: `title_format` addition: Only use fields that (still) exist

---

src/Users.php

Resolved small bug that occurs when first user is created via app/nut command without Root permissions.
At line 458, `addRole()` is aimed to accept a user id (int or string), the whole user object as array was passed instead causing a crash at line 234 when userId is used in `array_key_exists`.
Sorry for IDE autoindent

Only pass user's ID into Users::addRole()

---

app/view/twig/exception/_trace.twig

Fixes a small deprecated warning: Twig Filter "trimtext" is deprecated. Use "excerpt" instead in @bolt/exception/_trace.twig at line 9

Change trimtext to excerpt

---

src/Helpers/Str.php

Fixes #7090
Related to PHP bug [66773](https://bugs.php.net/bug.php?id=66773), [66862](https://bugs.php.net/bug.php?id=66862) and [71079](https://bugs.php.net/bug.php?id=71079) (commit https://github.com/php/php-src/commit/2a75f5026a47099f585e29c5a9d8a2989dab42af)

Remove import for Bolt\Common\Deprecated

---

app/src/sass/editcontent/_legacy.scss

Fixes this annoying behaviour, by restricting resizing to vertical only: 
http://g.recordit.co/9n4MsAWTHx.gif

Fixed: Restrict resizing of `<textarea>` to vertical only.

---

app/view/twig/editcontent/fields/_block.twig

Nothing fancy, but this is a nice PoC/snippet.
It's not as advanced as the `group` for fields, because this one goes from top to bottom and doesn't check for existing groups.
The button isn't split with a button and a caret anymore.
From:
To:

Allow `group` on named repeater's sets

---

app/view/twig/components/panel-activity.twig
src/Controller/Async/General.php

Don't show empty "Latest changes panel" if the changelog is not enabled.

---

src/Composer/Script/BootstrapYamlUpdater.php
src/Composer/Script/BundleConfigurator.php
src/Composer/ScriptHandler.php
src/Nut/Init.php

Discussion: https://github.com/bolt/composer-install/pull/28

[3.4] Composer script logic for default site bundle

---

src/Storage/Entity/ContentRouteTrait.php

Fixes a small bug where calls to `content.link()` were not falling back to defaults if the value was not set.

[FIX] In route generation, lookup parameters from the route defaults

---

src/Storage/ContentRequest/Modify.php

Fixes #7088
Runs a delete query on relevant field content when a main content item is deleted.

Handle deletion of field content after a content record is deleted

---

src/Storage/Query/Handler/SearchQueryHandler.php
src/Storage/Query/Handler/SelectQueryHandler.php

Fixes #6938
In general the idea was to standardise results as a QueryResultset object which can be added to, counted and iterated etc.
However after the issue above was raised it does seem to make a bit more sense to treat queries with the `returnsingle` flag set to return either a single object or false in the absence of any result.
In Twig both eventualities can be covered by always using the `|length` filter which will return true if 1 result or more and false if no results.

In single fetch mode return false instead of empty set

---

src/Storage/Mapping/ContentTypeTitleTrait.php
tests/phpunit/unit/Storage/Mapping/ContentTypeTitleTest.php
tests/phpunit/unit/Storage/Mapping/Mock/ContentTypeTitleMock.php

Fixed: Edge-case in `title_format` for CT's with no textual fields

---

app/view/twig/editcontent/fields/_block.twig

Fixes #7116
Just a port of the same issue with normal repeaters. Adding a hidden empty form value makes sure that the field is saved even if the content is empty.

add an empty hidden field to ensure the field is saved

---

src/Extension/AssetTrait.php
src/Provider/AssetServiceProvider.php

Fixes #7077
The controversial part here is the addition of the web root as an asset package. We've avoided it up until now for several reasons, but I personally think it valid. 
If we're behind this enough to merge, then I'll follow up with some changes in the docs around this.

[3.3] Handle extension asset packages using paths based on web root

---

src/Storage/Field/Type/JoinTypeBase.php
src/Storage/Field/Type/TaxonomyType.php

Fixes #7107
This PR introduces the ability to vary the separator used on grouping queries. It means for taxonomies which may contain a comma as part of the results then we can switch to avoid breakages.

Fix taxonomy grouping queries with commas

---

src/Controller/Backend/Records.php
src/Storage/Collection/Taxonomy.php
src/Storage/ContentRequest/Listing.php
src/Storage/ContentRequest/ListingOptions.php

Fixes #7096
Adds support in the new storage layer for reordering a resultset based on a grouping taxonomy.

Fix grouping support in backend overview

---

src/Storage/Mapping/MetadataDriver.php
src/Storage/Query/Handler/SelectQueryHandler.php

Fixes #7124
Fixes a couple more places where hyphens were leaking into the query engine.

Ensure hyphens in urls are replaced with underscores before going into the Query Engine

---

app/view/twig/dashboard/_recently_edited.twig
app/view/twig/dashboard/dashboard.twig

Additional fix for #7124, using 'key' instead of 'slug'. Using the CT from #7124, you'd get this on the dashboard: 
In the listings, we pass in the permissions, using `context.permissions[contenttype.slug]`, but this should use the 'key' instead.

On Dashboard listings, use 'key' instead of 'slug'

---

app/view/twig/editcontent/_relations.twig

As pointed out by @JarJak on Slack: _**Incoming**_ relationships show a bunch of contextual options in the dropdown, that make no sense in this context. Also, they break. 
So, this PR removes the unneeded options, leaving us with:

Remove permissions in incoming relationships.

---

app/view/twig/exception/_request.twig

When an exception occurs before there's a session, the exception page could break. This PR checks if there's data, before trying to output it. 
Screenshot: 
After:

Fixed: Don't break the exception page on early exceptions

---

src/Composer/Script/BundleConfigurator.php

[3.4] Update namespace for default bundle :koala: 

---

src/Provider/WebProfilerServiceProvider.php

Handles break introduced in https://github.com/symfony/symfony/pull/24236

[3.4] Compensate for upstream BC break in TwigDataCollector constructor

---

src/Storage/Field/Type/TaxonomyType.php

Fixes #7149
This was a slight logic error, we only want to set the group if the taxonomy concerned is a grouping one, otherwise we just skip over it.

Only set a group when the taxonomy is relevant

---

src/Controller/Async/Records.php

Fixes #7151
Add the new group sorting flag on the ajax action so it behaves the same as the normal overview action.

Enable new group sorting on the equivalent ajax action

---

src/Storage/ContentRequest/Listing.php

Fixes #7150
In instances where no taxonomy is set on a record some were slipping through the net, this ensures that they get passed on to the results array.

Allocate the other results to an ungrouped array

---

src/Embed/GuzzleDispatcher.php

Look ma', a :koala:!
* PSR-7 getHeader() always returns an array
* Call getContents() on the body object to return the stream contents
… found in one of those _"you don't want to know"_ moments.

[3.3] Correct logic for MIME type detection

---

src/Composer/Script/BundleConfigurator.php

Fixes #7178
Fixes https://github.com/bolt/collection/issues/32
Using Composer from a PHAR doesn't currently load the "files" section, meaning that calls to is_iterable() are not being handled by the polyfill on installs prior to PHP 7.1.

[3.4] Remove recursive Bag use from BundleConfigurator

---

app/view/twig/_base/_listing.twig
src/Twig/Extension/RecordExtension.php
src/Twig/Runtime/RecordRuntime.php

Fixes #7194
Note: Once Ross' work for #6985 lands, this will be integrated into that, and this specific implementation will be replaced / removed.

[3.4] Use "first_image" to return the first image, for display in overview listings.

---

src/Storage/ContentRequest/Listing.php

Fixes #7195
Fixes the regression where keyword filters are ignored.

Switch to search mode if a text filter is passed into the overview filter

---

app/view/twig/_sub/_record_list.twig

When list of records is empty, it's very **friendly** to show a button "create new" button.  That really helps for some of users.
(sorry for colors, i use themes for my clients)

Added "create new" button in contentedit

---

tests/phpunit/unit/Controller/FrontendTest.php
tests/phpunit/unit/Extension/MenuTraitTest.php
tests/phpunit/unit/Extensions/SnippetLocationTest.php
tests/phpunit/unit/Field/ManagerTest.php
tests/phpunit/unit/Helper/ArrTest.php
tests/phpunit/unit/Logger/ChangeLogTest.php
tests/phpunit/unit/Provider/TwigServiceProviderTest.php

Symfony deprecated this in the PHPUnit bridge in 3.3

[Tests] Use @legacy annotation to mark tests as "legacy group"

---

app/src/js/init.js

The log in form now uses Symfony Forms. This changed the `name` of the password input.

Fixed: "Show" / "Hide" password toggle on log in screen works again.

---

src/Storage/Field/Type/IncomingRelationType.php
src/Storage/Field/Type/RelationType.php

Bumped into this when updating an older site to 3.4. Missing relationships would throw an exception, rendering the backend useless.

Fixed: ContextErrorException in RelationType.php, on sites with "missing" relationships.

---

app/resources/translations/nl_NL/messages.nl_NL.yml

Error in the translation resulting in a non-functional link.

Fix NL translation

---

app/src/js/init.js

Fixed: On log in page, prevents 'An invalid form control is not focusable' on hidden form field

---

src/Storage/ContentRequest/Listing.php
src/Storage/Query/SearchConfig.php
src/Storage/Query/SearchQuery.php

Fixes #7214 
This adds a toggle to the search config class to allow searching on those contenttypes that would ordinarily be invisible.

Allow backend filtering of unsearchable contenttypes

---

src/Provider/UploadServiceProvider.php

translates non-ascii European symbols to ascii-latin + transliteration
Related to #7198

Improved uploaded file sanitizer

---

src/Storage/Field/Collection/RepeatingFieldCollection.php

Fixes #7232 
As described in the issue, block types where the fields had the same names as other blocks were being cross written to. This was a bug in the code that selected the correct entity to update.
This fix checks to see if the block exists and if so ensures that the new value matches the old one.

add extra check to test block exists and matches

---

app/view/twig/_sub/_messages.twig

Fixes "missing" flashbags of type 'danger' and 'warning'.

[koala] Pass in `user` in `flashbag()` macro. :koala:

---

composer.json

Glad it is already gone in master … that is all.

[Tests] Require symfony/browser-kit to keep CodeCeption running

---

src/Storage/Field/Type/RepeaterType.php

Hopefully fixes #7248
Some mysql versions seem not to pull these out in the correct order (and I think it might be the case in SQLite too) so just to make sure we sort the fetched values by the grouping number to make sure they are rendered in the correct order.

ksort the repeater hydrate to ensure grouping order is maintained

---

app/src/js/widgets/fields/fieldRepeater.js

Check for CKE changes on repeater duplication.
Fixes: #7241 
Details
-------
CKEditor is "fun" in that it doesn't update the value of the textarea that spawns it, however in some cases may load instances later, where the data in the textarea can be expected to be up to date. This switches from simply grabbing the input value, to first checking if it's a CKE field and if so looking for an instance with the potentially updated data. If there's no instance yet or if it's simply not a CKE field, it then can safely just use the value.

Fix for 7241: Check for CKE changes on repeater duplication

---

app/src/js/modules/extend.js
app/src/sass/modules/_extend.scss
src/EventListener/ExceptionToJsonListener.php
src/Provider/EventListenerServiceProvider.php

If you've used the Extensions screen, you've undoubtedly seen this: 
There are two main reasons why this happens: 
- The result is an exception, and we should return proper JSON
- The result is an exception / error we couldn't catch or have no control over.
This PR won't fix it for all cases, but it improves on this behaviour for the end user in two distinct ways: 
1) For async requests to our own Bolt code, return a JSON-formatted error. 
(note, i've changed the structure, to match [what's used elsewhere](https://github.com/bolt/bolt/blob/3.4/src/Controller/Backend/Extend.php#L496-L503).)
2) When the result is _not_ JSON, it displays it as plain text, instead of the JSON parse error.

Improve upon the dreaded `unexpected token <` in Extensions screen.

---

app/src/lib/select2-ext/select2.sortable.js

Couple of small tweaks to the select2sortable plugin to work with the slightly altered dom layout of the latest version.

Update sortable plugin to work with latest version of select2

---

src/Controller/Backend/Users.php
src/Form/FormType/UserEditType.php

Require password for new users from admin.
Fixes: #7266 
Details
-------
Adds an option to the user edit type to dynamically require the password depending on if the loaded user entity has an id yet.
I know @GawainLynch is closest to the SF forms stuff, and am curious if there's a better way to do this, perhaps a conditional constraint in the AbstractUserType, though this seemed the simplest solution to me currently.

Fix for #7266, Require password for new users from admin

---

src/Storage/ContentRequest/Edit.php

Get fields from Block, even if Block isn't last.

---

app/view/twig/_nav/_secondary.twig

If a custom backend menu item has children menu items this adds a submenu with those children items.
Example usage in a extension:
```php
protected function registerMenuEntries()
{
$menu = new MenuEntry('koala-menu', 'koala');
$menu->setLabel('Koala Catcher')
->setIcon('fa:leaf')
->setPermission('settings')
;
$submenuItemOne = new MenuEntry('koala-submenu-one', 'koala-tree');
$submenuItemOne->setLabel('Koala One')
->setIcon('fa:leaf')
->setPermission('settings');
$submenuItemTwo = new MenuEntry('koala-submenu-two', 'koala-food');
$submenuItemTwo->setLabel('Koala Two')
->setIcon('fa:leaf')
->setPermission('settings');
$menu->add($submenuItemOne);
$menu->add($submenuItemTwo);
return [
$menu,
];
}
```

Add submenu items to custom menu items in backend

---

app/view/twig/editcontent/fielddata/_video.twig

[3.4] Use `path` instead of `url` for the Video embed endpoint.

---

app/view/twig/editcontent/fielddata/_oembed.twig

Same as #7299, only for the generic OEmbed field, instead of Video.

[3.5] Use `path` instead of `url` for the oembed endpoint.

---

src/Asset/JsonManifestVersionStrategy.php
src/Provider/AssetServiceProvider.php

When using Symfony Encore one can enable `Encore.enableVersioning(Encore.isProduction())` which will output files that include a _"chunk hash"_ in the file name, and a `manifest.json` file that allows the base file name to be mapped to the hashed file name.
For example a `manifest.json` might contain something like:
```json
{
"build/app.css": "/build/app.8fd8daccd3a40a57bad06ae2d8f4c28d.css",
"build/app.js": "/build/app.2fec6da74d584bcd9fd2.js"
}
```
With this PR, you can enable a package/mount-point to use the manifest strategy by setting the relative path to the JSON file as a value in `config.yml`, e.g.
```yaml
assets:
web:
json_manifest_path: build/manifest.json 
```
Then in your Twig templates:
```twig
<link rel="stylesheet" href="{{ asset('assets/app.css', 'web') }}" />
<script …
```

[3.5] Enabled JSON manifest asset version strategy

---

src/Nut/DatabaseExport.php
src/Nut/DatabaseImport.php
src/Storage/Migration/Export.php
src/Storage/Migration/Import.php

Give this a bit of a kick around before we merge.
```yaml
__bolt_export_meta:
date: '2018-01-21T15:16:17+00:00'
version: 3.5.0
platform: sqlite
__users:
-
id: 1
username: gawain
password: $2y$08$deadb33f
email: gawain.lynch@gmail.com
displayname: 'Gawain Lynch'
enabled: true
roles:
- root
- everyone
pages: {  }
entries: {  }
showcases: {  }
blocks: {  }
```

[3.5] Add user accounts to import/export

---

app/src/lib/select2-ext/select2.sortable.js

Another bug from the changes to underlying select2 library.
When we use the `contenttype/id,title` layout on a field then the value of the original and duplicated titles are not the same so instead this adjusts it to select on the full text content so they sort correctly.

Update select2sortable plugin to sort on the full text value of element

---

src/Storage/Collection/Taxonomy.php
src/Storage/ContentRequest/Listing.php

Allow grouping for other taxonomies than only the first one that has `behaves_like: grouping`.

---

src/Controller/Backend/Users.php
src/Form/FieldType/UserRoleType.php
src/Form/FormType/AbstractUserType.php
src/Form/FormType/UserData.php
src/Form/FormType/UserEditType.php
src/Form/FormType/UserNewType.php
src/Form/FormType/UserProfileType.php
src/Helpers/ListMutator.php
tests/phpunit/unit/Form/FormType/UserDataTest.php
tests/phpunit/unit/Helper/ListMutatorTest.php

Fixes #7309
There are two key things here, that I really wanted to tackle ages ago, but thought we could work around in the meantime … Namely, add a list mutator, and use a DTO on the user forms
This mutator is constructed with a list of available possible items, and a second sub-list of items that can be mutated.
The object can then be invoked with two parameters, first is the original list contents, the second being proposed changes.
The returned list will:
- contain only items that are in the 'available' list
- contain any items that appear in both original and proposed lists
- gain only available items that are also mutatable
- lose only items that are mutatable

[3.4] Update handling of user form data

---

src/Storage/ContentRequest/Save.php
tests/phpunit/unit/Controller/Backend/RecordsTest.php

Fixes #7344 
If we have a "new" item, don't immediately redirect, but take `save and return` and `save and add new` into account. 
(ps: the changelog looks wonky. I changed a lot less lines)

Correct redirect after saving "new" record.

---

src/EventListener/NotFoundListener.php

fixes #7345
Now it catches the error in `->resolveTemplate()` and any in `->render()`
I can use `use` statement for that. Also i suppose that we can check if template exists and throw more explanatory exception, before rendering it in chain. 
```php
$template = $this->twig->resolveTemplate($template);
$html = $template->render($context);
```

Update exception handling in NotFoundListener

---

src/Form/Resolver/Choice.php
tests/phpunit/unit/Form/Resolver/ChoiceTest.php

as discussed in #7303 adjusts the choice builder to store multiple contenttype queries as contenttype/id
Fixes: #7303 
Fixes: #7339

Fix to support multiple contenttypes

---

app/view/twig/editcontent/_aside-preview.twig
app/view/twig/editcontent/_buttons.twig

Fixes these issues, when the developer removed the 'contentlink' route: 
- Don't show the "show saved on site" button, because it can not link to a sensible page
- Don't throw an exception after saving (regression found in #7340)

If there's no route for 'contentlink', don't show the "save on site" button
